### ISSUE TITLE
V0.0.9移除了吗

### ISSUE THREAD

**Issue by mikezhuo1022** [ronggang/PT-Plugin-Plus#1]
额，0.0.9的挺简洁好用哈，兼容性也很棒。
我用1.0.4和1.0.5版本右键没发送选项也是迷。
在电脑里翻到老版本包了，so，我还是滚回去用老版本了...

**Comment by ronggang** [comment]
嗯，新版有些功能还没完全移植过来，可以暂时先用老版本，待新版把功能移完了就可以替换了。
