### ISSUE TITLE
keepfrds favicon图标404

### ISSUE THREAD

**Issue by foxconndmd** [ronggang/PT-Plugin-Plus#100]
默认地址：
https://pt.keepfrds.com/favicon.ico
可用地址：
https://pt.keepfrds.com/static/favicon.ico

**Comment by Rhilip** [comment]
重复：https://github.com/ronggang/PT-Plugin-Plus/pull/98

**Comment by Rhilip** [comment]
已合并，相关commit： https://github.com/ronggang/PT-Plugin-Plus/commit/6833431c0575c118f95597f9bd84b8eae1bdf9ae
