### ISSUE TITLE
关于获取第一页种子

### ISSUE THREAD

**Issue by HaibaraMegumi** [ronggang/PT-Plugin-Plus#1005]
## 您的功能请求是否与问题有关？ 请描述一下。

请问怎么在获取第一页种子的时候自动过滤掉官方长期置顶的种子

## 描述你想要的解决方案

能不能添加一些过滤规则呢

**Comment by ted423** [comment]
@HaibaraMegumi 会显示页面所有种子，不显示置顶只会减少显示数目，其他的进一步的功能请求请等next。例如筛选什么的

**Comment by ted423** [comment]
想了想还是不实现比较好。
想看的话按时间排序。
有的站第一页已经被官种占满了。

或者另一个办法就是给置顶也来个标签，不过跟人感觉意义不大并且浪费大量精力
