### ISSUE TITLE
建议在时间轴数据图中，加入UID显示

### ISSUE THREAD

**Issue by pjw20911** [ronggang/PT-Plugin-Plus#1007]
## 您的功能请求是否与问题有关？ 请描述一下。
可以方便查看各站UID，也方便发邀者快速定位求邀者的个人链接，核查真实数据。

## 描述你想要的解决方案
在“这些年走过的路”数据图中，加入UID显示，并且在右上添加一个开关（指“网站名称” “模糊站点图标”的附近位置）

**Comment by ted423** [comment]
uid以及个链并不保存入ptpp，新增这一列个人感觉意义不大（另外还有邮箱这些），还会有隐私方面的担忧。
如有需求，直接沟通或许会是一个比较好的选择
