### ISSUE TITLE
建议增加豆瓣电影一键搜索

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#101]
建议在豆瓣电影网页实现一键搜索。
具体功能描述：豆瓣电影具体的电影页面网页端增加插件的一键搜索按钮，点击后能够提取影视名称按默认预订策略完成搜索。如果能够按照豆瓣id实现搜索就更精确了，不过这个应该需要各PT站点提供接口。
感谢开发者的辛苦工作。

**Comment by Rhilip** [comment]
你好，可以直接选择影视名称后右键搜索，具体请看wiki说明
https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-search#%E6%96%B9%E5%BC%8F%E4%BA%8C

**Comment by luckiestone** [comment]
1.05出了这个功能啊，感谢，不过当时不是标记了won't fix嘛，我以为不做了呢。
