### ISSUE TITLE
听听歌收藏页面适配问题

### ISSUE THREAD

**Issue by isalie** [ronggang/PT-Plugin-Plus#1013]
- PT Plugin Plus version:
- v1.5.2.f2e4f20
- PT Plugin Plus installation method: (market installation, or zip package installation)
- zip
- Browser name and version:
- chrome 版本 99.0.4844.74（正式版本） （64 位）
- Whether the browser has other plugins installed:
- yes
- Is it working properly after disabling other plugins:
- no
- Problem Description:
- 听听歌的收藏页没有适配ptpp助手，尝试其他几个站点收藏页面能正常解析。

- Related screenshots:

- Reproduce steps:
- https://听听歌网址/bookmarks.php
- 页面右侧没有ptpp工具栏
-

**Comment by shenhuilin** [comment]
#1014  试一试
