### ISSUE TITLE
北洋园上传和下载数据信息无法获取

### ISSUE THREAD

**Issue by ThierryCheng** [ronggang/PT-Plugin-Plus#1015]
- PT 助手版本:1.5.2
- PT 助手安装方式：zip包
- 浏览器名称及版本：chrome最新版本99.0.4844.51
- 浏览器是否安装了其他插件：无其他冲突插件
- 停用其他插件后是否正常工作：
- 问题描述：

北洋园上传和下载数据信息无法获取
- 相关截图：
<img width="324" alt="image" src="https://user-images.githubusercontent.com/8851199/158736094-a1baa2a1-1486-4ca5-8bf8-f073ed286d99.png">
<img width="1691" alt="image" src="https://user-images.githubusercontent.com/8851199/158736157-7c5ff86a-370a-4ad8-b4ac-d67699ba7a73.png">

- 重现步骤：

**Comment by ted423** [comment]
readme看一下
