### ISSUE TITLE
打开参数配置页搜索框仍然显示上次搜索结果

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#102]
- PT 助手版本:  v1.0.4
- PT 助手安装方式：市场安装）
- 浏览器名称及版本：Chrome 73.0.3683.103（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：搜索完成后，关闭配置页面，下次打开时搜索框仍然有上次搜索内容，重启浏览器无效。

- 相关截图：
![Snipaste_2019-04-10_09-04-48](https://user-images.githubusercontent.com/35324456/55844466-f287e300-5b6f-11e9-92dd-fc1b70155327.png)

**Comment by tongyifan** [comment]
![](https://img.shields.io/badge/That's-a%20feature-green.svg)

**Comment by ronggang** [comment]
目前是这样设定的。
