### ISSUE TITLE
Opencd站种子详情页“说谢谢”功能无效

### ISSUE THREAD

**Issue by dzw13579** [ronggang/PT-Plugin-Plus#1020]
- PT 助手版本:v1.5.2.274f0e6
- PT 助手安装方式：GitHub
- 浏览器名称及版本：chrome 99.0.4844.51
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：
在OpenCD站种子详情页面中，“说谢谢”按钮缺失

- 相关截图：
![image](https://user-images.githubusercontent.com/59822418/158947598-244a12c4-ae21-452c-9335-15cb6db927bd.png)

- 重现步骤：
进去即可重现

**Comment by ted423** [comment]
安装https://github.com/ronggang/PT-Plugin-Plus/actions/runs/2002094167
