### ISSUE TITLE
第一次打开PTPP 几秒内搜索框会丢失焦点

### ISSUE THREAD

**Issue by isudfv** [ronggang/PT-Plugin-Plus#1027]
- PT 助手版本: 版本1.5.2.f2e4f20
- PT 助手安装方式：edge插件市场
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
第一次打开PTPP 几秒内搜索框会丢失焦点，搜索时总是被打断，有一点影响体验

- 相关截图：
![1](https://user-images.githubusercontent.com/70507125/159906607-54b1429a-dc19-40b7-9045-86dac73222dc.gif)

- 重现步骤：

**Comment by ted423** [comment]
看起来是豆瓣热门后加载的问题
![image](https://user-images.githubusercontent.com/7042766/159924338-74187f29-691f-4e2d-a96d-21a0650003f0.png)
个人觉得还好

**Comment by ted423** [comment]
看起来是豆瓣热门后加载的问题
![image](https://user-images.githubusercontent.com/7042766/159924338-74187f29-691f-4e2d-a96d-21a0650003f0.png)
个人觉得还好

**Comment by Rhilip** [comment]
觉得和 #870 相关，我还是建议在 #984 中对这个热门的问题进行讨论。

**Comment by MewX** [comment]
是的，习惯了快速搜索，这个突然打字打到一半丢失焦点挺郁闷的。

我觉得这个issue可以只修复焦点问题（应该不复杂），另一个讨论是否保留的问题。

**Comment by Rhilip** [comment]
> 是的，习惯了快速搜索，这个突然打字打到一半丢失焦点挺郁闷的。
> 
> 我觉得这个issue可以只修复焦点问题（应该不复杂），另一个讨论是否保留的问题。

搜索框左侧的 `热门` 是延迟加载的（因为需要请求网络数据），加载完成后导致页面DOM变化，所以失焦。
要修复 **只能把左侧 `热门` 功能删去**。

---------------

但目前 master 和 dev 分支处于 maintenance 状态，不做BC change。估计不可能做相关修复。
我在next分支的想法是不要这个热门的框，将其和 #938 结合另外写一个页面。

**Comment by MewX** [comment]
> > 是的，习惯了快速搜索，这个突然打字打到一半丢失焦点挺郁闷的。
> > 
> > 我觉得这个issue可以只修复焦点问题（应该不复杂），另一个讨论是否保留的问题。
> 
> 搜索框左侧的 `热门` 是延迟加载的（因为需要请求网络数据），加载完成后导致页面DOM变化，所以失焦。
> 要修复 **只能把左侧 `热门` 功能删去**。
> 
> ---------------
> 
> 但目前 master 和 dev 分支处于 maintenance 状态，不做BC change。估计不可能做相关修复。
> 我在next分支的想法是不要这个热门的框，将其和 #938 结合另外写一个页面。

最简单的那就热门按钮一直放着好了 😆 后台加载啥就加载着

**Comment by Rhilip** [comment]
> 最简单的那就热门按钮一直放着好了 😆 后台加载啥就加载着，别更新dom就好

技术上没有问题。。
那这样会引出另一个问题， 为什么我点左侧 `热门` 按钮一直没反应，要点好几下才显示 😂
