### ISSUE TITLE
馒头站资源下载地址问题

### ISSUE THREAD

**Issue by dawei233** [ronggang/PT-Plugin-Plus#103]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.4
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Google Chrome 版本 73.0.3683.103
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：no
- 问题描述：在下载馒头pt的资源时获取的到的地址为IPV4+HTTPS ,无法获取IPV6-HTTPS地址。
并且在推送该地址到下载器会报错下载超时 ，下载器配置是正常的，有些可以推送成功但是大部分会报错。

- 相关截图：
![image](https://user-images.githubusercontent.com/31338729/55855147-3d6a2080-5b99-11e9-91f6-0e71b623cdf3.png)

**Comment by ronggang** [comment]
默认是获取的IPv4地址，大部份站还没有v6的选项，看看能不能加个IPv6选项
超时问题可以尝试将超时时间设置长一点。

**Comment by dawei233** [comment]
大佬牛逼
