### ISSUE TITLE
推送种子提示“无效的种子文件”，实际发现推送站点有误

### ISSUE THREAD

**Issue by pickalexrener** [ronggang/PT-Plugin-Plus#1033]
- PT 助手版本:1.5.2.f2e4f20
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 100.0.4896.60
- 浏览器是否安装了其他插件： 是
- 停用其他插件后是否正常工作：否
- 问题描述：使用种子页面的下载功能（包括“一键下载”和“下载到”两种形式），偶尔会出现“无效的种子文件”提示。查看console报告显示实际去查询并推送了audience的种子，显然按其他站的种子id去观众站搜索查不到结果，而audience是我站点设置里默认排序（按名称）的第一个站点。

- 相关截图：
![Snipaste_2022-04-02_12-08-32](https://user-images.githubusercontent.com/51726771/161371051-bc836d1b-851b-4168-9773-667208fd07c0.jpg)
![Snipaste_2022-04-02_15-00-45](https://user-images.githubusercontent.com/51726771/161371212-d50d5b12-b2db-4961-aa38-24ccd8f65b1f.jpg)
![Snipaste_2022-04-02_14-58-22](https://user-images.githubusercontent.com/51726771/161371205-30d9f899-f539-476b-9de2-e060a8d4bc5e.jpg)
![Snipaste_2022-04-02_14-59-25](https://user-images.githubusercontent.com/51726771/161371209-ed34af26-cd51-4f44-81a2-d0eac60f65c4.jpg)
![Snipaste_2022-04-02_15-00-08](https://user-images.githubusercontent.com/51726771/161371210-79184a37-01da-4f1a-b450-ce54e051f511.jpg)

- 重现步骤：
挺难复现，因为出现概率比较低，但截图里的种子我依旧可以复现“无效种子”问题。
以上截图的几个种子id：
图一图二，我堡176265
图三，岛171839
图四，柠檬291975
图五，猫195570

**Comment by ted423** [comment]
提交问题的版本有误，建议先更新到dev版本

**Comment by pickalexrener** [comment]
已更新到actions最新版本v1.5.2.f412eba，依然能复现上述错误

**Comment by ted423** [comment]
尝试使用crx安装

**Comment by nicholastz** [comment]
crx安装问题依旧

**Comment by ted423** [comment]
不同的人，建议都提供详细的环境信息。
提供当时的搜索信息，并说明下推送的是哪个任务
