### ISSUE TITLE
建议在通知气泡上添加下载服务器webui的超链接

### ISSUE THREAD

**Issue by Marsopera** [ronggang/PT-Plugin-Plus#1035]
## 您的功能请求是否与问题有关？ 请描述一下。

建议在右下角的通知上添加直达下载服务器WebUI的超链接。因为需要修改限速和分类，所以设置了添加后不自动开始下载，而且有的种子比较大，偶尔会出现超时错误，因此常常需要点击下载后再打开webui做一些后续的处理。（其实就是懒得点收藏夹了

## 描述你想要的解决方案

如上所述

## 描述您考虑过的替代方案

通知加不上超链接加别的地方也行
## 其他附加信息

无

**Comment by ted423** [comment]
这个建议用收藏夹 固定标签页等功能实现
