### ISSUE TITLE
聆音Club无法正常下载

### ISSUE THREAD

**Issue by tianhuanyun** [ronggang/PT-Plugin-Plus#1039]
- PT 助手版本: v1.5.2.f2e4f20
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：其他站点的可以正常用pt助手下载，聆音Club无法用助手下载，且已经多次手动下载过种子，而且下载器Transmission和Qbittorent都不行，都显示   “无效的种子文件，请参考『常见问题」” 

- 相关截图：

- 重现步骤：
无法正常推送下载

**Comment by ted423** [comment]
请装最新的action版本，看看readme以及wiki。仍有问题再开issue

**Comment by fzlins** [comment]
一版都是装最新的，就是第一个。

https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx
https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-zip

**Comment by tianhuanyun** [comment]
您好，我已经下载第一个了，而且用crx安装的，但是还是不行，还是显示“无效的种子文件”，很郁闷啊，有没有办法能够解决呢？麻烦您啦

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/599
这个站点我吴昊，因此建议你先看下这个issue，看看有没有关联

**Comment by fzlins** [comment]
你的截图是不是passkey露出来了，最好重置一下。这个站点我也没有账号。

**Comment by MewX** [comment]
我倒是油耗，assign给我吧

**Comment by ted423** [comment]
@MewX 看以前的issue,可能是站点设置如此

**Comment by tianhuanyun** [comment]
@fzlins 谢谢告知，已经重置。
@ted423 我尝试一下，谢谢啦。
@MewX 等你好消息哦

**Comment by ted423** [comment]
> 你的截图是不是passkey露出来了，最好重置一下。这个站点我也没有账号。

你会发现那不是一个passkey而是磁力链接，我在想他是不是手滑，所以导致了图片以及这个issue
我刚还以为包含磁力链是不是站点特性，后面想了想似乎不对

**Comment by tianhuanyun** [comment]
那个磁力链接后半部分包含passkey

> > 你的截图是不是passkey露出来了，最好重置一下。这个站点我也没有账号。
> 
> 你会发现那不是一个passkey而是磁力链接，我在想他是不是手滑，所以导致了图片以及这个issue 我刚还以为包含磁力链是不是站点特性，后面想了想似乎不对

是个磁力链接，但是后半部分包括passkey

**Comment by ted423** [comment]
磁力链接形状的passkey?

**Comment by tianhuanyun** [comment]
![_20225606095607](https://user-images.githubusercontent.com/36239496/161880310-7a162fe8-eaee-4486-aabf-b5078bd32a0d.png)
![_20225606095657](https://user-images.githubusercontent.com/36239496/161880319-db05811c-8b49-4375-8c53-6de909db9d89.png)

**Comment by tianhuanyun** [comment]
> 

你好，我看到这个问题了，但是好像没有给出解决办法

**Comment by tianhuanyun** [comment]
> #599 这个站点我吴昊，因此建议你先看下这个issue，看看有没有关联


@ted423 你好，我看到这个问题了，但是好像没有给出解决办法

**Comment by MewX** [comment]
> 您好，我已经下载第一个了，而且用crx安装的，但是还是不行，还是显示“无效的种子文件”，很郁闷啊，有没有办法能够解决呢？麻烦您啦

话说你这边正在使用的版本是多少？

我貌似没有办法复现，下载到两个服务器都是可以成功的

<img width="169" alt="image" src="https://user-images.githubusercontent.com/5752560/162569217-7ad7ca26-5e18-461d-8111-1b1c34295deb.png">

点击过快会触发网站的高负载保护，然后出现这个：

<img width="168" alt="image" src="https://user-images.githubusercontent.com/5752560/162569248-160a53ae-8952-4f2c-adc2-2b55482d8505.png">

<img width="178" alt="image" src="https://user-images.githubusercontent.com/5752560/162569325-e15a3cae-6671-4b64-a3ea-123defa28b89.png">

<img width="389" alt="image" src="https://user-images.githubusercontent.com/5752560/162569319-f587459a-2dac-4dd4-8f99-c213ca824d53.png">



等一秒之后又可以成功了：

<img width="178" alt="image" src="https://user-images.githubusercontent.com/5752560/162569274-8030529b-0bfd-4b4c-9102-48a55d0e2119.png">

测试的种子：
- 58046: 不灭 2016
- 78242: Halo S01E01

**Comment by tianhuanyun** [comment]
![_20225911055904](https://user-images.githubusercontent.com/36239496/162714933-c38fb417-7e8d-4726-99e4-9b8166721852.png)
![_20220011060051](https://user-images.githubusercontent.com/36239496/162715263-32968115-a5ab-4493-8647-7fa794563967.png)
![_20220211060216](https://user-images.githubusercontent.com/36239496/162715466-0e42c772-bfe4-42f3-9fd3-637dcbc11673.png)
你好，我试了你这边的两个种子，还是不行，我确定我配置的是没有问题的，在其他所有网站都可以正常下载。

**Comment by tianhuanyun** [comment]
@MewX 而且在种子列表下载全部显示已发送，但是transmission内没有添加的种子。
![_20220811060857](https://user-images.githubusercontent.com/36239496/162716563-2e2d5ed9-a2cf-44aa-940a-0dabdb60f07a.png)

**Comment by MewX** [comment]
> 我刚才仔细看了你的截图，你是在批量种子列表中右键选择下载的，我这边也成功了，但是我之前都是在种子详情页面点击下载的，你试试在种子详情页行不行？

不是诶，我是在种子详情页面点右边菜单下载的。

**Comment by MewX** [comment]
> 你好，我试了你这边的两个种子，还是不行，我确定我配置的是没有问题的，在其他所有网站都可以正常下载。

多点几次也是一次都不能成功么？

**Comment by tianhuanyun** [comment]
还真是不行，种子详情页还是不行，不过我这不纠结了，反正能有用的地方就行

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/833
