### ISSUE TITLE
功能请求：种子搜索方案增加时间范围筛选器

### ISSUE THREAD

**Issue by Mosney** [ronggang/PT-Plugin-Plus#104]
目前搜索方案只能按照站点大分类做集合，搜索出来的种子也只能依靠分类和关键字筛选，与站点搜索框功能无异。  
如果增加一个时间限定条件，搜所方案可以设置为某一时间范围或者是最近一周、一个月的种子，在某些情况下会非常方便，另外基于NexusPHP的站点基本都没有时间范围筛选，希望PT助手可以增强一下这方面的功能。

**Comment by ronggang** [comment]
@Mosney 想法不错，不过就算加时间范围筛选，也只能对已获取的结果进行二次筛选，而不能对整站进行时间筛选。

**Comment by Rhilip** [comment]
如果站点不能提供相应接口（或者说方法）的话，我觉得对已经得到搜索进行二次筛选没多大意义。
而且，插件本身已经提供了排序功能，稍加翻页即可以定位到某一时间范围了。

**Comment by Mosney** [comment]
> @Mosney 想法不错，不过就算加时间范围筛选，也只能对已获取的结果进行二次筛选，而不能对整站进行时间筛选。

对，现在来看搜索方案还是基于关键词返回的结果来的，但是可以用压制组名等较大范围的关键字来搜索某一时间段内的种子。
另外，“查看最新的种子”这个功能似乎是选取当前搜索方案的前10个新种，如果上述按时间二次筛选意义不大的话是否可以在“查看最新的种子”这里增加自定义时间范围的新种？

**Comment by ronggang** [comment]
> > @Mosney 想法不错，不过就算加时间范围筛选，也只能对已获取的结果进行二次筛选，而不能对整站进行时间筛选。
> 
> 对，现在来看搜索方案还是基于关键词返回的结果来的，但是可以用压制组名等较大范围的关键字来搜索某一时间段内的种子。
> 另外，“查看最新的种子”这个功能似乎是选取当前搜索方案的前10个新种，如果上述按时间二次筛选意义不大的话是否可以在“查看最新的种子”这里增加自定义时间范围的新种？

@Rhilip 已经解释了，大部分网站是没有自定义时间这样的接口或方法的，所以搜索时没办法进行时间筛选，所以我才说如果要做也只能二次筛选😅

**Comment by Mosney** [comment]
> > > @Mosney 想法不错，不过就算加时间范围筛选，也只能对已获取的结果进行二次筛选，而不能对整站进行时间筛选。
> > 
> > 
> > 对，现在来看搜索方案还是基于关键词返回的结果来的，但是可以用压制组名等较大范围的关键字来搜索某一时间段内的种子。
> > 另外，“查看最新的种子”这个功能似乎是选取当前搜索方案的前10个新种，如果上述按时间二次筛选意义不大的话是否可以在“查看最新的种子”这里增加自定义时间范围的新种？
> 
> @Rhilip 已经解释了，大部分网站是没有自定义时间这样的接口或方法的，所以搜索时没办法进行时间筛选，所以我才说如果要做也只能二次筛选

噢噢，那最近的种子个数可以自定义嘛？算是变相自定义时间了

**Comment by ronggang** [comment]
> > > > @Mosney 想法不错，不过就算加时间范围筛选，也只能对已获取的结果进行二次筛选，而不能对整站进行时间筛选。
> > > 
> > > 
> > > 对，现在来看搜索方案还是基于关键词返回的结果来的，但是可以用压制组名等较大范围的关键字来搜索某一时间段内的种子。
> > > 另外，“查看最新的种子”这个功能似乎是选取当前搜索方案的前10个新种，如果上述按时间二次筛选意义不大的话是否可以在“查看最新的种子”这里增加自定义时间范围的新种？
> > 
> > 
> > @Rhilip 已经解释了，大部分网站是没有自定义时间这样的接口或方法的，所以搜索时没办法进行时间筛选，所以我才说如果要做也只能二次筛选
> 
> 噢噢，那最近的种子个数可以自定义嘛？算是变相自定义时间了

可以在基础设置里增加每站点搜索返回的数量。
