### ISSUE TITLE
安卓手机kiwi浏览器安装扩展后无法确定搜索

### ISSUE THREAD

**Issue by 122804787** [ronggang/PT-Plugin-Plus#1043]
## 您的功能请求是否与问题有关？ 请描述一下。

安卓kiwi浏览器可以看成chrome手机版，能安装正常使用，但是因为手机输入法的enter等于search，所以输入搜索内容后按enter会跳转下search框，导致无法确认搜索，现在只能在设置里面没有search框的界面搜索

ps:百度输入法  kiwi浏览器  安卓10系统

## 描述你想要的解决方案

添加一个手动确认的按钮。

**Comment by ted423** [comment]
手机这块目前不是官方支持范围

**Comment by 122804787** [comment]
可以增加一个手动确认的按钮？这样就完美使用了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月10日(周日) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ronggang/PT-Plugin-Plus] 安卓手机kiwi浏览器安装扩展后无法确定搜索 (Issue #1043)




 
手机这块目前不是官方支持范围

**Comment by 122804787** [comment]
现在只有一个问题是手机输入法按enter默认跳转到过滤搜索结果而已，其他的功能都完美使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月10日(周日) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ronggang/PT-Plugin-Plus] 安卓手机kiwi浏览器安装扩展后无法确定搜索 (Issue #1043)




 
手机这块目前不是官方支持范围

**Comment by Rhilip** [comment]
![image](https://user-images.githubusercontent.com/13842140/162877878-43f98f3c-ac5e-4d94-843a-b2c9af1b723b.png)
目前在手机小屏上环境下，已经很挤了。
放一个搜索按键不知道放得下不，我等下看下😂

**Comment by 122804787** [comment]
不适配手机页面也可以啊 ，手机浏览器可以用电脑模式的 能用就行了 ，不用硬挤阿😂😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 中午12:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ronggang/PT-Plugin-Plus] 安卓手机kiwi浏览器安装扩展后无法确定搜索 (Issue #1043)




 

 目前在手机小屏上环境下，已经很挤了。
 放一个搜索按键不知道放得下不，我等下看下😂

**Comment by 122804787** [comment]
![Screenshot_20220412_120923_com kiwibrowser browser](https://user-images.githubusercontent.com/32171417/162955029-fb0eb922-847a-4957-9f27-a04f10ce10ed.jpg)
![Uploading Screenshot_20220412_120931_com.kiwibrowser.browser.jpg…]()

**Comment by 122804787** [comment]
![Uploading Screenshot_20220412_120931_com.kiwibrowser.browser.jpg…]()

**Comment by 122804787** [comment]
![Screenshot_20220412_120931_com kiwibrowser browser_edit_917512246731351](https://user-images.githubusercontent.com/32171417/162957479-1336f3fd-c210-4dbd-9343-6ed9fa57f02f.jpg)
![Screenshot_20220412_120923_com kiwibrowser browser_edit_917474533199586](https://user-images.githubusercontent.com/32171417/162957478-3be9afc8-c916-43dd-8b3f-be2fd5aaf350.jpg)

**Comment by 122804787** [comment]
![Screenshot_20220412_195942_com kiwibrowser browser](https://user-images.githubusercontent.com/32171417/162958019-e9c16ee2-d3f7-4f33-8696-a1506b7ad58f.jpg)
![Uploading Screenshot_20220412_195922_com.kiwibrowser.browser.jpg…]()

**Comment by 122804787** [comment]
![Screenshot_20220412_200149_com kiwibrowser browser](https://user-images.githubusercontent.com/32171417/162958301-815f10c2-a0ca-417e-b788-6ea6732eee8d.jpg)
![Uploading Screenshot_20220412_195922_com.kiwibrowser.browser.jpg…]()

**Comment by 122804787** [comment]
![Uploading Screenshot_20220412_200149_com.kiwibrowser.browser.jpg…]()
![Uploading Screenshot_20220412_195922_com.kiwibrowser.browser.jpg…]()

**Comment by 122804787** [comment]
![Screenshot_20220412_195922_com kiwibrowser browser](https://user-images.githubusercontent.com/32171417/162958702-d73ede3b-5dad-4dde-9059-2c6bb397778f.jpg)
![Screenshot_20220412_200149_com kiwibrowser browser](https://user-images.githubusercontent.com/32171417/162958712-9d4a8e9e-bd03-42d7-8eff-c5c3df34cbf6.jpg)

**Comment by Lastfire** [comment]
我也是一样的问题，之前都可以直接搜索，最近才出现的问题。
补充些细节：
设备环境：华为Mate40Pro 鸿蒙2.0.0.223；Kiwi浏览器 101.0.4951.28；1.5.2 Crx安装

尝试重装插件后，在没有增加站点的情况下可以搜索（手机输入法右下角显示为“前往”）如图1，增加站点后手机输入法右下角显示为“下一项”，点击后会跳转到站点筛选部分，无法进入搜索界面如图2。
![1650011689(1)](https://user-images.githubusercontent.com/103735514/163547285-3ba0b78b-227e-44a1-b621-e979ccdedf6a.png)
![1650011728(1)](https://user-images.githubusercontent.com/103735514/163547369-fc50635e-4a24-48a2-90bf-163ef4bdd14c.png)

**Comment by Lastfire** [comment]
找到了一个临时解决方案。就是在“常规设置”页面 进行搜索，这个页面没有筛选框，不会跳转。

**Comment by SHL-COOL** [comment]
我自己测试已经能确定搜索了
可以测试一下这个#1083 之后的版本
