### ISSUE TITLE
pterclub站点升级之后，无法更新信息

### ISSUE THREAD

**Issue by FLIER001** [ronggang/PT-Plugin-Plus#1044]
- PT 助手版本: 1.5.2.975ad76
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：edge, 100.0.1185.39
- 浏览器是否安装了其他插件：是
- 问题描述：
插件刷新不出pterclub网站的信息

- 相关截图：
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/26852784/163505796-22ed6934-d874-4807-8a47-40d8e0586694.png">

- 重现步骤：无

**Comment by ted423** [comment]
@FLIER001 请先确认你能正常打开网页

**Comment by FLIER001** [comment]
> @FLIER001 请先确认你能正常打开网页

网页打开正常，插件刷新显示未登录。

**Comment by ted423** [comment]
@FLIER001 我这里是正常的，尝试下crx按症状

**Comment by ted423** [comment]
这种情况一般是客户端的问题，有时候可能是被cookies干扰，需要等到能登陆的时候清cookies重新登录
