### ISSUE TITLE
是否能将核心功能打包成一个服务可以装在nas上

### ISSUE THREAD

**Issue by jheroy** [ronggang/PT-Plugin-Plus#1045]
## 您的功能请求是否与问题有关？ 请描述一下。

是否能将核心功能打包成一个服务可以装在nas上

## 描述你想要的解决方案

核心功能打包成一个web服务,可以方便的装在nas上供远程访问,这样通过手机也能方便的使用了. 可以参考jackett, jackett就是服务的方式,不过他的搜索结果太简单的不提供副标题, 还有就是搜索没有进度提示.

**Comment by RtYkk** [comment]
duplicate: #670 #963 #240

**Comment by Rhilip** [comment]
和jackett专注于提供共同一的API服务不同，PTPP的定位是webextension。
同样和jackett不同，PTPP并不关心状态管理（session management, or out-of-box cookie)。

**Comment by Rhilip** [comment]
即使有下一步，也是考虑 react native 或者 electron 跨端，而不是一个docker服务。
