### ISSUE TITLE
求增加Xthor站点的支持

### ISSUE THREAD

**Issue by cxx66666** [ronggang/PT-Plugin-Plus#1048]
- 站点名称：Xthor
- 站点地址：https://xthor.tk
- 站点描述：Xthor是法国最好的General类型的PT站之一，拥有自己的HDTV，Remux小组，其对HD 720/1080进行重编码的所有法国P2P团队中最好的，是Web-dl的第一名。该PT站基于U232，具有不少有趣的玩法，包含了娱乐场，Tombola，二十一点，脉轮以及帮派系统，可与您的朋友一起创建您的帮派。

- 资源类型：综合
- 开放注册：否
- 是否连坐：否
- 站点规则：

**Comment by ted423** [comment]
一个不注意号可能没了的路过

**Comment by ted423** [comment]
成功拖到站点即将关门
