### ISSUE TITLE
北洋园无法正常获取上传量

### ISSUE THREAD

**Issue by handsomexdd1024** [ronggang/PT-Plugin-Plus#1049]
- PT 助手版本:1.5.2.f2e4f20
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Edge
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
北洋园更改H&R考核后无法获取上传量

- 相关截图：
![image](https://user-images.githubusercontent.com/36498278/165069738-73811903-5376-4405-a619-6ea9e7030ac2.png)
![image](https://user-images.githubusercontent.com/36498278/165069812-6e200b80-ed1f-4232-9bd7-110954f41de8.png)

- 重现步骤：

**Comment by ted423** [comment]
先看readme
