### ISSUE TITLE
m-team搜索结果不全

### ISSUE THREAD

**Issue by secretwiki** [ronggang/PT-Plugin-Plus#105]
- PT 助手版本:版本 v1.0.4
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Google Chrome 72.0.3626.121（正式版本） （32 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：搜索结果不全，如搜索“武林外传”关键字，在m-team网站中的搜索链接为：
https://tp.m-team.cc/torrents.php?incldead=1&spstate=0&inclbookmarked=0&search=武林外传&search_area=0&search_mode=0，搜索结果返回17条记录。
例如，搜索结果中能看到大小为141.83的种子（https://tp.m-team.cc/details.php?id=108955&hit=1）

同样以该关键字在PT助手中的搜索功能处进行搜索，关键字同样为“武林外传”，搜索结果只有10条，例如上面举例的结果，就没能搜索出来。

- 相关截图：
m-team搜索结果：
![image](https://user-images.githubusercontent.com/29435965/55928222-88903c00-5c4a-11e9-8665-9e4013badfef.png)
pt助手中搜索结果：
![image](https://user-images.githubusercontent.com/29435965/55928263-aeb5dc00-5c4a-11e9-9764-ca4b8f0a49a7.png)

**Comment by Rhilip** [comment]
你好，不能复现，请检查你插件设置中设定的“搜索时每站点返回结果数量”值是否为10

**Comment by secretwiki** [comment]
抱歉，是我个人设置问题。
非常感谢！
