### ISSUE TITLE
已设置搜索结果首页显示数量为100条，但PTPP搜索结果只显示50条

### ISSUE THREAD

**Issue by LoneFireBlossom** [ronggang/PT-Plugin-Plus#1053]
- PT 助手版本: v1.5.2.f2e4f20 zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 101.0.4951.41（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：依旧
- 问题描述：根据 
![为什么设置了每站返回 100 条，但搜索结果只返回 50 条？](https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%AE%BE%E7%BD%AE%E4%BA%86%E6%AF%8F%E7%AB%99%E8%BF%94%E5%9B%9E-100-%E6%9D%A1%E4%BD%86%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E5%8F%AA%E8%BF%94%E5%9B%9E-50-%E6%9D%A1) ，我已经在U2的网站设置里设置了每页显示100条搜索结果。但是PTPP对U2的搜索结果仍然只显示50条。其它设置过的站点也是这样。

- 相关截图：
- 
<img width="1754" alt="image" src="https://user-images.githubusercontent.com/50087596/166648249-e091a16a-0f73-4234-bcd7-e63d333c0fd7.png">
<img width="953" alt="image" src="https://user-images.githubusercontent.com/50087596/166648325-d10a0feb-39b2-462c-ab0d-452bc04d3c71.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/50087596/166648381-4c52d633-017d-4a54-abbb-b3df104f5529.png">

- 重现步骤：
- 1. 在U2里设置每页搜索结果的显示数量为100
- 2. 在PTPP里搜索

**Comment by ted423** [comment]
@LoneFireBlossom 看下ptpp设置

**Comment by LoneFireBlossom** [comment]
> @LoneFireBlossom 看下ptpp设置

谢谢，原来在设置里有……我改好了。

我当时想解决这个问题于是直接来GitHub搜issue看有没有别人提，搜到这个https://github.com/ronggang/PT-Plugin-Plus/issues/332然后看到QA就没想过PTPP还有设置= =
