### ISSUE TITLE
从 crx 并添加插件白名单的方式在新版本 chrome 失效了

### ISSUE THREAD

**Issue by shuosiw** [ronggang/PT-Plugin-Plus#1055]
更新到 chrome 101.0.4951.54 后，发现无法打开 ptpp 插件了，之前通过插件白名单的方式（ https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx ）在这个版本失效了

<img width="368" alt="image" src="https://user-images.githubusercontent.com/2578976/167334900-4c5c0b1a-052e-4352-8ead-241701440b8b.png">

* 我是 macOS 系统，使用描述文件来添加，之前会有提示`由贵单位管理`，现在没了，重新尝试安装一次描述文件也不行
* 还有一个朋友使用 windows10，也是升级到新版本 chrome，用 wiki 提到的方式通过注册表添加插件白名单也失效了

求助一下有没新的方式，在 google 上搜索了好久都没找到新的解决办法

**Comment by ted423** [comment]
win 10 chrome正常，请检查相应注册表是否正常

**Comment by Mit2g** [comment]
现在的wiki已经适应了chrome101的这个问题 其实就是字段改变了

Mac的问题也是对应修改即可 如果搞不定可以使用[这里的配置文件](https://t.me/ptpluginplus/115)

**Comment by shuosiw** [comment]
按照 @Mit 大佬提供的配置，可以正常配置上了，非常感谢！也谢谢 @ted423 解答

**Comment by xiaocainiao2020** [comment]
请问下是怎么解决的，我也是同样的问题，重装也不行。

**Comment by shuosiw** [comment]
> 

windows 开个管理员权限的 cmd 命令提示符，然后输入：

```
reg add HKLM\SOFTWARE\Policies\Google\Chrome\ExtensionInstallAllowlist /v 99999 /t reg_sz /d dmmjlmbkigbgpnjfiimhlnbnmppjhpea /f 
```

再重启 chrome 就行了
