### ISSUE TITLE
功能请求：建议搜索方案里可以搜索几个站点2天内重复的种子，以方便快速下载辅种。

### ISSUE THREAD

**Issue by wqzvic88** [ronggang/PT-Plugin-Plus#106]
如果能在搜索方案里勾选几个站点，然后能自动找寻2天内（可自设搜索时间范围）重复的种子，以方便用户观察哪个种子成为通用种子，快速下载辅种。

**Comment by Rhilip** [comment]
你好，重复种子如何定义？
另关于自设时间段的讨论请参见 https://github.com/ronggang/PT-Plugin-Plus/issues/104

**Comment by wqzvic88** [comment]
想法是，比如A站2天前出了一个种，B种2天后才转载，那我要是知道A、B站有2个一样的种子，且根据时间先后排序知道A站是首发原创，那我赶紧去A站下了种子跑来B站一辅种，那B站的上传基本都能吃到。

**Comment by ronggang** [comment]
通过搜索是无法准确的定位到相同种子的。
