### ISSUE TITLE
firefox用开发者中心办法安装后，hdsky搜索总是报错？

### ISSUE THREAD

**Issue by jiezi506** [ronggang/PT-Plugin-Plus#1061]
- PT 助手版本:1.5.2
- PT 助手安装方式：firefox开发者中心自构建
- 浏览器名称及版本：firefox 100
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：firefox用开发者中心办法安装ptpp后，hdsky搜索总是报错？

- 相关截图：
![图片](https://user-images.githubusercontent.com/76936994/168719151-1a3e2cb9-0ba9-44ef-beb3-5624ae702613.png)

- 重现步骤：

**Comment by ted423** [comment]
搜索了多少个站点，其他站都没报错？
之前是怎么使用的？有没有问题？

**Comment by jiezi506** [comment]
> 搜索了多少个站点，其他站都没报错？ 之前是怎么使用的？有没有问题？

62个站电，其他站都没有这个错误，以前用edge+文件夹形式使用不会报这个错，转到firefox，用开发者中心自构建附加组件的形式安装，就hdsky一直报这个错。

**Comment by ted423** [comment]
站点能否正常打开，有没有撞cf盾？

**Comment by ted423** [comment]
有没有试过清理这个站点的cookies，重新登陆

**Comment by jiezi506** [comment]
> 有没有试过清理这个站点的cookies，重新登陆。 页面里按f12可以单清某个站点的cookies ![image](https://user-images.githubusercontent.com/7042766/168721906-0b491d70-3854-4e91-9948-53372ec1c4fa.png)

试了清空hdsky的cookie重新登录，还是报错，不知道是不是我个人的问题，用用firefox+开发者中心自构建的人好像不多。

**Comment by ted423** [comment]
我这试了下 91 esr+v1.5.2.6e34444 正常

**Comment by ted423** [comment]
升到了100确实挂了
火狐传统艺能？

**Comment by jiezi506** [comment]
firefox版，hdsky页面右边的一键下载所有种，也是报undefined错，其他站好像没问题

**Comment by dfbb9216** [comment]
Chromium 102.0.5005.167
 v1.5.2.66028c6
HDSKY的站点数据刷新就是提示 发生错误。重新添加站点不行，不知道是哪里的问题

**Comment by ted423** [comment]
看了下，https://github.com/ronggang/PT-Plugin-Plus/blob/f2e4f20c47eca1ac65766be79f6cae988621547e/resource/schemas/NexusPHP/getSearchResult.js#L421
这里的问题，火狐100和chrome的显示不同，chrome是form，火狐还是a

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/commit/adc07b46bf6f5392409b2440efddf991dda71e21

**Comment by ted423** [comment]
已修复，不清楚这个是HDsky的页面兼容性问题，还是火狐的渲染兼容性问题，火狐100以后,sky种子列表上的imdb分数和豆瓣分数都没了
