### ISSUE TITLE
铂金家pthome下载种子提示无效

### ISSUE THREAD

**Issue by eschcn** [ronggang/PT-Plugin-Plus#1062]
- PT 助手版本:1.5.2.f2e4f20
- PT 助手安装方式：zip解压缩安装
- 浏览器名称及版本：chrome101
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
1、分类页面和种子页面下载都提示无效，尝试重新安装插件、重新添加站点，依然如此。
2、听读分类不显示PTPP侧边图标
- 相关截图：
[![O5QxoD.png](https://s1.ax1x.com/2022/05/17/O5QxoD.png)](https://imgtu.com/i/O5QxoD)

- 重现步骤：
打开PTHOME网站，在分类页面和种子页面点击一键下载或下载到...

**Comment by ted423** [comment]
错误的版本，请更新action 的dev版本
