### ISSUE TITLE
猫站显示未登录

### ISSUE THREAD

**Issue by starsjf** [ronggang/PT-Plugin-Plus#1064]
- PT 助手版本: v1.5.2.d363da8
- PT 助手安装方式：crx（市场安装，或zip包安装）
- 浏览器名称及版本：Microsoft Edge 版本 101.0.1210.53 (正式版本) (64 位)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：否
- 问题描述：

猫站显示未登录

- 相关截图：

![image](https://user-images.githubusercontent.com/49010890/170763589-1926eca1-3008-4f99-9648-a3541c6bd3d8.png)

- 重现步骤：

**Comment by starsjf** [comment]
补充一下，正常打开网页是可以的。

**Comment by starsjf** [comment]
今日测试，猫站工作正常了。

**Comment by ted423** [comment]
https://t.me/PTerClub/194457
