### ISSUE TITLE
猫站pt 助手获取不到用户信息

### ISSUE THREAD

**Issue by kaihavice** [ronggang/PT-Plugin-Plus#1067]
- PT 助手版本:v1.5.2.d363da8
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：mac chrome 102.0.5005.61
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：
- 问题描述：
猫获刷新获取不到用户信息，浏览器网页一切正常，其它站一切正常，看截图
- 相关截图：
![tg_image_2601896665](https://user-images.githubusercontent.com/5363037/170876670-d8416125-6e44-460b-8c15-2c2d3ddb7abd.jpeg)

![2022-05-29 23 07 59](https://user-images.githubusercontent.com/5363037/170876518-7ca3cd32-5ef7-434e-962a-9769fc7f4d6b.jpg)

![2022-05-29 23 07 43](https://user-images.githubusercontent.com/5363037/170876515-e33082f7-70d0-4a21-9f5d-94ae2df7bc78.jpg)

- 重现步骤：
点击刷新

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/1064#issuecomment-1139889654
目前的判断是,猫站自身可能有什么限制之类的？
另外一个可能是缓存跟网页缓存（？）不同？

或者先试下用wiki里的方法用crx安装试试

**Comment by kaihavice** [comment]
> [#1064 (comment)](https://github.com/ronggang/PT-Plugin-Plus/issues/1064#issuecomment-1139889654) 目前的判断是,猫站自身可能有什么限制之类的？ 另外一个可能是缓存跟网页缓存（？）不同？
> 
> 或者先试下用wiki里的方法用crx安装试试

我待会试试 crx 安装

**Comment by kaihavice** [comment]
> [#1064 (comment)](https://github.com/ronggang/PT-Plugin-Plus/issues/1064#issuecomment-1139889654) 目前的判断是,猫站自身可能有什么限制之类的？ 另外一个可能是缓存跟网页缓存（？）不同？
> 
> 或者先试下用wiki里的方法用crx安装试试

crx 就正常了，感谢
