### ISSUE TITLE
征集助手按钮弹出内容建议

### ISSUE THREAD

**Issue by ronggang** [ronggang/PT-Plugin-Plus#107]
PT助手重构已有一段时间，目前已基本完成对原有版本的所有功能，感谢各位一直以来的支持和陪伴！

现阶段还有一个功能未能好好设计，就是当点击助手图标时弹出的页面，即下图所示

![image](https://user-images.githubusercontent.com/8065899/56004617-e4b49800-5cfe-11e9-96e0-237ed0d132b5.png)

在此希望听听各位的建议，说说你最希望在这个区域放置哪些内容，不限于按钮，可以是任何内容，发挥你那天马行空的想象力，你的想法将会在后续本中出现。:heart:

**Comment by topstop3416** [comment]
显示概览就行吧

**Comment by mikezhuo1022** [comment]
什么时候能不能把旧版的右键发送到bt服务器下载的功能加回来了呢...感觉很好用啊

**Comment by ronggang** [comment]
> 什么时候能不能把旧版的右键发送到bt服务器下载的功能加回来了呢...感觉很好用啊

右键发送功能不是一直都在吗？

**Comment by ywyha** [comment]
那个位置放PT站点的未读短or系统通知消息数量吧，点进去后直接能进入相应站点的收件箱，然后希望在任何网页的空白处支持右键菜单，感觉还是右键菜单进入主页面更快捷方便。

最后超级感谢栽培者大佬对PT易用性改进做出的极大贡献，真的真的方便太多了。自从有这个工具后跟之前的使用比简直是天壤之别。

**Comment by mikezhuo1022** [comment]
不好意思，我的问题...之前的V0.x不需要设定默认下载服务器直接右键也会有发送按钮...这一版需要设定默认服务器才会出现...惯性思维了...sry

**Comment by mikezhuo1022** [comment]
> > 什么时候能不能把旧版的右键发送到bt服务器下载的功能加回来了呢...感觉很好用啊
> 
> 右键发送功能不是一直都在吗？

不好意思，我的问题...之前的V0.x不需要设定默认下载服务器直接右键也会有发送按钮...这一版需要设定默认服务器才会出现...惯性思维了...sry
