### ISSUE TITLE
搜索快照中HDB的种子变成UHD的

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#1074]
- PT 助手版本: action最新
- PT 助手安装方式：crx（市场安装，或zip包安装）
- 浏览器名称及版本：edge 最新稳定版
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
并且种子数量进行了合并...

- 相关截图：
![image](https://user-images.githubusercontent.com/7042766/173761092-3b53d4b1-f571-477d-8a10-b29504be735f.png)
![image](https://user-images.githubusercontent.com/7042766/173761159-7429208a-a88a-4fae-8f3f-5aa3114334ea.png)

- 重现步骤：

**Comment by Rhilip** [comment]
看起来是和之前 https://github.com/ronggang/PT-Plugin-Plus/issues/498 一样的问题？

**Comment by ted423** [comment]
应该类似，但没懂快照是在哪块代码写的..

**Comment by Rhilip** [comment]
太多类似重复的代码了2333
