### ISSUE TITLE
FileList一键复制的种子链接不是下载链接

### ISSUE THREAD

**Issue by PKUdream** [ronggang/PT-Plugin-Plus#1075]
- PT 助手版本: © 栽培者 2022, 版本 v1.5.2.f2e4f20 
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 100.0.4896.127版本
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：如题，FL复制的种子链接是例如https://filelist.io/download.php?id=785689这样的样式，粘贴到qb等客户端是没法下载的，正常的种子链接应该是包含passkey的下载链接。种子详情页面和种子列表页面的复制链接按钮都是这个bug。

- 相关截图：如上描述，大佬去操作下即可验证。

- 重现步骤：

**Comment by ted423** [comment]
1. 版本不对
2. 这不是bug,是feature,请手动设置passkey.默认站点没提供带passkey的连接
