### ISSUE TITLE
功能建议：中英文等级

### ISSUE THREAD

**Issue by dayback** [ronggang/PT-Plugin-Plus#108]
感谢各位的付出~ 
本人等级党，想提一个建议：
现在的等级是直接从个人网页提取出来的，对于每个站，结果有不同的风格和不同的名称。
能否为每个站做个中英文等级对应表，对个人网页取得的等级进行解析，解析成中文等级和英文等级，并在概览页面显示 。

**Comment by ronggang** [comment]
英文站不是很了解，对于 NP 站点是有固定等级，倒是可以做对应表。
如果还是用名称，可能还是会有不同的意见，倒是可以考虑以图标的方式来显示。

**Comment by dayback** [comment]
我整理了一些站的等级表，如下
https://docs.google.com/spreadsheets/d/1PinXGaQtYt1SB6NQTDdHCwDolL1v6t53x8FWWg6sfWk/edit?usp=sharing

另外，TTG/CCFBITS自成一套等级

**Comment by ted423** [comment]
个人想法，这种自己对照着看下就好了吧。
如果展现的话，可能需要一个比较合适的展现形式
投入也是需要考量的，目前给我的感觉是这么做要投入很大精力，然后开发出来的东西可能不是很必要。因为熟悉的话这个站的话，自然会知道自己在什么等级

**Comment by Rhilip** [comment]
感谢建议，不做考虑，还是直接显示站点直接就能抓到的信息就好。
