### ISSUE TITLE
HDTime 不显示实际做种体积

### ISSUE THREAD

**Issue by ChuanfengZhang** [ronggang/PT-Plugin-Plus#1088]
- PT 助手版本: v1.5.2.e7cdf1f
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 103.0.5060.114
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
HDTime 不显示实际做种体积，做种体积显示为 0。

- 相关截图：
![](https://raw.githubusercontent.com/ChuanfengZhang/Image-Hosting/master/img/HDTime1658493897.png)

- 重现步骤：
我的数据-刷新我的数据

**Comment by samcard1** [comment]
我今天也发现同样的问题，另外一个自定义网站也显示做种为0（piggo.me）

**Comment by ted423** [comment]
自定义站做种为0是比较正常的

**Comment by samcard1** [comment]
之前都正常除了白兔
