### ISSUE TITLE
M-Team站点不显示上传、下载和分享率数据，其他站点正常

### ISSUE THREAD

**Issue by jininglin** [ronggang/PT-Plugin-Plus#109]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.4
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 73.0.3683.103（正式版本） （64 位）
- 浏览器是否安装了其他插件：谷歌访问助手
- 停用其他插件后是否正常工作：停用后还是有问题
- 问题描述：
**M-Team站点不显示上传、下载和分享率数据，可以显示做种体积、魔力值、入站时间。**
其他站点这些数据都能显示。

- 相关截图：
![image](https://user-images.githubusercontent.com/49557940/56035310-62f35780-5d5c-11e9-99cb-f3c12f957434.png)

**Comment by jininglin** [comment]
追加反馈：今天发现M-Team站点的做种数、做种体积也显示不了了，只能显示魔力值、入站时间了。

**Comment by Archie87** [comment]
和楼主一个情况

**Comment by wuping24** [comment]
一样

**Comment by ronggang** [comment]
MT站应该有两种加载方式，不知道是根据做种数量还是等级来区分，现在还无法测试需要分页的方式。

**Comment by KempLeung** [comment]
我刚好相反，数据量和分享率都能显示，做种数量和做种体积不能显示

**Comment by lanochan2018** [comment]
我这数据量和分享率都能显示，做种数量和做种体积不能显示。和@KempLeung一样的问题

**Comment by mopsky** [comment]
有同样的问题

**Comment by lbq1121** [comment]
有同样的问题

**Comment by Aniverse** [comment]
我的问题是上传和下载量都显示为 7.88 TiB，其他数据（包括分享率、魔力值、做种数量等）全都正常；而在我上传量达到 1 PiB 以前没这个问题。
如果有需要的话我可以提供我页面的源码

**Comment by ronggang** [comment]
> 我的问题是上传和下载量都显示为 7.88 TiB，其他数据（包括分享率、魔力值、做种数量等）全都正常；而在我上传量达到 1 PiB 以前没这个问题。
> 如果有需要的话我可以提供我页面的源码

如果可以的话，发我邮箱。或者已加Q群或Telegram的话，可以私信给我。

**Comment by lbq1121** [comment]
再次出现这种问题 用的是商店最新版插件

**Comment by ronggang** [comment]
> 再次出现这种问题 用的是商店最新版插件

请上传站点的个人页面（userdetails.php）的截图，谢谢。
