### ISSUE TITLE
建议：移除 CHDBits 支持

### ISSUE THREAD

**Issue by KevinMX** [ronggang/PT-Plugin-Plus#1090]
- 如图。在站点/插件后续跟进其他改进措施之前，建议暂时移除。
![image](https://user-images.githubusercontent.com/17025286/180606058-0ae5ff92-8aa5-4cfc-b163-9bb99fc15ad8.png)

**Comment by ted423** [comment]
这种个人认为只有在站点明确不能使用ptpp的情况下才会进行。各类插件是个很模糊的说法。
个人认为ptpp不会带来巨额压力和流量

**Comment by KevinMX** [comment]
> 这种个人认为只有在站点明确不能使用ptpp的情况下才会进行。各类插件是个很模糊的说法。

根据 Mod 在论坛的回复，包括 PTPP 在内的所有 WebExtensions 插件，都算。

> 个人认为ptpp不会带来巨额压力和流量

如果有多分类并发搜索的话，可能是个问题。我不想揣测站方是出于何种考虑禁用所有插件的，个人愚见，还是谨慎为先吧。

**Comment by ted423** [comment]
仍然是个很模糊的说法，譬如KeepassXC这个扩展也会在chd的页面运行，只是不会产生影响。还有就是flexget算不算？YaRSS2算不算？有人自己写个rss订阅工具，算不算？自己写个gm脚本，算不算？
如果明确不行，公告和规则里应该有写。Mod的回复可以被参考，但我不明确这是他个人理解，还是管理组讨论过后的结果。
可以参考之前的AZ联盟的事，他们要求移除，我们这边就进行了移除。不过即便移除，现有的release仍会包含。

是否在chd上使用，目前很大程度上还是由用户自己决定。所以个人看法是，我们不用做出即刻反应，等后续就好。

并发搜索确实是个问题，但除非1个人每隔一小时都会跑去搜索，否则产生的流量仍然很少。
即便每隔1小时都搜索，1小时产生的量也才11次。

**Comment by w22gb8** [comment]
说的是那些刷数据上传的工具，会频繁访问服务器，ptpp 频率和正常人访问差不多。

**Comment by 4bookmark** [comment]
重点是 也不用移除支持 有没有一种 你把这个站点从你的站点列表里删除的选项呢？

**Comment by Rhilip** [comment]
**我们仅接受官方以本仓库issue形式提出的移除，其他任何途径不做考虑。**
因为我们不一定有账号来证明其确实是管理组意图。
