### ISSUE TITLE
[[ExoticaZ]网络请求失败！(451 , error)]

### ISSUE THREAD

**Issue by hayreddin2019** [ronggang/PT-Plugin-Plus#1091]
- PT 助手版本:   1.5.2
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome  版本 103.0.5060.134
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：无
- 问题描述：
- 搜索  ExoticaZ 网站 提示 "[[ExoticaZ]网络请求失败！(451 , error)]"

- 相关截图：

<img width="443" alt="截屏2022-07-24 08 24 57" src="https://user-images.githubusercontent.com/51017975/180627266-bd2392c0-62f4-453b-b9d9-8feb3438ff00.png">

- 重现步骤：

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/996

这几个站点已经不在支持列表里
