### ISSUE TITLE
hdsky错误

### ISSUE THREAD

**Issue by zlhdd108** [ronggang/PT-Plugin-Plus#1092]
正常登陆hdsky，直接点击可以打开，在ptpp里面更新提示错误
![image](https://user-images.githubusercontent.com/16465666/180918891-53968fb1-14ac-41fd-be0d-7a2263403159.png)
浏览器版本
![image](https://user-images.githubusercontent.com/16465666/180918963-98455c55-90d9-47d0-b3c6-8b0c28269fe0.png)

**Comment by pwbty** [comment]
同样有这个问题，搜索可以，信息更新不了，数据走的代理也不行。

**Comment by pwbty** [comment]
> 

网站重新登录后解决，可以获取用户信息。
