### ISSUE TITLE
空站无法刷新数据

### ISSUE THREAD

**Issue by claresongs** [ronggang/PT-Plugin-Plus#1093]
- PT 助手版本:dev-build-f772a58-crx
- PT 助手安装方式：crx安装
- 浏览器名称及版本：chrome  103.0.5060.134
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
空站hdsky未知错误

- 相关截图：

![Screenshot 2022-07-28 001543](https://user-images.githubusercontent.com/44543227/181297628-6d9029a5-4b54-4abc-b9d8-fae9f53ac37d.png)
- 重现步骤：
刷新数据

**Comment by ted423** [comment]
userid页面开了cf盾，不是扩展问题
