### ISSUE TITLE
建议增加语言选择

### ISSUE THREAD

**Issue by BlueDolphin9527** [ronggang/PT-Plugin-Plus#1094]
## 您的功能请求是否与问题有关？ 请描述一下。

我常使用的一款扩展，要求我必须在浏览器设置中使用非简体中文，因为他在国内的业务被流氓公司给搞了，必须把国内市场放弃掉。而PT助手默认在浏览器非简体中文下是英文选项，无法更改。

## 描述你想要的解决方案

建议增加语言选项

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/181601660-354a4d3b-c736-4c56-843c-4bda1858f3e0.png)
每个字看起来都认识.....
