### ISSUE TITLE
能否支持一下新版flood

### ISSUE THREAD

**Issue by BrunuhVille** [ronggang/PT-Plugin-Plus#1096]
## 您的功能请求是否与问题有关？ 请描述一下。

新版flood可以对接四种客户端[rTorrent](https://github.com/rakshasa/rtorrent)  [qBittorrent](https://github.com/qbittorrent/qBittorrent)  [Transmission](https://github.com/transmission/transmission)  [Deluge](https://github.com/deluge-torrent/deluge) ，而旧版仅支持[rTorrent](https://github.com/rakshasa/rtorrent)这一种客户端

## 描述你想要的解决方案

希望大佬可以开发一下

## 描述您考虑过的替代方案

pt小白，非常感谢大佬

**Comment by FLIER001** [comment]
目前最新不还是2021年的4.7版本吗

**Comment by BrunuhVille** [comment]
> 目前最新不还是2021年的4.7版本吗

对的，flood新版是4.x的，但是PT助手插件目前只支持2019年老版1.x的flood

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/715
在这里讨论就好
