### ISSUE TITLE
配置了下载目录发送后仍然下载到默认目录

### ISSUE THREAD

**Issue by allonli** [ronggang/PT-Plugin-Plus#11]
client : osx chrome
server : utorrent 2.2.1

**Comment by ronggang** [comment]
@allonli 抱歉，默认目前当前仅支持
- Transmission
- Synology Download Station
https://github.com/ronggang/PT-Plugin-Plus/wiki/config-download-client#%E8%AE%BE%E7%BD%AE%E9%BB%98%E8%AE%A4%E4%B8%8B%E8%BD%BD%E7%9B%AE%E5%BD%95
