### ISSUE TITLE
BUG：HDSky搜索结果下载种子到本地错误

### ISSUE THREAD

**Issue by EthanLeen** [ronggang/PT-Plugin-Plus#110]
- PT 助手版本:104
- PT 助手安装方式：市场安装
- 浏览器名称及版本：google chrome 版本 73.0.3683.103（正式版本） （64 位）
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
HDSky搜索结果下载种子到本地错误，错误提示如下：This method allows POST request only.

- 相关截图：

**Comment by ronggang** [comment]
参考 #99 
v1.0.5 会修复。
