### ISSUE TITLE
建议更新一下edge市场版

### ISSUE THREAD

**Issue by mobileliker** [ronggang/PT-Plugin-Plus#1105]
edge商店版最新版发布已超过一年，master已做了很多修复，能否考虑更新一下。
照顾照顾用商店版的孩子，谢谢。

**Comment by ted423** [comment]
作者已经失联，所以暂时办不到

**Comment by tainewoo** [comment]
> 作者已经失联，所以暂时办不到

啊....看看看了下,好像去年到现在没有活跃了...
要不crx的择机release个?以后大家切换到crx

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx

**Comment by tainewoo** [comment]
只能从action获取dev分支的包了~
master分支看起来都不太动了

**Comment by ted423** [comment]
更新相关问题统一到一个issue 
https://github.com/ronggang/PT-Plugin-Plus/issues/1070
