### ISSUE TITLE
ptpp统计数据来源是网站数据么

### ISSUE THREAD

**Issue by hnwp2008** [ronggang/PT-Plugin-Plus#1106]
- 
再下载MT一个大包的时候，Qb显示的上传是40G，但是ptpp显示的是150G。有点好奇，这个大包自由一个free标识，所以两个上传流量为何不一样。

**Comment by ted423** [comment]
肯定是来源网站.....ptpp显示的是总上传，不会显示某个任务的上传，问问题，请去discussion
