### ISSUE TITLE
站点无法正常搜索种子，只能搜索到音乐类型种子，搜索电影种子就会显示 发生网络或其他错误

### ISSUE THREAD

**Issue by 7788u** [ronggang/PT-Plugin-Plus#1108]
- PT 助手版本:v1.5.2.66028c6
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：GOOGLE
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：不能
- 问题描述：
突然在搜索种子的时候 pterclub无法正常搜索，之前是正常的。比如搜索“指环王”只能出现两个音乐作品，其他电影类型的种子无法搜索，直接搜索电影类型的种子就会显示   “（网址）发生网络或其他错误”
试过更换插件版本，重新注销账号在登陆 再添加站点，都无法解决这个问题 其他网站都是正常能搜索的
- 相关截图：
![_20220825103325](https://user-images.githubusercontent.com/43180644/186561103-6f979a5d-7bb8-4227-af60-c99ca37518bb.png)

- 重现步骤：
{
  "name": "PTer",
  "timezoneOffset": "+0800",
  "description": "PT之友俱乐部",
  "url": "https://pterclub.com/",
  "icon": "https://pterclub.com/favicon.ico",
  "tags": ["影视", "综合"],
  "schema": "NexusPHP",
  "host": "pterclub.com",
  "formerHosts": [
    "pter.club"
  ],
  "searchEntryConfig": {
    "fieldSelector": {
      "title": {
        "selector": ["a[href*='details.php?id='][title]:first"],
        "filters": ["query"]
      },
      "subTitle": {
        "selector": ["div>span"],
        "filters": ["query.text().trim()"]
      },
      "progress": {
        "selector": [".progbargreen", ".progbarred + .progbarrest", ".progbarred", ".progbarrest", ""],
        "switchFilters": [
          ["100"],
          ["query.prev().attr('style').replace('width: ','').replace('%;','')"],
          ["100"],
          ["0"],
          ["null"]
        ]
      },
      "status": {
        "selector": [".progbargreen", ".progbarred + .progbarrest", ".progbarred", ".progbarrest"],
        "switchFilters": [
          ["2"],
          ["3"],
          ["255"],
          ["3"]
        ]
      }
    }
  },
  "searchEntry": [{
    "name": "综合",
    "enabled": true
  }, {
    "entry": "/torrents.php?search=$key$&notnewword=1",
    "name": "综合",
    "enabled": true
  }, {
    "entry": "/music.php?search=$key$&notnewword=1",
    "name": "音乐",
    "enabled": true
  }],
  "selectors": {
    "userExtendInfo": {
      "merge": true,
      "fields": {
        "bonus": {
          "selector": ["td.rowhead:contains('猫粮') + td, td.rowhead:contains('Karma Points') + td, td.rowhead:contains('貓糧') + td"],
          "filters": ["query.text().replace(/,/g,'')", "parseFloat(query)"]
        },
        "seedingSize": {
          "selector": ["td.rowhead:contains('做种大小') + td, td.rowhead:contains('Seeding Size') + td, td.rowhead:contains('做種大小') + td"],
          "filters": ["query.text().trim().sizeToNumber()"]
        }
      }
    },
    "userSeedingTorrents": {
      "page": "/getusertorrentlist.php?userid=$user.id$&type=seeding",
      "fields": {
        "seeding": {
          "selector": ["tr:not(:eq(0))"],
          "filters": ["query.find('td.rowfollow:eq(1)').length"]
        }
      }
    }
  },
  "plugins": [{
    "name": "保种和官方列表",
    "pages": ["/reseed.php", "/officialgroup.php"],
    "scripts": ["/schemas/NexusPHP/common.js", "/schemas/NexusPHP/torrents.js"]
  }],
  "mergeSchemaTagSelectors": true,
  "torrentTagSelectors": [{
    "name": "⛔️",
    "selector": "a[href*='torrents.php?tag_exclusive=yes']"
  }]
}

**Comment by ted423** [comment]
我这正常...

**Comment by ted423** [comment]
请提供，浏览器版本，背景页控制台报错
![image](https://user-images.githubusercontent.com/7042766/188394258-0ff71bb0-f631-406a-825a-85e408578fa5.png)

**Comment by 7788u** [comment]
![20220905155431](https://user-images.githubusercontent.com/43180644/188397976-2c1321d5-a84d-41e4-a4b0-9b7643834beb.png)
感谢。浏览器版本是： 版本 104.0.5112.102（正式版本） （64 位）

**Comment by ted423** [comment]
点到网络这看看状态
![image](https://user-images.githubusercontent.com/7042766/188414337-0e097688-8fce-462e-bc2c-64daa4e07b20.png)
然后你点进去看下预览的页面
能不能正常看到种子列表

**Comment by 7788u** [comment]
![20220905172320](https://user-images.githubusercontent.com/43180644/188416081-6065d3be-d538-42a0-b6ad-8090d2928c31.png)
谢谢。预览页面可以正常看到种子列表

**Comment by ted423** [comment]
能加载到页面一般是脚本执行哪里有问题，不排除受到其他因素干扰。

尝试下crx安装的看下呢？

**Comment by 7788u** [comment]
![20220905174842](https://user-images.githubusercontent.com/43180644/188420989-7f24fa94-26fc-47b5-8044-7d600d6f99b7.png)
尝试了crx，也是同样的情况

**Comment by ted423** [comment]
这种大概只能用你的浏览器调试看看了，停用所有其他扩展也还是一样是吧？路由有没有广告过滤之类的。或者有没有其他会改变页面元素的。
只有猫站会出现么

**Comment by ted423** [comment]
看下有没其他人遇到，要么就是你权限跟普通用户不同？

**Comment by 7788u** [comment]
好的，谢谢，那我先把问题关闭了？

**Comment by ted423** [comment]
不用，挂在这看看还有没其他人有这问题

**Comment by ted423** [comment]
我这似乎也出现了，可能之前是缓存

**Comment by ted423** [comment]
因为猫把列表页 种子标题 a 的 title 拿了。
完全不理解为什么要这么做

**Comment by 7788u** [comment]
竟然找到了原因，辛苦了

**Comment by ted423** [comment]
修了
