### ISSUE TITLE
添加任务时能否设置分类

### ISSUE THREAD

**Issue by Pollo3470** [ronggang/PT-Plugin-Plus#1109]
## 您的功能请求是否与问题有关？ 请描述一下。

qbittorrent可以在添加下载任务时设置文件分类，可以配合脚本实现自动生成硬链接

## 描述你想要的解决方案

设置下载目录时可以添加分类，可以参考nastools

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/1030
