### ISSUE TITLE
BUG：HDArea搜索结果链接到了评论界面

### ISSUE THREAD

**Issue by EthanLeen** [ronggang/PT-Plugin-Plus#111]
- PT 助手版本:104
- PT 助手安装方式：市场安装
- 浏览器名称及版本：google chrome 版本 73.0.3683.103（正式版本） （64 位）
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
HDArea搜索结果显示”添加评论“。点击之后跳转到了评论界面。

- 相关截图：
![3](https://user-images.githubusercontent.com/29567348/56275297-0c5a9480-6133-11e9-94b5-2e6de3db0340.png)
![4](https://user-images.githubusercontent.com/29567348/56275298-0cf32b00-6133-11e9-93b3-f7ab2d63b9de.png)

**Comment by ronggang** [comment]
@EthanLeen 无法直接复现

![image](https://user-images.githubusercontent.com/8065899/56284462-16868e00-6147-11e9-8b31-5e63511a2f0c.png)

可否提供一下直接在站点里搜索结果整个页面的截图？

**Comment by Rhilip** [comment]
同样无法复现。
请问是该站管理组成员吗？
是否因为是管理组成员导致和普通用户访问导致的页面布局不一致？

**Comment by EthanLeen** [comment]
> @EthanLeen 无法直接复现
> 
> ![image](https://user-images.githubusercontent.com/8065899/56284462-16868e00-6147-11e9-8b31-5e63511a2f0c.png)
> 
> 可否提供一下直接在站点里搜索结果整个页面的截图？

您好，经过测试：直接在站点搜索是正常的。


另外，插件中搜索站点只有TLF，显示正常；如果是所有网站不限制，就会出错。见截图
![所有网站](https://user-images.githubusercontent.com/29567348/56329770-bda30e00-61b7-11e9-8cce-a1d7283115a1.png)
![只是TLF](https://user-images.githubusercontent.com/29567348/56329771-bda30e00-61b7-11e9-9fea-da5f6124d030.png)

**Comment by EthanLeen** [comment]
> @EthanLeen 无法直接复现
> 
> ![image](https://user-images.githubusercontent.com/8065899/56284462-16868e00-6147-11e9-8b31-5e63511a2f0c.png)
> 
> 可否提供一下直接在站点里搜索结果整个页面的截图？

辛苦开发组了，经过测试，是种子悬浮提醒的问题，猜测和馒头的问题一样，关闭以后就可正常显示了。
![HDArea设置](https://user-images.githubusercontent.com/29567348/56330052-03aca180-61b9-11e9-917a-c3907f141c9d.png)

**Comment by EthanLeen** [comment]
> 同样无法复现。
> 请问是该站管理组成员吗？
> 是否因为是管理组成员导致和普通用户访问导致的页面布局不一致？

感谢R酱的提醒，我想起来也是因为悬浮设置的问题，馒头搜索结果名称为空的问题，HDArea问题和馒头一样。再次感谢，已解决。
