### ISSUE TITLE
做种体积显示与网站显示不同

### ISSUE THREAD

**Issue by fan-cy** [ronggang/PT-Plugin-Plus#112]
- PT 助手版本:1.0.4
- PT 助手安装方式：安装包
- 浏览器名称及版本：73.0.3683.103
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：ttg做种体积显示与网站显示不同
- 相关截图：
![999](https://user-images.githubusercontent.com/30803671/56337015-880d1d80-61d5-11e9-8d3a-8d6daed60bc0.JPG)

**Comment by ronggang** [comment]
@fan-cy 助手目前是根据个人页面的上传种子列表体积进行合计得出的做种体积，和积分页的确不一样，我也不清楚积分页的做种体积是如何计算出来的。

**Comment by dawei233** [comment]
已经下载完的资源 才算是做种体积，没下载完的不算
