### ISSUE TITLE
观众和聆音两个站点搜索一直报错“未指定搜索入口”

### ISSUE THREAD

**Issue by mikulo** [ronggang/PT-Plugin-Plus#1123]
- PT 助手版本:  v1.5.2.4ece586
- PT 助手安装方式：CRX安装
- 浏览器名称及版本：Microsoft Edge 103.0.1264.77 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：搜索资源时观众和聆音两个站点一直报“未指定搜索入口”,但是其它站点正常，手动访问两个站点也是可以访问并且搜索的，站点设置里搜索功能也是打开的，尝试过重装插件以及站点，但是都不起作用，具体如图所示:

- 相关截图：
![image](https://user-images.githubusercontent.com/46894621/190293679-b9e7ef54-5959-4623-a506-1d65d747e7a2.png)
![image](https://user-images.githubusercontent.com/46894621/190293740-8f7f725e-161b-40e6-92b5-4eb258b285c2.png)

- 重现步骤：

**Comment by ted423** [comment]
无法再现
![image](https://user-images.githubusercontent.com/7042766/190305694-47b3f63d-d3da-449e-8e71-fdc9b88ae8da.png)

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/190305967-97fb42a3-fe61-4c01-8899-77f64fb06bfa.png)
看起来也应该支持，不过我没号

**Comment by ted423** [comment]
群内已处理，not a bug
