### ISSUE TITLE
当为Peasant时，下载整页数据会出现bug，直接下载网页

### ISSUE THREAD

**Issue by lyj0309** [ronggang/PT-Plugin-Plus#1125]
- PT 助手版本:  1.5.2
- PT 助手安装方式：市场安装
- 浏览器名称及版本：edge-latest
- 浏览器是否安装了其他插件：no
- 停用其他插件后是否正常工作： yes
- 问题描述：
如题，不管是下载到还是下载所以种子，都是不好使的

- 相关截图：
![image](https://user-images.githubusercontent.com/50474995/190538429-211766a5-125e-415b-9ef4-a453592fdc8d.png)

- 重现步骤：
1. 人是Peasant
2. 找到一个列表页
3. 下载全部种子

**Comment by ted423** [comment]
理论上Peasant就不要一页一页的下种子了，已有相关问题，在那个问题讨论即可
