### ISSUE TITLE
获取不到nicept做种量数据

### ISSUE THREAD

**Issue by LeviLXZ** [ronggang/PT-Plugin-Plus#1128]
- PT 助手版本:v1.5.2
- PT 助手安装方式：zip包安装（市场安装，或zip包安装）
- 浏览器名称及版本：chrome104.0.5112.102
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：
- 问题描述：
获取不到nicept做种量数据

- 相关截图：

![photo_2022-09-20_17-50-37](https://user-images.githubusercontent.com/20102865/191226919-a9686135-59c8-4833-aed2-44ff2112c2d5.jpg)
![QQ截图20220920175055](https://user-images.githubusercontent.com/20102865/191226949-da3ce635-4d7f-4a85-9f50-2327b13bdd29.jpg)

- 重现步骤：

**Comment by KyleHo94** [comment]
Hares Club同样获取不到nicept做种量数据

**Comment by ted423** [comment]
请先把项目的readme看了
