### ISSUE TITLE
我的数据里，如何更新各个站点的登记数据，发现有几个站点数据和官方不一致了

### ISSUE THREAD

**Issue by wuzheng40** [ronggang/PT-Plugin-Plus#1129]
- PT 助手版本:1.5.2.f2e4f20
- PT 助手安装方式：Chrome 插件
- 浏览器名称及版本：Chrome 105.0.5195.127（正式版本） （64 位）
- 浏览器是否安装了其他插件：没有
- 停用其他插件后是否正常工作：无法尝试
- 问题描述：
我的数据里，如何更新各个站点的等级数据，比如mteam的计算有差异

- 相关截图：
![image](https://user-images.githubusercontent.com/1391798/191883910-5eabb14b-0f3c-41f5-801f-ef7330c08c53.png)

- 重现步骤：

**Comment by ted423** [comment]
这个是白大版的问题，原版没这个功能

**Comment by wuzheng40** [comment]
感谢解答
