### ISSUE TITLE
建议增加未读站内信及重要公告数字角标

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#113]
建议在配置页手动刷新用户数据后，在站点图片后方显示未读站内信或者重要公告数量的角标。
如果可以的话，能够直接在插件图标显示角标就更好了，但是这样就得自动刷新数据。不知道是否可以采用服务端抓取各站点发送站内信或者公告的情况，远程推送数量信息到各个每个用户显示角标。这样想实现起来好像比较麻烦，也不知道是否有对应接口。

**Comment by ronggang** [comment]
谢谢建议，之前是有考虑过，后面应该会加入

**Comment by alen84204** [comment]
都是怎麼抓各站點的資料阿

**Comment by ronggang** [comment]
> 都是怎麼抓各站點的資料阿

基本上是读取指定页面html，获取指定的DOM内容。

**Comment by ronggang** [comment]
@luckiestone 已增加刷新数据时，获取站点信息数量 d749b529ab12ab148ac6af23fe176bac6d554848
请更新至最新版本。
