### ISSUE TITLE
hdfans、1PTBar、HDTime三个站点不显示做种体积

### ISSUE THREAD

**Issue by wagonew** [ronggang/PT-Plugin-Plus#1130]
- PT 助手版本:1.5.2
- PT 助手安装方式：zip（市场安装，或zip包安装）
- 浏览器名称及版本：360极速浏览器
- 浏览器是否安装了其他插件：安装了
- 停用其他插件后是否正常工作：仍不正常
- 问题描述：
hdfans、1PTBar、HDTime三个站点不显示做种体积，其他参数正常

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/1122 并案处理
