### ISSUE TITLE
插件显示的BTSCHOOL（学校）做种数量与实际做种数量不符

### ISSUE THREAD

**Issue by LoneFireBlossom** [ronggang/PT-Plugin-Plus#1132]
- PT 助手版本: 版本 v1.5.2.62267bc zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome  106.0.5249.61（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：依旧没有解决这个问题
- 问题描述：
学校网站上显示的做种数量和体积，与插件显示的不一致。

- 相关截图：
![image](https://user-images.githubusercontent.com/50087596/192994084-bf1482b9-5d78-4949-884a-ca70e2fb572b.png)

![image](https://user-images.githubusercontent.com/50087596/192994238-97f682be-84c3-41a1-8e83-cbf49b3e47c6.png)

- 重现步骤：

不需要写重现步骤吧，怎么刷新插件的读取也还是这样
我的其它站没有这个问题

**Comment by ted423** [comment]
看了下，其实网站的计算是不准的，双IP会计算两倍体积导致体积翻倍
![image](https://user-images.githubusercontent.com/7042766/197495901-fbc5eb68-ca98-465d-90ef-42526c0eb8c9.png)

不过也可以考虑以网站为准，因为btschool的提供信息的方式，还可以减少一次请求

**Comment by LoneFireBlossom** [comment]
© 栽培者 2022, 版本 v1.5.2.d1e8200 zip
学校更新了一下个人中心界面，现在做种体积读取不到了

<img width="340" alt="image" src="https://user-images.githubusercontent.com/50087596/199722299-bd160827-64c9-4157-a497-b91b7588f67f.png">

我觉得是不是把上面fix （ https://github.com/ronggang/PT-Plugin-Plus/commit/a3789140f95e4bfca6a05af2cce0c5b33926bde9 ）里的
`"filters": [ "query.text().replace(/.*共计/g,'').replace(')','')", "query.sizeToNumber()" ]`
改了就行了？

**Comment by LoneFireBlossom** [comment]
……怎么代码又回滚了
<img width="962" alt="image" src="https://user-images.githubusercontent.com/50087596/199860792-2720dc09-4ebe-4ae7-a075-28810c655f14.png">
