### ISSUE TITLE
猫站游戏种子页面不显示侧边工具栏

### ISSUE THREAD

**Issue by KempLeung** [ronggang/PT-Plugin-Plus#1133]
- PT 助手版本:v1.5.2.f2e4f20
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge 版本 106.0.1370.30 (正式版本) beta (64 位)
- 浏览器是否安装了其他插件：ADBlock 5.1.1，Tampermonkey 4.16.1（无脚本加载），Google翻译，EditThisCookies 1.6.3，IDM Integration Module 5.1.1，购物党自动比价工具 5.11.61，IE Tab 15.8.13.1，EverSync 19.1.5，
- 停用其他插件后是否正常工作：否
- 问题描述：猫站游戏种子页面不显示侧边工具栏，其他分类正常

- 相关截图：

- 重现步骤：打开任意猫站游戏类种子页面

**Comment by ted423** [comment]
先更新action版本

**Comment by KempLeung** [comment]
> 先更新action版本

更新了action版问题依旧

**Comment by ted423** [comment]
比如更新到了什么版本
种子列表页还是详情页

**Comment by KempLeung** [comment]
> 比如更新到了什么版本 种子列表页还是详情页

更新到了1.5.2.62267bc
详情页不显示侧边工具栏，种子列表正常
仅是游戏种子如此，其他类型正常
