### ISSUE TITLE
白兔俱乐部不显示做种体积和数量

### ISSUE THREAD

**Issue by caodapengrom** [ronggang/PT-Plugin-Plus#1134]
- PT 助手版本:v1.5.2.62267bc 
- PT 助手安装方式：zip
- 浏览器名称及版本：chrome106.0.5249.91
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：白兔俱乐部不显示做种体积和数量

- 相关截图：
![image](https://user-images.githubusercontent.com/97927797/193620495-b91a9257-dc85-4456-abb5-82ecf89555c3.png)

- 重现步骤：刷新数据

**Comment by ted423** [comment]
站点改版了，并且似乎不让直接访问获取信息的页面

**Comment by first1117** [comment]
同样的问题
