### ISSUE TITLE
海胆之家，刷新显示出错

### ISSUE THREAD

**Issue by starsjf** [ronggang/PT-Plugin-Plus#1138]
- PT 助手版本: v1.5.2.99ab2de
- PT 助手安装方式：zip安装
- 浏览器名称及版本：Edge 106.0.1370.42 
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

海胆之家，首页刷新显示出错，可以打开网页，但是PTPP一直说“发生错误”，重新添加也不行。

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
没这个站的号，无法测试，不知道是不是改版过？

**Comment by ryuubillow** [comment]
正常

**Comment by starsjf** [comment]
今天又重新清空缓存，清空cookie，重新登陆后可以了。此贴终结。
