### ISSUE TITLE
服务器无法连接，按照issue34解决后无效

### ISSUE THREAD

**Issue by edogawalee** [ronggang/PT-Plugin-Plus#114]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.4
- PT 助手安装方式：市场（市场安装，或zip包安装）
- 浏览器名称及版本：Chrome 73
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作： 否
- 问题描述：
1.直接选择服务器下载时显示无效的种子文件。选择下载种子文件到本地时，HDHome直接显示invalid passkey无法跳转。OpenCD只能跳转至主页面。
2.在页面悬浮插件选择下载至...时始终显示下载服务器超时，然而在设置里面服务器测试连接是通过的。

- 相关截图：
![1](https://user-images.githubusercontent.com/33904070/56384400-d9a5be80-624e-11e9-83c2-acd30c6c0425.png)
![2](https://user-images.githubusercontent.com/33904070/56384407-ddd1dc00-624e-11e9-8945-c9ebdab06c00.png)

**Comment by ronggang** [comment]
1、请参考wiki
https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E9%94%AE%E4%B8%8B%E8%BD%BD%E6%97%B6%E4%BC%9A%E6%8F%90%E7%A4%BA-%E6%97%A0%E6%95%88%E7%9A%84%E7%A7%8D%E5%AD%90%E6%96%87%E4%BB%B6-

2. 请描述具体的服务器类型

**Comment by edogawalee** [comment]
> 1、请参考wiki
> https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E9%94%AE%E4%B8%8B%E8%BD%BD%E6%97%B6%E4%BC%9A%E6%8F%90%E7%A4%BA-%E6%97%A0%E6%95%88%E7%9A%84%E7%A7%8D%E5%AD%90%E6%96%87%E4%BB%B6-
> 
> 1. 请描述具体的服务器类型

服务器是transmission 2.84，刷了OpenWrt Barrier Breaker 14.07 / LuCI Trunk (0.12+svn-r10530) 的下载博爱

**Comment by edogawalee** [comment]
> 1、请参考wiki
> https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E9%94%AE%E4%B8%8B%E8%BD%BD%E6%97%B6%E4%BC%9A%E6%8F%90%E7%A4%BA-%E6%97%A0%E6%95%88%E7%9A%84%E7%A7%8D%E5%AD%90%E6%96%87%E4%BB%B6-
> 
> 1. 请描述具体的服务器类型

![image](https://user-images.githubusercontent.com/33904070/56464807-d1eb4300-6423-11e9-8703-39c0a4ad356b.png)
这是我rpc的配置 麻烦您看一下，现在测试服务器的时候显示连接失败，按照issue34的方式也没有解决

**Comment by ronggang** [comment]
@edogawalee 你没有启用用户名和密码的方式是吗？你启用一下试试是否可以正常连接。
另外，看你第一张截图是下载种子超时，此时还没有发送到下载服务器。

**Comment by edogawalee** [comment]
> @edogawalee 你没有启用用户名和密码的方式是吗？你启用一下试试是否可以正常连接。
> 另外，看你第一张截图是下载种子超时，此时还没有发送到下载服务器。

按您的方法，测试的时候显示timeout

**Comment by ronggang** [comment]
@edogawalee 这样看不出问题来。
你直接访问TR的web页面看看能不能正常登录。
或参考
https://github.com/ronggang/PT-Plugin-Plus/issues/32#issuecomment-465859924
