### ISSUE TITLE
sysnology downloadstation无法添加，同时账号不安全

### ISSUE THREAD

**Issue by tyejuan** [ronggang/PT-Plugin-Plus#1142]
- 
添加下载服务器时无法添加sysnology downloadstation，群晖版本是DSM7.1，服务器测试没问题，就是身份认证失败，无法添加。另外账号不安全，我是填的外网转发后的服务器地址，和群晖的账号密码。没过多久，过了几个小时就发现有外地的IP使用我的账号登录了我的群晖。我填写的账号信息相对于管理员来说也许是透明的，这是万分的令人不安。。。。。。

**Comment by tyejuan** [comment]
只敢用局域网地址去测试

**Comment by ted423** [comment]
提issue前请先搜索
