### ISSUE TITLE
HDArea 站点中搜索结果存在大量 “添加评论” 的结果

### ISSUE THREAD

**Issue by Ghost-chu** [ronggang/PT-Plugin-Plus#1146]
- PT 助手版本: 1.5.2.f2e4f20
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Micorosoft Edge 106.0.1370.52 (正式版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
在 HDArea 站点搜索任意关键字，会出现大量 “添加评论” 结果，且点击进入确实是添加评论

- 相关截图：
![image](https://user-images.githubusercontent.com/30802565/197384161-7be7b6b7-0882-4e47-a38a-a495bea534b8.png)

- 重现步骤：
点击搜索框，输入 `海贼王` 或者其他关键字。
向下滚动即可重现。

日志请见附件，配置不便上传，HDA 为使用自动导入功能从浏览器中识别。

[PT-Plugin-Plus-System-Logs.zip](https://github.com/ronggang/PT-Plugin-Plus/files/9846112/PT-Plugin-Plus-System-Logs.zip)

**Comment by Ghost-chu** [comment]
更新：
使用 Action 版本 `1.5.2.9af1753` 后，该问题依旧存在

**Comment by ted423** [comment]
发现开了这俩后会出问题
![image](https://user-images.githubusercontent.com/7042766/197390302-de983fd3-aec0-4486-b17a-6ec05c822883.png)

**Comment by ted423** [comment]
测试是上面那个问题
并且该设置项应该没法体现作用了
