### ISSUE TITLE
frds站无法显示种子大小、做种数等信息

### ISSUE THREAD

**Issue by caodapengrom** [ronggang/PT-Plugin-Plus#1147]
- PT 助手版本:v1.5.2.62267bc
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 106.0.5249.119
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：frds站搜索结果均无种子大小、做种数等信息

- 相关截图：
![image](https://user-images.githubusercontent.com/97927797/197452320-d3e256dc-b692-44f2-b367-940ad8a55270.png)

- 重现步骤：
选择frds站获取第一页种子

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/commit/9adc5f4ca7e32335146571ec6899a57387964402
