### ISSUE TITLE
影片信息

### ISSUE THREAD

**Issue by shuer001** [ronggang/PT-Plugin-Plus#115]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.5
- PT 助手安装方式：（zip包安装）
- 浏览器名称及版本：Chrome 73.0.3683.103
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：①非NexusPHP站点，比如ttg，用豆瓣页面助手搜索提示无结果，是bug还是不支持? 
②目前显示影片信息很棒， 是否有助手内输入电影名搜索时也能显示影片信息的可能？ 

- 相关截图：

**Comment by ronggang** [comment]
@shuer001 
后续会进一步支持；
