### ISSUE TITLE
无法批量下载

### ISSUE THREAD

**Issue by YanceyWang** [ronggang/PT-Plugin-Plus#1151]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装） zip
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：
- 问题描述：
![image](https://user-images.githubusercontent.com/6010208/198282467-ebf52d10-03dd-4d84-967a-5e07676ed509.png)

![image](https://user-images.githubusercontent.com/6010208/198282500-a760b533-97aa-4219-bc91-1bd17f3e1d32.png)

批量下载时候没法正常下载，获取的每个下载链接是不正确的吧？

**Comment by ted423** [comment]
肯定会失败的，因为对玉站点来说你没登陆，要不用passkey,要不本地推送

**Comment by YanceyWang** [comment]
> ，状态码401 Unauthorized 代表客户端错误，

请问怎么解决？网站是自动导入的，cookie也不需要我手动设置吧？

**Comment by ted423** [comment]
询问网站方是否有流控，有些站不能太多一起下载

**Comment by Victor9578** [comment]
我也是 这个报错 点进详情 右击面板 就可以下载，在list页面 这个url不对吧 ，结尾都是https=1
