### ISSUE TITLE
请问是否考虑做成网页服务脱离浏览器运行？

### ISSUE THREAD

**Issue by xflcx1991** [ronggang/PT-Plugin-Plus#1162]
## 您的功能请求是否与问题有关？ 请描述一下。
我是PT助手PLUS新手，不知道多台设备多个浏览器都安装PT助手PLUS是否会导致数据统计不同步。如果不同步，那对多设备使用人员将是个麻烦：因为只能固定一台设备的某个浏览器来使用

## 描述你想要的解决方案
改造成HTTP服务，这样就解放了浏览器插件，可以虚拟机或者docker部署

## 描述您考虑过的替代方案
暂无

## 其他附加信息
暂无

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/1045

**Comment by Rhilip** [comment]
目前已经有很多类似功能替代的软件，PTPP不会考虑。
如： 
- Vertex： https://github.com/vertex-app/vertex
- nastools
- Jackett： https://github.com/Jackett/Jackett

**Comment by xflcx1991** [comment]
> 目前已经有很多类似功能替代的软件，PTPP不会考虑。 如：
> 
>     * Vertex： https://github.com/vertex-app/vertex
> 
>     * nastools： https://github.com/jxxghp/nas-tools
> 
>     * Jackett： https://github.com/Jackett/Jackett

感谢推荐
