### ISSUE TITLE
按照CRX安装的方法无法安装，提示程序包无效：“CRX_REQUIRED_PROOF_MISSING”

### ISSUE THREAD

**Issue by Glenffi** [ronggang/PT-Plugin-Plus#1166]
- PT 助手版本:[dev-build-d1e8200-crx](https://github.com/ronggang/PT-Plugin-Plus/suites/9103555344/artifacts/422202893)
- PT 助手安装方式：CRX安装
- 浏览器名称及版本：Chrome 版本 107.0.5304.89（正式版本）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：按照CRX安装的方法无法安装，提示程序包无效：“CRX_REQUIRED_PROOF_MISSING”

- 相关截图：
![image](https://user-images.githubusercontent.com/56630896/201051984-344c9951-9856-4ad2-a756-7642bd1e3e49.png)
![image](https://user-images.githubusercontent.com/56630896/201052019-7c16e6fa-bed2-489a-8859-94930e9b0160.png)
![image](https://user-images.githubusercontent.com/56630896/201052058-880f278f-026c-4bf5-9214-abb529249524.png)

- 重现步骤：正常按照[CRX安装](https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx)方法步骤

**Comment by Mywifi** [comment]
我也遇到这个问题了，咋解决的？
