### ISSUE TITLE
搜索结果显示 没有返回预期的数据

### ISSUE THREAD

**Issue by dumpling13** [ronggang/PT-Plugin-Plus#1167]
- PT 助手版本: 最新开发版
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome最新版
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
- 资源搜索时部分站点会提示 没有返回预期的数据 目前我这边的有GPW海豹 DIC海豚 HDAI海带
![微信截图_20221111142004](https://user-images.githubusercontent.com/117969279/201276447-c8f4481b-dd09-485d-b737-b680d9b828bd.png)

**Comment by ted423** [comment]
没有返回预期的数据可能是没有结果。
看你搜索的什么
