### ISSUE TITLE
北邮人BT域名已改

### ISSUE THREAD

**Issue by Looong01** [ronggang/PT-Plugin-Plus#1169]
由原来的bt.byr.cn改为了byr.pt

- PT 助手版本:1
- PT 助手安装方式：（市场安装，或zip包安装）1
- 浏览器名称及版本：1
- 浏览器是否安装了其他插件：1
- 停用其他插件后是否正常工作：1
- 问题描述：1

- 相关截图：1

- 重现步骤：1

**Comment by ted423** [comment]
不正确的信息
