### ISSUE TITLE
北邮人BT域名已改（已添加截图和复现步骤）

### ISSUE THREAD

**Issue by Looong01** [ronggang/PT-Plugin-Plus#1170]
由原来的bt.byr.cn改为了byr.pt

- PT 助手版本:0
- PT 助手安装方式：（市场安装，或zip包安装）0
- 浏览器名称及版本：0
- 浏览器是否安装了其他插件：0
- 停用其他插件后是否正常工作：0
- 问题描述：0

- 相关截图：
- 
![image](https://user-images.githubusercontent.com/69568351/201797024-36a25bbf-aa2c-4270-ba7e-b6eecb794342.png)
![image](https://user-images.githubusercontent.com/69568351/201797056-a96cf844-058e-434c-b367-4db65830c351.png)

- 重现步骤：
- 1. 浏览器打开bt.byr.cn，要求跳转byr.pt

**Comment by ted423** [comment]
readme有说明过，请使用最新的action版本。
扩展版本信息这些你要提issue,就得写。
提issue前先搜索相关issue

**Comment by ted423** [comment]
这个问题很早前就修过了

**Comment by Looong01** [comment]
> 

扩展版本指的是浏览器的插件商店的版本吗

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx
基于谷歌商店的问题，后续可能不太会继续在官方扩展商店更新

**Comment by Looong01** [comment]
> https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx 基于谷歌商店的问题，后续可能不太会继续在官方扩展商店更新

我是从edge的微软商店下载的，这个版本也不是最新的吗，能不能更新一下呢
