### ISSUE TITLE
HDTime 不显示做种体积

### ISSUE THREAD

**Issue by lyj0309** [ronggang/PT-Plugin-Plus#1173]
- PT 助手版本:d1e8200
- PT 助手安装方式：zip
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
无法获取到hdtime的做种体积

- 相关截图：

![image](https://user-images.githubusercontent.com/50474995/202348681-d1a4e145-d89a-4743-bfce-52095ee86188.png)

- 重现步骤：

**Comment by ted423** [comment]
之前修过 不清楚是界面又有改版还是语言设置之类的问题

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/pull/1089
https://github.com/ronggang/PT-Plugin-Plus/pull/1131
而且都修过两次了..

**Comment by lyj0309** [comment]
> #1089 #1131 而且都修过两次了..

我感觉应该能获取到的
![image](https://user-images.githubusercontent.com/50474995/202479538-9eaca912-8fb3-49c1-a163-e0a505d055c3.png)
我想问问这个`query`是jquery吗`query.text()`包含html标签吗

**Comment by ted423** [comment]
query是selecter获取到的jquery结果，.text()就是输出文本

**Comment by ted423** [comment]
看下这个commit有没有修好
https://github.com/ronggang/PT-Plugin-Plus/commit/522d241c2631805ec2dd6b043abc01e7a3c44321#diff-4ca9589c5d865ed6259c2a36ba0cadcb8352dc0245cf1aac6b6c98a9f3333c72
