### ISSUE TITLE
希望增加发送种子时自动在目录新建文件夹的功能

### ISSUE THREAD

**Issue by Cyberxxt** [ronggang/PT-Plugin-Plus#1175]
## 您的功能请求是否与问题有关？ 请描述一下。

很多站点的种子下载后只有一个单独的视频，刮削之后会在根目录创建很多关联的文件看着很乱。
现在的解决方法是在tr里每次手动输入一个子目录的文件夹去存放视频以及刮削的文件，但这样只能手动下载种子，因为pt助手不能在下载时手动指定目录。

## 描述你想要的解决方案

可以在增加一个功能，使发送种子的同时在目的地文件夹新建一个和种子同名称的目录，这样刮削的资料不会全都堆在根目录里了。
或者增加发送地址后手动选择目录的步骤的开关，这样也可以手动指定目录。

## 其他附加信息

希望实现这样的层级
![image](https://user-images.githubusercontent.com/40683077/202653872-bb5df16c-394e-4f7b-ab9d-431eaf43c3b7.png)

**Comment by ted423** [comment]
ptpp不涉及到修改新增文件夹的操作，这部只能在下载器里操作。
其次PTPP是不会去解析种子的，因此无法判断种子是否单文件。也无法获取到种子里的文件名，顶多知道种子名，如果种子名不标准，那么后续都无法操作。
推荐操作是暂停推入下载器，然后手动修改路径。
