### ISSUE TITLE
关于增加hawke.uno的站点请求

### ISSUE THREAD

**Issue by yzlyu** [ronggang/PT-Plugin-Plus#1178]
- 站点名称：hawke.uno
- 站点地址：https://hawke.uno/
- 站点描述：hawke-one (aka HONE) is a DISCORD COMMUNITY built around media entertainment offering a cutting-edge Plex Streaming Service and a secure Internal Private Tracker. As such, we are not just a group of silent binge enthusiasts but we amplify that experience through a diverse and active membership base that spans the globe.

- 资源类型：
- 开放注册：是
- 是否连坐：否
- 站点规则：有5天HR要求

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/pull/1177
