### ISSUE TITLE
明教pt论坛无法用右键下载种子，提示无效种子

### ISSUE THREAD

**Issue by gwfblank** [ronggang/PT-Plugin-Plus#1179]
- PT 助手版本:1.5.2.f2e4f20
- PT 助手安装方式：（市场安装，）
- 浏览器名称及版本：360 13.1
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：是
- 问题描述：
明教pt论坛无法用右键下载种子，还是提示无效种子
我已经自己手动下载过好几次种子了，依旧提示无效，但是直接把标题拖入右侧就好使
其他pt论坛都可以直接右键标题下载种子添加到qb

**Comment by ted423** [comment]
请安装action的版本
