### ISSUE TITLE
M-TEAM大种子添加失败

### ISSUE THREAD

**Issue by shuer001** [ronggang/PT-Plugin-Plus#118]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.5.1
- PT 助手安装方式：zip包安装
- 浏览器名称及版本： Chrome 73 .0.3683.103
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：mteam服务器下载大种子都会提示超时 错误。（60G以上都会）  小种子一次成功。其它站点无此问题。  手动下载种子文件到本地正常 

- 相关截图：

**Comment by shuer001** [comment]
经过测试，应该是mteam的站点连接性不好，修改基本设置里的 连接下载服务器的超时时间，大文件可以成功下载，
希望修复下载历史中 超时错误 状态提示为✔的bug  。

**Comment by ronggang** [comment]
> 经过测试，应该是mteam的站点连接性不好，修改基本设置里的 连接下载服务器的超时时间，大文件可以成功下载，
> 希望修复下载历史中 超时错误 状态提示为✔的bug 。

感谢反馈。

**Comment by ronggang** [comment]
@shuer001 请更新至v1.0.6后再试试问题是否还存在，本主题先关闭。

**Comment by shuer001** [comment]
> @ shuer001请更新至1.0.6后再试试问题是否还存在，本主题先关闭。

1.0.6下载超时错误后， 下载历史还是✔ 提示，希望能改为×提示。 
下载大文件目前正常，（1.0.5.1调整时间后也能正常下载，具体可能和服务器波动有关）后续继续测试.
