### ISSUE TITLE
BLU 无法获取搜索结果

### ISSUE THREAD

**Issue by Mark-Imaginist** [ronggang/PT-Plugin-Plus#1189]
- PT 助手版本:v1.5.2.6992454
- PT 助手安装方式：zip
- 浏览器名称及版本：Edge 108.0.1462.42
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：BLU 无法获取搜索结果

- 相关截图：
<img width="423" alt="Snipaste_2022-12-07_21-47-35" src="https://user-images.githubusercontent.com/38615702/206196888-5f4bdda4-0aa3-49ac-a09a-a791ec5756d3.png">
<img width="785" alt="Snipaste_2022-12-07_21-51-27" src="https://user-images.githubusercontent.com/38615702/206196899-52c85cb2-c2a6-4c2d-84f0-a65d5604e1b1.png">

- 重现步骤：使用关键字或 IMDb 编号搜索

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/commit/dc47f44dc43eb2dc4c8a100bbf1bf58d2be25a02
