### ISSUE TITLE
RED站信息读取不完整，插件安装方式识别错误

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#119]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本： 73.0.3683.103（正式版本）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
1. 配置首页，RED站除了用户名能够正确读取，其他数据均不能读取，上传下载都为0，还有该站没有bonus系统，对应栏建议显示为N/A。
2. 首页左下角应该显示的是插件安装方式，我插件是Chrome商店的，但是版本号右边显示的是zip。

- 相关截图：

**Comment by ronggang** [comment]
@luckiestone 感谢反馈
1. RED 站并未做个人信息适配，支持情况可参考：https://github.com/ronggang/PT-Plugin-Plus/wiki/supported-sites ；另外，下次会把不支持的问题显示为 N/A；

2. 是我的问题，打包之前没把测试参数调整回来。

**Comment by luckiestone** [comment]
> @luckiestone 感谢反馈
> 
> 1. RED 站并未做个人信息适配，支持情况可参考：https://github.com/ronggang/PT-Plugin-Plus/wiki/supported-sites ；另外，下次会把不支持的问题显示为 N/A；
> 2. 是我的问题，打包之前没把测试参数调整回来。

感谢回复，辛苦了！

**Comment by ronggang** [comment]
@luckiestone 安装方式识别问题已修复 (f1e933dc1dea6044559b6b951b11b586be7fdf0a)，本主题先关闭。
