### ISSUE TITLE
NicePT、HDAtmos、IPT三个站点做种体积不显示

### ISSUE THREAD

**Issue by luboshi-founder** [ronggang/PT-Plugin-Plus#1193]
- PT 助手版本:© 栽培者 2022, 版本 v1.5.2.f2e4f20 zip
- PT 助手安装方式：zip包安装（市场安装，或zip包安装）
- 浏览器名称及版本：Google Chrome  版本 107.0.5304.63（正式版本） （64 位）
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
1、NicePT、HDAtmos、IPT三个站点做种体积不显示
2、NicePT、HDAtmos两个站点做种数显示错误，实际保重数量站点直接显示均超100，ptpp里不能显示大于100做种数。
- 相关截图：
![image](https://user-images.githubusercontent.com/120150551/206610987-22969957-428f-47a1-af14-2f329d41d708.png)
<img width="475" alt="225" src="https://user-images.githubusercontent.com/120150551/206611255-7dbe29ca-1b5a-4885-8ecd-d79cce7ae5ab.png">
<img width="394" alt="159" src="https://user-images.githubusercontent.com/120150551/206611266-b69853f6-2a3e-47bf-b1b2-f490e3d123f8.png">

- 重现步骤：
其它多个站点保种数和做种体积均正常，重新下载PTPP 1.5.2版本这3个站点依然相同问题

**Comment by ted423** [comment]
ipt不准备支持做种体积
扩展版本错误
