### ISSUE TITLE
BLU搜不到种子

### ISSUE THREAD

**Issue by LoneFireBlossom** [ronggang/PT-Plugin-Plus#1195]
- PT 助手版本: 栽培者 2022, 版本 v1.5.2.c81e4e7 zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：版本 108.0.5359.98（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：依旧有下面的问题
- 问题描述：

blutopia在PTPP里搜索，显示没有结果。（不是网络请求失败）
例如搜索“law order”，在BLU网站里搜索能搜出很多，但是在PTPP里搜索就啥也没有。不知道是我这边的问题还是啥

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
dupe https://github.com/ronggang/PT-Plugin-Plus/issues/1189
