### ISSUE TITLE
自定义搜索URL

### ISSUE THREAD

**Issue by LoneFireBlossom** [ronggang/PT-Plugin-Plus#1196]
## 您的功能请求是否与问题有关？ 请描述一下。

目前在PTPP中搜索有遇到两个问题：

1. 有些站点如UNIT3D架构的站点（如BHD），搜索结果默认每页只显示25条，我把它改成100条后，下次搜索它还会自己变回来；在PTPP里搜索时，无论“搜索时每站点显示结果数量”是多少，搜索都只显示25条，这样数量太少了，我一直没有找到在哪里能更改这个设置（NexusPHP架构的站点都能设置成最大100条，UNIT3D的我一直没找到）。
<img width="337" alt="image" src="https://user-images.githubusercontent.com/50087596/206683267-886d65f8-950f-4a97-a863-f0eb1277b85b.png">

2. 有的时候一个站点的搜索结果显示100条也不够，比如说搜索“Doraemon”想要找TV旧版大山版/新版水田版下载、辅种，会搜出一大堆哆啦A梦相关的动画电影，好些站点的搜索结果都超过了100。但又不方便加关键词，因为有些种子并没有额外标注“TV/大山/水田”等信息。这样就只能自己再额外到那些站点单独搜索一遍，特别麻烦。

## 描述你想要的解决方案

如果PTPP能够自动自定义搜索URL的话就好了，例如`https://www.baidu.com/s?wd={query}`。

1.「每页显示的搜索结果数量」是在BHD的链接里就显示为
`https://xxxxxxxxxxxxx/torrents?search={query}&doSearch=Search&(其它搜索语法，略)&qty=100`。
2. 单站搜索结果超过100的话，我去站点单独搜索的时候一般会选择「按照资源体积大小降序排列」，体积小的那些一般都是没什么用的，反应在馒头的链接里就显示为`https://kp.m-team.cc/torrents.php?incldead=0&spstate=0&inclbookmarked=2&search={query}&search_area=0&search_mode=0&sort=5&type=desc`。

所以，如果PTPP能够允许用户自定义指定站点的搜索URL的话，第一个问题就能解决，第二个问题能得到极大缓解。
这种功能在一些实用软件里也有，例如Alfred：

> Adding a Custom Search URL manually

![image](https://user-images.githubusercontent.com/50087596/206686361-6e786386-87cf-4675-a50b-4abb0b8920f2.png)

https://www.alfredapp.com/help/features/web-search/custom-searches/

**Comment by ted423** [comment]
u3d应该没办法，因为默认都是一页返回25条

**Comment by ted423** [comment]
自定义比较复杂，我先试着默认都 &qty=100好了

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/206703813-577e20c6-d46c-4d66-b500-a8fd99846dd8.png)

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/206704036-9ce7fd07-d16b-4808-b5b6-b7a49b68af5d.png)
这个位置原来有

**Comment by LoneFireBlossom** [comment]
NEXUSPHP的站点似乎都可以这么设置，不过UNIT3D的点击了添加没反应（例如monikadesign，bhd）？

<img width="778" alt="image" src="https://user-images.githubusercontent.com/50087596/206822283-5ced9232-9588-433f-8ad9-a3ed0ddb557d.png">

**Comment by ted423** [comment]
> NEXUSPHP的站点似乎都可以这么设置，不过UNIT3D的点击了添加没反应（例如monikadesign，bhd）？
> 
> <img alt="image" width="778" src="https://user-images.githubusercontent.com/50087596/206822283-5ced9232-9588-433f-8ad9-a3ed0ddb557d.png">

u3d有不同的版本，bhd最新的已经设置100了，是用 &qty=100

**Comment by LoneFireBlossom** [comment]
> u3d有不同的版本

这个意思是不是说得自己写脚本啊🥲

> 搜索结果解析脚本 : 可选，如果没有指定脚本文件，则可以直接填写脚本内容；脚本需要接收一个参数 options ，属性如下

**Comment by ted423** [comment]
不是，不同的u3d版本的网站的搜索url是不一样的perPage那个是最新的

**Comment by LoneFireBlossom** [comment]
没看懂啥意思，大佬能再解释一下么😂

比如monikadesign的搜索链接是（搜索每页100个结果、按体积降序排列）
https://monikadesign.uk/torrents?perPage=100&name=doraemon&sortField=size
我就往入口页面填上
/torrents?perPage=100&name=$key$&sortField=size

这样填写，点击“添加”没有反应，不知还需要修改哪里？

**Comment by LoneFireBlossom** [comment]
这是操作过程

![CleanShot 2022-12-10 at 10 49 22](https://user-images.githubusercontent.com/50087596/206825151-cf963f4c-83f7-455e-ae1b-c6f7431b8b43.gif)

**Comment by ted423** [comment]
我没monika,我拿 bhd举例好了 /torrents?search=a&qty=100
搜索是这样的，其实自定义搜索这个我也没用过，可以查下wiki

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/search-entry-definition

**Comment by LoneFireBlossom** [comment]
我觉得是插件这里有问题吧，我照着wiki添加NEXUSPHP的站点没问题，但是BHD这种没法添加

![CleanShot 2022-12-10 at 17 09 08](https://user-images.githubusercontent.com/50087596/206842642-092554c7-1c3d-4308-ad36-4725c501edf7.gif)
![CleanShot 2022-12-10 at 17 10 25](https://user-images.githubusercontent.com/50087596/206842652-009d18e0-0b65-4d53-9181-2011dbb67f1c.gif)

**Comment by ted423** [comment]
@LoneFireBlossom 上面wiki有说，你这个情况大概是没定义搜索脚本，你可以看下已有站点的json里怎么配的
