### ISSUE TITLE
获取HDU个人信息是积分异常，变成100多W

### ISSUE THREAD

**Issue by demoxu** [ronggang/PT-Plugin-Plus#122]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome 74 @OSX
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
获取HDU个人信息是积分异常，变成100多W
其他网站信息正常

- 相关截图：
#

**Comment by Rhilip** [comment]
同样不能复现，请补充相关截图（站点以及插件个人信息页面，请注意无关信息打码）说明。

**Comment by demoxu** [comment]
![Snipaste_2019-05-05_08-53-22.png](https://i.loli.net/2019/05/05/5cce3431ae5e8.png)
![Snipaste_2019-05-05_08-53-02.png](https://i.loli.net/2019/05/05/5cce344886c68.png)
我大约是1.05.1出现的数据异常（当时用的是dev模式），现在切换回去了市场的1.05.1.异常数据一致保留了

**Comment by Rhilip** [comment]
暂时不能对已经获取的数据（哪怕是异常数据）进行编辑。
数据与站点主域名绑定，只要站点主域名不变，就会保留。

**Comment by Rhilip** [comment]
由于未能复现HDU个人信息获取失败的情况，先close。如果有再现，请reopen

**Comment by demoxu** [comment]
![2271571020188_ pic](https://user-images.githubusercontent.com/3461435/66726722-a34ba380-ee6d-11e9-88ca-8d0795bd136f.jpg)
![2261571020151_ pic](https://user-images.githubusercontent.com/3461435/66726723-a3e43a00-ee6d-11e9-8067-9dd07ff67c8f.jpg)
补充截图吧，多个版本更新一直未解决

**Comment by ronggang** [comment]
@demoxu 可否截个个人信息页面的图？主要是魔力显示的位置。

**Comment by demoxu** [comment]
![WechatIMG233](https://user-images.githubusercontent.com/3461435/66801175-c13b0600-ef4a-11e9-994d-8a8184134484.jpeg)
![WechatIMG232](https://user-images.githubusercontent.com/3461435/66801176-c13b0600-ef4a-11e9-8f87-970a6b2ea608.jpeg)
已更新
