### ISSUE TITLE
www.hdarea.co 搜索不出结果

### ISSUE THREAD

**Issue by hexianfu** [ronggang/PT-Plugin-Plus#124]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

**Comment by hexianfu** [comment]
![QQ图片20190502182055](https://user-images.githubusercontent.com/17141299/57069387-1a014400-6d07-11e9-91a1-c1922e4ea28a.png)

**Comment by Rhilip** [comment]
不能复现，请查看脚本使用域名（带www）是否是你登录的域名

**Comment by hexianfu** [comment]
在CDN域名下面添加了一次该网站地址,跟系统自带的地址一样,不过这样居然可以了
