### ISSUE TITLE
备份不成功，发送远程服务器不成功

### ISSUE THREAD

**Issue by ivyshow** [ronggang/PT-Plugin-Plus#125]
你好，
我今天在家里点备份到Google，然后在杜甫虚拟机上点从Google恢复，无效，登录的同一个GoogleDrive，Drive里也没有备份的JSON文件。手动备份恢复后，发现仅备份了设置，PT数据没有备份

发送到远程服务器会出现这个，然后远程服务器没有新种。配置肯定没问题的，手机上用Transdroid能正确发送，用的ruTorrent

![image](https://user-images.githubusercontent.com/46221123/57120025-f7236e00-6da0-11e9-8f69-e6e969e736ac.png)

另外建议搜索种子的时候，能显示是否已经做种，辅种比较方便

感谢做了这么方便的工具

**Comment by ivyshow** [comment]
![image](https://user-images.githubusercontent.com/46221123/57120085-5e412280-6da1-11e9-808a-a360c64a276e.png)

**Comment by Rhilip** [comment]
1. Google备份的话，正确方法是使用Chrome浏览器，浏览器中登录同一个帐号，并启用账户同步功能。

![TIM截图20190503151041](https://user-images.githubusercontent.com/13842140/57123775-a9653080-6db5-11e9-8451-8eac1ead1668.png)

使用网页登录GoogleDrive不起作用，这个是Google那边的限制，以下是文档说明

> From: https://developers.chrome.com/extensions/storage#using-sync
> the stored data will automatically be synced to any Chrome browser that the user is logged into, provided the user has sync enabled.
> When Chrome is offline, Chrome stores the data locally. The next time the browser is online, Chrome syncs the data. Even if a user disables syncing, storage.sync will still work. In this case, it will behave identically to storage.local.

2. 目前设置页面确实只能备份插件设置。目前插件使用的google同步方式能存放的数据量有限，很难完整存放PT数据。本地导出功能还在做，未完成。 https://github.com/ronggang/PT-Plugin-Plus/issues/87

3. 建议根据Wiki信息补充后台日志。

4. 重复，目前看很难完成，不会做优先考虑。 https://github.com/ronggang/PT-Plugin-Plus/issues/43

**Comment by ivyshow** [comment]
![image](https://user-images.githubusercontent.com/46221123/57124249-9eab9b00-6db7-11e9-83f0-9ba703dbd1b9.png)
1.确定开启了数据同步，家里爬墙的网络很稳定，杜甫在海外不存在网络问题。备份恢复确实没成功

2.有本地导出功能也足够了

3.后续发现发送服务器虽然显示红框，但是今天种子是成功添加了，很奇怪，回头我找Log发上来

4.同类工具PT Tools会显示一个下载率，有这个显示也就足够了
![image](https://user-images.githubusercontent.com/46221123/57124383-2beeef80-6db8-11e9-9416-70c094c223c2.png)

不知道这个实现起来难不难

**Comment by ronggang** [comment]
@ivyshow 云端备份的确不好保证每次都能完成，其中可能出现的问题太多。
另外，是否下载过和下载进度需要并非每个站都支持直接获取，所以目前还没有完整的计划。

**Comment by luckiestone** [comment]
接上条，忘记给链接了。可以从这里查看Chrome同步状态：chrome://sync-internals/

**Comment by ronggang** [comment]
@luckiestone 时间戳的建议不错。

**Comment by Rhilip** [comment]
鉴于插件在市场已经下架，通过谷歌浏览器自带同步不可行。本issue做关闭处理。
