### ISSUE TITLE
ourbits 快捷按钮和助手按钮重叠

### ISSUE THREAD

**Issue by wuping24** [ronggang/PT-Plugin-Plus#126]
- PT 助手版本:v1.0.5.1
- PT 助手安装方式：（zip包安装）
- 浏览器名称及版本：360极速
- 问题描述：ourbits更新后，右侧新增了个常用按钮，
和助手插件重叠

- 相关截图：
![360截图-8717164](https://user-images.githubusercontent.com/29621079/57173846-ab3bfc00-6e68-11e9-917b-1579066cec72.jpg)

**Comment by Rhilip** [comment]
不好意思，已修复右侧导航不能移动的问题（指OurBits）

**Comment by ronggang** [comment]
OurBits加新功能了啊
助手我也加个可移动吧。
