### ISSUE TITLE
CMCT搜索结果不全

### ISSUE THREAD

**Issue by hexianfu** [ronggang/PT-Plugin-Plus#127]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.051
- PT 助手安装方式：市场安装
- 浏览器名称及版本：74.0.3729.108
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
CMCT很多资源搜索不出来,请看截图.

- 相关截图：
![QQ图片20190502182055](https://user-images.githubusercontent.com/17141299/57181111-47deb800-6ec2-11e9-9049-2b1c25ce0dee.png)
![QQ图片2019050423113331](https://user-images.githubusercontent.com/17141299/57181114-4ca36c00-6ec2-11e9-8e65-fd344c5c0e18.png)

**Comment by hexianfu** [comment]
搜索方案是全部选择了的

**Comment by Rhilip** [comment]
请在插件设置中中把获取数调高

**Comment by ronggang** [comment]
@hexianfu 请参考R酱的方法。
另外建议多看看wiki

**Comment by hexianfu** [comment]
> 请在插件设置中中把获取数调高，
> 下次这种问题直接close

不关获取数的问题啊,最新的这几个都搜不出来,我之前是20个,刚刚改成40个还是搜不出昨天搜不出图片里的几个,就拿昨天晚上22点40左右发布的资源---(触不可及) 现在搜也是搜不出来.
![11111111QQ图片20190505093513](https://user-images.githubusercontent.com/17141299/57186883-615f1e80-6f19-11e9-826e-024267e98af1.png)你看时间还是停留再昨天的18点29

**Comment by ronggang** [comment]
@hexianfu 因为CMCT现在置顶的种子已经超了50个，所以点最新种子看到的都是置顶种子。

**Comment by hexianfu** [comment]
@ronggang  刚刚看了确实是那6个绿色种子下面的最新看不到, 无语- -
