### ISSUE TITLE
用戶數據HDArea 無法抓取

### ISSUE THREAD

**Issue by alen84204** [ronggang/PT-Plugin-Plus#128]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：版本 74.0.3729.131 (正式版本) (64 位元)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：HDArea 無法抓取用戶數據

- 相关截图：

**Comment by Rhilip** [comment]
建议你先调整界面语言为chs，插件暂时对en和cht页面语言支持有限

**Comment by alen84204** [comment]
手動刷新後資料有被抓取到了

**Comment by Rhilip** [comment]
那就先关了，如果还有问题请reopen或者new
