### ISSUE TITLE
聚合搜索种子时，按时间顺序排列，葡萄站点的种子会排在最前面

### ISSUE THREAD

**Issue by wqzvic88** [ronggang/PT-Plugin-Plus#129]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome 74.0.3729.131
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：没测试
- 问题描述：
聚合搜索种子时，按时间顺序排列，葡萄站点的种子会排在最前面，不管葡萄的种子时间如何，它的所有种子总会在最前面。
- 相关截图：
![微信图片_20190506090710](https://user-images.githubusercontent.com/49506362/57203042-c9c40380-6fde-11e9-870f-e0b3933e2f22.png)

**Comment by Rhilip** [comment]
是bug，建议你先把站点时间类型改成发生时间使得种子列表时间为日期格式。

**Comment by Rhilip** [comment]
refs: https://github.com/Rhilip/PT-help/issues/2#issuecomment-368011986
