### ISSUE TITLE
bug:搜索结果显示的大小错误

### ISSUE THREAD

**Issue by kyslll** [ronggang/PT-Plugin-Plus#130]
- PT 助手版本:1.0.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome74.0.3729.131
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：依然不对
- 问题描述：搜索结果显示的大小错误，测试了下，PTHOME,BTSCHOOL,STSPT这几个站的结果基本上显示的大小都不对，PTDREAM的结果正确。

- 相关截图：

**Comment by kyslll** [comment]
![微信截图_20190506123335](https://user-images.githubusercontent.com/36595157/57206829-62687c80-6ffb-11e9-9566-3ae2048aada3.jpg)
![微信截图_20190506123403](https://user-images.githubusercontent.com/36595157/57206830-63011300-6ffb-11e9-9ad2-9b6b8444dec7.jpg)

**Comment by ronggang** [comment]
@kyslll PTHOME试了一下，大小正常，可否把搜索什么内容告知一下，我看能不能重现。
其他两个没号不好测试。

**Comment by kyslll** [comment]
刚刚又拿PTHOME试了下，是这样：
搜索方案选默认或者所有站点，点查看最新种子或者关键词搜索特定种子时，PTHOME站的结果大小显示错误。
搜索方案限定PTHOME或者包括PTHOME在内的几个站时，点查看最新或搜索特定种子时，显示结果正常。

**Comment by ronggang** [comment]
@kyslll 按你的方法试了一下，还是未发现异常。请截个列表的对比图片

**Comment by kyslll** [comment]
![有关键词，搜所有站](https://user-images.githubusercontent.com/36595157/57352710-c70d0e00-7198-11e9-9ecb-4eec15569fb0.jpg)
![有关键词，搜一个站](https://user-images.githubusercontent.com/36595157/57352719-cc6a5880-7198-11e9-8070-1b3266a8bb0e.jpg)
![有关键词，搜两个站](https://user-images.githubusercontent.com/36595157/57352726-d12f0c80-7198-11e9-8145-ab49057a5245.jpg)
为方便截图，设置了每站只返回两个搜索结果 。
上面的图都是搜同一个关键词返回的结果，不同的是搜索方案：
第一个是搜所有站，返回结果除去PTDREAM外的6个大小显示均不正确。
第二个是搜PTHOME和BTSCHOOL两个站，结果显示大小正常。
第三个只搜PTHOME一个站，结果显示大小正常。
这里是搜关键词，不搜关键词查看最新种子时也是一样的效果。另外通过图片对比发现搜索相同关键词或者查看最新种子在不同的搜索方案下返回的结果也不完全相同？

**Comment by ronggang** [comment]
@kyslll 感谢测试，其实我是想看一下助手和网站上实际搜索结果的对比。
我也按你说的，用不同的方案测试了几个站，和网站上直接搜索的列表显示是一致的。

- 所有站
![chrome_2019-05-08_16-15-50](https://user-images.githubusercontent.com/8065899/57360386-98009780-71ac-11e9-9449-ccdd75b1601a.png)

- 指定方案
![chrome_2019-05-08_16-12-19](https://user-images.githubusercontent.com/8065899/57360239-37715a80-71ac-11e9-90f6-851e66a2dd19.png)
----------------------------------------
- 网站上搜索的结果
![chrome_2019-05-08_16-12-48](https://user-images.githubusercontent.com/8065899/57360240-37715a80-71ac-11e9-89d4-c08b9921d008.png)

![chrome_2019-05-08_16-15-20](https://user-images.githubusercontent.com/8065899/57360383-97680100-71ac-11e9-8ede-c9b142e313f0.png)

另外，关于相同关键字返回结果不同，这个比较有意思，助手只对抓取网页结果，默认不排序的情况下和站点搜索结果应该是一致的。

**Comment by kyslll** [comment]
> 检查下是否开了悬浮提示，已知悬浮提示会对脚本解析出来的网页结构产生影响。
> refs: #70 #111

检查了三个显示不正常的站都没有开启悬浮提示，尝试开关了这个选项，没有发现对助手产生什么影响；另外的一个正常的站里没找到这个选项。

**Comment by ronggang** [comment]
悬浮提示开关新版本应该已不受影响。
不过你的这个问题我暂时还未找到原因，希望有同样问题的同学路过帮忙找一下原因。:pray:
