### ISSUE TITLE
请教qbittorrent服务器设置问题

### ISSUE THREAD

**Issue by kyslll** [ronggang/PT-Plugin-Plus#131]
我的设备是威联通NAS，同一台设备安装了transmission,在PTplug里添加服务器能正常使用，qb添加之后始终提示连接服务器失败,地址试过IP:端口、主机名:端口、域名:端口，均无效。QB版本是4.1.5，设置里没有找到“启用跨站请求伪造(CSRF)保护”的选项，不知道如何配置，求教。

**Comment by ronggang** [comment]
@kyslll QB只接触过Windows版的，其他版本不太清楚，可以参考一下之前网友提供的方法：
https://github.com/ronggang/PT-Plugin-Plus/wiki/download-client-qBittorrent

**Comment by alen84204** [comment]
4.1.5設置有“启用跨站请求伪造(CSRF)保护”的选项阿 你再找找 我就是用4.1.5 正常跑呢

**Comment by kyslll** [comment]
> @kyslll QB只接触过Windows版的，其他版本不太清楚，可以参考一下之前网友提供的方法：
> https://github.com/ronggang/PT-Plugin-Plus/wiki/download-client-qBittorrent

可以了，感谢。

**Comment by kyslll** [comment]
> 4.1.5設置有“启用跨站请求伪造(CSRF)保护”的选项阿 你再找找 我就是用4.1.5 正常跑呢

可以了，确实是那个选项的问题，谢了。

**Comment by valianliu** [comment]
> @kyslll QB只接触过Windows版的，其他版本不太清楚，可以参考一下之前网友提供的方法：
> https://github.com/ronggang/PT-Plugin-Plus/wiki/download-client-qBittorrent

这个wiki需要修正，关闭这个选项需要设置成 false，而不是true
亲自验证了一下有效

**Comment by ted423** [comment]
> > @kyslll QB只接触过Windows版的，其他版本不太清楚，可以参考一下之前网友提供的方法：
> > https://github.com/ronggang/PT-Plugin-Plus/wiki/download-client-qBittorrent
> 
> 这个wiki需要修正，关闭这个选项需要设置成 false，而不是true
> 亲自验证了一下有效

应该是手滑打错了
