### ISSUE TITLE
特定站點無法正常運行

### ISSUE THREAD

**Issue by alen84204** [ronggang/PT-Plugin-Plus#133]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：版本 74.0.3729.131 (正式版本) (64 位元)
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：右側功能列不見，右鍵無PTT功能

- 相关截图：
![image](https://user-images.githubusercontent.com/35393339/57265377-09a3ed00-70aa-11e9-9d3c-87a97d1b8d11.png)

**Comment by Rhilip** [comment]
具体是那些站点？

**Comment by alen84204** [comment]
HDAREA
PTHOME
HDU
其他的AvistaZ、ExoticaZ、港知堂、M-TEAM、我堡、PTer都正常運作中。

**Comment by ronggang** [comment]
@alen84204 请参考站点CDN设置
https://github.com/ronggang/PT-Plugin-Plus/wiki/config-site

**Comment by alen84204** [comment]
@ronggang 不是這個問題 CDN早就設置過 因為同一個畫面有時候會有 有時候又消失不見

**Comment by alen84204** [comment]
比方說HDArea 加入種子會全數列入無效種子
![image](https://user-images.githubusercontent.com/35393339/57296213-04bd5880-70ff-11e9-8382-eae1c5846c2b.png)

**Comment by ronggang** [comment]
@alen84204 
- 如果不是CDN問題，還有幾種可能
  - 頁面未加載完成，助手沒有顯示出來
  - 可以看看是否被廣告插件給誤殺了？
- 無效種子可以嘗試手工下載一個種子文件試試，大部份情況為首次下載種子文件需要確認客戶端。
  - https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions
