### ISSUE TITLE
开发建议：以闭包js文件形式获取用户信息

### ISSUE THREAD

**Issue by Rhilip** [ronggang/PT-Plugin-Plus#134]
目前站点搜索的使用js闭包的形式来获取并解析对应结果，但是
用户信息的获取使用的配置文件的形式，这样造成了类似 https://github.com/ronggang/PT-Plugin-Plus/issues/109 https://github.com/ronggang/PT-Plugin-Plus/issues/68 的问题。
即对于特殊站点获取原方法存在适配性较复杂的问题。
就如MT（按照现在的观察）就是 100种以下 和其他NexusPHP站点表现相同，而100种以上另起单独页面并有分页情况。

**Comment by ronggang** [comment]
可以考虑添加闭包的方式，如果定义了脚本，则调用脚本，如果没有则以配置的表达式解析。
其实一直想把搜索也增加可直接配置表达式，可以对一些相对简单的站进行直接配置，而不需要写脚本。
