### ISSUE TITLE
功能建议：插件内搜索结果页增加收藏及下载框选项

### ISSUE THREAD

**Issue by scxhwhb** [ronggang/PT-Plugin-Plus#135]
对于通过rss订阅自动下载的用户来说，这个功能在远程无法操作下载机时比较实用。

**Comment by Rhilip** [comment]
下载框并不是每个站都支持的，此外收藏的话，其实各站的接口都不一致。
可能会延后考虑实现吧

**Comment by hustfeather** [comment]
同希望能加入这个功能

**Comment by ted423** [comment]
建议还是点开种子详情页操作。
各类站点实现方式不一样，表现形式也不大一样。
适配以及维护的都需要比较大的成本，所以我倾向于先关掉
