### ISSUE TITLE
外网新增黑群晖tr服务器失败

### ISSUE THREAD

**Issue by fsn163163** [ronggang/PT-Plugin-Plus#136]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 测试版
- PT 助手安装方式：（市场安装，或zip包安装）谷歌浏览器插件
- 浏览器名称及版本：谷歌浏览器版本 74.0.3729.131
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：黑群晖是通过openwrt的ddsnto插件实现外网访问的，地址是https://XXXX.ddnsto.com/transmission/web/，外网访问这个地址能直接打开tr，但添加PT服务器用这个地址就不行，用户名密码没有问题，是什么原因？

- 相关截图：

**Comment by Rhilip** [comment]
所以截图那，在无明确说明情况下，请参照 https://github.com/ronggang/PT-Plugin-Plus/issues/32 https://github.com/ronggang/PT-Plugin-Plus/issues/88 等已有issue讨论
