### ISSUE TITLE
U2 DNS污染，助手无法搜索和添加下载

### ISSUE THREAD

**Issue by qzhuwei** [ronggang/PT-Plugin-Plus#137]
- 问题描述：
你好，我刚微信捐了5.99元，现在U2的DNS污染，无法在助手里搜索内容和添加远程下载，有什么好的解决办法么请问。
![QQ图片20190511134709](https://user-images.githubusercontent.com/19317921/57565609-79d8a880-73f3-11e9-81ed-934b79a614c3.png)

**Comment by ronggang** [comment]
@qzhuwei 感谢支持。
DNS污染的问题，只能在DNS层面去解决，助手无能为力。:expressionless:
