### ISSUE TITLE
chrome 如何更新1.0.6 or 1.0.7

### ISSUE THREAD

**Issue by alen84204** [ronggang/PT-Plugin-Plus#141]
chrome 如何更新1.0.6 or 1.0.7

**Comment by ylxb2016** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-zip
https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-chrome-webstore

**Comment by luckiestone** [comment]
商店上线要审核，有点慢，我也在等，哈哈

**Comment by Rhilip** [comment]
见wiki说明

**Comment by alen84204** [comment]
原來要等 謝拉
