### ISSUE TITLE
[建议]希望能增加一键下载种子文件的功能

### ISSUE THREAD

**Issue by LisonFan** [ronggang/PT-Plugin-Plus#144]
Transmission 在下载大种的时候，rpc 发不过去。。
一键下载种子文件的话我就能放在 Watch 文件夹里让它自动添加

**Comment by Rhilip** [comment]
你的意思是通过插件将种子发送到remote的watch目录吗？
如果不是这个意思，插件本身在搜索界面提供种子一键下载，网站也提供下载链接导出，可以再用其他工具进行下载。
如果是的话，TR本身rpc不支持发送到watch目录。或许可以考虑以后用jsftp的形式，目前应该是不会做其他考虑。

**Comment by LisonFan** [comment]
> 你的意思是通过插件将种子发送到remote的watch目录吗？
> 如果不是这个意思，插件本身在搜索界面提供种子一键下载，网站也提供下载链接导出，可以再用其他工具进行下载。
> 如果是的话，TR本身rpc不支持发送到watch目录。或许可以考虑以后用jsftp的形式，目前应该是不会做其他考虑。

一键调用浏览器自带的下载吧
说实话目前没发现其他工具能批量下载（迅雷除外，怕泄露 KEY

**Comment by ronggang** [comment]
你是想在种子列表页直接批量下载种子文件是吧
https://github.com/ronggang/PT-Plugin-Plus/projects/1#card-16562763
这个计划放了好久，还没做上去:laughing:

**Comment by LisonFan** [comment]
> 你是想在种子列表页直接批量下载种子文件是吧
> https://github.com/ronggang/PT-Plugin-Plus/projects/1#card-16562763
> 这个计划放了好久，还没做上去😆

233
是的
