### ISSUE TITLE
NPUBT下载失效

### ISSUE THREAD

**Issue by Alvinnfly** [ronggang/PT-Plugin-Plus#146]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.7
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome 71
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：
npupt下载403，复制链接为https://npupt.com/javascript:download_link("https://npupt.com/download.php?id=161956&passkey=****");&https=1
类似地，byr复制的链接为
https://bt.byr.cn/download.php?id=284727&https=1

**Comment by Rhilip** [comment]
请问是如何调用的产生的下载动作？

**Comment by Alvinnfly** [comment]
> 请问是如何调用的产生的下载动作？
> 插件内搜索页面结果应该没问题，是网页右键还是网页右侧工具导入？

种子列表页面右键显示成功，但实际上并未下载下来
种子内页右侧点击一键下载或复制链接显示链接为https://npupt.com/javascript:download_link("https://npupt.com/download.php?id=161956&passkey=****");&https=1

**Comment by Rhilip** [comment]
那看来和 https://github.com/ronggang/PT-Plugin-Plus/issues/60 有点相关，都是因为站点的对应链接 (a标签的href属性) 为JavaScript动作或为空，而不是正常http相对或绝对链接。。
到时候看看好不好修吧，目前只能建议先别进行这个动作了。
（或者用注入脚本把这几个链接给改了？

**Comment by Alvinnfly** [comment]
看了下确实是
href="javascript:torrent_download(*****,6,100,0,false,false)"，引用的是https://npupt.com/js/main.js中的一个函数
不过为什么不带着种子id请求download.php？感觉大部分站直接请求就行（虽然个别站如hdc这样不行）

**Comment by Rhilip** [comment]
> 看了下确实是
> href="javascript:torrent_download(*****,6,100,0,false,false)"，引用的是https://npupt.com/js/main.js 中的一个函数
> 不过为什么不带着种子id请求download.php？感觉大部分站直接请求就行（虽然个别站如hdc这样不行）

NPU的torrent_download这个方法是拿来做RP判断的，RP不够的时候前端提示等待。。。
相关链接构造方法可见 https://github.com/ronggang/PT-Plugin-Plus/blob/dev/resource/schemas/NexusPHP/details.js#L37-L79
NPU的错误似乎是出在了L50那里

建议在种子页面点击 更多 -> 种子链接 ，在弹出对话框中的链接中右键发送。。

**Comment by Alvinnfly** [comment]
谢谢，直接在种子列表页面右键发送也可以发送，也就是说根据种子id构造下载链接是可以的，那也就是说是不是这样可以绕过rp限制？算一个小bug吧，只做了前端判定，没做后端的。

**Comment by Rhilip** [comment]
> 谢谢，直接在种子列表页面右键发送也可以发送，也就是说根据种子id构造下载链接是可以的，那也就是说是不是这样可以绕过rp限制？算一个小bug吧，只做了前端判定，没做后端的。

是的，他们rp限制只做了前端判定233333

**Comment by xfl03** [comment]
2019/12/25 仍未修复，使用右键发送错误为`undefined`，请问是否需要重开issue呢？

**Comment by ted423** [comment]
> 2019/12/25 仍未修复，使用右键发送错误为`undefined`，请问是否需要重开issue呢？

你是否仔细看了上面的讨论，你的情况与提问者是否完全一致呢？

**Comment by xfl03** [comment]
> > 2019/12/25 仍未修复，使用右键发送错误为`undefined`，请问是否需要重开issue呢？
> 
> 你是否仔细看了上面的讨论，你的情况与提问者是否完全一致呢？

已阅读，情况完全一致，一键下载无效且报错相同。
Workaround
> 在种子页面点击 更多 -> 种子链接 ，在弹出对话框中的链接中右键发送
是有效的，但是确实有点麻烦，还希望可以修复一键下载。

**Comment by xfl03** [comment]
@Rhilip 已修复，请关闭此issue
