### ISSUE TITLE
开发建议：使用getfavicon类库获取favicon信息

### ISSUE THREAD

**Issue by Rhilip** [ronggang/PT-Plugin-Plus#147]
我们曾因为favicon处理过一些issue（包括pr），如 https://github.com/ronggang/PT-Plugin-Plus/pull/98  https://github.com/ronggang/PT-Plugin-Plus/issues/100  https://github.com/ronggang/PT-Plugin-Plus/pull/143 （还居然都是朋友站。。。）
同时，手动为站点制定favicon带来了配置上的重复项。毕竟多数站点还是以`$schema://$host/favicon.ico` 的格式
是否可以考虑通过考虑使用npm上面 getfavicon类功能库（ https://www.npmjs.com/search?q=keywords:favicon ），使得获取站点缩略图的方式变成更自动化。缓存favicon图标（已有实现），并在可能获取失败（比如站点关闭或者暂时无法访问）的情况下，使用某一缺省图标进行替代。

**Comment by ronggang** [comment]
嗯，可以考虑在build时获取icon进行缓存，不过像教育网好像不能直接获取，得另想办法。
