### ISSUE TITLE
Ourbits不显示助手图标

### ISSUE THREAD

**Issue by 1kevin335200** [ronggang/PT-Plugin-Plus#148]
> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.7
- PT 助手安装方式：（市场安装，或zip包安装）市场
- 浏览器名称及版本：Chrome Version 74.0.3729.131
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
Ourbits不显示助手图标，其他站点正常

- 相关截图：

**Comment by Rhilip** [comment]
检查域名是否一致或设置cdn域名

**Comment by 1kevin335200** [comment]
的确因为域名不一致，助手的不带www。
