### ISSUE TITLE
下载目录设置问题

### ISSUE THREAD

**Issue by LisonFan** [ronggang/PT-Plugin-Plus#149]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.7
- PT 助手安装方式：Chrome Store
- 浏览器名称及版本：Chrome 74.0.3729.157
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：
设置了下载目录，采用手动输入的方式 <...>，在网站点击一键下载，弹出输入框，输入名字后发送给 tr 的路径不对

- 相关截图：
![image](https://user-images.githubusercontent.com/9424775/58219062-12e4b900-7d3c-11e9-90b0-e227a0521ae6.png)

**Comment by ronggang** [comment]
@LisonFan 可否描述一下具体步骤，比如在哪个页面，输入了什么内容，最终得到什么内容。

**Comment by LisonFan** [comment]
> @LisonFan 可否描述一下具体步骤，比如在哪个页面，输入了什么内容，最终得到什么内容。

设置一个下载目录“/downloads/complete/<...>” -> 打开 PT 站 -> 找到一个种子点击一键下载 -> 在弹出的框里输入保存在哪个文件夹

步骤是这样的，发到 tr 去的时候没有替换成输入的名字，还是 <...>

但是不一键下载，使用 下载到... 就没问题

**Comment by ronggang** [comment]
感谢反馈

**Comment by LisonFan** [comment]
> 感谢反馈

还有一个问题，在种子列表一键下载没法手动输入文件夹名称

**Comment by ronggang** [comment]
一键下载设计时不允许动态目录，要不然就不叫一键下载了。

**Comment by LisonFan** [comment]
> 一键下载设计时不允许动态目录，要不然就不叫一键下载了。

下载到... 也没得选择

**Comment by LisonFan** [comment]
> 一键下载设计时不允许动态目录，要不然就不叫一键下载了。

这个是在种子列表
![image](https://user-images.githubusercontent.com/9424775/58292255-36b70600-7df3-11e9-8484-5268655b1261.png)

这个是在种子页面
![image](https://user-images.githubusercontent.com/9424775/58292283-4df5f380-7df3-11e9-9e4f-e6d24224fc97.png)

**Comment by ronggang** [comment]
可否提供以下内容：
1. 详细的目录配置信息；
2. 完整的截图信息，注意去除服务器地址等个人信息；
3. 具体的网站信息；

**Comment by LisonFan** [comment]
1、
![image](https://user-images.githubusercontent.com/9424775/58295208-9c5dbf00-7e00-11e9-90aa-cd51a9f41c59.png)

2、
![image](https://user-images.githubusercontent.com/9424775/58295255-cc0cc700-7e00-11e9-914a-31dad557d53d.png)

3、https://tp.m-team.cc/torrents.php

**Comment by ronggang** [comment]
@LisonFan 按照你的设置，我还是无法复现。
你可以试着在种子列表页，按F12开启开发者工具，看看有没有错误。
另外，查一下有没有其他插件冲突了。

**Comment by LisonFan** [comment]
> @LisonFan 按照你的设置，我还是无法复现。
> 你可以试着在种子列表页，按F12开启开发者工具，看看有没有错误。
> 另外，查一下有没有其他插件冲突了。

![image](https://user-images.githubusercontent.com/9424775/58534209-31a3ed80-821d-11e9-98f2-0f8a2e87c600.png)

**Comment by ronggang** [comment]
@LisonFan 升级到最新版，不知道现在你的问题还在不在？

**Comment by LisonFan** [comment]
测试了一下，还是存在

**Comment by ted423** [comment]
猜测可能是域名的锅
未复现且时间过长
