### ISSUE TITLE
备份到Google功能不起作用

### ISSUE THREAD

**Issue by wolonggl** [ronggang/PT-Plugin-Plus#15]
PT助手可以正常备份到Google；
PT Plugin Plus备份到Google无任何反应及提示；

**Comment by Rhilip** [comment]
1. 具有备份到Google功能的目前还在dev分支，之前仅作占位设计，请等待测试完成后合并。 https://github.com/ronggang/PT-Plugin-Plus/commit/35652ab296425166ae7666b35c94440d027bc894
2. 使用zip压缩包形式安装的插件不支持备份到Google功能，请使用从商店安装的版本。
