### ISSUE TITLE
希望能增加天雪站

### ISSUE THREAD

**Issue by wk333** [ronggang/PT-Plugin-Plus#150]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

**Comment by wk333** [comment]
https://www.skyey2.com/

**Comment by pcatang** [comment]
Chrome市场安装的插件，如何自行修改网站的域名呢？

**Comment by ronggang** [comment]
> Chrome市场安装的插件，如何自行修改网站的域名呢？

可以修改网站的 CDN 列表。

**Comment by pcatang** [comment]
> > Chrome市场安装的插件，如何自行修改网站的域名呢？
> 
> 可以修改网站的 CDN 列表。

如何操作呢？ 谢谢

**Comment by ronggang** [comment]
@pcatang 可参考：https://github.com/ronggang/PT-Plugin-Plus/wiki/config-site
