### ISSUE TITLE
建议搜索返回增加种子存活时间和本人下载进度。

### ISSUE THREAD

**Issue by feifan1840** [ronggang/PT-Plugin-Plus#151]
希望在搜索结果返回页面里
1、增加种子存活时间，或替换掉发布时间，直接显示几分几小时，这样更直观的反应种子的新旧程度。
2、同时希望在搜索返回结果里显示本人下载进度（有的网站显示的是百分比，有的网站显示的是进度条），这样方便用户了解自己的下载状况。

**Comment by ronggang** [comment]
1. 可能会增加时间切换，一般情况不会看两个时间；
2. 计划中，但不是所有站点都有进度显示；

**Comment by ywyha** [comment]
这个功能刚需，进度条配以颜色显示比较直观
