### ISSUE TITLE
hdsky 获取出来的种子和请求网站获取到的种子不一致是什么原因

### ISSUE THREAD

**Issue by timewalkerF** [ronggang/PT-Plugin-Plus#153]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.7
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
获取出来的种子和请求网站获取到的种子不一致是什么原因

- 相关截图：

**Comment by Rhilip** [comment]
请问具体哪个地方不一致

**Comment by timewalkerF** [comment]
就是点查看最新种子，出来的并非是获取https://hdsky.me/torrents.php这个里面的种子吗。
里面有时候有些种子获取不到。

**Comment by ronggang** [comment]
> 就是点查看最新种子，出来的并非是获取[https://hdsky.me/torrents.php这个里面的种子吗。](https://hdsky.me/torrents.php%E8%BF%99%E4%B8%AA%E9%87%8C%E9%9D%A2%E7%9A%84%E7%A7%8D%E5%AD%90%E5%90%97%E3%80%82)
> 里面有时候有些种子获取不到。

是种子页的内容，默认获取第一页种子，数量以常规设置里的“搜索时每站点返回结果数量”为准，默认为10。

**Comment by timewalkerF** [comment]
可能我没事喜欢刷新吧，刷新出来的不知道是那里来的
