### ISSUE TITLE
Beyond-HD的支持

### ISSUE THREAD

**Issue by OliverLew** [ronggang/PT-Plugin-Plus#154]
Beyond-HD最近换了UNIT3D，但是貌似通过自定义站点添加后，搜索不到结果。

**Comment by ronggang** [comment]
如果你试过不能搜索，那可能需要进一步适配。但目前我没有该站点账号，希望有号的同学可以适配一下。

**Comment by ronggang** [comment]
已添加 87ceeea9e9c5e95a822d7f25dc741ee32b6021e4
请更新至新版
