### ISSUE TITLE
BTSCHOOL更换域名

### ISSUE THREAD

**Issue by txrtanzi** [ronggang/PT-Plugin-Plus#155]
BTSCHOOL的域名已更换为 https://pt.btschool.club

**Comment by Aniverse** [comment]
大家好！网站于20190.5.23启用新域名 [本信息禁止公开]
禁止在公共网络空间（包括但不限于百度贴吧、各类论坛、微博、QQ群）讨论本站。

感觉有点微妙……

**Comment by txrtanzi** [comment]
> 大家好！网站于20190.5.23启用新域名 [本信息禁止公开]
> 禁止在公共网络空间（包括但不限于百度贴吧、各类论坛、微博、QQ群）讨论本站。
> 
> 感觉有点微妙……

或者直接把插件内置的站点信息去掉，改成自助添加？

**Comment by Rhilip** [comment]
**在助手处做任何意义上的隐藏或者混淆都没有意义。**
为了用户的个人信息安全，我们也不会考虑接受混淆（站点对应的搜索以及个人信息获取方法），更别说用户侧数据极其容易被反编译。

------------------------

手动添加站点功能会一直保留。

------------------------

助手所有收录支持站点均为用户提交并自发维护。
如果你是**站点管理组成员**，且不希望站点被助手收入请在issue或者pr的形式**正式**向我们提出。在这种情况下，我们仅为用户提供基础的模板匹配（既用户只能以自定义添加并制定模板的形式添加站点支持），且对应删除信息将在下一版本进行更新并写入日志和commit历史。

**Comment by Rhilip** [comment]
refs pr: https://github.com/ronggang/PT-Plugin-Plus/pull/152

**Comment by peterkkk366** [comment]
same issue.

**Comment by ronggang** [comment]
closes 65bb638804fce4d957880569fe7c632450a2b8a2
