### ISSUE TITLE
请问如何关闭右侧的小工具栏？

### ISSUE THREAD

**Issue by icetea0822** [ronggang/PT-Plugin-Plus#156]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.8
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：是
- 问题描述：
请问如何关闭PT种子页打开时右侧出现的竖向的工具栏？谢谢

- 相关截图：
<img width="96" alt="屏幕快照 2019-05-27 上午11 23 43" src="https://user-images.githubusercontent.com/12151645/58393614-f9ac7700-8071-11e9-8194-22a9338f7e3e.png">

**Comment by Rhilip** [comment]
暂不支持关闭，我们会在后续版本考虑对工具栏提供关闭功能

**Comment by ronggang** [comment]
我在想，是全局關呢，還是可以針對單個站點可以開關。

**Comment by icetea0822** [comment]
> 我在想，是全局關呢，還是可以針對單個站點可以開關。

我觉得单个站关闭没什么太大必要吧，要是实现起来简单的话当然提供一下也不错。另外如果能够提供打开某个种子的详情页面，小助手可以检测是什么电影，点一下直接跳转到豆瓣或者imdb这样的话，就太好了。

**Comment by ronggang** [comment]
> > 我在想，是全局關呢，還是可以針對單個站點可以開關。
> 
> 我觉得单个站关闭没什么太大必要吧，要是实现起来简单的话当然提供一下也不错。另外如果能够提供打开某个种子的详情页面，小助手可以检测是什么电影，点一下直接跳转到豆瓣或者imdb这样的话，就太好了。

如果是常规电影，一般网站都已提供了豆瓣或imdb链接了，如果再提出来做到助手工具栏里，会不会显得按钮过多，到时候还得加个配置显示哪些按钮 😅

**Comment by icetea0822** [comment]
> > > 我在想，是全局關呢，還是可以針對單個站點可以開關。
> > 
> > 
> > 我觉得单个站关闭没什么太大必要吧，要是实现起来简单的话当然提供一下也不错。另外如果能够提供打开某个种子的详情页面，小助手可以检测是什么电影，点一下直接跳转到豆瓣或者imdb这样的话，就太好了。
> 
> 如果是常规电影，一般网站都已提供了豆瓣或imdb链接了，如果再提出来做到助手工具栏里，会不会显得按钮过多，到时候还得加个配置显示哪些按钮 😅

不会啊，也就ourbites全面点，像馒头只有imdb，其他hdhome、pthome只有文字信息啊。
