### ISSUE TITLE
功能建议：单独刷新某个站点的数据

### ISSUE THREAD

**Issue by Aniverse** [ronggang/PT-Plugin-Plus#157]
由于我网络的原因，刷新全部站点速度比较慢，并且有些站我要挂代理才能上（由于某些原因我不想把这些站点设定为自动走代理），这就会导致每次全部刷新的时候总有一些站刷不出来，可以单独刷新的话我可以设定成刷新那些站点的时候再启用代理

**Comment by ronggang** [comment]
點擊站點圖標可以單獨刷新。

**Comment by Aniverse** [comment]
原来如此。这个设计不太容易发现（光标移动到站点图标上也不会变），我之前都没找到有单独刷新的按钮，只知道点站点名字可以打开站点不知道点图标可以单独刷新……

**Comment by ronggang** [comment]
原本是用來測試的，所以沒有做特別的提示 :laughing:
