### ISSUE TITLE
qb自定义目录无法使用，只能默认下载到默认目录

### ISSUE THREAD

**Issue by marxvr** [ronggang/PT-Plugin-Plus#159]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: v1.0.8
- PT 助手安装方式：zip包安装
- 浏览器名称及版本： （64 位） (Chromium 72.0.3626.121)
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：
qb自定义目录无法使用，只能默认下载到默认目录

- 相关截图：

**Comment by marxvr** [comment]
> 请给明具体例子
服务器设置:
![1 服务器设置](https://user-images.githubusercontent.com/17882380/58524212-183d7a00-81fa-11e9-95be-e374545b851b.png)
qb默认目录:
![2 qb默认目录](https://user-images.githubusercontent.com/17882380/58524209-17a4e380-81fa-11e9-82e5-fe90809b024b.png)
指定目录下载:
![3 下载](https://user-images.githubusercontent.com/17882380/58524210-17a4e380-81fa-11e9-83f2-c9ec273291fd.png)
下载到了默认目录：
![4 只能保存到默认目录](https://user-images.githubusercontent.com/17882380/58524211-183d7a00-81fa-11e9-8cd8-44989c9b205f.png)

**Comment by marxvr** [comment]
电脑端也这样尝试过，一样是这种情况。
qb都是4.1.6

**Comment by Rhilip** [comment]
不好意思，我参照你的截图尝试了一下，不能复现。。。。

-----------------------

能否参考该wiki https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page
抓一下插件向qb发送种子的请求，如下图
查看箭头所指位置的信息是不是你设定的自定义目录，如果是的话，问题出在qb那边。。。
![image](https://user-images.githubusercontent.com/13842140/58526264-feebfc00-8200-11e9-8a6c-775403f64243.png)

**Comment by marxvr** [comment]
@Rhilip 非常感谢，看了教程之后，我已经找出问题了，开启了qb的自动管理种子功能，会导致自定义目录下载失效。

**Comment by ronggang** [comment]
> @Rhilip 非常感谢，看了教程之后，我已经找出问题了，开启了qb的自动管理种子功能，会导致自定义目录下载失效。

这可以可以列到注意事项里了👏
