### ISSUE TITLE
希望搜索种子界面下载种子的时候能选择保存的路径

### ISSUE THREAD

**Issue by willie91** [ronggang/PT-Plugin-Plus#16]
因为我使用了emby刮削封面，一般下载的时候会选择路径，以便于更好的分类，但是在搜索界面的话，右键是没有路径可以选的，只有发送到下载服务器这个功能，我只能返回种子的站点页面右键才能选择下载的路径。

**Comment by willie91** [comment]
查看最新种子这个功能我个人觉得，如果能做成自动刷新，然后根据评分给推送信息，比如豆瓣7分或者imdb7分给推送信息。
现在目前只能看到最新种子，也没有评分情况，除了专门在刷数据，感觉这个功能没太大作用。

**Comment by ronggang** [comment]
@willie91 
1、关于搜索结果保存路径会考虑增加。
2、商店正在提交，但不知道审核什么时候通过。
3、关于自动个性化推送可以做为计划，以后看看能不能加入。

**Comment by willie91** [comment]
好的，感谢
