### ISSUE TITLE
HDCity读取数据异常

### ISSUE THREAD

**Issue by PatrickCaoHN** [ronggang/PT-Plugin-Plus#160]
- PT 助手版本:1.0.8
- PT 助手安装方式：chrome市场
- 浏览器名称及版本：360安全浏览器10.1.1695.0
- 浏览器是否安装了其他插件：去广告插件等
- 停用其他插件后是否正常工作：否
- 问题描述：HDCity读取数据异常

- [[相关截图：]]
![TIM截图20190529193800](https://user-images.githubusercontent.com/9863430/58556636-0df99b00-824f-11e9-95d5-a3536a4c55a6.png)

**Comment by ronggang** [comment]
@PatrickCaoHN 暂无该站点号，无法验证是该问题。
你可以按 https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page 这个方法来查看获取到了什么内容，是否有出错。

**Comment by Rhilip** [comment]
不能复现，
请检查使用域名是不是助手默认域名，贴出`https://hdcity.city/userdetails` 页面信息（注意个人信息打码）
或按ronggang指出的wiki中检查原始获取数据情况。

**Comment by Rhilip** [comment]
无法复现，且未得到用户回复，关闭。
