### ISSUE TITLE
U2搜索失败

### ISSUE THREAD

**Issue by 1kevin335200** [ronggang/PT-Plugin-Plus#162]
- PT 助手版本: 1.0.8
- PT 助手安装方式：市场
- 浏览器名称及版本：Version 74.0.3729.169
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

options | SearchTorrent.Search.Error2 | 2019-05-30 20:55:30 | u2.dmhy.org 发生网络或其他错误 | delete
-- | -- | -- | -- | --
{"host":"u2.dmhy.org","key":"哥斯拉","name":"U2","result":[]}

- 相关截图：

**Comment by ronggang** [comment]
@1kevin335200 请确认你已正常登录U2。

**Comment by 1kevin335200** [comment]
![Screenshot_2019-05-31_21-14-55](https://user-images.githubusercontent.com/15524267/58729246-33221100-83e9-11e9-8947-167aedc58667.png)
正常登录，可获取流量信息
![Screenshot_2019-05-31_21-15-42](https://user-images.githubusercontent.com/15524267/58729273-4634e100-83e9-11e9-8ce4-0b420ff3feae.png)

**Comment by lbq1121** [comment]
> @ 1kevin335200请确认你已正常登录U2。

同样问题 并且馒头做种数获取错误
