### ISSUE TITLE
无法备份到Google

### ISSUE THREAD

**Issue by billysun76** [ronggang/PT-Plugin-Plus#165]
- PT 助手版本:1.08
- PT 助手安装方式：市场安装
- 浏览器名称及版本：CentBrowser 3.9.2.45 (Chromium 72.0.3626.121)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：不正常
- 问题描述：选择备份到Google时插件显示：要保存的内容大小超出了Google限制（8K）

**Comment by ronggang** [comment]
@billysun76 因为 Google 限制了最大只允许8K，所以内容多了就无法备份了。

**Comment by ronggang** [comment]
另外，如何各位有什么好的可用于备份参数的方案也可以推荐一下，因为8K对于站点多的同学，基本上不够用，再加上以后如果要备份历史数据，就更不用说了。

**Comment by Rhilip** [comment]
TamperMonkey可以将文件备份到GoogleDrive、Dropbox、OneDrive、WebDav 等处，可以学习下

![image](https://user-images.githubusercontent.com/13842140/58707832-9eb7ae80-83e8-11e9-9455-81894718c189.png)

**Comment by ronggang** [comment]
> TamperMonkey可以将文件备份到GoogleDrive、Dropbox、OneDrive、WebDav 等处，可以学习下
> 
> ![image](https://user-images.githubusercontent.com/13842140/58707832-9eb7ae80-83e8-11e9-9455-81894718c189.png)

我了解一下。

**Comment by billysun76** [comment]
是的，@Rhilip 的方法比价好，备份下来的文件还可以导入zip版，这样两个版本的备份功能就统一了。

**Comment by ronggang** [comment]
@billysun76 请尝试新版的备份服务器功能，后续如果加上 WebDAV ，备份到Google将可能会取消。
本主题暂时关闭。
