### ISSUE TITLE
功能建议：替换 NexusPHP /torrents.php 中单个种子的下载链接，使其包含 passkey

### ISSUE THREAD

**Issue by Aniverse** [ronggang/PT-Plugin-Plus#166]
如题。有时候希望在 torrents.php 中直接获取单个种子的含 passkey 链接，方便添加到远程服务器上

更进一步地，有无可能实现在 torrents.php 上拖拽特定种子到悬浮工具栏上，从而直接获取到这个种子的含 passkey 链接（也就是【复制链接】），或者把这个种子推送到某个远程服务器的客户端上（也就是【下载到】）？

此外目前有一些站点在 details.php 中获取到的下载链接不包含 passkey，比如 KeepFRDS（我在站点设置里是填写了 passkey 的，并且 FRDS 的 details.php 里也包含了 passkey）

**Comment by Rhilip** [comment]
意思是类似userscript那样，插入content script，更改网站内a标签的href属性？？

**Comment by Aniverse** [comment]
（其实我一窍不通，所以我不敢说我完全理解了你的意思）应该就是你说的这个意思。
类似的  userscript 也有见到，要求用户自己在脚本内填写 passkey 然后替换的
由于我这方面水平为 0 所以……就出来伸手了 ←_←

**Comment by ronggang** [comment]
拖拽复制带passkey的方法可以试一下。:smile:
