### ISSUE TITLE
mteam无法获取用户数据

### ISSUE THREAD

**Issue by Alvinnfly** [ronggang/PT-Plugin-Plus#167]
- PT 助手版本: 1.0.7
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome 71
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：mteam只能获取魔力值，获取不到分享率做种体积上传量

![InkedSnipaste_2019-06-03_19-35-28_LI.jpg](https://i.loli.net/2019/06/03/5cf506b77c62717996.jpg)

**Comment by Rhilip** [comment]
重复issue： https://github.com/ronggang/PT-Plugin-Plus/issues/109
