### ISSUE TITLE
站点搜索入口配置页面不显示新增的配置

### ISSUE THREAD

**Issue by sdepool** [ronggang/PT-Plugin-Plus#1679]
站点搜索入口配置页面不显示新增的配置

**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x] 搜素过Issue，确认没有相关问题
- [x] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本: v1.6.1.2492
- PT 助手安装方式：crx
- 浏览器名称及版本：Edge
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：正常
- 问题描述：
站点搜索入口配置 可以添加新配置，在站点编辑页面和搜索方案中可以选择已经添加的配置，但搜索入口配置页面中没有显示新增的配置项，由于不能显示，也无法对搜索入口配置进行编辑或删除

- 相关截图：
![photo_2023-12-04_17-28-34](https://github.com/pt-plugins/PT-Plugin-Plus/assets/34946491/f7a7bd73-2167-4334-8d9c-664a47d1ea38)

- 重现步骤：

**Comment by IITII** [comment]
https://github.com/pt-plugins/PT-Plugin-Plus/wiki/search-entry-definition

**Comment by LUCKxxLUCK** [comment]
我同样遇到了这个问题，

PT 助手版本: v1.6.1.2749
PT 助手安装方式：crx
浏览器名称及版本：Edge
浏览器是否安装了其他插件：无
停用其他插件后是否正常工作：否
问题描述：
站点搜索入口配置 可以添加新配置，在站点编辑页面和搜索方案中可以选择已经添加的配置，但搜索入口配置页面中没有显示新增的配置项，由于不能显示，也无法对搜索入口配置进行编辑或删除
相关截图：
![1](https://github.com/user-attachments/assets/6af3ef18-28bb-475f-b695-f9ba25e37cc8)
![1](https://github.com/user-attachments/assets/353a0cc4-151e-4b01-b830-e565f4403885)
重新步骤：
1. 新增搜索方案，选定站点范围，
2. 从搜索方案页面进入搜索入口设置页面，新增搜索入口，
3. 完成后再再新增搜索方案时，可以选到新增的搜索入口，
4. 回到搜索入口页面无法显示已有的搜索入口配置（问题所在）※※※

我看到这个问题在2023年已经有人提出过，但目前似乎还没解决。
