### ISSUE TITLE
设置界面保存按钮是灰色的

### ISSUE THREAD

**Issue by lucenli** [ronggang/PT-Plugin-Plus#168]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.8
- PT 助手安装方式：（市场安装，或zip包安装） 市场安装
- 浏览器名称及版本：Cent浏览器4.0.9.112（正式版本） （64 位） (Chromium 74.0.3729.169)
- 浏览器是否安装了其他插件：是，有一些其他的，但是和pt功能无关
- 停用其他插件后是否正常工作：未尝试
- 问题描述：
在修改设置之后，保存按钮是灰色的，不能点击保存。我确定已经给了权限。包括收集网址在内的所有权限。

- 相关截图：
不知道为什么上传截图失败

**Comment by lucenli** [comment]
好像是因为没有设置“默认下载站点”

**Comment by Rhilip** [comment]
是这个原因，
