### ISSUE TITLE
功能建议：添加字幕信息

### ISSUE THREAD

**Issue by somulight** [ronggang/PT-Plugin-Plus#169]
很多资源的字幕是作为附件的，一个一个查很麻烦，如果可以在结果列表里直接显示出有无字幕附件就好了

**Comment by ronggang** [comment]
@somulight 除个别站可以一次获取字幕信息外，大部分站不能直接获取到这些信息，所以请求量太大，对服务器有影响，还有可能被限制，所以不太可取。
如果使用第三方服务查询字幕，不一定能精准匹配，所以加了可能作用不大。
