### ISSUE TITLE
将来会支持rtorrent吗

### ISSUE THREAD

**Issue by Frank-Gith** [ronggang/PT-Plugin-Plus#17]
感谢作者写了这么优秀的软件，请问后面可能会支持rtorrent下载服务器吗

**Comment by ronggang** [comment]
@Frank-Gith 回头研究一下，看看接口复不复杂。

**Comment by Rhilip** [comment]
请 升级到 `1.0.0.16` 以上
https://github.com/ronggang/PT-Plugin-Plus/releases/tag/v1.0.0.16
