### ISSUE TITLE
keepfrds 魔力值位置变动，抓取成做种率

### ISSUE THREAD

**Issue by zieglar** [ronggang/PT-Plugin-Plus#170]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.8
- PT 助手安装方式：zip
- 浏览器名称及版本： chrome 74.0.3729.169
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：无
- 问题描述：
朋友站魔力信息位置变动，魔力数值抓取成做种率

- 相关截图：
![image](https://user-images.githubusercontent.com/514693/59280565-5de95080-8c98-11e9-8125-f510ad126180.png)
![image](https://user-images.githubusercontent.com/514693/59280573-63df3180-8c98-11e9-9af5-22fcd2e71282.png)

**Comment by ronggang** [comment]
暂无该站的号，有号的同学可以帮助看一下。

**Comment by dahubiox** [comment]
确实如此，魔力值显示的是做种率

**Comment by doyouhike** [comment]
这个问题已经有人发现了，顶一下

**Comment by Rhilip** [comment]
当前的dom结构
```html
<tr>
   <td width="1%" class="rowhead nowrap" valign="top" align="right">魔力值</td>
   <td width="99%" class="rowfollow" valign="top" align="left">
      <table border="0" cellspacing="0" cellpadding="0">
         <tbody>
            <tr>
               <td class="embedded"><strong>做种率（魔力值/下载量）</strong>: 232</td>
            </tr>
            <tr>
               <td class="embedded"><strong>魔力值</strong>: 56130.2564 ₿&nbsp;&nbsp;&nbsp;&nbsp;[16.83 ₿/h]</td>
            </tr>
         </tbody>
      </table>
   </td>
</tr>
```
按照当前的处理方式（https://github.com/ronggang/PT-Plugin-Plus/blob/master/resource/schemas/NexusPHP/config.json#L110） 确实将**做种率**作为“魔力值”抓取了
（将做种率解释成 *魔力值/下载量* 也是有意思23333
