### ISSUE TITLE
一键导入站点失败，只能导入我宝一个站点……

### ISSUE THREAD

**Issue by ywyha** [ronggang/PT-Plugin-Plus#172]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：然后常规设置里的保存按钮一直是灰色，点不了…… 重装原版windows10，都没法解决，晕死了……

- 相关截图：

**Comment by ywyha** [comment]
额，保存按钮问题明白了，就是以前记着导入站点可以一键导入所有未添加的站点，现在貌似只有登陆后才能一键导入

**Comment by ronggang** [comment]
@ywyha 看来已经自己搞明白了😄

**Comment by ywyha** [comment]
> @ywyha看来已经自己搞明白了😄

感谢大佬提供这么方便的工具，谢谢。
