### ISSUE TITLE
麦田无法获取魔力值

### ISSUE THREAD

**Issue by 1kevin335200** [ronggang/PT-Plugin-Plus#174]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: 1.0.8
- PT 助手安装方式：（市场安装，或zip包安装）市场
- 浏览器名称及版本：Chrome 75
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
如图

- 相关截图：
![Screenshot_2019-06-14_08-34-14](https://user-images.githubusercontent.com/15524267/59488226-48824b00-8e7f-11e9-8d58-ac315b66573b.png)

**Comment by ronggang** [comment]
@1kevin335200 抱歉，该站我无法调试

**Comment by Rhilip** [comment]
该站在用户详情页‘魔力’行为“麦粒”，脚本暂不支持，我先通过修改NexusPHP的config.json文件先解决下吧。到时候再看看怎么处理这种各站该行名称不一致导致的问题，总感觉这种不断往 bonus->selector 里面塞不好。

是不是使用`mybonus.php`页面，这个`用你的[魔力值|麦粒]（当前5,515,020.6）换东东！` ，基本可以正则出来，这个会比较好些，不过这样会增加一次网络请求。

![image](https://user-images.githubusercontent.com/13842140/59553336-3eb72f80-8fc6-11e9-9fd0-1756d1f802cf.png)

**Comment by ronggang** [comment]
@Rhilip 多了之后，把 bonus->selector 挂到各自网站下也行。
或者把“魔力”这个名称单独抽出来定义，但这样不知道会不小题大作了。
