### ISSUE TITLE
ttg下载到服务器错误

### ISSUE THREAD

**Issue by sanzuwu** [ronggang/PT-Plugin-Plus#175]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.8
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Yandex Browser最新版
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
ttg搜索后下载到服务器错误，代码404，密钥已经添加到设置里

- 相关截图：
https://s2.ax1x.com/2019/06/14/V5Atyt.png

**Comment by ronggang** [comment]
@sanzuwu 无法复现出来，我测试时用不用passkey都没有出现你说的错误。
你可以试一下复制下载链接，直接在浏览器打开看看能不能下载。
如果不能下载，请把passkey去了，重新搜索，再试试能不能下载。
