### ISSUE TITLE
关于MT整页种子下载失败

### ISSUE THREAD

**Issue by Sakuyaaaaaa** [ronggang/PT-Plugin-Plus#176]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本: V1.08
- PT 助手安装方式：（市场安装，或zip包安装）chrome 应用商店
- 浏览器名称及版本：chrome stable 74.0.3729.169 
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：批量下载种子到服务器是会出现部分种子丢失，点击两次下载所有/下载到服务器，100个种子仅下载了80个，其中还有20个没有下载到服务器

- 相关截图：
[https://i.loli.net/2019/06/15/5d04e3f7d5f4238009.png](url)

**Comment by Sakuyaaaaaa** [comment]
期待您的回复

**Comment by ronggang** [comment]
@Sakuyaaaaaa 通常应该是网络问题，看一下助手的日志，有没有错误信息。如果是超时问题，可以把超时时间设置大一些。

**Comment by Sakuyaaaaaa** [comment]
好的，超时时间我设置下，之前为最小值500，现调整为10000进行测试

**Comment by Sakuyaaaaaa** [comment]
可以了，已经解决
