### ISSUE TITLE
firefox 51 无法使用该add-on，跳出授权页，无法下一步

### ISSUE THREAD

**Issue by jzz3933** [ronggang/PT-Plugin-Plus#177]
- PT 助手版本: 1.0.8
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Firefox 51.0.1（32位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：添加该add-on后，点击准备配置会跳出授权页，如图所示，无论是全选授权还是右边开关，均无法实现授权，无法进入下一个页面配置服务器

- 相关截图：
![bug](https://user-images.githubusercontent.com/7555599/59665034-b6fb3c00-91e4-11e9-8703-77d202b24af5.png)

**Comment by ronggang** [comment]
@jzz3933  刚刚试了一下Firefox 66版本的，可以正常使用。低版本的的确没有测试过，不知道会不会有其他问题。你看看可否升级一下版本？

**Comment by jzz3933** [comment]
使用chrome最新的浏览器，确实使用正常，应该是FF版本太老的原因，感谢开发这么优秀的插件！！！
