### ISSUE TITLE
ruT使用Flood前端无法推送

### ISSUE THREAD

**Issue by zuosc** [ronggang/PT-Plugin-Plus#178]
- PT 助手版本: 1.1.0
- PT 助手安装方式：（市场安装，或zip包安装） zip
- 浏览器名称及版本：版本 75.0.3770.100（正式版本） （64 位）
- 浏览器是否安装了其他插件： 是
- 停用其他插件后是否正常工作： 未尝试
- 问题描述：
利用开源项目  https://github.com/Flood-UI/flood 和docker镜像 https://hub.docker.com/r/romancin/rutorrent-flood/ ，  在docker中安装了这个项目。
在最外层利用nginx，进行了代理和域名配置。

这个项目如果直接访问的话，需要的端口是3000。所以在nginx中，配置的访问路径是3000。  整体对外只暴露了443端口，统一由nginx负责转发。

在配置服务器的时候，测试正常。但是无法正确下载，如下图。

- 相关截图：
![image](https://user-images.githubusercontent.com/8411781/60323576-072c8800-99b5-11e9-8c2b-bd489710340f.png)

![image](https://user-images.githubusercontent.com/8411781/60319359-c0d12c00-99a8-11e9-9ec1-ad49e159d7a4.png)
![image](https://user-images.githubusercontent.com/8411781/60319378-ce86b180-99a8-11e9-969f-51727e54f30d.png)

**Comment by zuosc** [comment]
翻了下源码，似乎不支持我这个客户端😣😫😣😥

咋办呢

**Comment by Rhilip** [comment]
暂不支持flood，这个要另写适配

**Comment by zuosc** [comment]
@Rhilip   不要咕咕咕  拉我，我当实验对象！！！

**Comment by ronggang** [comment]
请更新至 v1.1.2 版本。
