### ISSUE TITLE
Mac上的chrome  添加站点后无法搜索  显示连接错误

### ISSUE THREAD

**Issue by 1106681834** [ronggang/PT-Plugin-Plus#18]
Mac上的Chrome 71.0.3578.98  ptplugin  1.0.0.14
添加一个站点时  可以正常搜索  查看最新种子
在添加四五个站点的时候 再进行搜索  所有站点均会提示网络连接错误

另外  连接不上deluge下载服务  显示连接失败

同样网络环境  windows下无此问题

**Comment by ronggang** [comment]
@1106681834 请更新到最新版再观察错误是否还存在，主题暂时先关闭了，有需要再打开。
