### ISSUE TITLE
使用一键推送出现提示：系统依赖函数（getQueryString）未正确加载，请尝试刷新页面或重新启用插件。

### ISSUE THREAD

**Issue by aptxhql** [ronggang/PT-Plugin-Plus#181]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:v1.1.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Google Chrome 版本 75.0.3770.100（正式版本）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
使用一键推送出现提示：系统依赖函数（getQueryString）未正确加载，请尝试刷新页面或重新启用插件。

- 相关截图：
![bug](https://user-images.githubusercontent.com/50664015/60720947-e63cd780-9f5e-11e9-9252-6f35852ea1d7.png)

**Comment by ronggang** [comment]
@aptxhql 感谢反馈，该bug已修复，待发布。https://github.com/ronggang/PT-Plugin-Plus/commit/334becbd2c16042b0ede51903daf96ee3099e05e

**Comment by aptxhql** [comment]
感谢，这个插件真的很好用
