### ISSUE TITLE
春天的域名改下

### ISSUE THREAD

**Issue by Se7enMuting** [ronggang/PT-Plugin-Plus#182]
复活了，春天的域名改下

如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

**Comment by Rhilip** [comment]
知道了，不用催，催了也没用。（你也要等下一版发版。
请自己先用CDN域名顶上
