### ISSUE TITLE
下载历史不显示标题

### ISSUE THREAD

**Issue by longnk** [ronggang/PT-Plugin-Plus#189]
- PT 助手版本:v1.1.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Google Chrome(70.0.3538.110)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
在种子列表页使用右键推送下载时,下载历史中不显示标题
在种子列表页拖动种子链接到助手图标下载时,下载历史中显示标题,但是链接错误
在种子详情页使用右键推送下载时,下载历史中不显示标题
- 相关截图：
![1](https://user-images.githubusercontent.com/28484363/61018369-384f8400-a3c9-11e9-9ca0-971441ae65c0.jpg)

**Comment by ronggang** [comment]
@longnk 感谢反馈，这的确是已知的Bug，因为现在还没有好的办法在点击右键时获取正确的标题。

**Comment by longnk** [comment]
@ronggang 感谢作者的回复
这是个相当好用的插件,希望能早日找到解决方法
