### ISSUE TITLE
希望默认下载服务器可以选和新增下载服务器(Vuze)

### ISSUE THREAD

**Issue by zhihaofans** [ronggang/PT-Plugin-Plus#191]
**您的功能请求是否与问题有关？ 请描述一下。**

1. 在没有选择下载服务器的情况下无法保存设置，有时不想用下载功能都不能保存设置

2. 希望新增对Vuze Remote的支持

**描述你想要的解决方案**

1. Vuze 官方wiki: https://wiki.vuze.com/w/Vuze_Web_Remote

**描述您考虑过的替代方案**
无

**其他附加信息**
无

**Comment by Rhilip** [comment]
试试使用trabsmission的方式注册vuez remote，因为看文档说明，两者实现差不多？

**Comment by ronggang** [comment]
@zhihaofans 以后会考虑允许不设置默认下载服务器。
另外，如 @Rhilip 所说，文档上的确写了兼容Transmission的接口，试一下填写类似这样的地址：
```
http://192.168.1.1:9091/vuze/rpc
```
看看是否能正常工作。

**Comment by zhihaofans** [comment]
@ronggang @Rhilip 在浏览器未登陆vuze remote网页版时扩展就提示`身份验证失败`，在浏览器登陆后就提示`error`

**Comment by ronggang** [comment]
@zhihaofans 试了一下，直接使用 `http://192.168.1.1:9091/ ` 这样的地址即可。
用户名我使用的是默认的 vuze
密码就是那个什么安全码

**Comment by ted423** [comment]
vuze似乎很久很久没更新。
是否有进一步反馈？
是否使用TR模板即可？

**Comment by ted423** [comment]
vuze最后更新日期为2017年，感觉保持现状就好
