### ISSUE TITLE
deluge默认下载目录存在问题

### ISSUE THREAD

**Issue by hydd** [ronggang/PT-Plugin-Plus#194]
- PT 助手版本:1.1.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Chrome 75.0.3770.80
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
1、在常规设置中设置deluge为默认下载服务器后，在pt站种子详情页点击“一键下载”或者“下载到deluge（未包含插件下载目录设置中设置的目录）”时，文件被默认下载到服务器根目录（/），而非deluge默认下载目录。
2、当点击包含自定义下载目录的deluge下载连接时下载正常。
如下截图蓝色服务器会出现错误，红色选中正常（一键下载同样错误）。
- 相关截图：
![image](https://user-images.githubusercontent.com/10320073/61516085-ba2d5600-aa36-11e9-97a9-809136af3927.png)

**Comment by LeonChenlz** [comment]
You should confirm your Sava path is not the absoluted path，if you run your download programme in docker
