### ISSUE TITLE
新增下载服务器没有类型

### ISSUE THREAD

**Issue by pwbty** [ronggang/PT-Plugin-Plus#2]
新增下载服务器没有类型，点击下面指引按钮到git里下载也不知道放在哪里，wiki中也没有写

**Comment by ronggang** [comment]
如果是一个类型也出不来，可能是配置信息没有加载完成。如果没有想要的类型，现在只能放到github仓库才可以，如果要添加新的，要提交新的RP，我合并后就可以了，文档会继续完善。

**Comment by pwbty** [comment]
> 如果是一个类型也出不来，可能是配置信息没有加载完成。如果没有想要的类型，现在只能放到github仓库才可以，如果要添加新的，要提交新的RP，我合并后就可以了，文档会继续完善。

是一个都没有，我没有试长时间加载。通过商店安装的插件。

**Comment by ronggang** [comment]
> > 如果是一个类型也出不来，可能是配置信息没有加载完成。如果没有想要的类型，现在只能放到github仓库才可以，如果要添加新的，要提交新的RP，我合并后就可以了，文档会继续完善。
> 
> 是一个都没有，我没有试长时间加载。通过商店安装的插件。

商店通过审核了吗？我去看看。
商店的版本滞后，所以有些BUG，你可以试试用压缩包的方式安装最新版本看看。

**Comment by smilezino** [comment]
同样问题  

版本：v1.0.0.11
chrome版本： 71.0.3578.98（正式版本） （64 位）
插件配置页面错误日志：
```
TypeError: Cannot read property 'clients' of undefined
    at a.created (Index.vue:123)
    at Je (vue.runtime.esm.js:3025)
    at a.t._init (vue.runtime.esm.js:4722)
    at new a (vue.runtime.esm.js:4888)
    at Gn (vue.runtime.esm.js:4391)
    at init (vue.runtime.esm.js:4222)
    at m (vue.runtime.esm.js:5695)
    at f (vue.runtime.esm.js:5642)
    at S (vue.runtime.esm.js:5933)
    at D (vue.runtime.esm.js:6036)
```

**Comment by ronggang** [comment]
@pwbty @smilezino 更新到新版试试还有没有这个错误。

**Comment by pwbty** [comment]
那天我又弄了，是把chrom代理方式从系统代理换成直连之后就获取到了。在此之前从商店版换成了离线安装，之后获取了几次都没问题了。

**Comment by Rhilip** [comment]
这个问题应该在 https://github.com/ronggang/PT-Plugin-Plus/releases/tag/v1.0.0.13 中得到了解决，我们将资源直接打包到本地，而不是通过Github获取。
请尝试更新并反馈 @pwbty @smilezino
