### ISSUE TITLE
关于PT站点gay-torrents.org的支持

### ISSUE THREAD

**Issue by James-Jie** [ronggang/PT-Plugin-Plus#202]
- 希望大佬能加入下gay-torrents.org站点的支持 因为目前所有的类型都试过了都不能够自定义添加 这个也是一个十年的老站了

**Comment by ronggang** [comment]
为更好的收集需求，请重新选择【新站点请求】模板发起 issue。本主题暂时关闭。

**Comment by z997974738** [comment]
可以求一个gay-torrents的邀请吗，我找了好久关于bl的站点，终于在这里看到了。自己有nas

**Comment by z997974738** [comment]
如果可以的话，这是我的邮箱，z997974738@qq.com，非常感谢
