### ISSUE TITLE
种子下载到服务器没有反应

### ISSUE THREAD

**Issue by LeonChenlz** [ronggang/PT-Plugin-Plus#203]
- PT 助手版本:v1.1.1
- PT 助手安装方式：（市场安装，或zip包安装）市场安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：未测试
- 问题描述：
馒头自定义网址后，下载种子到服务器时，选择自定义的目录 无效

- 相关截图：

点击下载种子到服务器后无效，但是选择下载器默认的目录有效。
- 重现步骤：
 修改馒头为新地址后，重新设置下载目录，默认下载目录有效，自定义的目录无效

**Comment by LeonChenlz** [comment]
![image](https://user-images.githubusercontent.com/20943712/61938501-dcd5e680-afc3-11e9-885a-3cac6ac50973.png)

**Comment by LeonChenlz** [comment]
![image](https://user-images.githubusercontent.com/20943712/61938550-f6772e00-afc3-11e9-910f-37b42b016666.png)

**Comment by ronggang** [comment]
@LeonChenlz 感谢反馈。
