### ISSUE TITLE
天雪PT无法显示做种体积

### ISSUE THREAD

**Issue by mitsuha97** [ronggang/PT-Plugin-Plus#205]
- PT 助手版本:1.1.1
- PT 助手安装方式：（市场安装）
- 浏览器名称及版本：火狐版本: 68.0.1 (64 位)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：天雪PT保种数量133正常显示，但是保种体积显示N/A。我保种估计3-4T。是不是因为太大显示不了？

- 相关截图：
![图片](https://user-images.githubusercontent.com/46256599/62064534-a4eacf80-b25f-11e9-903c-ab3cbd4312ea.png)

- 重现步骤：

**Comment by ronggang** [comment]
暂时没发现哪里可以获取保种体积，如果你知道方法，还请告知。
