### ISSUE TITLE
搜索结果中  chd种子名称中的@及后续字符会显示成[email protected]

### ISSUE THREAD

**Issue by 786745168** [ronggang/PT-Plugin-Plus#206]
- PT 助手版本:V1.1.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：谷歌浏览器 75.0.3770.142
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：
- 问题描述：搜索结果中chd种子名称中的@及后续字符会显示成[email protected]

- 相关截图：
![image](https://user-images.githubusercontent.com/48416620/62120071-80403780-b2f3-11e9-8a1f-5463d2769c4c.png)

- 重现步骤：

**Comment by Rhilip** [comment]
请问是否与该issue情况相同 https://github.com/ronggang/PT-Plugin-Plus/issues/97

**Comment by 786745168** [comment]
> 请问是否与该issue情况相同 #97

是的，不过我的TTG不会，只有CHD是这样

**Comment by ronggang** [comment]
> > 请问是否与该issue情况相同 #97
> 
> 是的，不过我的TTG不会，只有CHD是这样

因为TTG已被 @Rhilip 修复了。

**Comment by 786745168** [comment]
> > > 请问是否与该issue情况相同 #97
> > 
> > 
> > 是的，不过我的TTG不会，只有CHD是这样
> 
> 因为TTG已被 @Rhilip 修复了。

搜噶，那期待在下一个版本中CHD也能被修复
