### ISSUE TITLE
2778版Pter（猫站）无法获取用户数据

### ISSUE THREAD

**Issue by liuqiqi79** [ronggang/PT-Plugin-Plus#2072]
**请确认你已经做过并了解如下步骤，在 `[]` 中填入 `x` 选中**
- [x ] 仔细看并搜索过[Wiki](https://github.com/pt-plugins/PT-Plugin-Plus/wiki)
- [x ] 请确认你的版本比当前[Pre-release](https://github.com/pt-plugins/PT-Plugin-Plus/tags)要新，我们建议使用crx版本作为标准
- [x ] 搜素过Issue，确认没有相关问题
- [x ] 不理解、询问问题或者使用上的问题请使用Discuissions

- PT 助手版本:1.6.1.2778
- PT 助手安装方式：github下载的crx安装
- 浏览器名称及版本：360X 22.3，傲游7.1.8
- 浏览器是否安装了其他插件：安装有PTPP1.5.2版本
- 停用其他插件后是否正常工作：否
- 问题描述：更新到1.6.1.2778后，别的站可一键导入站点且数据正确。Pter需手动添加，添加后更新数据显示：“发生错误”

- 相关截图：
![QQ20241206-161217](https://github.com/user-attachments/assets/2293d203-254e-4051-a428-8b26ea748c93)

- 重现步骤：
1、从github下载的1.6.1.2778版本crx，拖入浏览器，完成安装
2、站点设置——一键导入站点——其他站可自动导入，Pter搜索不到
3、站点设置——新增——手动添加Pter
4、我的数据——刷新分组数据，其它站点都可获取，Pter显示：发生错误。连续两天不同时段，不同浏览器尝试刷新，都显示：发生错误。
5、搜索种子功能正常。

**Comment by nobodypengium** [comment]
1.6.1.1版本，有同样问题。
更新站点数据时，pter显示“发生错误”
![image](https://github.com/user-attachments/assets/09dae0bb-844a-4d6e-8919-0e81f9e41e2e)
刷新页面后，显示“未知错误”
![image](https://github.com/user-attachments/assets/90c807ed-d95f-4d52-978f-da4f73f4eb6a)

**Comment by hui-shao** [comment]
这是因为 CF 盾吧，大概率要等站点解除

**Comment by jingsu2000** [comment]
![1](https://github.com/user-attachments/assets/5223b6c0-946d-445e-b86d-ef771c5cb2fb)
同样的问题，点了报错“打开异常状态的网站”，弹出来的网站没有id，导致报错

**Comment by nobodypengium** [comment]
> 1.6.1.1版本，有同样问题。 更新站点数据时，pter显示“发生错误” ![image](https://private-user-images.githubusercontent.com/13833330/393503543-09dae0bb-844a-4d6e-8919-0e81f9e41e2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDk5NjQsIm5iZiI6MTczNDQ0OTY2NCwicGF0aCI6Ii8xMzgzMzMzMC8zOTM1MDM1NDMtMDlkYWUwYmItODQ0YS00ZDZlLTg5MTktMGU4MWY5ZTQxZTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE1MzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjYTk1NTI3MGJhZDJjMmZlOGQ3MzVlNjNhZGE5NjI4YmIwZmFjZjQyZDgwOTQ1YmViMmRlOGNhODJmNjc1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wAHiPYBy1JGEsVq6PLyGIFknVJ9vxPhLH3r8SLKpF-E) 刷新页面后，显示“未知错误” ![image](https://private-user-images.githubusercontent.com/13833330/393503601-90c807ed-d95f-4d52-978f-da4f73f4eb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NDk5NjQsIm5iZiI6MTczNDQ0OTY2NCwicGF0aCI6Ii8xMzgzMzMzMC8zOTM1MDM2MDEtOTBjODA3ZWQtZDk1Zi00ZDUyLTk3OGYtZGE0ZjczZjRlYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE1MzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViY2I2MGZjNTczZjcwN2YyMWE5OGExYTY2YTQ2NjJlZDlkNjY1MWU3NDI5NjlhOGVhM2QwNWJhZDFmNjA4ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KnWYHSKBi7Xje6AFbq18TKFOz-WCfgm8GbC8UWAw5GU)
更新，我这里好用了。

**Comment by ted423** [comment]
删站点配置，重加试试
https://github.com/pt-plugins/PT-Plugin-Plus/issues/1063
