### ISSUE TITLE
ExoticaZ站点无法获取做种体积，显示为N/A

### ISSUE THREAD

**Issue by songzelin** [ronggang/PT-Plugin-Plus#208]
- PT 助手版本:1.1.0/1.1.1
- PT 助手安装方式：GOOGLE商店（市场安装，或zip包安装）
- 浏览器名称及版本：QQ浏览器
- 浏览器是否安装了其他插件：很多
- 停用其他插件后是否正常工作：不能
- 问题描述：ExoticaZ站点无法获取做种体积，显示为N/A，上传下载分享率等正常，
只有做种体积显示错误

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
暂不支持。

**Comment by ted423** [comment]
看起来https://github.com/ronggang/PT-Plugin-Plus/releases/tag/v1.4.3 中解决了
