### ISSUE TITLE
M-team搜索无副标题

### ISSUE THREAD

**Issue by charmingYouYou** [ronggang/PT-Plugin-Plus#209]
- PT 助手版本: v1.1.2
- PT 助手安装方式：chrome插件（市场安装，或zip包安装）
- 浏览器名称及版本：chrome v75.0.3770.142
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
M-team搜索无副标题

- 相关截图：
![image](https://user-images.githubusercontent.com/31199453/62456992-5d5acb00-b7ac-11e9-9f0d-1d634567a842.png)

- 重现步骤：
任意搜索

**Comment by ronggang** [comment]
@charmingYouYou 请提供一下站点里的[设置](https://pt.m-team.cc/usercp.php?action=tracker)信息，如：
![image](https://user-images.githubusercontent.com/8065899/62501610-30470080-b81e-11e9-9d20-35891b1aade4.png)
谢谢。

**Comment by charmingYouYou** [comment]
![image](https://user-images.githubusercontent.com/31199453/62508738-4a430c00-b83b-11e9-881d-9e776e0dd751.png)
已反馈

**Comment by ronggang** [comment]
@charmingYouYou 按你的配置无法复现。
你把站点删除，重新添加试一下。

**Comment by charmingYouYou** [comment]
把站点删除还是没有用, 删除1.1.2插件重新从谷歌商店下载后还是无效, 目前改用v1.1.1可以正常显示副标题 @ronggang

**Comment by ronggang** [comment]
> 把站点删除还是没有用, 删除1.1.2插件重新从谷歌商店下载后还是无效, 目前改用v1.1.1可以正常显示副标题 @ronggang

感谢反馈。
是搜索解析的地方，域名没有变更过来。

**Comment by charmingYouYou** [comment]
@ronggang 想问下, 项目还需要开发者吗? 对这个项目挺感兴趣的, 也想参与进来 . 自己是个前端~

**Comment by ronggang** [comment]
> @ronggang 想问下, 项目还需要开发者吗? 对这个项目挺感兴趣的, 也想参与进来 . 自己是个前端~

欢迎参与开发，可以加入开发交流Q群一起讨论：773500545
