### ISSUE TITLE
有些东西搜不到

### ISSUE THREAD

**Issue by waltchan007** [ronggang/PT-Plugin-Plus#21]
M-Team 搜 “知否知否” 搜不到

**Comment by Rhilip** [comment]
无法复现，请检查是不是被MT的二步验证给拦截了
![image](https://user-images.githubusercontent.com/13842140/52101813-40381a80-2618-11e9-8319-1845cb7b4c5e.png)

**Comment by Rhilip** [comment]
长期未得到反馈，请尝试升级到最新版本，如果问题还是出现。请重新开启此issue或另行反馈
