### ISSUE TITLE
一键添加站点错误的添加了ourbits

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#210]
- PT 助手版本:
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：
可随便重现

之前完全没访问过ourbits

**Comment by ted423** [comment]
另外moecat 无法被添加

**Comment by ted423** [comment]
唔，我是通过pt4.moecat登进去的，这个站点有点奇怪。。。可以不管了

**Comment by ted423** [comment]
custom里经常窗口自己就关了

**Comment by ted423** [comment]
custom添加后schema无法修改

**Comment by Rhilip** [comment]
烦请一次性说清楚问题，也请不要同一个issue叙述不同问题。
