### ISSUE TITLE
moecat站点搜索无法显示大小

### ISSUE THREAD

**Issue by windmaster-pt** [ronggang/PT-Plugin-Plus#215]
- PT 助手版本:v1.12
- PT 助手安装方式：群晖教程
- 浏览器名称及版本：360
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：
- 问题描述：
moecat站点搜索无法显示大小
其他站都没问题 

- 相关截图：
![QQ图片20190814052247](https://user-images.githubusercontent.com/53789414/62978321-96053f00-be53-11e9-9acd-5216a775b122.png)

- 重现步骤：

**Comment by ronggang** [comment]
@windmaster-pt 请提供一下站点的“网站设定”完整截图，谢谢。

**Comment by windmaster-pt** [comment]
![QQ图片20190814081820](https://user-images.githubusercontent.com/53789414/62985985-42531f80-be6c-11e9-98c0-02737bcbebe4.png)

**Comment by ronggang** [comment]
@windmaster-pt 按你的设置无法复现。
请确认是否使用的是官方提供的配置添加的站点。如果是自定义的方式添加的站点，无法保证所有功能都正常。

**Comment by windmaster-pt** [comment]
是自动添加的站点 不是自定义的发自我的华为手机-------- 原始邮件 --------主题：Re: [ronggang/PT-Plugin-Plus] moecat站点搜索无法显示大小 (#215)发件人：栽培者 收件人：ronggang/PT-Plugin-Plus 抄送：windmaster-pt <82826691@qq.com>,Mention @windmaster-pt 按你的设置无法复现。

请确认是否使用的是官方提供的配置添加的站点。如果是自定义的方式添加的站点，无法保证所有功能都正常。



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ronggang/PT-Plugin-Plus/issues/215?email_source=notifications\u0026email_token=AM2MFZTHXHFVF56UAKLRT23QENGJ7A5CNFSM4ILO45S2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4HLJTA#issuecomment-521057484",

"url": "https://github.com/ronggang/PT-Plugin-Plus/issues/215?email_source=notifications\u0026email_token=AM2MFZTHXHFVF56UAKLRT23QENGJ7A5CNFSM4ILO45S2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4HLJTA#issuecomment-521057484",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ronggang** [comment]
那只能试试换个干净的浏览器试一下。

**Comment by Bender1337** [comment]
我用的QQ浏览器也是这个问题。 MTEAM不显示副标题，其他网站正常！

**Comment by snailwind** [comment]
你好，我同样使用了这个站点，刚测试了一下，可以显示大小，不清楚你那边是否解决了。不过我有其他的搜索方面的问题，部分内容无法搜索到。测试内容【海边的曼彻斯特】，在站内可以搜索到。 @windmaster-pt @ronggang

**Comment by ronggang** [comment]
> 你好，我同样使用了这个站点，刚测试了一下，可以显示大小，不清楚你那边是否解决了。不过我有其他的搜索方面的问题，部分内容无法搜索到。测试内容【海边的曼彻斯特】，在站内可以搜索到。@windmaster-pt @ronggang
> 刚看了下设置，默认使用的是ID搜索未能搜索到，启用模糊搜索后可以找到。 虽然符合逻辑，但ID在发布时已经进行过匹配，应该也可以对应到才对。不清楚这是否算bug。

当前站点不支持 IMDB 编号直接搜索，后续会改为豆瓣编号。

**Comment by xmt328** [comment]
我也遇到了同样的问题，下面是网站设定截图
1.3.1版本，站点不是手动添加的
搜索任意关键字都不显示种子大小，比如“教父”
![image](https://user-images.githubusercontent.com/17491710/66647455-8d669480-ec5b-11e9-859f-e9d1929e1f11.png)
