### ISSUE TITLE
ipt站概览无法显示做种体积 其他站点正常

### ISSUE THREAD

**Issue by windmaster-pt** [ronggang/PT-Plugin-Plus#216]
- PT 助手版本:v1.1.2
- PT 助手安装方式：群晖
- 浏览器名称及版本：360
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
ipt站概览无法显示做种体积 其他站点正常
![QQ图片20190814052540](https://user-images.githubusercontent.com/53789414/62978578-30658280-be54-11e9-8fe3-ada7b98d4488.png)

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
N/A 表示暂不支持。
