### ISSUE TITLE
能否关联tr增加一键辅种功能

### ISSUE THREAD

**Issue by windmaster-pt** [ronggang/PT-Plugin-Plus#217]
**您的功能请求是否与问题有关？ 请描述一下。**

pt辅种起来可以大工程 一个两个站不显 要是上前的种子 十几个站 一个个手工找起来那功夫可就大了
**描述你想要的解决方案**

比如可以让用户关联tr 在tr或ptpp里为每个正在做种的种子后面增加选项 如果后台搜索到用户其他关联pt站点有相同的种子 可以提示并通知用户可以选择一键为所有网站 或自定义站定辅种 
**描述您考虑过的替代方案**

**其他附加信息**

**Comment by Rhilip** [comment]
1. 相关功能已有类似实现，请考虑直接使用 https://github.com/tongyifan/Reseed-backend 
2. 本repo之前已有issue讨论过相关问题， https://github.com/ronggang/PT-Plugin-Plus/issues/106

**Comment by windmaster-pt** [comment]
看过了 可惜卡在TJUPT注册方面了 唉 我试试能不能搞到邀请码吧
------------------
----------------------------------------------------------------------------
顺颂商祺！


张春意


北京中立鸿会计师事务所有限责任公司
地址：北京市海淀区西直门北大街32号枫蓝国际中心B座504A
邮编：100082
电话：010-82418607
手机：13366065395
传真：010-82418135



 




------------------ 原始邮件 ------------------
发件人: "Rhilip"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 上午7:46
收件人: "ronggang/PT-Plugin-Plus"<PT-Plugin-Plus@noreply.github.com>;
抄送: "风少"<82826691@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ronggang/PT-Plugin-Plus] 能否关联tr增加一键辅种功能 (#217)



 
相关功能已有类似实现，请考虑直接使用 https://github.com/tongyifan/Reseed-backend
 
本repo之前已有issue讨论过相关问题， #106

**Comment by tongyifan** [comment]
@windmaster-pt 留邮箱

**Comment by windmaster-pt** [comment]
82826691@qq.com

**Comment by windmaster-pt** [comment]
呃 非常感激 意外收获一枚啊发自我的华为手机-------- 原始邮件 --------主题：Re: [ronggang/PT-Plugin-Plus] 能否关联tr增加一键辅种功能 (#217)发件人：Yifan Tong 收件人：ronggang/PT-Plugin-Plus 抄送：windmaster-pt <82826691@qq.com>,Mention @windmaster-pt 留邮箱



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ronggang/PT-Plugin-Plus/issues/217?email_source=notifications\u0026email_token=AM2MFZT6ICWWOO5XAWRPVA3QENF5DA5CNFSM4ILPCDVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4HLE5Q#issuecomment-521056886",

"url": "https://github.com/ronggang/PT-Plugin-Plus/issues/217?email_source=notifications\u0026email_token=AM2MFZT6ICWWOO5XAWRPVA3QENF5DA5CNFSM4ILPCDVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4HLE5Q#issuecomment-521056886",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by ronggang** [comment]
@windmaster-pt 邮件回复个人信息严重泄露啊。😅

**Comment by Rhilip** [comment]
@windmaster-pt 已帮忙删除所有信息，还请理解。
其他希望获取tju邀请的看 Reseed 相关tg频道 https://t.me/reseed_tongyifan_me 的说明信息。

**Comment by windmaster-pt** [comment]
请教一下 那个辅种的教材群晖为何无法保存JSON文件
站内pm你 总是上传图片失败


------------------ 原始邮件 ------------------
发件人: "Rhilip"<notifications@github.com>;
发送时间: 2019年8月14日(星期三) 上午7:46
收件人: "ronggang/PT-Plugin-Plus"<PT-Plugin-Plus@noreply.github.com>;
抄送: "风少"<82826691@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ronggang/PT-Plugin-Plus] 能否关联tr增加一键辅种功能 (#217)




Closed #217.

**Comment by Rhilip** [comment]
@windmaster-pt 无关ptpp插件问题还请与他处讨论，感谢理解。
