### ISSUE TITLE
如何在Web页面上调用PT助手的下载功能

### ISSUE THREAD

**Issue by yushiro** [ronggang/PT-Plugin-Plus#220]
我自己在PT站的浏览页做了一些脚本， 目前想模拟对某一条目右键->PT plugin plus->发送到某一服务器， 这样的操作， 请问如何调用PT助手的内部下载link？

**Comment by Rhilip** [comment]
做不到，通过Tampermonkey等注入的用户脚本访问不到助手注入页面的PTService对象，也无法访问助手后台。

**Comment by ronggang** [comment]
助手暂未提供这样的接口。

**Comment by yushiro** [comment]
好的， 感谢各位回复。
只是觉得目前下载某一条目， 要么进入详情页， 要么需要鼠标邮件点击好几次才能下载， 有点麻烦， 所以看看能否把“下载”的功能坐在列表页， 这样可以直接点击下载了。

**Comment by ronggang** [comment]
> 好的， 感谢各位回复。
> 只是觉得目前下载某一条目， 要么进入详情页， 要么需要鼠标邮件点击好几次才能下载， 有点麻烦， 所以看看能否把“下载”的功能坐在列表页， 这样可以直接点击下载了。

直接拖放就可以了。

**Comment by yushiro** [comment]
> > 好的， 感谢各位回复。
> > 只是觉得目前下载某一条目， 要么进入详情页， 要么需要鼠标邮件点击好几次才能下载， 有点麻烦， 所以看看能否把“下载”的功能坐在列表页， 这样可以直接点击下载了。
> 
> 直接拖放就可以了。

直接拖放不能选择服务器， 我希望能够在某些板块下， 下载link发送到服务器2， 某些板块，发送到服务器1， 所以才想用js手动调用

**Comment by ronggang** [comment]
> > > 好的， 感谢各位回复。
> > > 只是觉得目前下载某一条目， 要么进入详情页， 要么需要鼠标邮件点击好几次才能下载， 有点麻烦， 所以看看能否把“下载”的功能坐在列表页， 这样可以直接点击下载了。
> > 
> > 
> > 直接拖放就可以了。
> 
> 直接拖放不能选择服务器， 我希望能够在某些板块下， 下载link发送到服务器2， 某些板块，发送到服务器1， 所以才想用js手动调用

直接拖放到 `下载到` 图标上就可以了。
1.1.2 及之前的版本支持 `NexusPHP` 站点；
1.1.2 之后支持所有站点；

如果真的想自己写脚本，可以考虑自定义插件的方式：
https://github.com/ronggang/PT-Plugin-Plus/wiki/config-custom-plugin

**Comment by yushiro** [comment]
> > > > 好的， 感谢各位回复。
> > > > 只是觉得目前下载某一条目， 要么进入详情页， 要么需要鼠标邮件点击好几次才能下载， 有点麻烦， 所以看看能否把“下载”的功能坐在列表页， 这样可以直接点击下载了。
> > > 
> > > 
> > > 直接拖放就可以了。
> > 
> > 
> > 直接拖放不能选择服务器， 我希望能够在某些板块下， 下载link发送到服务器2， 某些板块，发送到服务器1， 所以才想用js手动调用
> 
> 直接拖放到 `下载到` 图标上就可以了。
> 1.1.2 及之前的版本支持 `NexusPHP` 站点；
> 1.1.2 之后支持所有站点；
> 
> 如果真的想自己写脚本，可以考虑自定义插件的方式：
> https://github.com/ronggang/PT-Plugin-Plus/wiki/config-custom-plugin

感谢，已经用插件的方式， 基本实现原先的期望功能了。
