### ISSUE TITLE
大佬 大佬，统计数据能不能增加个自由切换PB、TB、GB单位呀

### ISSUE THREAD

**Issue by ywyha** [ronggang/PT-Plugin-Plus#221]
**您的功能请求是否与问题有关？ 请描述一下。**
现在的统计数据PB之后是以10TB为单位，这个范围太大了也无法精确显示数据量

**描述你想要的解决方案**
 所以希望增加个切换单位的按钮

**描述您考虑过的替代方案**

**其他附加信息**

感谢大佬为PT提供这么好用的工具

**Comment by ronggang** [comment]
因为没有PB的场景可以测试，回头我模拟一下看看如何显示看起来比较直观。

**Comment by ywyha** [comment]
> 因为没有PB的场景可以测试，回头我模拟一下看看如何显示看起来比较直观。

![QQ截图20190819202429](https://user-images.githubusercontent.com/38624632/63265130-6d4fd000-c2bf-11e9-9ec9-89680e36a523.png)
大佬，还有如果能在首页直接显示出所有站点的累计上传下载魔力数据量和与上一次刷新数据的增减就好了，那样就能更直观的了解每日数据变化
