### ISSUE TITLE
movies I want 

### ISSUE THREAD

**Issue by zuosc** [ronggang/PT-Plugin-Plus#223]
**您的功能请求是否与问题有关？ 请描述一下。**
https://hub.docker.com/r/linuxserver/couchpotato

this project has one feature: movies I want

so, can we do this?

**描述你想要的解决方案**
like this:  https://hub.docker.com/r/linuxserver/couchpotato

**描述您考虑过的替代方案**

**其他附加信息**

**Comment by ronggang** [comment]
是否具体描述一下。

**Comment by zuosc** [comment]
> 是否具体描述一下。

简单来说，就是输入一个还没出或者快要出的电影名称。  然后定时去轮询。如果一旦发现，就立刻通知或者自动下载。

基本上就是这样一个功能。  感觉应该挺有用~

**Comment by ronggang** [comment]
设置想要电影简单，下载就挺复杂，主要是要知道什么样的目标才合适，比如大小，分辨率，小组等等。

**Comment by zuosc** [comment]
> 设置想要电影简单，下载就挺复杂，主要是要知道什么样的目标才合适，比如大小，分辨率，小组等等。

是的。有很多细节问题是需要好好考虑的。

不过新功能嘛，如果觉得可以有。  可以先实现，后完善嘛~

毕竟只是个建议~

**Comment by ronggang** [comment]
长时间后台任务，这个是硬伤，除非你浏览器一直开着。
