### ISSUE TITLE
瀏覽器側邊欄異常

### ISSUE THREAD

**Issue by Pazuzu5688** [ronggang/PT-Plugin-Plus#224]
- PT 助手版本: 1.1.2
- PT 助手安装方式：Chrome 官方擴展
- 浏览器名称及版本：Chrome 76.0.3809.100
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

側邊欄文字顯示異常

- 相关截图：

https://i.imgur.com/Tu6PH3b.png

- 重现步骤：

**Comment by ronggang** [comment]
@Pazuzu5688 看起來像是語言文件沒有正常載入，請問打開設置頁面是正常的嗎？

**Comment by Pazuzu5688** [comment]
目前設定頁面及其它頁面看起來都是正常的

https://i.imgur.com/JswAzyj.png
https://i.imgur.com/f0Pju4S.png

如有需要其它資訊，請再跟我說

**Comment by Pazuzu5688** [comment]
> @Pazuzu5688 看起來像是語言文件沒有正常載入，請問打開設置頁面是正常的嗎？

目前設定頁面及其它頁面看起來都是正常的

https://i.imgur.com/JswAzyj.png
https://i.imgur.com/f0Pju4S.png

如有需要其它資訊，請再跟我說

**Comment by ronggang** [comment]
@Pazuzu5688 嘗試切換成英文，再切換回中文，重新打開一個種子頁面看看是否正常。如果這樣操作後可以正常顯示，那應該是匹配語言資訊時出問題了。

**Comment by Pazuzu5688** [comment]
> @Pazuzu5688 嘗試切換成英文，再切換回中文，重新打開一個種子頁面看看是否正常。如果這樣操作後可以正常顯示，那應該是匹配語言資訊時出問題了。

切換回來之後就正常了，問題應該是如您所述

**Comment by ronggang** [comment]
> > @Pazuzu5688 嘗試切換成英文，再切換回中文，重新打開一個種子頁面看看是否正常。如果這樣操作後可以正常顯示，那應該是匹配語言資訊時出問題了。
> 
> 切換回來之後就正常了，問題應該是如您所述

感謝反饋，這個問題理論上應該只在從v1.0.8升級爲v1.0.9之後的版本，又沒有進行過參數更新或語言參數不存在才會出現。🤣
v1.1.3 之後應該不會再有這個問題了。

**Comment by ronggang** [comment]
@Pazuzu5688 此Bug应已修复，本主题暂时关闭，如有疑问请重新开启。
