### ISSUE TITLE
站点的插件功能代码疑惑

### ISSUE THREAD

**Issue by yushiro** [ronggang/PT-Plugin-Plus#225]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
根据https://github.com/ronggang/PT-Plugin-Plus/wiki/config-custom-plugin的描述，站点插件的定义如下
···
(function() {
class App extends window.NexusPHPCommon { ......
···
但实际在页面载入的时候， 并没有window.NexusPHPCommon这个对象，导致自定义插件报错。
目前的解决方法是用settimeout方法，延迟5秒执行class的定义， 这时候就不会出错了。

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
@yushiro 感谢反馈，我检查一下执行时机。

**Comment by ronggang** [comment]
看了下是按顺序加载的，可否告知一下，具体的站点，及应用的页面。

**Comment by yushiro** [comment]
又验证了一下， 是MTeam站的adult.php页面会出现这个问题， 而同样的代码， 在movie.php页面就没问题。

`
VM296:3 Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at eval (eval at <anonymous> (content.js:1), <anonymous>:3:28)
    at eval (eval at <anonymous> (content.js:1), <anonymous>:19:3)
    at content.js:1
    at new Promise (<anonymous>)
    at Object.execScript (content.js:1)
    at Object.applyScripts (content.js:1)
    at content.js:1
`

**Comment by ronggang** [comment]
@yushiro 感谢提供信息，已定位到问题所在。
