### ISSUE TITLE
IMDb编号搜索时CHD不返回结果

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#228]
- PT 助手版本: v1.1.2
- PT 助手安装方式：市场安装
- 浏览器名称及版本：76.0.3809.100（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：如题，正常用名称搜索时正常

- 相关截图：

- 重现步骤：

**Comment by luckiestone** [comment]
影客也是如此。

**Comment by ronggang** [comment]
CHD不清楚。
影客不支持IMDb编号搜索，需要豆瓣编号来搜索，后继会支持。

**Comment by luckiestone** [comment]
> CHD不清楚。
> 影客不支持IMDb编号搜索，需要豆瓣编号来搜索，后继会支持。

@ronggang CHD是支持的，搜索范围需要为简介，比如搜索复联4可以用这个搜索链接获得结果：

> https://chdbits.co/torrents.php?incldead=1&search_area=1&notnewword=1&search=tt4154796

**Comment by ronggang** [comment]
> > CHD不清楚。
> > 影客不支持IMDb编号搜索，需要豆瓣编号来搜索，后继会支持。
> 
> @ronggang CHD是支持的，搜索范围需要为简介，比如搜索复联4可以用这个搜索链接获得结果：
> 
> > https://chdbits.co/torrents.php?incldead=1&search_area=1&notnewword=1&search=tt4154796

没有账号无法测试，欢迎你适配后提交PR。🤝

**Comment by Rhilip** [comment]
我不认为在简介中搜索imdb号是站点对imdb搜索的支持

**Comment by luckiestone** [comment]
> 我不认为在简介中搜索imdb号是站点对imdb搜索的支持

@Rhilip 我看了下代码，检测到tt开头搜索字段自动加&search_area=4，这应该是有返回结果的，但是实际上无法获取CHD的结果，不知道什么原因。影客的看了下，应该为&search_area=5。不知道插件搜索IMDb编号是否使用了其他接口。

**Comment by ronggang** [comment]
> > 我不认为在简介中搜索imdb号是站点对imdb搜索的支持
> 
> @Rhilip 我看了下代码，检测到tt开头搜索字段自动加&search_area=4，这应该是有返回结果的，但是实际上无法获取CHD的结果，不知道什么原因。影客的看了下，应该为&search_area=5。不知道插件搜索IMDb编号是否使用了其他接口。

&search_area=4 为默认的NP框架使用的IMDb搜索接口，但一些站不支持。
影客&search_area=5为搜索豆瓣编号，不能搜索IMDb。

**Comment by luckiestone** [comment]
> > > 我不认为在简介中搜索imdb号是站点对imdb搜索的支持
> > 
> > 
> > @Rhilip 我看了下代码，检测到tt开头搜索字段自动加&search_area=4，这应该是有返回结果的，但是实际上无法获取CHD的结果，不知道什么原因。影客的看了下，应该为&search_area=5。不知道插件搜索IMDb编号是否使用了其他接口。
> 
> &search_area=4 为默认的NP框架使用的IMDb搜索接口，但一些站不支持。
> 影客&search_area=5为搜索豆瓣编号，不能搜索IMDb。

谢谢。影客我又多试了下，有点迷，豆瓣和IMDb都支持，但是都支持不全。我试的几个同一个种子id似乎只能被一种方式搜到，可能和网站有关了。

**Comment by luckiestone** [comment]
@ronggang CHD已修复，影客豆瓣和IMDb支持都不好，暂时没修。
#229
