### ISSUE TITLE
HDU 需要登录后在搜索

### ISSUE THREAD

**Issue by frank777777777** [ronggang/PT-Plugin-Plus#23]
其他站点正常，HDU需要登录再搜索，在浏览器已经登录了HDU了啊。
![image](https://images2.imgbox.com/6b/ed/OrYXKIpe_o.jpg)

**Comment by Rhilip** [comment]
目前脚本使用该站的CDN域名作为搜索域名 
https://github.com/ronggang/PT-Plugin-Plus/blob/master/resource/sites/pt.hdupt.com/config.json
请在此域名下再次登录获取Cookies即可。
相关Project可见： https://github.com/ronggang/PT-Plugin-Plus/projects/1#card-16419146

**Comment by Rhilip** [comment]
fix: https://github.com/ronggang/PT-Plugin-Plus/commit/4bad2110bc996b2ccf6c66d2f5f83e583de8e90a
请尝试按照Wiki中的说明，为该站点添加CDN设置：[关于站点 CDN 列表](https://github.com/ronggang/PT-Plugin-Plus/wiki/config-site#%E5%85%B3%E4%BA%8E%E7%AB%99%E7%82%B9-cdn-%E5%88%97%E8%A1%A8)
