### ISSUE TITLE
JOYHD站点茉莉系统无法显示 

### ISSUE THREAD

**Issue by honestpony** [ronggang/PT-Plugin-Plus#232]
- PT 助手版本:v1.1.2
- PT 助手安装方式：（市场安装，或zip包安装）市场安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：常用插件
- 停用其他插件后是否正常工作：否
- 问题描述：
JOYHD站点无法显示茉莉

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
似乎和 https://github.com/ronggang/PT-Plugin-Plus/issues/174 相同原因，需要使用merge的方法（https://github.com/ronggang/PT-Plugin-Plus/commit/4b06047228307caf24d1cf24a14f887760614c03#diff-f64f637ea54add2867a2a3b67e8f4863）

该站对应的站点魔力值结构位置html为
```html
<tr><td width="1%" class="rowhead nowrap" valign="top" align="right">银元</td><td width="99%" class="rowfollow" valign="top" align="left">893068&nbsp;(<a href="myhistory.php?id=<userid>" class="faqlink">查看银元、账户历史</a>)</td></tr>
```
