### ISSUE TITLE
测试服务器是否可连接时插件崩溃

### ISSUE THREAD

**Issue by travis-tang** [ronggang/PT-Plugin-Plus#233]
- PT 助手版本：1.1.2
- PT 助手安装方式：市场安装（市场安装，或zip包安装）
- 浏览器名称及版本：chrome 76.0.3809.100 (Official Build) (64-bit)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 操作系统：Arch Linux
- 问题描述：
我用的rutorrent，是直接搭在本地的电脑上的，点击测试服务器是否可连接时插件崩溃。换成firefox时，插件不会崩溃，但是在一直转圈，是我的设置有问题吗？

- 相关截图：
chrome下：
![2019-08-27_00:29:42_select](https://user-images.githubusercontent.com/46301849/63706371-d2786800-c861-11e9-85b8-0aa085d40c11.png)
firefox下一直转圈：
![2019-08-27_00:31:47_select](https://user-images.githubusercontent.com/46301849/63706481-18cdc700-c862-11e9-9313-fea89e2e3fa5.png)

**Comment by ronggang** [comment]
@travis-tang 直接访问这个地址看看。

**Comment by travis-tang** [comment]
> @travis-tang 直接访问这个地址看看。

直接访问没有问题，可以打开rutorrent的界面。直接用127.0.0.1/rutorrent就能打开了。

**Comment by ronggang** [comment]
@travis-tang 测试是请求 `/php/getsettings.php` 这个页面，你试试直接访问这个页面是什么结果。

**Comment by travis-tang** [comment]
@ronggang  file not found.

**Comment by Rhilip** [comment]
访问`http://127.0.0.1:80/rutorrent/php/getsettings.php` 应弹出Web认证界面，认证完显示一堆JSON格式字符串。
显示`file not found.`的话，请检查你rutorrent的安装，以及Nginx代理等情况。

**Comment by travis-tang** [comment]
@ronggang 输错地址了，访问`http://127.0.0.1:80/rutorrent/php/getsettings.php`，出现‘‘{"webui.fls.view":0...’开头的一堆字符，应该是没问题的
