### ISSUE TITLE
Mteam,WHUPT,HUDBT无法显示副标题

### ISSUE THREAD

**Issue by hustlyt** [ronggang/PT-Plugin-Plus#235]
- PT 助手版本:1.1.2
- PT 助手安装方式：chrome插件（市场安装，或zip包安装）
- 浏览器名称及版本：chrome 76.0.3809.100
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
以下网站部分搜索结果无法显示副标题：
WHUPT，HUDBT，MTeam

与 #209 配置相同，重新删除添加也没用
- 相关截图：

![微信图片_20190827151204.png](https://i.loli.net/2019/08/27/sXjWnLNrc8MRBZH.png)
![微信图片_20190827151209.png](https://i.loli.net/2019/08/27/GcU4IpVfdyTL2Xr.png)

另外两个网站类似
- 重现步骤：
搜索“哲学”关键词

**Comment by ronggang** [comment]
@hustlyt MT已修复待发布，其他两个站点暂时无法测试。
