### ISSUE TITLE
增加类似PTP的collections?

### ISSUE THREAD

**Issue by hustlyt** [ronggang/PT-Plugin-Plus#236]
**您的功能请求是否与问题有关？ 请描述一下。**

1、**增加collections：** 一种类别的资源可能分布在不同的网站上，比如PHP学习资料，可以在看到自己喜欢的资源后把它加到collections里，既可以一键发送到服务器下载，也可以先不下，以后服务器或硬盘有空间了再下。如果能看到别人的collections就更好啦，就像豆瓣的豆列一样。。。
2、增加一个到顶的箭头

大佬萌要是觉得没必要的话就算了，感觉现在功能也挺好用了
**描述你想要的解决方案**

**描述您考虑过的替代方案**

**其他附加信息**

**Comment by ronggang** [comment]
@hustlyt 相当于收藏喽？收藏各站点喜欢的资源是吧？不错的想法。👏
