### ISSUE TITLE
请求增加快速辅种功能

### ISSUE THREAD

**Issue by rolamao** [ronggang/PT-Plugin-Plus#238]
**您的功能请求是否与问题有关？ 请描述一下。**
①现在好多人都是从一个站或者几个站慢慢，收集的站越来越多
②各个站之间会不断的有人转发种子

**描述你想要的解决方案**
现在是复制已经下载完的种子信息，然后查找其他站有无，再辅种，种子多了之后比较麻烦，
能不能新增一个功能，就是查找已经下载完的种子，别的站点是否有，是否可以给其他站辅种
3Q

**描述您考虑过的替代方案**

**其他附加信息**

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/217 https://github.com/ronggang/PT-Plugin-Plus/issues/106
查找已经下载完的种子，判断种子之间是否重复已经超过了本插件的能力范围。
且已有更成熟的软件可以替代，请考虑使用。
