### ISSUE TITLE
增加使用HTTPS/HTTP选项

### ISSUE THREAD

**Issue by Taosky** [ronggang/PT-Plugin-Plus#239]
**您的功能请求是否与问题有关？ 请描述一下。**
由于自身原因，部分站点（SSD）使用HTTPS连接tracker连不上，发现PT助手默认是下载带HTTPS  tracker地址的种子。

**描述你想要的解决方案**
希望能增加一个选项，选择是否使用HTTPS连接tracker。

**描述您考虑过的替代方案**
目前使用Header Editor重定向请求到 xxxxxxx&https=0

**其他附加信息**
无

**Comment by ronggang** [comment]
得重新考虑下处理方式。

**Comment by Taosky** [comment]
> 
> 
> 得重新考虑下处理方式。

增加个选项就可以了吧，链接做一个替换，当然每个站点不太一样，可能比较麻烦。

**Comment by Rhilip** [comment]
@Taosky 虽然时隔一年了，但是在v1.5.0中取消了强制`&https=1`，NPHP站点将按照登陆时选项进行设置，请问在新版本下是否可行？

**Comment by Taosky** [comment]
> 
> 
> @Taosky 虽然时隔一年了，但是在v1.5.0中取消了强制`&https=1`，NPHP站点将按照登陆时选项进行设置，请问在新版本下是否可行？

PT站好像早已经修复了tracker HTTPS的问题，一直都可用😂

**Comment by Rhilip** [comment]
> > @Taosky 虽然时隔一年了，但是在v1.5.0中取消了强制`&https=1`，NPHP站点将按照登陆时选项进行设置，请问在新版本下是否可行？
> 
> PT站好像早已经修复了tracker HTTPS的问题，一直都可用😂

那就做close处理了
