### ISSUE TITLE
是否有计划开发成docker版？

### ISSUE THREAD

**Issue by marcosteam** [ronggang/PT-Plugin-Plus#240]
这个插件做的越来越好，功能也越来越像sonarr和radarr靠近
都是通过BT（s和r还额外支持新闻组）的方式来下载电影
都支持通过外部数据源（IMDB，豆瓣）来查找电影
如果做成docker版，开放API给用户，我觉得它可以成为下一个sonarr

**Comment by ronggang** [comment]
@marcosteam 你说的sonarr应该属于媒体服务器吧？类型不一样。

**Comment by marcosteam** [comment]
> @marcosteam 你说的sonarr应该属于媒体服务器吧？类型不一样。

还是不一样的,PT助手其实就是sonarr的下载功能，如果能完善一下自然是极好的

**Comment by Aniverse** [comment]
> 还是不一样的,PT助手其实就是sonarr的下载功能，如果能完善一下自然是极好的
不认同，像我基本不用 PPTP 的搜索下载功能（我很少从 PT 上下东西），我就是统计 PT 站数据和添加种子到盒子上

**Comment by Rhilip** [comment]
lz似乎对浏览器插件和docker之间有些误解？
我们没有类似的计划，以后也会集中在浏览器插件上。
lz可以自己考虑开发移植插件功能，PTPP的LICENSE是MIT，很宽容的。
