### ISSUE TITLE
功能请求：/statistic中增加各项数据增长量记录以及更细粒度的原始数据

### ISSUE THREAD

**Issue by Mosney** [ronggang/PT-Plugin-Plus#243]
**您的功能请求是否与问题有关？ 请描述一下。**

**描述你想要的解决方案**  

个人认为数据图表中的数据还有很大的展示潜力  
例如`{上传/下载/bonus/保种数}{每小时/每日/每周/每月}{增长量/时段内平均量}    `

目前我个人的需求是单个站**每小时的魔力值增长量**，
因为frds存在邀请奖励所以只看网站的保种获魔数据不准确    

另外，目前自动刷新数据似乎是每天一次，希望可以添加更多样的更新频率，
例如每小时一次，以便提供更高粒度的原始数据

**描述您考虑过的替代方案**

**其他附加信息**

之前的issue #242 被bot自动关闭了，重新按格式提交

**Comment by ronggang** [comment]
这个以后可以考虑增加频率设置。
具体统计形式有待讨论。

**Comment by hxsf** [comment]
我想加入两个新功能

1. 在“站点数据”里加入 时魔 的显示
2. 自定义站点跳转链接（直接跳转到某个分类页面，而不是主页）。

**Comment by ted423** [comment]
每小时的刷新，估计不少站点都会想到负载问题，故不考虑
