### ISSUE TITLE
HDcity、OpenCD，结果集中出现无关结果

### ISSUE THREAD

**Issue by hustlyt** [ronggang/PT-Plugin-Plus#244]
- PT 助手版本:1.2.2
- PT 助手安装方式：chrome插件（市场安装，或zip包安装）
- 浏览器名称及版本：chrome 76.0.3809.100
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
搜索“树先生”，结果集中出现无关结果

- 相关截图：

![tu1.png](https://i.loli.net/2019/09/06/D45G9CuNcqkSOAs.png)

![tu2.png](https://i.loli.net/2019/09/06/THBJhadRN7EtMkf.png)

- 重现步骤：
搜索“树先生”

**Comment by ronggang** [comment]
应该是搜索IMDb编号导致。
