### ISSUE TITLE
能否增加对edge chromium版的支持？

### ISSUE THREAD

**Issue by 2375399351** [ronggang/PT-Plugin-Plus#245]
- edge chromium用的内核是chrome的但是测速crx无法直接安装上去

**Comment by ronggang** [comment]
@2375399351 暂时还没有环境测试。

**Comment by ronggang** [comment]
经测试，chromium 内核的 edge 可以直接安装使用 zip 版，请直接尝试安装 zip 版。本主题关闭。

**Comment by 873314461** [comment]
可以直接从google市场安装，经测试，没出现什么问题。
