### ISSUE TITLE
M-team 种子页面 右击 发送到默认服务提示无效种子

### ISSUE THREAD

**Issue by hncdbai** [ronggang/PT-Plugin-Plus#248]
- PT 助手版本:  v1.2.2
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Google Chrome 版本 76.0.3809.100（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：一样有问题
- 问题描述：
M-team 种子列表页面 右击 发送到默认服务提示无效种子。同样的方式试过其他2个站好像没问题。
打开种子的独立页面，再发送下载就正常

- 相关截图：

background | contextMenus.sendTorrentToClient.error | 2019-09-11 10:47:26 | 下载链接发送失败！ | delete
-- | -- | -- | -- | --
{"msg":"无效的种子文件","success":false,"type":"error"}

background | service.controller.doDownload.error | 2019-09-11 10:47:26 | 下载服务器qBittorrent处理[addTorrentFromURL]命令失败！ | delete
-- | -- | -- | -- | --
{"msg":"无效的种子文件","success":false,"type":"error"}

- 重现步骤：

**Comment by ronggang** [comment]
@hncdbai 看帮助
https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E9%94%AE%E4%B8%8B%E8%BD%BD%E6%97%B6%E4%BC%9A%E6%8F%90%E7%A4%BA-%E6%97%A0%E6%95%88%E7%9A%84%E7%A7%8D%E5%AD%90%E6%96%87%E4%BB%B6-

**Comment by hncdbai** [comment]
谢谢，确实是这个问题，下载一次，  点了个窗口提醒什么的窗口，现在好了
