### ISSUE TITLE
下载所有种子文件/All Torrents只下载到php文件

### ISSUE THREAD

**Issue by OliverLew** [ronggang/PT-Plugin-Plus#250]
- PT 助手版本: v1.2.2
- PT 助手安装方式：Firefox addon 商店
- 浏览器名称及版本：Firefox 69.0 (64-bit), Arch Linux
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

  在种子列表页面（默认种子第一页）使用“所有种子/下载所有种子文件”按钮下载本页种子时，会出现各种问题，如下载到的都是php页面本身，如"download.php"或"torrents.php"。

  在尝试的所有网站中，包含NexusPHP/Gazelle/AvistaZ/Unit3D/IPT等站点或者架构，结果如下：

  - 只有IPT是正常下载的，因为IPT的下载链接是种子直链
  - Unit3D框架的链接是直链，但链接是“种子名.种子ID”，所以下载到的虽然是种子，但是文件名也是“种子名.种子ID”，而不是点击下载按钮（指种子本身的）而下载到的“种子名.torrent"
  - 其他框架和站点如NexusPHP/Gazelle/AvistaZ下载链接是类似"xxx.php?参数"的情况，下载到的就只有php文件本身

- 相关截图：

- 重现步骤：
  - 禁用其他所有插件，重启浏览器
  - 打开网站（如UHDBits）种子页
  - 等待网页和插件加载完毕，点击“所有种子”按钮
  - 得到所有文件都是torrents.php

**Comment by Rhilip** [comment]
看起来更像是firefox的‘feature’，我们这边无能为力，建议向firefox那边反应。

插件调用下载命令是浏览器默认的下载方法，在chrome上是 `chrome.downloads.download()`  
文档： https://developer.chrome.com/extensions/downloads#method-download

我在Firefox的插件的背景页手动调用 `chrome.downloads.download()` （ff在插件层面提供chrome对象兼容） 以及 `bowser.downloads.download()` (ff自带的WebExtension方法， 文档： https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download ， 文档最后说`This API is based on Chromium's chrome.downloads API.` ) 得到的表现均是问题描述现象。

此外，调大 `about:config` 中`broser.download.saveLinkAsFilenameTimeout` 无助于解决问题。

只能认为在 `chrome.downloads.download()` 这个方法上，ff的实现不能从请求响应的`Content-Disposition`头中自动获取文件名信息。

由于我们无法在options中添加filename键值对（种子文件名在请求响应的`Content-Disposition`头中），所以只能建议换用chrome内核浏览器。

**Comment by OliverLew** [comment]
所以按我的理解，这只是Unit3D框架站点文件名问题的原因，那最有问题的第三种情况，只下载到php文件又是什么原因呢？

**Comment by Rhilip** [comment]
不是，ff只是简单的把下载链接中的文件名作为下载保存的文件名，例如：

```
https://xxxx.com/download.php/xxxx/1.torrent  -> 1.torrent 
https://xxxx.com/download.php?id=xxxxx          -> download.php
```

通过翻阅ff的相关bugtracker，特别是  **https://bugzilla.mozilla.org/show_bug.cgi?id=1579456**
以及相关
https://bugzilla.mozilla.org/show_bug.cgi?id=1245652
https://bugzilla.mozilla.org/show_bug.cgi?id=1424502

---------------

目前只能建议：

1. 更换浏览器为chrome内核浏览器；
2. 使用IDM等类似下载工具 监听/劫持 Firefox的下载动作。

**Comment by OliverLew** [comment]
嗯，谢谢详细的调查，这个8天前的bug甚至正好能够针对这个问题。但是看之前的bug report，感觉近期不会解决了。

**Comment by Rhilip** [comment]
感谢理解，那这个issue先做close处理了
