### ISSUE TITLE
建议增加 cookie 一键导出

### ISSUE THREAD

**Issue by 10467106** [ronggang/PT-Plugin-Plus#252]
**您的功能请求是否与问题有关？ 请描述一下。**
现在要一个站一个站导出 还是挺麻烦的。

**描述你想要的解决方案**
用户授权后，可以导出cookie，存储可以采用 owss ，cookie 数据与 owss id 异或加密后存储。

**描述您考虑过的替代方案**
无

**其他附加信息**
无截图

**Comment by xmt328** [comment]
1.3.1版本为什么不支持备份cookie到google啊，要特意搭一个OWSS感觉很浪费

**Comment by Rhilip** [comment]
> 1.3.1版本为什么不支持备份cookie到google啊，要特意搭一个OWSS感觉很浪费

因为光备份设置，有些用户都已经超过google的限制（4K大小）了，加上cookies更加备份不上去。
