### ISSUE TITLE
pthome site url

### ISSUE THREAD

**Issue by zhaoloving** [ronggang/PT-Plugin-Plus#255]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
pthome的url少了"www"前缀，应该是https://www.pthome.net

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
不含www的同样能访问，不属于bug，如有需要请添加CDN域名（操作见Wiki）
