### ISSUE TITLE
建议增加favicon自定义选项

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#256]
## 您的功能请求是否与问题有关？ 请描述一下。

建议在站点设置的编辑站点中新增favicon自定义选项

## 描述你想要的解决方案

NA

## 描述您考虑过的替代方案

NA

## 其他附加信息

有些站点的favicon分辨率较低，在概览页面以及数据图表上方选择站点处看着都很难受，比如AHD和OB等。希望能够增加favicon自定义功能，自行替换为高分辨率图像。

**Comment by Rhilip** [comment]
其实更好的方式是 https://github.com/ronggang/PT-Plugin-Plus/issues/147
让插件在运行时自动获取并缓存，而不手动指定
至于favicon再添加自定义，总觉得需求过度了

**Comment by luckiestone** [comment]
> 其实更好的方式是 #147
> 让插件在运行时自动获取并缓存，而不手动指定
> 至于favicon再添加自定义，总觉得需求过度了

@Rhilip 我也考虑过增加自定义可能会导致有人随意定义的情况。获取并缓存的这个方式我没有很理解具体如何操作，倒是有个情况我觉得也是挺合适的，不知可否实现：
类似于Chrome默认情况下新建标签页的情况，常用网页的thumbnail都是使用的缓存。我如果自己写了一个脚本，替换了比如说OB的favicon，并且网页加载完成，那么我重新打开Chrome的新标签页，常用网页的thumbnail会变成我自定义的已经缓存的图标。

**Comment by ronggang** [comment]
近期我把图标的事情弄一下吧，应该会使用 @Rhilip 说的方式打包时自动获取站点的图标，不过唯一的影响就是会使整个代码库和安装包体积变大。
另外，如果增加图标自定义，会进一步增加程序的复杂度，所以暂时先不考虑自行定义了，以后看情况再说。

**Comment by Rhilip** [comment]
我觉得不一定要打包时获取，可以在用户运行插件时获取并缓存🧐

**Comment by ronggang** [comment]
> 我觉得不一定要打包时获取，可以在用户运行插件时获取并缓存🧐

这个方法可行，回头试一下看看。

**Comment by luckiestone** [comment]
> 近期我把图标的事情弄一下吧，应该会使用 @Rhilip 说的方式打包时自动获取站点的图标，不过唯一的影响就是会使整个代码库和安装包体积变大。
> 另外，如果增加图标自定义，会进一步增加程序的复杂度，所以暂时先不考虑自行定义了，以后看情况再说。

感谢。这种是缓存自定义的某个图标库，还是缓存用户运行插件时对应站点自行产生的favicon，亦或是查找浏览器本身缓存的该站点的favicon？

**Comment by Rhilip** [comment]
按照我的设想，是使用favicon库的话，获取到的应是“用户运行插件时对应站点自行产生的favicon”（定义在html meta里），之前开发意见的提出主要是因为要避免由于站点更换favicon位置，导致需要我们在插件处重新定义站点favicon并存在发布延迟的问题。查找浏览器缓存的话，可能不太现实（具体还得查查有没有相关接口）不过浏览器缓存的favicon其实质量也不高基本就16x16的水平，或和使用favicon库的结果类似。Sent from my Huawei phone-------- Original message --------From: luckiestone <notifications@github.com>Date: Tue, Sep 24, 2019, 08:37To: ronggang/PT-Plugin-Plus <PT-Plugin-Plus@noreply.github.com>Cc: Rhilip <rhilipruan@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [ronggang/PT-Plugin-Plus] 建议增加favicon自定义选项 (#256)
近期我把图标的事情弄一下吧，应该会使用 @Rhilip 说的方式打包时自动获取站点的图标，不过唯一的影响就是会使整个代码库和安装包体积变大。
另外，如果增加图标自定义，会进一步增加程序的复杂度，所以暂时先不考虑自行定义了，以后看情况再说。

感谢。这种是缓存自定义的某个图标库，还是缓存用户运行插件时对应站点自行产生的favicon，亦或是查找浏览器本身缓存的该站点的favicon？

**Comment by Rhilip** [comment]
考虑到目前插件已经实现从favicon -> base64 的功能，且favicon不太适合作为自定义内容，故关闭。
