### ISSUE TITLE
插件工具栏显示问题

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#258]
- PT 助手版本:1.3.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Chrome 76.0.3809.100（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：插件太多，未尝试
- 问题描述：
在手上的几个站中，有俩存在现实问题。
一个是UHDBits站，插件工具栏背景色和字体几乎完全一样，看不清服务器列表，如截图1，服务器列表保护隐私打了薄码，但是实际看上去也几乎就这样。
另一个是FilelList，工具栏插件图标显示错位，如截图2 。

- 相关截图：
截图1：
![UHD](https://user-images.githubusercontent.com/35324456/65679916-9c105180-e088-11e9-8e88-08f74b61db6f.png)截图2：
![FL](https://user-images.githubusercontent.com/35324456/65679917-9c105180-e088-11e9-90da-3341be9cc54e.png)

- 重现步骤：

**Comment by ronggang** [comment]
第一个问题在其他站一直存在，还没调整。
第二个问题还没遇到过，应该是和站点的样式冲突了，不过没法测试，我看看能不能调吧。

**Comment by luckiestone** [comment]
> 第一个问题在其他站一直存在，还没调整。
> 第二个问题还没遇到过，应该是和站点的样式冲突了，不过没法测试，我看看能不能调吧。

好的谢谢，麻烦啦

**Comment by luckiestone** [comment]
> 第一个问题在其他站一直存在，还没调整。
> 第二个问题还没遇到过，应该是和站点的样式冲突了，不过没法测试，我看看能不能调吧。

第二个问题我去看了下，确实是和.logo这个class的样式冲突了。可能改个不容易重复的名字或者加个父项就好了。另外的问题我就不会定位问题了，已经是现学现卖了。。。

**Comment by ronggang** [comment]
> > 第一个问题在其他站一直存在，还没调整。
> > 第二个问题还没遇到过，应该是和站点的样式冲突了，不过没法测试，我看看能不能调吧。
> 
> 第二个问题我去看了下，确实是和.logo这个class的样式冲突了。可能改个不容易重复的名字或者加个父项就好了。另外的问题我就不会定位问题了，已经是现学现卖了。。。

整体样式到时统一调整吧，只能尽量做到不冲突。

**Comment by Rhilip** [comment]
可以考虑加前缀 （我在豆瓣脚本上就是这样干的
```
.logo -> .ptpp-logo
```

**Comment by ronggang** [comment]
> 可以考虑加前缀 （我在豆瓣脚本上就是这样干的
> 
> ```
> .logo -> .ptpp-logo
> ```

嗯，这是比较好的解决方式。前缀越长冲突的机率越小🤣
