### ISSUE TITLE
UHDBits总是搜索失败并失败信息显示错误

### ISSUE THREAD

**Issue by OliverLew** [ronggang/PT-Plugin-Plus#259]
- PT 助手版本: v1.3.0
- PT 助手安装方式：火狐市场安装
- 浏览器名称及版本：Firefox 69.0.1 (64-bit)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
  1. UHDBits在每次搜索中都失败
  2. 每次都是很长时间之后（大概半分钟至一分钟）显示失败。到目前为止，UHDBits总是最后一个，其他站点就算失败也早已结束了
  3. 如截图中显示，失败后下面显示`[M-Team] is not targeting the torrent list, or there is no related torrent`或`[nebulance] did not find the relevant torrent`，这都是上一个失败的站点的失败信息，而不是UHDBits自己的

  P.S. 我能正常登录并浏览、搜索UHDBits网站

- 相关截图：
![Screenshot_2019-09-26_19-27-06](https://user-images.githubusercontent.com/12032219/65685888-a422be00-e095-11e9-996e-46736984f9ef.png)
![Screenshot_2019-09-26_19-41-38](https://user-images.githubusercontent.com/12032219/65685907-b13fad00-e095-11e9-87f4-733484cb21ec.png)

- 重现步骤：
  1. 禁用除助手外所有插件
  2. 打开助手页面，搜索任意常见关键词
  3. 得到uhdbits失败，错误信息与上一个失败站点相同，但前往网站搜索却有搜索结果

**Comment by Rhilip** [comment]
我这边不能复现，删除该站点再重新添加能否复现？
并提供下该站搜索的日志信息。

**Comment by OliverLew** [comment]
我现在在另一台机器上，重新删除站点，添加后依然如此。
日志：https://pastebin.com/mq09qEtW

**Comment by ronggang** [comment]
尝试仅搜索该站点，看看是什么结果。

**Comment by OliverLew** [comment]
和之前类似，现在是没有任何信息显示出来。
![Screenshot_2019-09-27_23-05-54](https://user-images.githubusercontent.com/12032219/65780006-65ffca00-e17b-11e9-817e-a742a4e224c6.png)
日志：https://pastebin.com/msfMCSjG
具体是单独设置了只有该站点的search solution，试了4次，除了第一次很快，四次都是空白结果，并且第一次很快结束这一点无法复现。

**Comment by OliverLew** [comment]
我用虚拟机里新的浏览器尝试都不行，包括下面讲的archlinux，我刚刚又试了win10，也不行。如果你们真的无法复现，这个难道和我的站点帐号/设置有关吗？还有什么地方会出问题。。。

![Screenshot_2019-09-28_00-39-37](https://user-images.githubusercontent.com/12032219/65786160-9f8b0200-e188-11e9-9521-28b1802f65fb.png)


===

下面的是我尝试win10之前写的

我不知道和系统环境有没有关系，我用的linux，上面提到的两台机器是archlinux和manjaro，后者基于archlinux。

我刚在一个很新的archlinux虚拟机里装了firefox，只装了助手插件，只登陆这一个站点。没有什么个人配置文件，浏览器未登录帐号，我想大概把我本地操作的影响降到最小了。但是结果还是上面那样

**Comment by ronggang** [comment]
@OliverLew 感谢耐心测试，看起来应该是解析出错了，如果你愿意，请参考 [这个方法](https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page) 查看一下搜索时，页面（Network）返回结果，以及在 console 输出的错误信息。

**Comment by OliverLew** [comment]
用只有该站点的search solution搜索，Network页面没有任何和站点相关的请求，只有键入搜索框时两个豆瓣api的请求。
![Screenshot_2019-09-28_09-54-48](https://user-images.githubusercontent.com/12032219/65809941-100c4000-e1d6-11e9-9917-9f4556edcd09.png)


console输出：https://pastebin.com/c0SgmMH9
不清楚怎么导出比较可读的格式，我觉得相关的部分截图如下
![Screenshot_2019-09-28_09-44-58](https://user-images.githubusercontent.com/12032219/65809916-ae4bd600-e1d5-11e9-998e-9e69354ffbd0.png)

**Comment by ronggang** [comment]
@OliverLew 看到了一个关键错误，看了一下，是因为这个站点配置文件里的 `host` 没有定义，导致加载解析脚本失败，及其他结果错乱，我先修复一下这个失误看看能不能解决这个问题。

**Comment by OliverLew** [comment]
在本地build是成功的，等AMO更新后再试一下
