### ISSUE TITLE
希望增加HDCity搜索支持

### ISSUE THREAD

**Issue by wolonggl** [ronggang/PT-Plugin-Plus#26]

**Comment by ronggang** [comment]
@wolonggl 暂时没有 HDCity 站，不清楚是否是原生的NP架构。如果可以，是否愿意提交一下配置？

配置方法参考：
https://github.com/ronggang/PT-Plugin-Plus/tree/master/resource/sites#%E7%AB%99%E7%82%B9%E5%AE%9A%E4%B9%89

**Comment by Rhilip** [comment]
这个站有点难做，对原生NP修改很多，而且也存在多域名（CDN）的情况
还存在多种种子列表页风格的情况 （https://github.com/Rhilip/PT-help/issues/12）
可能会在以后提供支持

**Comment by doykitlee** [comment]
HDCITY显示"未登录",也无法取得搜索结果,谢谢!

**Comment by Rhilip** [comment]
请更新到v1.0.3以上版本并测试，如有问题请再次反馈，此issuce先关闭

相关commit:
https://github.com/ronggang/PT-Plugin-Plus/commit/b49f7bde72db07c5b0e2a45e9bb13fd2aecca86b
https://github.com/ronggang/PT-Plugin-Plus/commit/1f8d3c12d1a5a16b26d3605a07042a1f338fe4ec
https://github.com/ronggang/PT-Plugin-Plus/commit/77e3c6003eda6a749efb47ffc78311fd8d15cd80
