### ISSUE TITLE
增加公共下载目录数量

### ISSUE THREAD

**Issue by reky04** [ronggang/PT-Plugin-Plus#261]
## 描述你想要的解决方案

大佬，不能增加公共下载目录数量，设置好一个目录，再增加会修改前面的。不知道是不是我操作方法不对。本地影片是按类型分目录的，比如电影、电视剧、综艺。。。没有按网站分。所以，希望能设置多个公共下载目录。

**Comment by Rhilip** [comment]
可能是你操作错误，能否贴出你下载目录定义页面截图？

**Comment by ronggang** [comment]
@reky04 添加目录时，一次可以添加多个，在文本框里输入多个目录按回车分隔。如需再增加公用目录，只需要点击`<所有站点>`，编辑即可。多次点击添加公共目录时的确会覆盖原来的。

**Comment by reky04** [comment]
> @reky04 添加目录时，一次可以添加多个，在文本框里输入多个目录按回车分隔。如需再增加公用目录，只需要点击`<所有站点>`，编辑即可。多次点击添加公共目录时的确会覆盖原来的。

收到，谢谢！
