### ISSUE TITLE
希望能取消点击窗口外关闭窗口，因为经常导致误操作未保存关闭

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#263]
- PT 助手版本:1.3.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Cent browser 最新
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：未测试
- 问题描述：操作时鼠标选择某块区域，可能因为鼠标移到窗外导致窗口关闭

- 相关截图：

- 重现步骤：
[2019-09-27 14-13-00.zip](https://github.com/ronggang/PT-Plugin-Plus/files/3661116/2019-09-27.14-13-00.zip)

**Comment by Rhilip** [comment]
鼠标移到dialog（窗口）外不会导致dialog关闭，只有你在overlay（窗外）上做点击了才会导致dialog关闭。
另外，点击遮罩层关闭窗口是基本交互逻辑，不会做改变的。

**Comment by ronggang** [comment]
其实严格来讲，这属于 `vuetifyjs` v1.5.x 的Bug，在他的 v2 版本已修复了，不过 v2 变化有点大，所以暂时还没有考虑升级，等他们升级到 v2.1 之后再看看吧。

**Comment by ted423** [comment]
> 鼠标移到dialog（窗口）外不会导致dialog关闭，只有你在overlay（窗外）上做点击了才会导致dialog关闭。
> 另外，点击遮罩层关闭窗口是基本交互逻辑，不会做改变的。

抱歉我没说清楚，因为隔的有些久了，当时也没弄清楚头绪。

正常应该是点击外面关闭。
但我遇到的是自定义站点，粘贴网址到里面，鼠标选取一些字段，拖到了窗口外松开鼠标导致窗口关闭。

那时候感觉就像是窗口自己关了一样。导致未保存数据全部得重新设置。

@ronggang 
不知道我说的这个跟你说的那个vuetifyjs是不是同一个事哈，不好意思我不是很懂这个

**Comment by ronggang** [comment]
@ted423 你的问题我了解，是目前助手中所使用 `vuetifyjs` 框架的 Bug，所以暂时不会修复，待哪天更新到 v2 了就好了。

**Comment by ted423** [comment]
> @ted423 你的问题我了解，是目前助手中所使用 `vuetifyjs` 框架的 Bug，所以暂时不会修复，待哪天更新到 v2 了就好了。

明白了，感谢回复
