### ISSUE TITLE
不再支持m-team

### ISSUE THREAD

**Issue by InfiniteSin** [ronggang/PT-Plugin-Plus#264]
- PT 助手版本:1.3.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome latest
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：未测试
- 问题描述：
更新到1.30版本后，站点设置中m-team显示为为登录，打开m-team网页后，网页不定时转变为你已登录的提示。

- 相关截图：
暂无

- 重现步骤：

**Comment by InfiniteSin** [comment]
尝试通过config.json文件导入，结果显示import failed

**Comment by Rhilip** [comment]
这是站点的限制（MT对已经登陆的监测很奇怪），
我们这边没有办法

**Comment by ted423** [comment]
mt的二次验证是变IP就会要重新验证，所以你需要变IP以后验证过了再获取数据

**Comment by hncdbai** [comment]
> mt的二次验证是变IP就会要重新验证，所以你需要变IP以后验证过了再获取数据

我的现在也是这样，重新登陆都没用，要关二级验证才有行。1.3.0以前的版本好像没这个问题，mt管理说是IP改变就会这样，但是IP是肯定没变的。

**Comment by Rhilip** [comment]
@hncdbai 这种“ip肯定没有变”真的很难说也没有意义。你再开一个mt的页面，出现任意二步验证或者提示你已经登录的提示，都说明你被该站点拦了。
所以请自己再验证获取，毕竟总不可能我们插件给你保管生成二步验证码吧？
