### ISSUE TITLE
搜索显示异常

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#266]
- PT 助手版本: 1.3.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：cent browser最新版
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：未测试
- 问题描述：
搜索时无结果站点名显示异常，并且部分已有数据站点会搜索不到
怀疑是脚本有问题导致卡住，可能跟某个特定数字有关
如南洋是有这个种子的
- 相关截图：
![2019-10-01 01_34_38-PT-Plugin-Plus - Cent Browser](https://user-images.githubusercontent.com/7042766/65901880-acf3f680-e3eb-11e9-948a-fd44a99c148e.png)

- 重现步骤：

**Comment by ted423** [comment]
新发现，高清街不会去搜索，也不会在搜不到的站点里出现

**Comment by ted423** [comment]
![2019-10-08 08_46_18-PT-Plugin-Plus - Cent Browser](https://user-images.githubusercontent.com/7042766/66359105-56b52380-e9a8-11e9-9614-037230a63aec.png)
字幕被搜索到并计算了大小

**Comment by ronggang** [comment]
尝试单个站点搜索试试会不会出现同样的错误。

**Comment by ted423** [comment]
> 尝试单个站点搜索试试会不会出现同样的错误。

现在搜索又不会出现了 
主要可能要特定情况 ，不过天雪字幕那个还请帮看下

**Comment by ted423** [comment]
> 尝试单个站点搜索试试会不会出现同样的错误。

又出现了
![image](https://user-images.githubusercontent.com/7042766/66558331-f5e34200-eb85-11e9-9de1-4d4ebe0ec19b.png)

**Comment by ted423** [comment]
{success: false, msg: "[PTsbao]没有搜索到相关的种子", data: {…}}
chunk-702561c9.60806668.js:1 {success: false, msg: "[SkyeySnow]没有定位到种子列表，或没有相关的种子", data: {…}}
chunk-702561c9.60806668.js:1 {success: false, msg: "[52pt]没有搜索到相关的种子", data: {…}}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}readyState: 0status: 0statusText: "error"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {success: false, msg: "[备胎]没有搜索到相关的种子", data: {…}}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {success: false, msg: "[RED]数据解析失败！"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "error"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "timeout"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "timeout"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "timeout"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "timeout"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "timeout"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "timeout"}
chunk-702561c9.60806668.js:1 {readyState: 0, status: 0, statusText: "timeout"}

**Comment by ted423** [comment]
又试了下，发现跟网络有一定关系，代理开全局可以搜到全部4个，也就是timeout不会正常显示timeout,另外其中一个站点卡住似乎会导致后面的站点一起timeout

**Comment by ted423** [comment]
总之现在似乎逻辑变了
