### ISSUE TITLE
HDCHINA无法发送到下载服务器

### ISSUE THREAD

**Issue by zzzzevazzzz** [ronggang/PT-Plugin-Plus#267]
- PT 助手版本:1.3.1
- PT 助手安装方式：（市场安装，或zip包安装）市场安装
- 浏览器名称及版本：Chrome 77.0.3865.90
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
在hdchina种子页面，右击发送到下载服务器出错。 检查了一下发送的链接，PT助手发送的是种子id+passkey，而站点的下载链接是hash+uid，希望大神早日修复。

- 相关截图：

- 重现步骤：

hash=D1QCSxmsdafasdfasdfasfdadf&uid=228

**Comment by Rhilip** [comment]
请在插件对应站点设置中删掉passkey栏内容

**Comment by yhzdyhzd** [comment]
遇到同样问题，hdc 获得的复制链接，下载不到种子，站点设置把passkey删掉，只是链接里没有passkey了，还是不正确的hash+uid链接地址，请问怎么解决？感谢
