### ISSUE TITLE
站点设置页面无法正常操作

### ISSUE THREAD

**Issue by xlpppp** [ronggang/PT-Plugin-Plus#268]
- PT 助手版本: 1.3.1
- PT 助手安装方式：zip
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：
   站点设置页面无法完成任何操作（新增，编辑，删除等），一键导入点击后可正常导入（需要刷新页面才能看到新导入的站点）

- 相关截图：

![pt1](https://user-images.githubusercontent.com/32667278/66104973-ae404180-e5ec-11e9-8f5e-b2ac0374df8c.jpg)

- 重现步骤：

**Comment by xlpppp** [comment]
尝试更换到1.3.0，1.2.2版本也是同样
我站点有点多，有超过25个
之前一直正常的，不知是否这个原因

**Comment by xlpppp** [comment]
- -！

**Comment by ronggang** [comment]
一打开这个页面就出现这个错误吗？

**Comment by xlpppp** [comment]
是的，其它页面正常。
另外在这个页面点击跳转到其它页面时，地址栏地址会变，但页面不会切换，按F5刷新才会正常跳转。
