### ISSUE TITLE
IPT时间显示问题

### ISSUE THREAD

**Issue by OliverLew** [ronggang/PT-Plugin-Plus#269]
- PT 助手版本: v1.3.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Firefox 69.0.2 (64-bit)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
  我之前提交过一个issue，因为格式不规范被关了。。。但是这个问题挺烦人的，还是再专门开一个issue吧，解决应该很简单。
  IPT（不清楚其他站还有没有这个问题）部分种子在上传时间旁边还会有上传者的信息，像`7.6 months ago by TvTeam`，助手没有处理这种情况，就会原样不变地放在结果里。这样最大的问题就是按时间排序会出错。
  助手已经能把前面一半（`7.6 months ago`）转化为通用日期格式了，但是好像还没考虑当后面存在上传者名字时的情况，能否将这种特殊情况稍带处理一下，谢谢。

- 相关截图：
  
  ![Screenshot_2019-10-06_21-11-26](https://user-images.githubusercontent.com/12032219/66269681-ec07c900-e87d-11e9-817a-6ed2b70aabc6.png)

- 重现步骤：

**Comment by ronggang** [comment]
@OliverLew 正常浏览时没有发现有这种情况，可否提供一下搜索关键字，我试一下能不能搜出来这样的内容。

**Comment by OliverLew** [comment]
比如下面是搜索“toy story”的结果，我截取了正好能说明问题的两类种子：
![Screenshot_2019-10-08_22-05-49](https://user-images.githubusercontent.com/12032219/66402853-24430f00-ea18-11e9-828b-f9920eb4378f.png)
![Screenshot_2019-10-08_22-05-37](https://user-images.githubusercontent.com/12032219/66402864-286f2c80-ea18-11e9-9be9-d9a5dc0ef40a.png)

**Comment by ronggang** [comment]
为何我搜索时没有显示上传者，是等级问题？
![image](https://user-images.githubusercontent.com/8065899/66442584-effa3d80-ea6d-11e9-9517-8f84b346bbdd.png)

**Comment by OliverLew** [comment]
我是poweruser，但是并没有看到任何相关的说明，不懂是什么条件才会显示。

我这里没有显示上传者的，点进详情页都是`by anonymous`，所以没有匿名的都显示了。

**Comment by ronggang** [comment]
那先不管了，我把正则更新一下试试吧。
