### ISSUE TITLE
希望集成一键签到功能

### ISSUE THREAD

**Issue by wolonggl** [ronggang/PT-Plugin-Plus#27]
增加一键批量签到，刷新登陆，防止长时间未登陆过期；

**Comment by ronggang** [comment]
@wolonggl 签到不会考虑集成。关于防止长时间未登录，只要搜索过，就不会过期，相当于已经访问过网站。

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/13
