### ISSUE TITLE
手机竖屏看不到搜索结果大小排序，横屏可以看到，以前的版本不存在这种问题

### ISSUE THREAD

**Issue by px008** [ronggang/PT-Plugin-Plus#270]
- PT 助手版本:1.3.1
- PT 助手安装方式：（市场安装
- 浏览器名称及版本：yandex
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：手机竖屏看不到搜索结果大小排序，横屏可以看到，以前的版本不存在这种问题

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
@px008 移动端的界面后续可能会调整。

**Comment by ronggang** [comment]
@px008 请更新最新版本。
