### ISSUE TITLE
插件在 ptschool  站点页面不显示助手图标和工具栏

### ISSUE THREAD

**Issue by lautokwah** [ronggang/PT-Plugin-Plus#271]
- PT 助手版本: v1.3.1 
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Firefox 69.0.2 (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
插件升级到 v1.3.1 后在 ptschool 站点页面不显示助手图标和工具栏（1. 设置中已开启；2. 升级正常显示；3. 其他站点正常显示）

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
@lautokwah 请核对当前使用的域名是否和助手相同。可参考 https://github.com/ronggang/PT-Plugin-Plus/wiki/config-site 的CDN说明。

**Comment by lautokwah** [comment]
更新到  v1.3.3 后问题已解决
