### ISSUE TITLE
HDhome网页无法弹出页面助手和工具栏

### ISSUE THREAD

**Issue by lianggongli** [ronggang/PT-Plugin-Plus#273]
- PT 助手版本:v1.3.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Google Chrome | 77.0.3865.90 (正式版本) （64 位） (cohort: Stable)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
HDhome网页无法弹出页面助手和工具栏，M-team正常

- 相关截图：
![image](https://user-images.githubusercontent.com/56346690/66475153-5a8a9800-eac5-11e9-97a1-028839080feb.png)

- 重现步骤：

**Comment by ronggang** [comment]
@lianggongli 请核对当前使用的域名是否和助手相同。可参考 https://github.com/ronggang/PT-Plugin-Plus/wiki/config-site 的CDN说明。
