### ISSUE TITLE
能否在基本数据栏添加导入原数据功能

### ISSUE THREAD

**Issue by XHLYDZ** [ronggang/PT-Plugin-Plus#274]
## 您的功能请求是否与问题有关？ 请描述一下。

在基本数据栏有导出原数据功能，因为一些原因，比如我从Google备份恢复后发现基本数据被清空，而我恰好不久前导出过数据，既然有导出，能不能添加导入功能，谢谢

**Comment by Rhilip** [comment]
导入数据很难避免用户使用fake数据导入，这点值得在开发之前做详细探讨，特别是在目前插件截图在某种程度上是求药的必备。
毕竟目前导出的格式较为简单，且没有校验，直接修改重新导入即相当于对历史数据篡改。
虽然在某种程度上使用F12一样可以对输出结果进行fake，但是在没有导入原数据功能之前，插件本身记录的数据较难以修改。

**Comment by ronggang** [comment]
> 导入数据很难避免用户使用fake数据导入，这点值得在开发之前做详细探讨，特别是在目前插件截图在某种程度上是求药的必备。
> 毕竟目前导出的格式较为简单，且没有校验，直接修改重新导入即相当于对历史数据篡改。
> 虽然在某种程度上使用F12一样可以对输出结果进行fake，但是在没有导入原数据功能之前，插件本身记录的数据较难以修改。

正因如此，才一直没做导入功能。如果真要做，导出的数据结构需要重新设计一下，得好好讨论讨论。

**Comment by XHLYDZ** [comment]
> 
> 
> > 导入数据很难避免用户使用fake数据导入，这点值得在开发之前做详细探讨，特别是在目前插件截图在某种程度上是求药的必备。
> > 毕竟目前导出的格式较为简单，且没有校验，直接修改重新导入即相当于对历史数据篡改。
> > 虽然在某种程度上使用F12一样可以对输出结果进行fake，但是在没有导入原数据功能之前，插件本身记录的数据较难以修改。
> 
> 正因如此，才一直没做导入功能。如果真要做，导出的数据结构需要重新设计一下，得好好讨论讨论。

好的，感谢解惑
