### ISSUE TITLE
搜索连接超时显示为无结果站点

### ISSUE THREAD

**Issue by foxconndmd** [ronggang/PT-Plugin-Plus#282]
- PT 助手版本:1.3.3
- PT 助手安装方式：市场安装
- 浏览器名称及版本：firefox
- 问题描述：
搜索时个别网站连接超时显示为无结果站点，以前老版本显示连接失败并可单独重试失败的站点。

**Comment by ted423** [comment]
超时跟我说的这个是不是一个现象
https://github.com/ronggang/PT-Plugin-Plus/issues/266

**Comment by foxconndmd** [comment]
> 
> 
> 超时跟我说的这个是不是一个现象
> #266

应该是的
