### ISSUE TITLE
希望添加一个删除站点指定日期的同步数据的功能

### ISSUE THREAD

**Issue by hashim1987** [ronggang/PT-Plugin-Plus#283]
## 您的功能请求是否与问题有关？ 请描述一下。

站点有时候会因为各种原因倒是数据同步失败,但是还是会记录数据,默认为0,在查看数据曲线时非常影响观看,建议添加删除某个指定时间点的同步数据

**Comment by ronggang** [comment]
@hashim1987 删除到时看要不要加吧。下一版本将会处理失败的数据，让数据看起来是连续的，不会大起大落。

**Comment by hashim1987** [comment]
> @hashim1987 删除到时看要不要加吧。下一版本将会处理失败的数据，让数据看起来是连续的，不会大起大落。

收到,大佬辛苦了

**Comment by hashim1987** [comment]
[曲线图连接](https://img.m-team.cc/images/2019/11/04/aaf20ecfbc9b9a9ec4540629d664644c.png)

已更新到1.4.2版本,zip包安装模式,原来同步错误的数据还是感觉有点碍眼,再次请求大佬添加删除指定时间点的同步数据的能,谢谢了

**Comment by Rhilip** [comment]
暂时走这条路吧： https://github.com/ronggang/PT-Plugin-Plus/issues/537
