### ISSUE TITLE
大佬大佬，请求添加右键发送磁力链接到客户端的功能

### ISSUE THREAD

**Issue by ywyha** [ronggang/PT-Plugin-Plus#292]
## 描述你想要的解决方案
BT PT功能重合度比较高，希望添加右键发送网页的磁力链接到下载服务器的功能，希望有个中国人自己开发的这类插件，超级感谢大佬对PT的贡献，有了PT助手后易用性提升了几万倍

**Comment by Rhilip** [comment]
我和你用的不是同一个插件吗？
![image](https://user-images.githubusercontent.com/13842140/67352101-a0456700-f581-11e9-9b40-2cd3104c20c9.png)

**Comment by ywyha** [comment]
> 我和你用的不是同一个插件吗？
> ![image](https://user-images.githubusercontent.com/13842140/67352101-a0456700-f581-11e9-9b40-2cd3104c20c9.png)

发帖之前我试了，发送到默认的QB客户端一直都是显示正在发送链接至下载服务器，无法添加成功，而同样的操作PT站的种子链接就可以添加成功

**Comment by Rhilip** [comment]
关于magent链接处理，我看了看目前是匹配40位hex编码格式，而不是直接匹配magent开头，之前的这种写法觉得很奇怪
https://github.com/ronggang/PT-Plugin-Plus/blob/2c2812c4a98fe5cff903b120f3532ebb2b45c9f8/resource/clients/deluge/init.js#L177-L191
如果直接a标签 例如`<a href="FLOC7DOFM2IINJBVKLY4JQCMGHKTLALQ">` 这种情况，助手最终的得到的是还是http开头，走了后面的处理流程。
另外，magent除了40位的hex格式之外，还有32位的base32格式（见2L图）。直接走url开始判断比较好些

**Comment by ted423** [comment]
话说可以了么，我这试似乎不行？https://www.1337x.to/torrent/4138320/Frozen-Fever-2015-1080p-BDRip-x265-DTS-HD_MA-5-1-Kira-SEV/

**Comment by ronggang** [comment]
> 话说可以了么，我这试似乎不行？https://www.1337x.to/torrent/4138320/Frozen-Fever-2015-1080p-BDRip-x265-DTS-HD_MA-5-1-Kira-SEV/

暂无法测试。
