### ISSUE TITLE
火狐浏览器更新1.4.0以后侧边栏不显示

### ISSUE THREAD

**Issue by herokillerJ** [ronggang/PT-Plugin-Plus#293]
- PT 助手版本:1.4.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：firefrox 70.0(6位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
1.3.3版本没问题,更新到1.4.0以后侧边栏不显示了

- 相关截图：
![图片](https://user-images.githubusercontent.com/24591046/67620814-761fcd80-f83d-11e9-9c2d-0906a525f078.png)

红圈里的侧边栏没有了,我回到1.3.3版本重新截的图
- 重现步骤：
火狐浏览器更新1.4.0即可

**Comment by ronggang** [comment]
@herokillerJ 感谢反馈，已确认在FF下存在问题，尽快修复。
