### ISSUE TITLE
搜索结果中缺ahd

### ISSUE THREAD

**Issue by xyou365** [ronggang/PT-Plugin-Plus#294]
- PT 助手版本: 1.4
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome Version 78.0.3904.70
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：未测，这个应该没关系
- 问题描述：
搜索框搜 Witchcraft Through the Ages 的时候没有 ahd 的结果
但是实际呢是有的 torrents.php?id=27086

**Comment by ted423** [comment]
你是ahd这个站的结果出不来么？

**Comment by ronggang** [comment]
@xyou365 暂时无法复现。可尝试单独搜索该站点试试。
