### ISSUE TITLE
希望支持聆音的阅听专区页面整页下载

### ISSUE THREAD

**Issue by kidofgalaxy** [ronggang/PT-Plugin-Plus#295]
## 您的功能请求是否与问题有关？ 请描述一下。

希望支持聆音的阅听专区页面整页下载
live.php页面当前无法一键下载整页

**Comment by ronggang** [comment]
@kidofgalaxy 该站点暂未收录，无法适配。你可以通过自定义插件的方式来添加该页面。
https://github.com/ronggang/PT-Plugin-Plus/wiki/config-custom-plugin

**Comment by ronggang** [comment]
请更新至 v1.4.6

**Comment by mayziran** [comment]
> 请更新至 v1.4.6

已更新至1.5.0，想批量下点电子书保种升茉莉，但发现还是不支持整页下载，可以看到右下角蓝色提示框发送的链接不包含passkey
