### ISSUE TITLE
OPS统计数据异常

### ISSUE THREAD

**Issue by SuTree** [ronggang/PT-Plugin-Plus#298]
- PT 助手版本: 1.4.1
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome 版本 78.0.3904.70（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：数据量、分享率、魔力值均为0；做种数、做种体积、入站时间显示空白

- 相关截图：
![20191028100100](https://user-images.githubusercontent.com/7479059/67646612-f04d7080-f969-11e9-8263-955afc69b05a.png)

- 重现步骤：略

**Comment by ted423** [comment]
未复现，当前版本是否正常？

**Comment by ted423** [comment]
未复现且长期无回应
