### ISSUE TITLE
学校（pt.btschool.club）搜索结果少

### ISSUE THREAD

**Issue by sniperking1234** [ronggang/PT-Plugin-Plus#299]
- PT 助手版本: 1.4.0
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：chrome 77
- 问题描述：学校搜索结果少

- 相关截图：
以星际迷航为例，学校里面可以搜索到23个，而助手只搜索到10个
![image](https://user-images.githubusercontent.com/7834655/67676524-a5107d80-f9bc-11e9-9d91-8ffdae68fcdd.png)
![image](https://user-images.githubusercontent.com/7834655/67676577-c40f0f80-f9bc-11e9-97f9-f58135c6b28b.png)

- 重现步骤：学校搜索星际迷航

**Comment by Rhilip** [comment]
@sniperking1234 这么还有这么傻的孩子🙈🙈🙈

**Comment by sniperking1234** [comment]
@Rhilip 原来默认是10。。close
