### ISSUE TITLE
更新到1.0.0.7后，基本设置界面无法保存

### ISSUE THREAD

**Issue by 1mogude1** [ronggang/PT-Plugin-Plus#3]
遇到的问题：基本设置界面无法保存，保存按钮灰色并且点了无效。
在各站种子界面未出现之前版本有的浮动窗口（但是在基本设置界面显示开着）
所有站都开了搜索但是只有四个站能搜，提示其他的站 暂不支持搜索的站点：    不知道是bug还是未完成的功能，特来问询

**Comment by ronggang** [comment]
@1mogude1 感谢反馈。由于没有hdsky，无法直接测试，可否把hdsky的种子页面的html源码发私发我一下，发之前把个人信息去掉，我分析看看，或者你看看他们的rss订阅里下载链接是哪个，如果不一样，那么hdsky得单独设置了。

**Comment by 1mogude1** [comment]
脚本执行出错的报错是在聚合搜索部分

**Comment by ronggang** [comment]
@1mogude1 现在更新到最新版本试试能不能正常使用。

**Comment by 1mogude1** [comment]
已经解决。感谢。另外搜索界面能否实现把种子促销信息加进去，这样的话会实用的多，否则还是要回到网站里看是不是free

**Comment by ronggang** [comment]
> 已经解决。感谢。另外搜索界面能否实现把种子促销信息加进去，这样的话会实用的多，否则还是要回到网站里看是不是free

种子的各类标签信息已在计划中。

**Comment by ronggang** [comment]
@1mogude1 标签功能已加，这个issue先关了。
