### ISSUE TITLE
mteam下载推送失败

### ISSUE THREAD

**Issue by deemoartisan** [ronggang/PT-Plugin-Plus#305]
- PT 助手版本:1.3.3
- PT 助手安装方式：市场安装
- 浏览器名称及版本：78.0.3904.87正式版本
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
从mt搜索页面一键下载当前页面所有的种子时，系统日志显示 下载服务器qBittorrent atlantic处理[addTorrentFromURL]命令失败！
已经手动在网站上下过种子到推送的服务器，还是不行。

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@deemoartisan 为啥关了重发一遍？

**Comment by deemoartisan** [comment]
因为没有bug label感觉不够正经（

**Comment by ted423** [comment]
我试了下1.4.2的，是正常的，我在怀疑你是不是哪里设置有问题

**Comment by deemoartisan** [comment]
> 我试了下1.4.2的手动安装的，是正常的，我在怀疑你是不是哪里设置有问题

我也手动安装了1.42，还是不行，报错信息一样的。。。。设置也是按照wiki来的，没有问题啊

**Comment by ted423** [comment]
> > 我试了下1.4.2的手动安装的，是正常的，我在怀疑你是不是哪里设置有问题
> 
> 我也手动安装了1.42，还是不行，报错信息一样的。。。。设置也是按照wiki来的，没有问题啊

单个推送都正常？

**Comment by deemoartisan** [comment]
> > > 我试了下1.4.2的手动安装的，是正常的，我在怀疑你是不是哪里设置有问题
> > 
> > 
> > 我也手动安装了1.42，还是不行，报错信息一样的。。。。设置也是按照wiki来的，没有问题啊
> 
> 单个推送都正常？

是的，无比正常。。。

**Comment by ronggang** [comment]
@deemoartisan 可尝试以下方法：
1、减少搜索结果，看看是否可以推送成功；
2、调大超时时长；
3、调整『下载』参数中『每个链接的间隔时间』；

**Comment by deemoartisan** [comment]
> @deemoartisan 可尝试以下方法：
> 1、减少搜索结果，看看是否可以推送成功；
> 2、调大超时时长；
> 3、调整『下载』参数中『每个链接的间隔时间』；

依旧不行，系统日志里的失败记录非常亮眼

**Comment by ronggang** [comment]
> > @deemoartisan 可尝试以下方法：
> > 1、减少搜索结果，看看是否可以推送成功；
> > 2、调大超时时长；
> > 3、调整『下载』参数中『每个链接的间隔时间』；
> 
> 依旧不行，系统日志里的失败记录非常亮眼

那请把详细日志贴一下。

**Comment by deemoartisan** [comment]
> > > @deemoartisan 可尝试以下方法：
> > > 1、减少搜索结果，看看是否可以推送成功；
> > > 2、调大超时时长；
> > > 3、调整『下载』参数中『每个链接的间隔时间』；
> > 
> > 
> > 依旧不行，系统日志里的失败记录非常亮眼
> 
> 那请把详细日志贴一下。

![截屏2019-11-06下午8 55 46](https://user-images.githubusercontent.com/46527398/68300062-fb29a300-00d7-11ea-8c8c-11562c8e67e8.png)

**Comment by ronggang** [comment]
> > > > @deemoartisan 可尝试以下方法：
> > > > 1、减少搜索结果，看看是否可以推送成功；
> > > > 2、调大超时时长；
> > > > 3、调整『下载』参数中『每个链接的间隔时间』；
> > > 
> > > 
> > > 依旧不行，系统日志里的失败记录非常亮眼
> > 
> > 
> > 那请把详细日志贴一下。
> 
> ![截屏2019-11-06下午8 55 46](https://user-images.githubusercontent.com/46527398/68300062-fb29a300-00d7-11ea-8c8c-11562c8e67e8.png)

提示无效种子通常还是那个问题，你需要到站点下载一个种子，不要使用推送功能，直接点站点页面里的『下载种子』链接进行下载，第一次需要确认一下，确认过就可以了。

**Comment by deemoartisan** [comment]
> > > > > @deemoartisan 可尝试以下方法：
> > > > > 1、减少搜索结果，看看是否可以推送成功；
> > > > > 2、调大超时时长；
> > > > > 3、调整『下载』参数中『每个链接的间隔时间』；
> > > > 
> > > > 
> > > > 依旧不行，系统日志里的失败记录非常亮眼
> > > 
> > > 
> > > 那请把详细日志贴一下。
> > 
> > 
> > ![截屏2019-11-06下午8 55 46](https://user-images.githubusercontent.com/46527398/68300062-fb29a300-00d7-11ea-8c8c-11562c8e67e8.png)
> 
> 提示无效种子通常还是那个问题，你需要到站点下载一个种子，不要使用推送功能，直接点站点页面里的『下载种子』链接进行下载，第一次需要确认一下，确认过就可以了。

有这么简单能解决我就不来问问题了。。。。。

**Comment by deemoartisan** [comment]
今天尝试了一下，就算是两个种子一块儿推送，都有问题。。。不明白啊不明白

**Comment by ronggang** [comment]
> 今天尝试了一下，就算是两个种子一块儿推送，都有问题。。。不明白啊不明白

那你只能追踪一下网络请求，看看返回了什么结果吧。

**Comment by deemoartisan** [comment]
> > 今天尝试了一下，就算是两个种子一块儿推送，都有问题。。。不明白啊不明白
> 
> 那你只能追踪一下网络请求，看看返回了什么结果吧。

没搞明白，我手动推送的种子每个都正常，只要用批量推送就不行。。。

**Comment by ronggang** [comment]
> > > 今天尝试了一下，就算是两个种子一块儿推送，都有问题。。。不明白啊不明白
> > 
> > 
> > 那你只能追踪一下网络请求，看看返回了什么结果吧。
> 
> 没搞明白，我手动推送的种子每个都正常，只要用批量推送就不行。。。

所以需要检查一下网络请求返回的结果，看看是返回了什么内容。可按以下方法操作：
https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page

**Comment by e71828** [comment]
@ronggang 聊天机？

**Comment by lvhe19880210** [comment]
ttg发生同样问题
<img width="1341" alt="截屏2019-12-07下午10 08 51" src="https://user-images.githubusercontent.com/29178968/70375899-62887c00-193e-11ea-9206-14076fa0ca5e.png">

**Comment by uu5266** [comment]
Version1.4.9，站点馒头，第一天可以整页推送，开启二级验证后（怀疑），第二天不能整页推，只能进详细种子页面推送，在外面拖动单个种子也不行。关闭二级验证后问题依旧。查看控制台后，response显示无效passkey,此时passkey为密码。单个推送的passkey为一长串hash码。为什么在种子搜索页面推送的url会把passkey赋值为password?
只在馒头这个站点发现这个问题，同环境下其它站点正常。

**Comment by ted423** [comment]
@uu5266 检查你ptpp里mteam passkey的设置，别告诉我你填了密码进去

**Comment by uu5266** [comment]
> @uu5266 检查你ptpp里mteam passkey的设置，别告诉我你填了密码进去

还真是，改完就解决了。
