### ISSUE TITLE
搜索结果页增加查看站点站点个人数据功能

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#306]
## 您的功能请求是否与问题有关？ 请描述一下。

很多时候，搜索同一个资源，很多站点都有相同的资源。这时候有时会想从下载量少的站点下载，有时候会选择从下载量临近升级的站点下载。
是否可以添加在搜索结果页查看站点数据的功能

## 描述你想要的解决方案

搜索结果页站点图标上鼠标悬浮，展示站点的个人上传量和下载量。

**Comment by ted423** [comment]
@luckiestone 我觉得切下标签不是很难...

**Comment by luckiestone** [comment]
> @luckiestone 我觉得切下标签不是很难...

世界是由懒人改变的。

**Comment by Rhilip** [comment]
@luckiestone 感觉没有意义

**Comment by ronggang** [comment]
可以讨论讨论实用性。
其实鼠标悬浮一个一个看也挺麻烦的，是不是要搞个算法推荐，然后按颜色标注。。。🤣🤣

**Comment by luckiestone** [comment]
> 可以讨论讨论实用性。
> 其实鼠标悬浮一个一个看也挺麻烦的，是不是要搞个算法推荐，然后按颜色标注。。。

后者这个我想过，后者实现起来麻烦，而且主要不同人需求不同有的是挑buffer大的下，有的跳下载量快到升级点的下。所以还是悬浮自己看比较合适。而且实际情况是，同一个资源所有站同时有站点数量不至于太多。
如果要算法推荐如果考虑到升级的话，就还得搞个库，哪个站多少升级，还挺麻烦。
或者两者结合，算法推荐挑选一个buffer最大的，有别的需求自己悬浮查看

**Comment by ronggang** [comment]
> > 可以讨论讨论实用性。
> > 其实鼠标悬浮一个一个看也挺麻烦的，是不是要搞个算法推荐，然后按颜色标注。。。
> 
> 后者这个我想过，后者实现起来麻烦，而且主要不同人需求不同有的是挑buffer大的下，有的跳下载量快到升级点的下。所以还是悬浮自己看比较合适。而且实际情况是，同一个资源所有站同时有站点数量不至于太多。
> 如果要算法推荐如果考虑到升级的话，就还得搞个库，哪个站多少升级，还挺麻烦。
> 或者两者结合，算法推荐挑选一个buffer最大的，有别的需求自己悬浮查看

想多了。
