### ISSUE TITLE
yarn build 的时候出错，Error: Cannot find module 'test/dist/buildResource.js'

### ISSUE THREAD

**Issue by zieglar** [ronggang/PT-Plugin-Plus#31]
https://github.com/ronggang/PT-Plugin-Plus/blob/a476a9bb5199ead4cce11f7a4d3cfddd1a165849/package.json#L7

**Comment by ronggang** [comment]
@zieglar 感谢反馈。

**Comment by ronggang** [comment]
@zieglar 目前可以先执行 yarn res 生成相关文件，再执行 yarn build 就可以了。

**Comment by zieglar** [comment]
谢谢
