### ISSUE TITLE
对于断种的种子搜索里能否出现？

### ISSUE THREAD

**Issue by liliangzhi** [ronggang/PT-Plugin-Plus#311]
## 您的功能请求是否与问题有关？ 请描述一下。

最近几个版本中。想搜索种子来辅种。发现断种的而站点没有删除的种子搜索里搜索不到。这样很不利于辅种

## 描述你想要的解决方案

希望添加0做种的页面 或者有设置的按钮 可以支持显示0做种的页面。方便辅种

**Comment by Rhilip** [comment]
@liliangzhi 请检查你在对应站点的设置，插件本身搜索并不带强制活种的
请求项。

**Comment by ronggang** [comment]
除了 @Rhilip 说的以外，请提供一下具体站名。

**Comment by liliangzhi** [comment]
> @liliangzhi 请检查你在对应站点的设置，插件本身搜索并不带强制活种的
> 请求项。

感谢回复。刚测试了下确实可行。由于大部分站点都是默认  
控制面板-网站设定--显示断种活种   默认是活种  
简单测试  设置HDSKY和MT后插件搜索有效显示。但是奇怪的是 HDA确不用更改设置 就可以搜索出来 
关键词例：Out Of The Furnace 2013 HK Blu-Ray 1080p AVC TrueHD 5.1 -TTG

**Comment by liliangzhi** [comment]
> 除了 @Rhilip 说的以外，请提供一下具体站名。

目前简单测试例子  有HDSKY MT 两个设置后可以搜出来  TTG找不到有设置搜索的地方 但插件是可以搜出的  由于基本全部站都是这个默认设置。好奇的是hdarea 不用设置居然也能搜索出来

**Comment by ted423** [comment]
大部分是基于站点设置
