### ISSUE TITLE
torrentleech 做种体积获取异常

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#314]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
TL的completed是下了才算complete,辅种的completed是0，不知道这个算不算point
所以
```
 datas.forEach(item => {
          // item[7] 是否已完成
          // item[8] 活动状态
          console.log(item);
          if (item[7] == 1 && item[8] == "Yes") {
	        console.log(results.seedingSize);
            results.seeding++;
            results.seedingSize += item[3].sizeToNumber();
          }
```
这段代码是扩展里的（而且我一开始第一个种子显示不活动，然后我获取更多peer就提示活动了.....）
总之怪怪的。
然后最后似乎只算了我完整下载的种子体积到做种体积里。不知道是不是算的下载...
- 相关截图：

![image](https://user-images.githubusercontent.com/7042766/68486779-cd319380-027c-11ea-933a-cc3fd957787f.png)
![image](https://user-images.githubusercontent.com/7042766/68487405-fb63a300-027d-11ea-9bfe-ffda384b26db.png)

- 重现步骤：

**Comment by ted423** [comment]
代码里用的item3 ,但似乎应该用item[1]

```
1: "<span class="torrent_name2">44.06 GB</span>"
2: "41"
3: "0 B"
4: "0 B"
5: "inf."
6: 809
7: 0
8: "Yes"
9: "<button id="737448" title="Le Ban Hammer" style="background: none;" class="ban_hammer_button" data-toggle="modal" data-target="#banHammerModal"><i class='fa fa-gavel'></i></button>"
```

**Comment by ted423** [comment]
```
      if (datas) {
        datas.forEach(item => {
          // item[7] 是否已完成
          // item[8] 活动状态
          console.log(item);
          if (item[7] == 1 && item[8] == "Yes") {
            results.seeding++;
            results.seedingSize += item[1].replace('<span class=\"torrent_name2\">',"").replace('</span>',"").sizeToNumber();
          }
        });
      }
```

改成这样似乎可以
似乎我要稍微弄点东西让种子变成completed才行.....

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/68493040-ad06d200-0286-11ea-81f0-f671ba026f77.png)
![image](https://user-images.githubusercontent.com/7042766/68493074-b728d080-0286-11ea-94c4-f057ba334e7b.png)

感觉这破站必须下点东西才给判定completed，不知道影不影响tl point 的获取

**Comment by ronggang** [comment]
之前的逻辑也是猜的，当时认为 `completed` 状态必需为1，然后获取已下载的大小，未曾考虑过辅种的情况。如果算上辅种的话，的确不应该使用已下载大小。

**Comment by ted423** [comment]
> 之前的逻辑也是猜的，当时认为 `completed` 状态必需为1，然后获取已下载的大小，未曾考虑过辅种的情况。如果算上辅种的话，的确不应该使用已下载大小。

我现在有个2了，所以==1估计还不行.....得>=1
闲着无聊挪了下位置...
![image](https://user-images.githubusercontent.com/7042766/68737075-5cdc9680-061d-11ea-8cd4-937be52ba13f.png)

**Comment by ted423** [comment]
> 之前的逻辑也是猜的，当时认为 `completed` 状态必需为1，然后获取已下载的大小，未曾考虑过辅种的情况。如果算上辅种的话，的确不应该使用已下载大小。
```
  if (datas) {
        datas.forEach(item => {
          // item[7] 是否已完成
          // item[8] 活动状态
          console.log(item);
          if (item[7] >= 1 && item[8] == "Yes") {
            results.seeding++;
            results.seedingSize += item[1].replace('<span class=\"torrent_name2\">',"").replace('</span>',"").sizeToNumber();
          }
        });
      }
```

作者大大可以考虑这个，总之这个站的辅种状态无法判断，我试了下个新的，在snatchlist跟直接辅种显示没有任何区别。
唯一可以做参考的只有complete
我挪了下位置，Complete会莫名奇妙变成2。
并且删了重新下载的话，也是完全无法分辨的。

但是他的point判断估计是直接跟据tracker状态，18号我加了个大包，跟据历史记录可以明显感觉到point增加速度翻倍，但snatchlist里那个大包的complete是0

另一个考虑是取消支持做种体积的显示，毕竟tl全黑种，辅种可能会比较靠谱。而且不准的数据有点难搞
