### ISSUE TITLE
时间轴增加做种天数数据

### ISSUE THREAD

**Issue by sniperking1234** [ronggang/PT-Plugin-Plus#315]
## 您的功能请求是否与问题有关？ 请描述一下。

时间轴增加做种天数数据，和其他数据一起显示。

**Comment by ronggang** [comment]
暂无数据可用，所以目前做不了。

**Comment by sniperking1234** [comment]
@ronggang 这个无法从userdetails页面抓取么

**Comment by ronggang** [comment]
> @ronggang 这个无法从userdetails页面抓取么

只有NP有这个数据，而且看起来意义不是很大。
