### ISSUE TITLE
站点数据更新问题

### ISSUE THREAD

**Issue by LC-BX** [ronggang/PT-Plugin-Plus#316]
- 
R酱好~ 手动滑稽
读了常见问题没找到相关信息。

问题：我只需要用这个NB的工具来自动更新站点数据（避免被自动清理）。我是否必须设一个**有效的**下载服务器？
用自动搜索添加了站点，随便填了一个下载服务器，更新站点数据长时间无返回结果。
Thanks.
Regards

**Comment by ted423** [comment]
不必须，你获取不到应该是站点设置的问题

**Comment by Rhilip** [comment]
@LC-BX 自动添加站点后请刷新页面以便助手重新加载配置，如果刷新页面后仍然不行请贴出详细日志。

**Comment by LC-BX** [comment]
> @LC-BX 自动添加站点后请刷新页面以便助手重新加载配置，如果刷新页面后仍然不行请贴出详细日志。

原来只需要刷新页面==多谢了

**Comment by 18070508837** [comment]
zz
