### ISSUE TITLE
Qb在右键种子加入的时候设置单种限速

### ISSUE THREAD

**Issue by lixiaolong2** [ronggang/PT-Plugin-Plus#317]
## 您的功能请求是否与问题有关？ 请描述一下。

Qb在右键种子加入的时候设置单种限速。在网页版自己添加种子可以限速设置。不知道能不能助手也加入这个功能。在配置的时候自定义好？

**Comment by Rhilip** [comment]
似乎和这个重复了
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/145
