### ISSUE TITLE
坚果云 webdav适配失败

### ISSUE THREAD

**Issue by mylovesaber** [ronggang/PT-Plugin-Plus#319]
- PT 助手版本:版本 v1.4.2
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 78.0.3904.97（正式版本） （32 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：看了下好像没有安装和webdav有关或者其他的同步插件
- 问题描述：坚果云备份失败

- 相关截图：

- 重现步骤：
1. 登录坚果云个人信息界面
https://www.jianguoyun.com/d/home#/safety
2. 界面中间偏右下蓝色按钮添加应用，应用名PT Plugin Plus，点击生成密码后复制密码
3. ptpp插件打开，参数备份与恢复-添加备份服务器-webdav，
服务器名ptpp
地址https://dav.jianguoyun.com/dav/
登录名为坚果云信息界面显示的用户名我显示的是邮箱名
密码粘贴上面复制的密码，
4. 测试连接失败，同样操作用于另一个webdav服务（纯纯写作app）功能正常

**Comment by hzgjq** [comment]
坚果云中手动建一个文件夹，地址改成https://dav.jianguoyun.com/dav/新建的文件夹名称
关闭Digest认证
测试可用

**Comment by mylovesaber** [comment]
> 坚果云中手动建一个文件夹，地址改成[https://dav.jianguoyun.com/dav/新建的文件夹名称](https://dav.jianguoyun.com/dav/%E6%96%B0%E5%BB%BA%E7%9A%84%E6%96%87%E4%BB%B6%E5%A4%B9%E5%90%8D%E7%A7%B0)
> 关闭Digest认证
> 测试可用

测试了下果然可用，但又引出一个bug，第一次添加的时候该输入的都填写完后，确认按钮是灰色不可选；
点空白处关掉弹窗然后重新打开那个webdav的填写信息界面，这时候刚才填写的信息都还在，只是确认选项依旧是灰色，打开Digest选项时确认选项才可选，但这个选项开着测试连接性就报错，关掉后确认选项依旧可选，连接性测试就能通过，然后确认后就能正常同步了，不知道作者会不会看到这个bug汇报

**Comment by ronggang** [comment]
> > 坚果云中手动建一个文件夹，地址改成[https://dav.jianguoyun.com/dav/新建的文件夹名称](https://dav.jianguoyun.com/dav/%E6%96%B0%E5%BB%BA%E7%9A%84%E6%96%87%E4%BB%B6%E5%A4%B9%E5%90%8D%E7%A7%B0)
> > 关闭Digest认证
> > 测试可用
> 
> 测试了下果然可用，但又引出一个bug，第一次添加的时候该输入的都填写完后，确认按钮是灰色不可选；
> 点空白处关掉弹窗然后重新打开那个webdav的填写信息界面，这时候刚才填写的信息都还在，只是确认选项依旧是灰色，打开Digest选项时确认选项才可选，但这个选项开着测试连接性就报错，关掉后确认选项依旧可选，连接性测试就能通过，然后确认后就能正常同步了，不知道作者会不会看到这个bug汇报

会看到，谢谢反馈。
