### ISSUE TITLE
下载服务器不能使用

### ISSUE THREAD

**Issue by wyl219** [ronggang/PT-Plugin-Plus#32]
连接和账号密码都是正确的，但是测试连接失败，点下载也没效果

**Comment by wyl219** [comment]
Transmission不行，黑群的可以。通过webgui可以连接Transmission

**Comment by ronggang** [comment]
> Transmission不行，黑群的可以。通过webgui可以连接Transmission

@wyl219 可否提供填写的服务器地址格式？另外，黑群可以是什么意思？是指的synologyDownloadStation吗？

**Comment by wyl219** [comment]
是的,黑群就是黑群晖,synologyDownloadStation
地址格式试过以下几种:
http://192.168.0.233:9091
http://192.168.0.233:9091/web/
还有就是用的域名带端口的形式.

**Comment by ronggang** [comment]
> 是的,黑群就是黑群晖,synologyDownloadStation
> 地址格式试过以下几种:
> http://192.168.0.233:9091
> http://192.168.0.233:9091/web/
> 还有就是用的域名带端口的形式.
> 
> 也试过不带[http://的形式](http://%E7%9A%84%E5%BD%A2%E5%BC%8F)

地址格式用 http://ip:port 没问题
你看一下 TR 的 settings.josn 文件，是否启用了 rpc 白名单，检查一下以下参数
```
"rpc-host-whitelist": "",
"rpc-host-whitelist-enabled": false,
"rpc-whitelist": "127.0.0.1",
"rpc-whitelist-enabled": false
```

**Comment by wyl219** [comment]
看了一下，关闭了白名单以后依旧错误。

**Comment by ronggang** [comment]
> 看了一下，关闭了白名单以后依旧错误。

也是说之前启用了白名单是吗？是否在停用TR的情况下再修改的 settings.json 文件？如果不是，请尝试停用TR后再修改 settings.json 文件。

如果问题依然存在，那只能查看插件的背景页 console 的错误信息了。

**Comment by wyl219** [comment]
> > 看了一下，关闭了白名单以后依旧错误。
> 
> 也是说之前启用了白名单是吗？是否在停用TR的情况下再修改的 settings.json 文件？如果不是，请尝试停用TR后再修改 settings.json 文件。
> 
> 如果问题依然存在，那只能查看插件的背景页 console 的错误信息了。

之前"rpc-host-whitelist-enabled":true，但是白名单是空的。而且可以通过公网连接，服务器在家里，在单位可以连接。
是在停用的情况下修改的配置文件。

是这个日志么？
`[{"event":"requestMessage.saveUIOptions","module":"background","time":1550580930662},{"event":"requestMessage.testClientConnectivity","module":"background","time":1550580936931},{"data":{"data":{"code":200,"msg":"parsererror","status":"error"},"success":false,"type":"error"},"event":"testClientConnectivity","module":"background","msg":"测试客户连接失败[http://192.168.0.233:9091]","time":1550580937149},{"event":"requestMessage.saveConfig","module":"background","time":1550580938781},{"event":"requestMessage.openOptions","module":"background","time":1550580945208}]
`

**Comment by ronggang** [comment]
> > > 看了一下，关闭了白名单以后依旧错误。
> > 
> > 
> > 也是说之前启用了白名单是吗？是否在停用TR的情况下再修改的 settings.json 文件？如果不是，请尝试停用TR后再修改 settings.json 文件。
> > 如果问题依然存在，那只能查看插件的背景页 console 的错误信息了。
> 
> 之前"rpc-host-whitelist-enabled":true，但是白名单是空的。而且可以通过公网连接，服务器在家里，在单位可以连接。
> 是在停用的情况下修改的配置文件。
> 
> 是这个日志么？
> `[{"event":"requestMessage.saveUIOptions","module":"background","time":1550580930662},{"event":"requestMessage.testClientConnectivity","module":"background","time":1550580936931},{"data":{"data":{"code":200,"msg":"parsererror","status":"error"},"success":false,"type":"error"},"event":"testClientConnectivity","module":"background","msg":"测试客户连接失败[http://192.168.0.233:9091]","time":1550580937149},{"event":"requestMessage.saveConfig","module":"background","time":1550580938781},{"event":"requestMessage.openOptions","module":"background","time":1550580945208}] `

看到好像是解析错误（parsererror），那应该是连接TR时返回的内容不是JSON格式的内容，可以按以下步骤打开调试信息
![image](https://user-images.githubusercontent.com/8065899/53060365-3ad23f80-34f5-11e9-9086-73ea1c6e48c5.png)
打开背景页之后，再到助手里点TR连接测试，看看获取到什么结果

![image](https://user-images.githubusercontent.com/8065899/53060493-b8964b00-34f5-11e9-8724-49fb53921cc1.png)

分区将 console 和 network 的内容截图一下我们分析一下看看能不能修复。

**Comment by wyl219** [comment]
> > > > 看了一下，关闭了白名单以后依旧错误。
> > > 
> > > 
> > > 也是说之前启用了白名单是吗？是否在停用TR的情况下再修改的 settings.json 文件？如果不是，请尝试停用TR后再修改 settings.json 文件。
> > > 如果问题依然存在，那只能查看插件的背景页 console 的错误信息了。
> > 
> > 
> > 之前"rpc-host-whitelist-enabled":true，但是白名单是空的。而且可以通过公网连接，服务器在家里，在单位可以连接。
> > 是在停用的情况下修改的配置文件。
> > 是这个日志么？
> > `[{"event":"requestMessage.saveUIOptions","module":"background","time":1550580930662},{"event":"requestMessage.testClientConnectivity","module":"background","time":1550580936931},{"data":{"data":{"code":200,"msg":"parsererror","status":"error"},"success":false,"type":"error"},"event":"testClientConnectivity","module":"background","msg":"测试客户连接失败[http://192.168.0.233:9091]","time":1550580937149},{"event":"requestMessage.saveConfig","module":"background","time":1550580938781},{"event":"requestMessage.openOptions","module":"background","time":1550580945208}] `
> 
> 看到好像是解析错误（parsererror），那应该是连接TR时返回的内容不是JSON格式的内容，可以按以下步骤打开调试信息
> ![image](https://user-images.githubusercontent.com/8065899/53060365-3ad23f80-34f5-11e9-9086-73ea1c6e48c5.png)
> 打开背景页之后，再到助手里点TR连接测试，看看获取到什么结果
> 
> ![image](https://user-images.githubusercontent.com/8065899/53060493-b8964b00-34f5-11e9-8724-49fb53921cc1.png)
> 
> 分区将 console 和 network 的内容截图一下我们分析一下看看能不能修复。

找不到背景页的进入方式
![Uploading QQ截图20190220100241.jpg…]()

**Comment by wyl219** [comment]
![qq 20190220100241](https://user-images.githubusercontent.com/20471813/53060977-39097b80-34f7-11e9-9d36-969525aff01e.jpg)

**Comment by ronggang** [comment]
@wyl219 点详细信息进去也可以，里面有背景页
![image](https://user-images.githubusercontent.com/8065899/53061470-b71a5200-34f8-11e9-827c-129ecd4b2403.png)

另外，你这个是什么浏览器？

**Comment by wyl219** [comment]
> @wyl219 点详细信息进去也可以，里面有背景页
> ![image](https://user-images.githubusercontent.com/8065899/53061470-b71a5200-34f8-11e9-827c-129ecd4b2403.png)
> 
> 另外，你这个是什么浏览器？
找到了，用的是chrome，需要打开开发者模式
![qq 20190220102533](https://user-images.githubusercontent.com/20471813/53061957-3197a180-34fa-11e9-9898-15a6101d4230.jpg)

![qq 20190220102937](https://user-images.githubusercontent.com/20471813/53062041-728fb600-34fa-11e9-8919-1d3982783660.jpg)

**Comment by ronggang** [comment]
@wyl219 谢谢，不过我没看到测试连接后的信息，你打开后，再去助手里点击“测试服务器是否可用”，然后看看 **console** 和 **network** 有没有错误。
![image](https://user-images.githubusercontent.com/8065899/53134277-7cc0bb80-35b1-11e9-9e0a-fc09bcffda9b.png)

看最后一条 rpc ，应该会有服务器返回的信息。

**Comment by wyl219** [comment]
![1](https://user-images.githubusercontent.com/20471813/53135639-f8713700-35b6-11e9-89c5-d40fe444f14c.png)
![2](https://user-images.githubusercontent.com/20471813/53135640-fa3afa80-35b6-11e9-9750-8c7d1dc85239.png)
![3](https://user-images.githubusercontent.com/20471813/53135645-fc9d5480-35b6-11e9-94be-7bdbec3c0a69.png)

**Comment by wyl219** [comment]
> @wyl219 是有问题，请求被转到web页面了。
> 题外话，你的web页面好像被插入广告了吧。

那该怎么解决呢?

题外话,你不说我没注意,你说了我一看,嘿,关于里还真有广告.还挺眼熟.
![qq 20190221100225](https://user-images.githubusercontent.com/20471813/53137997-d16b3300-35bf-11e9-85f2-b9c7b05462ee.png)

**Comment by wyl219** [comment]
当时是用的网上的一键包安装的,不过看界面上是没广告的.

**Comment by ronggang** [comment]
@wyl219 
1. 直接用浏览器访问你的 http://192.168.0.233:9091/transmission/rpc ，看看是什么结果，如果被跳转了，说明配置可能不一样；
2. 检查一下 TR 的 settings.json 文件，看一下 rpc-url 内容是不是等于  /transmission/
![image](https://user-images.githubusercontent.com/8065899/53138830-8141a000-35c2-11e9-9569-0d4026d94401.png)
如果这个值不等于 /transmission/ , 那么在填写服务器地址时就要把这个也跟上了，如：
http://192.168.0.233:9091/你看的值/rpc
这样再试试看。

另外，那个被插入的内容好像是广告拦截插件干的

**Comment by wyl219** [comment]
> @wyl219
> 
> 1. 直接用浏览器访问你的 http://192.168.0.233:9091/transmission/rpc ，看看是什么结果，如果被跳转了，说明配置可能不一样；
> 2. 检查一下 TR 的 settings.json 文件，看一下 rpc-url 内容是不是等于  /transmission/
>    ![image](https://user-images.githubusercontent.com/8065899/53138830-8141a000-35c2-11e9-9569-0d4026d94401.png)
>    如果这个值不等于 /transmission/ , 那么在填写服务器地址时就要把这个也跟上了，如：
>    [http://192.168.0.233:9091/你看的值/rpc](http://192.168.0.233:9091/%E4%BD%A0%E7%9C%8B%E7%9A%84%E5%80%BC/rpc)
>    这样再试试看。
> 
> 另外，那个被插入的内容好像是广告拦截插件干的

是的，http://192.168.0.233:9091/web/rpc就可以了，谢谢。之前试过http://192.168.0.233:9091/web/。
这个好像是当时tr的一键包的问题，一直没管他。

**Comment by EthanLeen** [comment]
@wyl219 [看到最后发现和你是相同的问题，那最后的解决办法是什么？服务器地址填写如下：2、3浏览器是可以返回Tr界面，但是测试一直不能通过，提示参数错误。
![image](https://user-images.githubusercontent.com/29567348/57446757-09614880-7288-11e9-9032-68f6a5900e82.png)
![image](https://user-images.githubusercontent.com/29567348/57446867-4b8a8a00-7288-11e9-80df-8cf5c026ac64.png)

**Comment by chenyz1984** [comment]
实测tr的汉化包会导致此插件连接服务器失败，但是却不影响tr-remote-gui客户端的使用。

**Comment by ted423** [comment]
@chenyz1984 哪来的汉化包...什么版本，什么系统.......

**Comment by Rhilip** [comment]
@chenyz1984 真有意思，讲的是ronggong写的webui吧。
然而webui和remote gui走的都是transmission的webapi，不可能存在一个有用一个没用的。

**Comment by 89clark** [comment]
![捕获1](https://user-images.githubusercontent.com/59367706/71624779-44e9c200-2c1f-11ea-8873-7c15e8082116.JPG)
![捕获2](https://user-images.githubusercontent.com/59367706/71624780-47e4b280-2c1f-11ea-81e9-3b51f2604508.JPG)

    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": "@@@@@@@@",
    "rpc-port": 9099,
    "rpc-url": "/transmission/",
    "rpc-username": "admin",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,

帮忙看看是什么错误，谢谢

**Comment by xzyinjun** [comment]
@89clark 地址最后加个/

**Comment by 89clark** [comment]
> @89clark 地址最后加个/

我在下载服务器 输入http://192.168.1.4:9099/ 加不加/都没用。。
