### ISSUE TITLE
修改猫站域名

### ISSUE THREAD

**Issue by mylovesaber** [ronggang/PT-Plugin-Plus#320]
- 猫站q群和tg群都发公告说12月初将使用新域名，原有域名去掉“.”并在原链接后添加“.com”

**Comment by u0n179** [comment]
+1
pter.club--->pterclub.com

**Comment by YXHTom** [comment]
+1

**Comment by ted423** [comment]
@YXHTom 可以close了已经

**Comment by Rhilip** [comment]
受不了这个站的小白了，先把这个issue开了。等release了再关
