### ISSUE TITLE
备份恢复未恢复数据

### ISSUE THREAD

**Issue by zaw007** [ronggang/PT-Plugin-Plus#323]
- PT 助手版本:v1.4.2
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：360极速浏览器（chromium 69.0.3497.100）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：不正常
- 问题描述：
在一台电脑上备份了，然后再另外一台电脑上恢复，数据未恢复

- 相关截图：

- 重现步骤：
1.在A电脑浏览器上使用OWSS备份一次
2.在B电脑浏览器上使用OWSS恢复最新的版本
3.提示参数已恢复，刷新之后查看站点等数据，均未恢复到最新版本，仍然显示为原来的数据
4.去OWSS服务器上将备份包下载下来
5.在B电脑浏览器上使用恢复，选择刚下载的备份包，情况与之前相同，仍然显示为原来的数据
6.打开备份包，查看json数据，确认为最新的数据，并且数据完整

**Comment by luckiestone** [comment]
备份后有刷新一下插件页面吗？

**Comment by zaw007** [comment]
> 备份后有刷新一下插件页面吗？

原因找到了，恢复的浏览器设置了密匙，备份的浏览器没设置，所有失败了，建议恢复时密匙出错，给个提醒或者写个错误日志

**Comment by ronggang** [comment]
> > 备份后有刷新一下插件页面吗？
> 
> 原因找到了，恢复的浏览器设置了密匙，备份的浏览器没设置，所有失败了，建议恢复时密匙出错，给个提醒或者写个错误日志

正常情况，密钥错误时，会弹出一个让你输入正常密钥的对话框，查看是否弹出框被禁止了？

**Comment by zaw007** [comment]
> > > 备份后有刷新一下插件页面吗？
> > 
> > 
> > 原因找到了，恢复的浏览器设置了密匙，备份的浏览器没设置，所有失败了，建议恢复时密匙出错，给个提醒或者写个错误日志
> 
> 正常情况，密钥错误时，会弹出一个让你输入正常密钥的对话框，查看是否弹出框被禁止了？

之前确实没有弹出任何对话框，今天我重新测试了一次，有对话框了
