### ISSUE TITLE
HDChina搜索发生错误

### ISSUE THREAD

**Issue by VaeGreen** [ronggang/PT-Plugin-Plus#326]
- PT 助手版本: v1.4.2
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome Version 77.0.3865.120 & Microsoft Edge Version 79.0.309.25 (Official build) beta (64-bit)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：搜索种子HDChina报错：发生网络或其他错误

- 相关截图：
![image](https://user-images.githubusercontent.com/22101261/69202764-89dcfc00-0b7d-11ea-80ea-3b14f368befd.png)

- 重现步骤：
在豆瓣电影详情页右侧小部件直接搜索，或在插件内搜索框直接搜索，均会出现

**Comment by ted423** [comment]
@VaeGreen 无法再现，有登陆么？能否正常在网站内搜索》

**Comment by VaeGreen** [comment]
@ted423 登陆了，在PT站内搜索没问题

**Comment by VaeGreen** [comment]
@ted423 发现部分影片会触发，如海上钢琴师

**Comment by ted423** [comment]
@VaeGreen

**Comment by VaeGreen** [comment]
![image](https://user-images.githubusercontent.com/22101261/69205597-6322c380-0b85-11ea-8224-160ad06fa913.png)
这就很奇怪了 @ted423

**Comment by cnberg** [comment]
同样的问题

**Comment by ted423** [comment]
是否尝试清理cookies重登录再试过？
