### ISSUE TITLE
HDU魔力值统计异常

### ISSUE THREAD

**Issue by lu2fy** [ronggang/PT-Plugin-Plus#330]
- PT 助手版本:1.4.3
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：chrome 78
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

自从1.4.0版本“修复 HDU 魔力值获取异常的Bug”之后，HDU魔力值统计一直为0
回退到1.3.3版本魔力值统计正常

- 相关截图：
![image](https://user-images.githubusercontent.com/56574639/69432695-2c130480-0d75-11ea-941e-29ac72fe3688.png)
![image](https://user-images.githubusercontent.com/56574639/69432733-3c2ae400-0d75-11ea-8501-d63595941b01.png)

- 重现步骤：
更新至1.4.0-1.4.3版本，刷新HDU个人数据

**Comment by ronggang** [comment]
@lu2fy 没号无法验证，有 `HDU` 的同学试一下看看。

**Comment by ted423** [comment]
> @lu2fy 没号无法验证，有 `HDU` 的同学试一下看看。

![image](https://user-images.githubusercontent.com/7042766/69435813-3d5f0f80-0d7b-11ea-9f79-523bd524abed.png)
看来是的

**Comment by ted423** [comment]
@ted423 试了下，删掉filter就好了

**Comment by ronggang** [comment]
> @ted423 试了下，删掉filter就好了

不能简单的删除filter，如果删除了，就又回到原来的问题了#122 。
还得重新调整一下过滤器。

**Comment by ted423** [comment]
> > @ted423 试了下，删掉filter就好了
> 
> 不能简单的删除filter，如果删除了，就又回到原来的问题了#122 。
> 还得重新调整一下过滤器。

 没看懂为啥会出现......我太菜了
