### ISSUE TITLE
jpop搜索出现问题

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#331]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
搜索字词为
Eunjung DESIRE ，直接报错，网页搜索为一条数据
搜索字词为
Eunjung D 出现两条结果，网页搜索有6条数据，并且无Eunjung DESIRE (网页搜索中有)
- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
应该是分组的内容没包含。
