### ISSUE TITLE
ipt搜索结果不全

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#332]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
[REQ]Better Call Saul S01 2160p WEB-DL DTS x265-TrollUHD
这个种子搜索better call saul 搜不到，但是会显示50条结果出来，页面内搜索似乎是14页结果

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
参考wiki：
https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%AE%BE%E7%BD%AE%E4%BA%86%E6%AF%8F%E7%AB%99%E8%BF%94%E5%9B%9E-100-%E6%9D%A1%E4%BD%86%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E5%8F%AA%E8%BF%94%E5%9B%9E-50-%E6%9D%A1

**Comment by ted423** [comment]
> 参考wiki：
> https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#%E4%B8%BA%E4%BB%80%E4%B9%88%E8%AE%BE%E7%BD%AE%E4%BA%86%E6%AF%8F%E7%AB%99%E8%BF%94%E5%9B%9E-100-%E6%9D%A1%E4%BD%86%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E5%8F%AA%E8%BF%94%E5%9B%9E-50-%E6%9D%A1

Sorry
