### ISSUE TITLE
PuTao 做种体积和数量无法获取

### ISSUE THREAD

**Issue by zhuhongbojie** [ronggang/PT-Plugin-Plus#333]
- PT 助手版本:  1.3.3
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否

- 问题描述：
pt.sjtu.edu.cn无法获得做种体积的数据，上传下载和积分的数据正常显示
个人等级为User

- 相关截图：
https://i.loli.net/2019/11/25/iNonqakDfr6Kwpz.png

- 重现步骤：

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/297 and fixed in v1.4.2
