### ISSUE TITLE
增加手动一键签到，或者自动签到功能

### ISSUE THREAD

**Issue by chenyz1984** [ronggang/PT-Plugin-Plus#334]
## 您的功能请求是否与问题有关？ 请描述一下。

与问题无关

## 描述你想要的解决方案

增加手动一键签到，或者自动签到功能

**Comment by ted423** [comment]
@chenyz1984 以前讨论过不添加了

**Comment by tongyifan** [comment]
dupe: #13

**Comment by ronggang** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%8A%A9%E6%89%8B%E6%B2%A1%E6%9C%89%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%88%B0%E5%8A%9F%E8%83%BD
