### ISSUE TITLE
NPUbits无法搜索

### ISSUE THREAD

**Issue by relic5064** [ronggang/PT-Plugin-Plus#336]
- PT 助手版本: V.1.4.4
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Firefox 70.0.1 (64 位)
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：-
- 问题描述：
搜索时显示：**[NPUBits]没有定位到种子列表，或没有相关的种子**。
NPUBits(npupt.com)可以正常访问，插件也可以正常获取个人账号信息。
没有调整过搜索设置，其他网站可以正常搜索。

- 相关截图：

- 重现步骤：
搜啥都行……

**Comment by Rhilip** [comment]
v1.3.3 能复现，应该是merge深层配置的时候出问题了。

按照config.json的写法，应该调用站点配置的parse脚本，但是从实际后台运行截图来看，调用了schema的parse脚本。
另外 `没有定位到种子列表，或没有相关的种子` 也只有在NexusPHP的解析脚本中存在，NPU的解析脚本中并没有该提示。

https://github.com/ronggang/PT-Plugin-Plus/blob/4ae9ace8880bde5b9b5b137d39bf5a5bc33357d3/resource/sites/npupt.com/config.json#L17

![image](https://user-images.githubusercontent.com/13842140/69899580-5c752700-13a3-11ea-9643-0d43e28eb495.png)

**Comment by 873314461** [comment]
我也遇到了这个问题，版本是1.4.5，北邮人、北洋园都正常，只有蒲公英没法搜索种子，提示“[NPUBits]没有定位到种子列表，或没有相关的种子。”

**Comment by xfl03** [comment]
@Rhilip 已修复，希望可以关闭
https://github.com/ronggang/PT-Plugin-Plus/pull/374
