### ISSUE TITLE
希望增加搜索列表禁转标签的支持

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#339]
## 您的功能请求是否与问题有关？ 请描述一下。

感觉这个还蛮重要的

**Comment by ronggang** [comment]
关于自定义标签的形式暂时性这样处理，以后可能会把各站通用的标签颜色统一（如：`Free`，`2xFree` ，`禁转` 等），各站的 `config.json` 文件不再定义颜色；目前看起来有点冗余。😅
