### ISSUE TITLE
功能建议：增加 评分，类型，内容 等信息

### ISSUE THREAD

**Issue by willie91** [ronggang/PT-Plugin-Plus#34]
从我个人下片的习惯给出首页最新种子的功能建议
1. 先看评分，烂片一般也没人看。
2. 再看类型，偏爱科幻，不看爱情类。
3. 再看内容，就是电影描述，片子说了啥。

根据以上我个人觉得首页的最新种子，最好能打上来自豆瓣，IMDB的评分，其次是抓取页面描述，基本上都有写明类型，接着点击种子非链接区域弹出内容描述就最好了（可以参考下RSS订阅）

最后如果能后台运行自定义时间自动刷新资源再按照这些信息进行自定义推送(比如豆瓣7分科幻片)就更好了，毕竟不可能时不时刷新看更新了什么。

现在这个插件最大的意义可能是聚合搜索下载了，首页更新种子我基本上不会用，因为有用的信息太少，只有一个片名，没有心思点进去看评分，看内容，因为我本身就订阅了官方的rss更新。

这只是我个人对这个插件的愿景，如果可以的话，请作者多多考虑我的建议，谢谢，祝好。

**Comment by Rhilip** [comment]
不是很现实，各站的解析模板很不一致，人能直接觉得在一起的东西，解析起来不一定简单。更何况本插件需要适配多种不同的PT架构。
本插件就是 `主要用于辅助下载 PT 站的种子` 这样的用途呀。。。。。

**Comment by willie91** [comment]
> 不是很现实，各站的解析模板很不一致，人能直接觉得在一起的东西，解析起来不一定简单。更何况本插件需要适配多种不同的PT架构。
> 本插件就是 `主要用于辅助下载 PT 站的种子` 这样的用途呀。。。。。

是的,只是自己的一个想法,能做到当然好,做不了话也没关系,现在的聚合搜索还是很好用的,还是感谢你做出了这个插件

**Comment by ronggang** [comment]
@willie91 想法是好的，只是像 @Rhilip 说的做起来的确不容易。
关于评分的问题会考虑的，我个人找电影资源也和你的习惯差不多，另一种就是有目的性的找。
只是当前先把搜索功能做稳定之后再考虑其他。

**Comment by Rhilip** [comment]
v1.0.5 以及 v1.0.7 已增加 IMDb以及豆瓣信息。
