### ISSUE TITLE
增加站点公开注册或周年活动之类的消息推送

### ISSUE THREAD

**Issue by chenyz1984** [ronggang/PT-Plugin-Plus#340]
## 您的功能请求是否与问题有关？ 请描述一下。

增加站点公开注册或周年活动之类的消息推送

## 描述你想要的解决方案

增加一个消息盒子的功能，里边可以收集各个站点推广活动、公开注册、新站点等各类信息的推送。

**Comment by ted423** [comment]
@chenyz1984 谁来推送?R酱么...

**Comment by ronggang** [comment]
抱歉，做不了。
