### ISSUE TITLE
一键签到不再显示不起作用

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#341]
- PT 助手版本: 1.4.4
- PT 助手安装方式：crx安装 
- 浏览器名称及版本：cent browser
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
重启浏览器后一键签到按钮又回来了
测试Firefox正常

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
试了下，Cent Browser 4.0.9.112 无法复现

**Comment by ted423** [comment]
> 试了下，Cent Browser 4.0.9.112 无法复现

试了下，删掉重装又好了.....等我研究一下怎么复现

**Comment by ted423** [comment]
结果第二天它又冒出来了............................

**Comment by ronggang** [comment]
状态存于 localStorage ，如果这里被清除了就会又显示出来。

**Comment by ted423** [comment]
@ronggang 🙈这个我没动过啊，两台电脑貌似都是第二天冒出来

**Comment by ronggang** [comment]
> @ronggang 🙈这个我没动过啊，两台电脑貌似都是第二天冒出来

是否有可能浏览器同步配置不一致？

**Comment by ted423** [comment]
> > @ronggang 🙈这个我没动过啊，两台电脑貌似都是第二天冒出来
> 
> 是否有可能浏览器同步配置不一致？

咋说呢，我这是到了第二天就变成关浏览器再重开就会出现.
不确定是不是导入之前备份导致的
