### ISSUE TITLE
PTer网址换了，希望更新一下

### ISSUE THREAD

**Issue by rapon233** [ronggang/PT-Plugin-Plus#342]
- PT 助手版本:1.4.4
- PT 助手安装方式：（市场安装，或zip包安装）firefox
- 浏览器名称及版本：firefox
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
pter.club弃用了，换了新网址，希望助手更新一下，我试了无法编辑，只能手动新建一个

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@rapon233 发issue前建议先看下commit，以及搜索下其他issue🙈

**Comment by rapon233** [comment]
open 的issue里没有啊，只是提醒一下，如果有更新了就关闭issue吧

**Comment by Rhilip** [comment]
@rapon233 dupes： #320 #338

**Comment by ronggang** [comment]
新域名已更新待发布。目前可使用CDN功能。
不过，站点页面有改动，搜索功能无法使用。
