### ISSUE TITLE
功能请求：一键辅种

### ISSUE THREAD

**Issue by lazyrm** [ronggang/PT-Plugin-Plus#343]
## 描述你想要的解决方案

现在很多站点都是提供一样的种子，那一个站点的种子下载完成之后，希望其他的站点也能做到辅种，目前辅助都是下载完成之后，人工筛选一样的种子进行辅种，希望能做到一键辅种

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/217 https://github.com/ronggang/PT-Plugin-Plus/issues/237 https://github.com/ronggang/PT-Plugin-Plus/issues/238
