### ISSUE TITLE
HDCHINA获取不到魔力值

### ISSUE THREAD

**Issue by lu2fy** [ronggang/PT-Plugin-Plus#344]
- PT 助手版本:1.4.4
- PT 助手安装方式：（市场安装，或zip包安装）zip包
- 浏览器名称及版本：chrome 78
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
我的数据界面获取不到HDCHINA的魔力值，数据图表界面切换到HDCHINA站无法切换，仍显示所有站点的数据

- 相关截图：

![image](https://user-images.githubusercontent.com/56574639/69963512-502bce00-154b-11ea-9227-4aaa879d1a93.png)
![image](https://user-images.githubusercontent.com/56574639/69963604-80736c80-154b-11ea-9864-48eecc0cde32.png)

- 重现步骤：

刷新HDCHINA数据

**Comment by ted423** [comment]
我这正常，有尝试删除重新添加么？

**Comment by Rhilip** [comment]
你在站点的界面语言是简中吗？

**Comment by ted423** [comment]
@Rhilip 我的是

**Comment by lu2fy** [comment]
> 你在站点的界面语言是简中吗？

之前是简中，今天不知道怎么回事自动变成英文了，改回简中就好了。谢谢。
