### ISSUE TITLE
[功能请求]非关键词形式的搜索筛选功能 

### ISSUE THREAD

**Issue by Mosney** [ronggang/PT-Plugin-Plus#346]
## 您的功能请求是否与问题有关？ 请描述一下。

需求是筛选出最近热门种子，
例如筛选出MT成人区 `最近7天` 或者 `前10页` 中 `完成数超过400` 的种子。

大部分站点搜索箱自带的排序功能不支持时间范围，只能整个板块的种子一起排序。

## 描述你想要的解决方案

添加以非关键词形式的搜索功能， 
- 指定搜索站点、板块（已有） 
- 选择时间范围`或`前N页`或`第n页到第m页（后者似乎实现起来更简单）
- 指定其他筛选条件（如：`完成数` `做种数` `体积`  大于或小于X）
## 描述您考虑过的替代方案

如上例中筛选MT成人区热门种子除了人肉手动筛选之外似乎没有好办法。

**Comment by ronggang** [comment]
- 按时间筛选除了站点本身提供接口外，在前端不合适。（爬虫除外）
- 其他方式筛选其实也要基于站点原数据进行筛选，如果每次分页请求，感觉也不太合适，如果缓存站点数据也不合适。

**Comment by Mosney** [comment]
限制分页数，设定个比较低的阈值（例如10页）感觉没啥不合适的啊，也不会浪费太多站点资源

**Comment by ted423** [comment]
> 限制分页数，设定个比较低的阈值（例如10页）感觉没啥不合适的啊，也不会浪费太多站点资源

我觉得这种已经变成定制化开发了
