### ISSUE TITLE
HDU搜索置顶资源不显示大小

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#347]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

附上当时测试

㊎㊍㊌㊋㊏, [01.12.19 22:42]
仔细看看....上传下载数貌似也错位了🙈

㊎㊍㊌㊋㊏, [01.12.19 22:58]

![image](https://user-images.githubusercontent.com/7042766/70052835-220fc200-160f-11ea-99ee-a9468c46fde2.png)

@ronggang 看起来是cells里多了几个数据🙈

㊎㊍㊌㊋㊏, [01.12.19 22:58]
![image](https://user-images.githubusercontent.com/7042766/70052860-2c31c080-160f-11ea-9ebe-715022d123a3.png)
后面的就只有9个了

㊎㊍㊌㊋㊏, [01.12.19 23:13]

![image](https://user-images.githubusercontent.com/7042766/70052877-33f16500-160f-11ea-98aa-2ca86057f037.png)

其实我也搞不是很懂，超出我的能力范围了....rows里看起来是9个cell,然后跑let cells = row.find(">td");就跑出好多个cells,然后就出问题了....但不知道为啥后面的数据看起来差不多又不会出问题.......等大佬看好了🙈

- 重现步骤：

**Comment by Rhilip** [comment]
@ted423 问题应该处在这个站置顶的种子都有相同的id属性，把id属性删掉就没问题了，但是否值得这么做还待讨论
Patch如下：

patch
Index: resource/schemas/NexusPHP/getSearchResult.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- resource/schemas/NexusPHP/getSearchResult.js  (revision 1c6779adbf1e32bd9c7a7b58047f577ca5f56435)
+++ resource/schemas/NexusPHP/getSearchResult.js  (date 1575380846477)
@@ -150,6 +150,8 @@
         // 遍历数据行
         for (let index = beginRowIndex; index < rows.length; index++) {
           const row = rows.eq(index);
+          row.removeAttr('id');
+          
           let cells = row.find(">td");
 
           let title = this.getTitle(row);

**Comment by ronggang** [comment]
用 id 来做样式，当年我也干过。🤣
