### ISSUE TITLE
www.torrentleech.org 发生网络或其他错误

### ISSUE THREAD

**Issue by Wickyan** [ronggang/PT-Plugin-Plus#349]
- PT 助手版本:版本 v1.3.3 
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Google Chrome 78.0.3904.108
- 浏览器是否安装了其他插件：(不涉及该项)
- 停用其他插件后是否正常工作：(不涉及该项)
- 问题描述：

  站点设置一切正常，其他站点能正常检索，torrentleech能够正常访问

- 重现步骤：

**Comment by ted423** [comment]
@Wickyan 使用下最新版试试呢？

**Comment by Rhilip** [comment]
无法重现
