### ISSUE TITLE
希望页面上的一键下载可以显示多个文件夹路径

### ISSUE THREAD

**Issue by willie91** [ronggang/PT-Plugin-Plus#35]
![image](https://user-images.githubusercontent.com/32695308/53004119-77595900-346b-11e9-8d04-a1bee45a4b07.png)

目前只有一个默认的路径,希望能直接显示我添加的几个文件夹路径,这样可以更方便的下载到指定文件夹,虽然右键种子文件也可以,但步骤还是有点多了.

谢谢

**Comment by ronggang** [comment]
已在 https://github.com/ronggang/PT-Plugin-Plus/releases/tag/v1.0.2 上添加
