### ISSUE TITLE
欧派(oppaitime)无法正常检索用户数据

### ISSUE THREAD

**Issue by wisdomfox** [ronggang/PT-Plugin-Plus#353]
- PT 助手版本 v1.3.3:
- PT 助手安装方式：市场安装
- 浏览器名称及版本 ：78.0.3904.108(正式版本)(64 位)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：否
- 问题描述：
其他站点可以正常检索用户下载上传以及做种体积和入站时间，
但欧派(oppaitime)只能获取用户组信息其他信息均不可获取。

- 相关截图：
![image](https://user-images.githubusercontent.com/18511924/70400393-da9d9180-1a65-11ea-8a70-0ebc360d8a9d.png)

- 重现步骤：

**Comment by ted423** [comment]
看了下，site里只有最基本得信息，可以说是未作具体得适配

**Comment by ted423** [comment]
貌似要切GazelleJSONAPI 捂脸

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/pull/355
