### ISSUE TITLE
猫站PTer换网址后，自定义站点多功能失效。

### ISSUE THREAD

**Issue by chujionglie** [ronggang/PT-Plugin-Plus#354]
- 站点名称：PTerClub
- 站点地址：https://pterclub.com，原地址为https://pter.club
- 站点描述：猫站，PT之友俱乐部

- 资源类型：影视、音乐、游戏等
- 开放注册：否
- 是否连坐：是
- 站点规则：

**-存在的问题：助手无法获取做种体积、积分/魔力值，且无法搜索。**

**Comment by ted423** [comment]
@chujionglie 该问题已修复但还没发布…

**Comment by Rhilip** [comment]
dupe: #320
