### ISSUE TITLE
选中文字后通过右键菜单搜索相关种子时，选中文字没有填入搜索框

### ISSUE THREAD

**Issue by lanting** [ronggang/PT-Plugin-Plus#358]
- PT 助手版本:1.4.5
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：UC浏览器 6.2.4098.3
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
选中文字后通过右键菜单搜索相关种子时，选中文字没有填入搜索框，这样搜索框内容与下面的搜索结果不一致，看起来不太直观，想修改搜索内容时需要重新输入也不太方便。

- 相关截图：
![1](https://user-images.githubusercontent.com/5037002/70603504-a8408f80-1c31-11ea-9011-fb0094d64e10.jpg)
![2](https://user-images.githubusercontent.com/5037002/70603515-af679d80-1c31-11ea-9f84-ee6a7ce6ba6b.png)

- 重现步骤：
1、在网页中选中“阿甘正传”文字，点鼠标右键弹出菜单——“PT Plugin Plus”——“搜索“阿甘正传”相关的种子“。
2、浏览器自动打开”PT Plugin Plus“插件主界面并进行搜索显示搜索结果，但是此时插件顶部的搜索框显示的还是之前输入的搜索内容，并没有将”阿甘正传“填入搜索框。这样搜索框内容和下面的搜索结果不匹配。如果想对搜索内容进行修正，只能在搜索框重新输入。

**Comment by ted423** [comment]
截图有么？
电脑端还是手机端？

**Comment by lanting** [comment]
电脑端，右键菜单没法截图，一动键盘或鼠标进行截图时，右键菜单就关闭了。

很容易重现，随便一个网页选中几个文字点鼠标右键弹出菜单——“PT Plugin Plus”——“搜索“选中文字”相关的种子“。出来的插件主界面并没有把搜索文字填入搜索框，还是之前的内容。

**Comment by ted423** [comment]
> 电脑端，右键菜单没法截图，一动键盘或鼠标进行截图时，右键菜单就关闭了。
> 
> 很容易重现，随便一个网页选中几个文字点鼠标右键弹出菜单——“PT Plugin Plus”——“搜索“选中文字”相关的种子“。出来的插件主界面并没有把搜索文字填入搜索框，还是之前的内容。

我没注意看，这种时候直接改地址栏 回车 然后 f5刷新就好

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/70601192-80026200-1c2c-11ea-8a73-afe8c211bff9.png)
论greenshot得必要性

**Comment by lanting** [comment]
谢谢提醒，已经截好图了。可是又来了新问题……截图传不上来，拖放、复制粘贴、选择上传三种方式都试过了，浏览器兼容/极速模式切换试过了，用代理上网也试了……都不行。

**Comment by ted423** [comment]
@lanting 没事，这个问题我这也是这样。总之，你按我说的url里改就好

**Comment by lanting** [comment]
搞定，截图用WIN10自带的浏览器传上来了。我这边不用代理的话，截图都显示X号，必须用代理才能显示图片。

这个插件用起来实在是方便，爱不释手，相见恨晚……

**Comment by ronggang** [comment]
现在的确是这样的，可以考虑更新为最后搜索的关键字。

**Comment by lanting** [comment]
被作者大人钦点，荣幸之至^-^

谢谢辛苦开发了这么好的插件，非常感谢。
