### ISSUE TITLE
一键下载后进度提示条不正常

### ISSUE THREAD

**Issue by lanting** [ronggang/PT-Plugin-Plus#359]
- PT 助手版本:1.4.5
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：UC浏览器 6.2.4098.3
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
一键下载后进度提示条不正常，出现红色（内容为undefined）的进度提示条，蓝色（内容为：正在发送链接到服务器，请稍候……）进度提示条在添加完成后还一直显示。

- 相关截图：
1、一键下载：出现两个进度提示条，蓝色（内容为：正在发送链接到服务器，请稍候……），红色（内容为：undefined）。
![1](https://user-images.githubusercontent.com/5037002/70761810-780c0480-1d89-11ea-8fdf-195b0bf3c4c7.png)

2、种子已添加完成，出现绿色进度提示条，红色undefined已自动消失，蓝色存在。
![2](https://user-images.githubusercontent.com/5037002/70761815-7c382200-1d89-11ea-84ea-74cb7cb40689.png)

3、绿色种子已添加完成自动消失。蓝色还是存在。
![3](https://user-images.githubusercontent.com/5037002/70761819-80643f80-1d89-11ea-9fd1-68b55804a1be.png)

- 重现步骤：
1、打开PT电影种子页面，点击PT Plugin Plus工具条中的“一键下载”进行下载。
2、出现提示条（详见上面按步骤截图），多个PT网站下载都是相同的问题。
3、红色undefined不知道具体原因，建议提示详细错误信息供用户排查。
4、种子添加完成后，建议保留“种子已添加完成”的绿色进度条，不要自动关闭。因为在点了一键下载后，用户可能去浏览别的页面去了，回来看这个页面时绿色进度条已自动关闭，不容易知道结果。
5、种子添加完成后，建议自动关闭“正在发送链接到服务器，请稍候……”的蓝色进度条，只保留绿色完成进度条即可。
6、经常出现点一键下载后，即没有提示添加完成的绿色进度条，也没有提示错误信息，群晖DownloadStation中也没有添加成功。建议如果超时没有收到正常添加完成的反馈，给用户提示详细错误信息供用户排查。

**Comment by ted423** [comment]
@lanting 这种就是添加失败，而你需要检查的是你的发送的连接对不对

**Comment by Rhilip** [comment]
您都可以通过该 [wiki](https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page) 说明进行错误排查

**Comment by ted423** [comment]
再具体点就是你要说明，哪个站会红色并且什么页面操作，是否这个站点所有都会

**Comment by lanting** [comment]
1、出现红色undefined之后，也会出现提示已添加完成的绿色进度提示条，DownloadStation也已把种子添加进来了。
2、所有PT站点一键下载时都会出现红色提示。
3、按 @Rhilip 的提示进行错误排查，看到savePath参数为undefined：
![批注 2019-12-13 095610](https://user-images.githubusercontent.com/5037002/70763536-5d3c8e80-1d8f-11ea-9d26-479edfc15efb.png)
但是我已经设置好了DownloadStation的下载路径：
![image](https://user-images.githubusercontent.com/5037002/70763658-cfad6e80-1d8f-11ea-990a-829912b89c0e.png)
只是没有在站点设置中指定下载服务器，因为有提示：（如不选择则以基本设置的默认下载服务器为准），理论上不设置也是可以的。（又试了一下，设置下载服务器后也还是上面同样的问题）
![image](https://user-images.githubusercontent.com/5037002/70763772-40ed2180-1d90-11ea-8cd8-2bc55491e064.png)

**Comment by ronggang** [comment]
@lanting 建议更改 passkey，图中已泄漏。
仔细看了一下问题描述，应该是页面脚本执行过程中出现了异常。可以在种子页面按 F12 进行排查，应该会有错误。
按正常逻辑，那个蓝色的进度条会在成功或失败后自动消失，你的情况是未消失，猜测应该是哪里出错了。

关于发送成功或失败后是否保留状态条，需要进一步讨论，通常如果只是下载一个种子文件，速度比较快，在一秒内就可以完成，所以结果立即可见，如果再去手工点击关闭会显得有些多余。
如果是长时间未能下载完成，而转到其他页面去操作了，这种情况可考虑启用后台下载通知的形式，下载完成后无论成功与否，会以系统通知的形式提醒。

**Comment by ted423** [comment]
遮了一个，漏了另外一个..

**Comment by lanting** [comment]
已修正截图。亡羊补牢，尚不为晚 -_-

按F12排查，在console和network也没有提示错误。

我的可能发送种子到下载服务器比较慢（3~5秒，非局域网），所以会比较敏感，如果快的话也无所谓了。

**Comment by ronggang** [comment]
> 已修正截图。亡羊补牢，尚不为晚 -_-
> 
> 按F12排查，在console和network也没有提示错误。
> 
> 我的可能发送种子到下载服务器比较慢（3~5秒，非局域网），所以会比较敏感，如果快的话也无所谓了。

图片地址已生成并在TG一直存在，补不了了 😅，还是改了吧。

**Comment by lanting** [comment]
嗯嗯，再次亡羊补牢 -_-

**Comment by ronggang** [comment]
其实我比较好奇的是你那个蓝色的进度条没有消失，而且你说按 F12 出来之后也没有报错。
正常操作是有反馈的，像这样：
![PT-Plugin-Plus-使用动画 (2)](https://user-images.githubusercontent.com/8065899/70777770-92f76c80-1dbb-11ea-8610-962a363c2797.gif)

**Comment by lanting** [comment]
又用360浏览器试了一下，把UC浏览器的插件参数导入进来，一键下载正常了，和上面的截图一致。说明很可能是UC浏览器的问题。

而且新版本提供的CRX格式在UC浏览器上安装不上，提示程序包无效：“CRX_VERSION_NUMBER_INVALID”，在360浏览器上可以正常安装使用。

**Comment by Rhilip** [comment]
能否告知下uc浏览器所使用的内核版本？

**Comment by lanting** [comment]
![微信截图_20191216083923](https://user-images.githubusercontent.com/5037002/70872018-d4686180-1fdf-11ea-984e-d0191834ec11.png)

**Comment by ronggang** [comment]
@lanting 内核有点低，目前打包的crx是v3的。
刚去官网看了下，找不到PC版的应用可供下载，应该是不维护了，尽早转移吧。

**Comment by lanting** [comment]
确实如此，谢谢提醒，马上转移。
