### ISSUE TITLE
插件能否做成油猴脚本呢

### ISSUE THREAD

**Issue by 1990chs** [ronggang/PT-Plugin-Plus#36]
用的遨游的浏览器，不支持chrome插件，想问一下能否做成油猴脚本呢？

**Comment by Rhilip** [comment]
估计是不能了。。。。。

**Comment by 1990chs** [comment]
@Rhilip 好吧！遨游用习惯了一直没有换，感觉要换浏览器了！

**Comment by Rhilip** [comment]
我忽然觉得现阶段可以考虑另起一个项目，使用油猴脚本（userscript）来部分实现目前PTPP的功能。
因为目前Chrome （#318） 和Firefox （#467） 的应用商店均下架插件  
但以现在插件所涉及的功能深度，不包括依赖文件（依赖以CDN的形式引入），估计编译出来的文件大小就快1M，另外就还需要一个静态网页的支持（可以使用gh-page）

**Comment by ted423** [comment]
> 我忽然觉得现阶段可以考虑另起一个项目，使用油猴脚本（userscript）来部分实现目前PTPP的功能。
> 因为目前Chrome （#318） 和Firefox （#467） 的应用商店均下架插件
> 但以现在插件所涉及的功能深度，不包括依赖文件（依赖以CDN的形式引入），估计编译出来的文件大小就快1M，另外就还需要一个静态网页的支持（可以使用gh-page）

比如说？不过个人想法，聚合搜索这块是大头，像工具栏和下载服务器这些，似乎附带就能实现。油猴的话，打开独立页面似乎很难实现吧？

**Comment by Rhilip** [comment]
> 比如说？不过个人想法，聚合搜索这块是大头，像工具栏和下载服务器这些，似乎附带就能实现。油猴的话，打开独立页面似乎很难实现吧？

目前再做可行性测试。
独立页面打算使用gh-page来静态托管，但是这样要求用户在访问该页面的时候才能进行管理，
插件现在的定时刷新用户数据有点麻烦，意味着用户脚本要求所有页面的访问权限，但也不是说不能做。

**Comment by Rhilip** [comment]
我其实觉得我测试失败了 https://github.com/Rhilip/PT-Manager
以后有人想要尝试用户脚本的话，可以继续接着测试。

1. 我想法是gh-page直接一个引导页，以方便用户安装；但是即使已经安装脚本的用户，在脚本未生效时仍可以见到短时引导页。
2. 最致命的也就是如果页面应用 由userscript构建的话（也**只能由userscript构建而不能由页面原生构建**），在测试 Element 的 NavMenu、Dropdown这种组件时，均会报错导致对应部分无法被成功渲染。
3. 而如果userscript中Vue通过 `Vue.$emit()`以及`Vue.$on()` 的形式与页面中Vue进行通信的话，又显得过于繁琐且难以管理。
