### ISSUE TITLE
馒头站希望支持下载IPV6种子

### ISSUE THREAD

**Issue by LoveU3th** [ronggang/PT-Plugin-Plus#361]
## 您的功能请求是否与问题有关？ 请描述一下。
目前国内许多是内网IPV4,公网IPV6，馒头站也支持IPV6。

## 描述你想要的解决方案
希望助手能支持IPV6下载。

## 描述您考虑过的替代方案
馒头站IPV6种子下载地址比IPV4后缀多了"IPV6=1"

**Comment by Rhilip** [comment]
我个人意见和该issue相同 https://github.com/tongyifan/Reseed-backend/issues/14
并不是所有站都支持该params，同样也并不是所有用户都需要使用该params
此外该站所谓v6的tracker在实际announce response和正常tracker一样，如果你是纯ipv6用户应该考虑在bt软件上做限制（ipfilter同时限制v4 tracker和v6 tracker）

**Comment by LoveU3th** [comment]
> 我个人意见和该issue相同 [tongyifan/Reseed-backend#14](https://github.com/tongyifan/Reseed-backend/issues/14)
> 并不是所有站都支持该params，同样也并不是所有用户都需要使用该params
> 此外该站所谓v6的tracker在实际announce response和正常tracker一样，如果你是纯ipv6用户应该考虑在bt软件上做限制（ipfilter同时限制v4 tracker和v4 peer）

只是个人觉得可以有这个params，不一定默认打开，可以在需要的时候打开，毕竟PT站支持IPV6应该是趋势。
再说到添加功能的难度，我不是专业开发者，可能不能很好的体会到其中的难度，如果添加参数很难就当我没有提出过吧。

**Comment by ted423** [comment]
@LoveU3th v6的tracker在实际announce response和正常tracker一样，整体来讲并不是开发难度的问题。我感觉是你对v6tracker的理解跟开发者有区别

**Comment by ronggang** [comment]
@LoveU3th 可考虑自定义插件的方式来处理，之前记得有人在哪里提过，所以当时以ipv6来举了例子：
https://github.com/ronggang/PT-Plugin-Plus/wiki/config-custom-plugin#%E7%A4%BA%E4%BE%8B

**Comment by LoveU3th** [comment]
@ronggang 测试了一下在单个种子界面可以成功一键发送到服务器下载，非常感谢作者大佬百忙之中抽出时间回复 ^_^

**Comment by LoveU3th** [comment]
@ted423 因为现在本地的联通也不给公网IP，只有IPV6公网可以用，所以特殊需求吧。我需要学的还很多，感谢回复^_^
