### ISSUE TITLE
馒头站开启二次认证后无法获得数据。

### ISSUE THREAD

**Issue by hhxx1** [ronggang/PT-Plugin-Plus#366]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@hhxx1 请自行打开页面看看为什么...

**Comment by Rhilip** [comment]
@hhxx1 该站二步验证页面可能因为浏览器，出口ip等诸多因素变动而出现。插件本身不影响用户访问信息。
此外，插件并不具备帮您自动填写二步验证的功能。如果你持续遇到该问题请考虑
1. 关闭二步验证；
2. 手动进行二步验证。
