### ISSUE TITLE
请求在种子详情页面添加搜索按钮

### ISSUE THREAD

**Issue by lanting** [ronggang/PT-Plugin-Plus#369]
## 您的功能请求是否与问题有关？ 请描述一下。

在种子详情页面可以很方便的通过一键下载推送种子到服务器，但是经常遇到虽然很喜欢该资源，只是当前种子不符合自己的需求（清晰度等），想要在所有PT网站中搜索同名资源，选择最佳种子进行下载。现在只能打开助手手动输入资源名称进行搜索同名资源，如果可以把资源名称传送到助手搜索框并进行搜索就好了。

## 描述你想要的解决方案

在种子详情页面的助手工具条最下面添加一个搜索按钮，该按钮的功能类似于豆瓣电影详情的搜索按钮，点击后把当前资源名称推送到助手搜索框，并自动进行搜索。

这样省去了：
1、复制当前资源名称。
2、打开助手，把当前资源名称粘贴填入搜索框。
3、点击搜索按钮

## 描述您考虑过的替代方案

和选中资源名称后，点右键菜单——“PT Plugin Plus”——“搜索“当前资源名称”相关的种子”功能完全相同，但是添加搜索按钮可以完全傻瓜化操作。这个功能经常使用，属于高频操作，非常希望能够添加，谢谢。

## 其他附加信息

![微信截图_20191223112800](https://user-images.githubusercontent.com/5037002/71334041-58d65980-2577-11ea-9bbe-12297fd8b06d.png)
![微信截图_20191223112649](https://user-images.githubusercontent.com/5037002/71334045-5e33a400-2577-11ea-8d10-c522ad76ceef.png)

**Comment by Rhilip** [comment]
和你已提到的 右键搜索过于功能重合，
或许你可以考虑使用 [自定义插件](https://github.com/ronggang/PT-Plugin-Plus/wiki/config-custom-plugin) 自己实现

**Comment by ronggang** [comment]
如果直接增加搜索按钮，搜索关键字会有所争议，因为需求不同，搜索的关键字也不同。
对就你目前的需求，可以尝试以下方法：
- 参考R酱的方法来试试；
- 选中需要搜索的关键字，按右键来搜索；
- 拖放 `IMDb` 或 `豆瓣` 链接到助手工具图标直接搜索；

**Comment by lanting** [comment]
有道理，插件的功能实在太强大了，谢谢两位回复。
