### ISSUE TITLE
下载目录设置问题

### ISSUE THREAD

**Issue by dumperk** [ronggang/PT-Plugin-Plus#37]
Chrome 版本 67.0.3396.79（正式版本） （64 位）
服务器:deluge1.3.15, transmission 2.94 ,内网.
1.下载目录设置后,全选某一个服务器的站点,删除可用后,点了无反应.只能点"操作"后边的删除图标来删除.
2.下载目录设置和服务器内设置一样的路径,deluge提示Permission denied,下载路径显示为空.下载种子添加可以.
3.下载目录设置和transmission的路径不同,提示让重新设置目录.transmission开始按照默认路径下载.
是哪里设置的不对吗?

**Comment by ronggang** [comment]
@dumperk 
感谢反馈，请问助手使用的是哪个版本？

1. 这是我的问题，多选删除按钮功能没加上去 :sweat_smile:
2. 这个你看看日志里有没有详细信息
3. 可否把设置的值粘上来我看一下，提示是在什么时间出现的？

**Comment by dumperk** [comment]
助手你发布的最新版本.firefox最新版安不上,安装在了chrome上.
下载目录设置格式是这样:
/volume1/disk1/
/volume2/disk2/
tr的下载目录当前是/volume1/disk1  
deluge的下载目录是/volume1/disk1
deluge种子发送过去了,但是路径是空的. tr的话,哪个在上面种子都会按照tr所设置的目录进行下载.
请问为什么要每个站点都要单独设置下载目录,有什么好处呢?像你发布的web control那样就很好用了,每次添加种子后, 有目录供选择或者手动输入. 
如果每个站点所设置的目录和客户端的目录不一致的话,按您的设计,种子能否正常添加到客户端的默认目录? 
日志过几天发给你看.
辛苦了,多谢!

**Comment by dumperk** [comment]
options | SearchTorrent.sendTorrentClient | 2019-02-24 23:13:41 | 发送种子到下载服务器
`{"clientId":"我的passkey******","savePath":"","title":"[逆流而上的你] Unbeatable You 2019 EP15-16 WEB-DL 1080p H264 AAC-BtsTV","url":"https://pt.btschool.net/download.php?id=8659&passkey=078c993f2ad2d7160105462a0855c3cc&https=1"}`

requestMessage.sendTorrentToClient | 2019-02-24 23:13:41
requestMessage.getTorrentDataFromURL | 2019-02-24 23:13:41
service.controller.doDownload.finished | 2019-02-24 23:13:41 | 下载服务器Deluge处理[addTorrentFromURL]命令完成
`{"error":null,"id":0,"msg":"URL已添加至 Deluge 。","result":"1df0664cd82af43af58a0920fa3599a09bb3a11a","status":"success"}`
SearchTorrent.sendTorrentToClient.Success | 2019-02-24 23:13:41 | 发送种子到下载服务器成功
`{"data":{"error":null,"id":0,"msg":"URL已添加至 Deluge 。","result":"1df0664cd82af43af58a0920fa3599a09bb3a11a","status":"success"},"msg":"种子已添加","success":true,"type":"success"}`

deluge显示
`Permission denied: /[逆流而上的你].Unbeatable.You.2019.EP15-16.WEB-DL.1080p.H264.AAC-BtsTV/[逆流而上的你].Unbeatable.You.2019.EP15.WEB-DL.1080p.H264.AAC-BtsTV.mp4`
好像是在根目录下创建目录,save path 并不像手动添加时显示的 /volume1/disk1目录

**Comment by ronggang** [comment]
@dumperk 我想你应该是使用的 Chrome 上的 1.0.0.14 版本，所以在搜索结果页下载还不能选择目录，1.0.0.16 及之后的版本已可以选择目录。所以请升级到 1.0.0.14 之后的版本再尝试一下。

关于每个站需要设置单独目录，是为了针对站点使用不同目录保存而设计，后面会考虑增加全局设置。

另外，你是用的 Google 翻译吗？

**Comment by dumperk** [comment]
我正在用的版本是1.0.0.18
没用翻译

**Comment by dumperk** [comment]
@ronggang 找到问题所在了,现在好啦.
设置完下载目录后,要关闭浏览器,重新加载插件后,才能生效.
昨天添加的目录,今天选择种子下载到服务器后出现两行.一行带有添加的目录.
刚才有添加了一个站点,填完目录后不出现.重启浏览器就出现了.是我没仔细看说明吗?^^ 不好意思啦

**Comment by dumperk** [comment]
Ppql
