### ISSUE TITLE
使用“所有站点”搜索会有个别站无法搜到

### ISSUE THREAD

**Issue by zlhdd108** [ronggang/PT-Plugin-Plus#370]
- PT 助手版本:v1.4.5
- PT 助手安装方式：crx安装（市场安装，或zip包安装）
- 浏览器名称及版本：opera 65.0.3467.62
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
在搜索方案中选择“所有站点”，但是有些站点无法正常搜索

- 相关截图：
![image](https://user-images.githubusercontent.com/16465666/71387827-b5497f80-2630-11ea-8be1-6f76ac2f8da7.png)

- 重现步骤：
直接搜索相应的电影名称，不选择对应的豆瓣链接

**Comment by ted423** [comment]
@zlhdd108 https://github.com/ronggang/PT-Plugin-Plus/issues/313

**Comment by zlhdd108** [comment]
> @zlhdd108 #313
> 我这能搜到，建议你再检查下你站点设置里搜索是怎么勾的

我说的是“使用‘所有站点’搜索”，这个选项跟自己的设置没有关系

**Comment by ronggang** [comment]
> > @zlhdd108 #313
> > 我这能搜到，建议你再检查下你站点设置里搜索是怎么勾的
> 
> 我说的是“使用‘所有站点’搜索”，这个选项跟自己的设置没有关系

有点关系，如果自定义了搜索方案，之前的版本存在Bug，会改变默认的搜索分类。
请到站点设置里看一下搜索设置是否勾选了你想要的类型，如以下图所示：
![image](https://user-images.githubusercontent.com/8065899/71795274-6a902480-3080-11ea-85b8-5a9823f355bf.png)

所以指定了类型，可能有些内容无法搜索到，请选择全部，保存后再重新搜索即可。

**Comment by zlhdd108** [comment]
> > > @zlhdd108 #313
> > > 我这能搜到，建议你再检查下你站点设置里搜索是怎么勾的
> > 
> > 
> > 我说的是“使用‘所有站点’搜索”，这个选项跟自己的设置没有关系
> 
> 有点关系，如果自定义了搜索方案，之前的版本存在Bug，会改变默认的搜索分类。
> 请到站点设置里看一下搜索设置是否勾选了你想要的类型，如以下图所示：
> ![image](https://user-images.githubusercontent.com/8065899/71795274-6a902480-3080-11ea-85b8-5a9823f355bf.png)
> 
> 所以指定了类型，可能有些内容无法搜索到，请选择全部，保存后再重新搜索即可。

![image](https://user-images.githubusercontent.com/16465666/71795415-0c177600-3081-11ea-8515-76c852e1c45b.png)
![image](https://user-images.githubusercontent.com/16465666/71795455-349f7000-3081-11ea-9d8a-f2f8ed59560d.png)
选择“全部”后，再使用“所有站点”搜索，依旧无法搜索到

**Comment by ronggang** [comment]
@zlhdd108 不是在搜索方案里改，是在 `站点设置` 里改。因为 `所有站点` 使用的是每个站点设置的默认分类。

**Comment by zlhdd108** [comment]
> @zlhdd108 不是在搜索方案里改，是在 `站点设置` 里改。因为 `所有站点` 使用的是每个站点设置的默认分类。

嗯，修改后正常了
