### ISSUE TITLE
BHD界面更新后部分数据无法拉取

### ISSUE THREAD

**Issue by 365962648** [ronggang/PT-Plugin-Plus#373]
- PT 助手版本:1.4.5
- PT 助手安装方式：zip包安装（市场安装，或zip包安装）
- 浏览器名称及版本：chrome 78.0.3904.108
- 浏览器是否安装了其他插件： 是
- 停用其他插件后是否正常工作： 否
- 问题描述：
BHD界面更新后，数据量以及做种信息无法正常拉取

- 相关截图：
![QQ截图20191226111126](https://user-images.githubusercontent.com/20415374/71455701-32abf600-27d1-11ea-9cb9-76b4d0a8b40c.jpg)

- 重现步骤：
无

**Comment by tongyifan** [comment]
似乎是可以close了，测试最新版正常（ fa6348569ed7c9ace2ae1e731e3fffcd2f481ce9 ）

@Rhilip
