### ISSUE TITLE
时间轴界面中隐藏指定站点

### ISSUE THREAD

**Issue by Aniverse** [ronggang/PT-Plugin-Plus#375]
## 您的功能请求是否与问题有关？ 请描述一下。

目前，在【我的信息】【时间轴】界面中会显示所有统计个人信息的站点。
举个例子，我现在有 ABCD 四个站，我在【站点设置】中都打开了【个人信息】，那么这四个站点都会在【时间轴】界面里显示。

如果我有展示我【时间轴】界面给其他人的需求，但是我不想告诉别人我有 D 这个站的账号，目前的做法是去【站点设置】关掉 D 站的【个人信息】。
但关掉 D 站的【个人信息】后，在【我的信息】界面也不会显示这个站的数据。
如果只有一个 D 站需要关闭的话，给别人展示【时间轴】时临时操作下也不是很麻烦，但如果我有很多站点，我只想自己在看【我的信息】里时能看到，在时间轴中不展示的话，开关操作较为繁琐

窃以为，【我的信息】界面里的数据展示主要是给自己看的，【时间轴】界面里的数据展示不仅给自己看，也可以用于分享。因此，【我的信息】里最好能够展示全部的数据，而【时间轴】里可以选择部分展示

## 描述你想要的解决方案

在【站点设置】里单独增加一个开关，这个开关控制是否在时间轴中显示本站点
在【时间轴】里也加一个开关，【显示全部站点】
当在【时间轴】打开【显示全部站点】时，那些在【站点设置】中选择不在时间轴中显示的站点也会显示，这种模式适合给用户自己看
当在【时间轴】关闭【显示全部站点】时，只显示那些在【站点设置】中设置为在时间轴中显示的站点，这种模式适合需要分享时间轴界面给其他人的场合

**Comment by ted423** [comment]
@Aniverse 站点设置里可以不获取用户信息，这样就不会展示

**Comment by Aniverse** [comment]
> @Aniverse 站点设置里可以不获取用户信息，这样就不会展示

这我知道。实际上我在我的 issue 里已经提到了这个解决办法，并指出了这个办法的不足之处

**Comment by Rhilip** [comment]
@Aniverse 感谢建议，技术上没有实现问题

**Comment by Rhilip** [comment]
偷了个懒，没有按照上面实现方案来实现。
因为我认为对于时间轴的变动（站点隐藏、显示）是属于生成（也可以说是分享）时候的配置，所以相关设置不应该放置在站点设置中。
于是我将其直接放在了时间轴生成页面，在生成时间轴的时候进行显示调整。默认情况下显示所有允许获取用户信息的站点，而用户可以在时间轴生成页面右侧手动进行调准，变更站点显示状态。
而且我认为这是一个临时性质的配置，所以也没有将其进行持久化存储。

**Comment by tainewoo** [comment]
建议:
user-data-timeline和statistic: 建议两个都增加选项,勾选选择显示哪一些站点不显示哪一些站点.

**Comment by Rhilip** [comment]
> @Rhilip
> 
> 建议:
> user-data-timeline和statistic: 建议两个都增加选项,勾选选择显示哪一些站点不显示哪一些站点.
> 
> 并且我觉得将每个的开关直接设置在user-data-timeline页面和statistic页面比较方便.
> 
> 当打算生成时间轴的时候,用户可以临时决定(默认)生成所有站点(当前方案),还是隐藏掉部分站点.
> 当查看统计数据的时候,用户可以临时决定(默认)查看所有站点sum之后的数据(当前方案),还是只查看部分或者某一个特别关心的站点的数据.

statistic页面相对不是那么好改，建议另开issue。本issue只涉及到 user-data-timeline 页面的修改，并已经在dev中构建完成。
