### ISSUE TITLE
transmission无法查看

### ISSUE THREAD

**Issue by 89clark** [ronggang/PT-Plugin-Plus#378]
- PT 助手版本:1.4.5
- PT 助手安装方式：本站谷歌插件安装（市场安装，或zip包安装）
- 浏览器名称及版本：谷歌浏览器79.0.3945.88
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：
- 问题描述：
transmission无法查看

- 相关截图：
![捕获1](https://user-images.githubusercontent.com/59367706/71587918-91b79500-2b5a-11ea-937d-8b5595fda416.JPG)
![捕获2](https://user-images.githubusercontent.com/59367706/71587920-97ad7600-2b5a-11ea-8c11-0c643e402108.JPG)

- 重现步骤：

**Comment by 89clark** [comment]
"rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": false,
    "rpc-password": 
    "rpc-port": 9099,
    "rpc-url": "/transmission/",
    "rpc-username": "admin",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,

**Comment by ted423** [comment]
建议检查下你用户名密码对了没

**Comment by 89clark** [comment]
> 建议检查下你用户名密码对了没

密码肯定正确

**Comment by ted423** [comment]
1. webui是否能正常打开。
2. 你的描述的issue是否跟ptpp有关

**Comment by ronggang** [comment]
@89clark 参考 @ted423 的方法用浏览器直接打开 `http://192.168.1.4:9099` ，看有何提示；
如果是 `transmission` 问题，请先解决 `transmission` 问题；
只要在浏览器里可以正常打开 `transmission` ，在助手里正确的地址、用户名、密码就可以正常链接。

**Comment by 89clark** [comment]
> @89clark 参考 @ted423 的方法用浏览器直接打开 `http://192.168.1.4:9099` ，看有何提示；
> 如果是 `transmission` 问题，请先解决 `transmission` 问题；
> 只要在浏览器里可以正常打开 `transmission` ，在助手里正确的地址、用户名、密码就可以正常链接。

你好，http://192.168.1.4:9099，可以正常打开transmission，但是PT 助手就是不能添加上去，提示就是我贴图的那些。

**Comment by ronggang** [comment]
@89clark 按 [wiki](https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page) 打开助手背景页，然后测试服务器连接，看一下服务器返回的结果。
正常情况下会有两条网络请求，第一条是 409，用于获取 `X-Transmission-Session-Id`，只要第二条正确即可，如下图所示：
![PT-Plugin-Plus-使用动画 (4)](https://user-images.githubusercontent.com/8065899/71656393-f8fd6100-2d75-11ea-8448-64667181d36b.gif)

**Comment by 89clark** [comment]
> @89clark 按 [wiki](https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page) 打开助手背景页，然后测试服务器连接，看一下服务器返回的结果。
> 正常情况下会有两条网络请求，第一条是 409，用于获取 `X-Transmission-Session-Id`，只要第二条正确即可，如下图所示：
> ![PT-Plugin-Plus-使用动画 (4)](https://user-images.githubusercontent.com/8065899/71656393-f8fd6100-2d75-11ea-8448-64667181d36b.gif)

我点击“城市服务器是否可连接” 提示“服务器可连接”然后就是下面的图
![12](https://user-images.githubusercontent.com/59367706/71658814-57c7d800-2d80-11ea-9b79-d895ec9713f5.JPG)
![13](https://user-images.githubusercontent.com/59367706/71658822-5b5b5f00-2d80-11ea-9d93-23d3f551b4e0.JPG)
![14](https://user-images.githubusercontent.com/59367706/71658830-5dbdb900-2d80-11ea-9def-1cafc5bc03d9.JPG)

**Comment by ronggang** [comment]
@89clark 服务器可连接就可以了啊，直接确认保存就行了，还有什么问题？

**Comment by 89clark** [comment]
> @89clark 服务器可连接就可以了啊，直接确认保存就行了，还有什么问题？

![11](https://user-images.githubusercontent.com/59367706/71715646-14876b00-2e4d-11ea-8178-206eeec2fb8a.JPG)

![12](https://user-images.githubusercontent.com/59367706/71715651-181af200-2e4d-11ea-978b-463022db00bf.JPG)

点击“刷新我的数据”就一直转圈圈，不出数据。

**Comment by ted423** [comment]
你加站点了么...?

**Comment by 89clark** [comment]
> 你加站点了么...?

感谢，原来是需要站点。 我都下载的hao4K上的。。
