### ISSUE TITLE
在chrome79上以crx的方式安装时,提示程序包无效crx_required_proof_missing, 查了一下说是新版本的chrome需要crx3的格式

### ISSUE THREAD

**Issue by kingcomxu** [ronggang/PT-Plugin-Plus#380]
能否提供一个crx3格式

**Comment by ronggang** [comment]
目前提供的已是crx3格式，请参考 crx 安装说明：
https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx

**Comment by kingcomxu** [comment]
谢谢, 安装说明里没说要打开开发模式, 我打开了开发模式就安装上了
