### ISSUE TITLE
北洋园无法显示pt助手右侧边工具栏

### ISSUE THREAD

**Issue by Jayce-Xiong** [ronggang/PT-Plugin-Plus#381]
- PT 助手版本: v1.4.5
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：chrome79.0.3945.88
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
北洋园无pt助手侧边栏，

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
注意访问域名与pt助手内域名是否一致，是否都带www

**Comment by Rhilip** [comment]
无法复现，请确认域名或使用CDN域名

**Comment by matoung** [comment]
访问北洋园URL带上www（Chrome会隐藏）就不显示助手，不带就显示了，URL匹配的问题吧

**Comment by xfl03** [comment]
@Jayce-Xiong 请在北洋园的CDN列表内加入如下内容
站点设置-北洋园-编辑-站点CDN列表
```
https://tjupt.org/
https://www.tjupt.org/
```
