### ISSUE TITLE
允许搜索关闭后一样能搜索

### ISSUE THREAD

**Issue by tudnew** [ronggang/PT-Plugin-Plus#382]
- PT 助手版本:1.4.5
- PT 助手安装方式：市场安装
- 浏览器名称及版本：火狐 71（64位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
将全部站点活部分站点允许搜索功能关闭后进行搜索，一样显示完整结果

- 相关截图：
https://s2.ax1x.com/2020/01/02/lYDuwj.png
https://s2.ax1x.com/2020/01/02/lYDKTs.png

- 重现步骤：
将全部站点活部分站点允许搜索功能关闭后进行搜索

**Comment by ted423** [comment]
@tudnew 关闭后有f5刷新下页面不

**Comment by tudnew** [comment]
> 
> 
> @tudnew 关闭后有f5刷新下页面不

现在试了下，刷新后显示一样是关闭状态，再进行搜索一样有

**Comment by ronggang** [comment]
@tudnew 如果搜索时选择了 `<所有站点>` ，不管站点是否允许搜索，都会进行搜索。
关闭搜索的站点仅在选择 `<默认>` 方案时有效。
![image](https://user-images.githubusercontent.com/8065899/71656617-e0417b00-2d76-11ea-8ed7-606e4bc9088b.png)

**Comment by tudnew** [comment]
@ronggang 原来如此，我是选择所有了，谢谢大佬解答
