### ISSUE TITLE
整页一键下载到选定目录，种子发送出现问题

### ISSUE THREAD

**Issue by xxn1202** [ronggang/PT-Plugin-Plus#384]
PT 助手版本:1.4.5

PT 助手安装方式：压缩包安装

浏览器名称及版本：360极速和Google Chrome

浏览器是否安装了其他插件：是

停用其他插件后是否正常工作：否

问题描述：
天空、HDarea、北洋园，几个网站，我用整页一键下载到选定目录，只有几个种子添加，显示蓝色进度条：“正在发送链接到qb服务器”，比较缓慢，和以往的正常的绿色进度条不一样。以往整页下载是正常的。日志文件如下：

[PT-Plugin-Plus-System-Logs.zip](https://github.com/ronggang/PT-Plugin-Plus/files/4015065/PT-Plugin-Plus-System-Logs.zip)

- 相关截图：
![助手出现问题](https://user-images.githubusercontent.com/41607147/71654928-53df8a00-2d6f-11ea-8d1b-0dccb3eb53bc.png)

- 重现步骤：试了两种浏览器，多个网站，都是这样。

**Comment by ronggang** [comment]
@xxn1202 看日志大部分是下载超时和无效种子，请参考 [常见问题](https://github.com/ronggang/PT-Plugin-Plus/wiki/frequently-asked-questions)

**Comment by xxn1202** [comment]
电脑重启后北洋园正常了，不知道是为什么。之前等了很久，发送都结束了，客户端也没有动静。
