### ISSUE TITLE
大佬求带

### ISSUE THREAD

**Issue by lyh2668** [ronggang/PT-Plugin-Plus#385]
- 首先不好意思滥用了issues
本人刚玩pt不久，从业多年前端，主攻vue，大佬不介意的话可以互相讨论讨论，我也可以尝试提一些pr

**Comment by Rhilip** [comment]
你可以直接修改然后pr，我们会review的。
讨论你可以在QQ群或者tg群组，无需另建issue

**Comment by lyh2668** [comment]
@Rhilip 抱歉，就是暂时不知道q群和tg，所以在此发了issue，望告知
lyh2668@163.com

**Comment by ronggang** [comment]
@lyh2668 可以在助手使用界面找到 `tg` 链接，欢迎加入讨论。
