### ISSUE TITLE
v1.4.6版本所有站点入站时间没有显示

### ISSUE THREAD

**Issue by YXHTom** [ronggang/PT-Plugin-Plus#388]
- PT 助手版本:v1.4.6
- PT 助手安装方式：（市场安装）
- 浏览器名称及版本：火狐71.0
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
v1.4.6版本我的数据所有站点入站时间没有显示

- 相关截图：

[![lrhkfs.md.png](https://s2.ax1x.com/2020/01/06/lrhkfs.md.png)](https://imgchr.com/i/lrhkfs)
- 重现步骤：

**Comment by ted423** [comment]
@YXHTom 我这正常，我新装一个试试

**Comment by ted423** [comment]
@YXHTom 试了下，火狐上的确实没了，我把我的数据清了再试试..

**Comment by YXHTom** [comment]
你正常的最新版本安装在哪个浏览器上啊？

**Comment by ronggang** [comment]
FF上是有问题，查了一下是时间格式未按 `ISO 8601` 标准来设置时区引起，下版修复。

**Comment by YXHTom** [comment]
ok

**Comment by YXHTom** [comment]
刚发现mac版火狐入站时间也异常

**Comment by ronggang** [comment]
> 刚发现mac版火狐入站时间也异常

一样的，火狐内核处理方式相同。
