### ISSUE TITLE
搜索字符 & 应该自动改为%26

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#389]
- PT 助手版本: 1.4.6
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
搜索 ANK&philosophy-raws 会变成只搜索ANK
另外 似乎 “#”也需要处理，不过目前似乎很少人写这个到标题或者搜索

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
我觉得我们应该改变下后台请求的相关方法
https://github.com/ronggang/PT-Plugin-Plus/blob/master/src/background/searcher.ts#L414-L420
目前，我们是采用url拼合的形式直接构成请求字符串。如果把这个交给jQuery库是否会更好些？即使用
```
{url: 'https://example.com/test?t=1',data:{'params':1}}
```
替代
```
{url: 'https://example.com/test?t=1&params=1'}
```
是不是会更好些，这样关于 html escape 的问题也不需要我们在拼合字符串的时候进行考虑。

**Comment by ronggang** [comment]
> 我觉得我们应该改变下后台请求的相关方法
> https://github.com/ronggang/PT-Plugin-Plus/blob/master/src/background/searcher.ts#L414-L420
> 目前，我们是采用url拼合的形式直接构成请求字符串。如果把这个交给jQuery库是否会更好些？即使用
> 
> ```
> {url: 'https://example.com/test?t=1',data:{'params':1}}
> ```
> 
> 替代
> 
> ```
> {url: 'https://example.com/test?t=1&params=1'}
> ```
> 
> 是不是会更好些，这样关于 html escape 的问题也不需要我们在拼合字符串的时候进行考虑。

思路应该可行，不过得把搜索字段提取出来再处理。

**Comment by ronggang** [comment]
考虑再三，就目前的定义方式，不好直接以 `data` 的形式传递，所以还是延续原有的方式，仅对搜索关键字做转义处理。
