### ISSUE TITLE
U2 未下载完成的进度会导致识别下载人数错误

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#390]
- PT 助手版本: 1.4.6
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
这是U2的下载那里的代码
```
<td class="rowfollow leechhlc_inactive" title="未完成下载">0<br>54%</td>
```
看起来可能需要截取下第一行？

- 相关截图：
![image](https://user-images.githubusercontent.com/7042766/71802653-54db2900-3099-11ea-972a-288fd7855cb7.png)
![image](https://user-images.githubusercontent.com/7042766/71802661-5c9acd80-3099-11ea-9cad-48ffe77de901.png)

- 重现步骤：

**Comment by ted423** [comment]
```<td class="rowfollow leechhlc_inactive" title="未完成下载">0<br>54%</td>```

有点尴尬......这个下载人数是0，所以还不能用a:first

**Comment by ronggang** [comment]
> `<td class="rowfollow leechhlc_inactive" title="未完成下载">0<br>54%</td>`
> 
> 有点尴尬......这个下载人数是0，所以还不能用a:first

😅那换种方式。
