### ISSUE TITLE
关于下载到指定服务器时菜单的优化

### ISSUE THREAD

**Issue by devil-snow2018** [ronggang/PT-Plugin-Plus#393]
## 您的功能请求是否与问题有关？ 请描述一下。
在种子详情页面，点击“下载到...”时，会弹出服务器选择菜单，如果只有一台服务器的情况下，此选择菜单建议屏蔽，直接开始发送下载请求

**Comment by ted423** [comment]
@devil-snow2018 有一键下载吧？

**Comment by devil-snow2018** [comment]
@ted423 我不知道你说的一键下载在哪，我的意思是在种子页面，右边的助手工具中点击那个“下载到...”时，会弹出一个选择服务器的小菜单，然后点击我设定的服务器之后，才会将下载请求发到到服务器，对于大多数人来说，其实就一台NAS，可以不用选择的

**Comment by ted423** [comment]
@devil-snow2018 设置里设默认下载器……用一键下载

**Comment by devil-snow2018** [comment]
@ted423 找到这个设置了，在常规设置里边，之前没有设置，所以没有那个 一键下载的选项，感谢解答哈！
