### ISSUE TITLE
EDGE上用qBittorrent连接不到服务器

### ISSUE THREAD

**Issue by aqqbjfquve** [ronggang/PT-Plugin-Plus#395]
- PT 助手版本:1.4.6
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：edge beta
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：无
- 问题描述：在EDGE上用qBittorrent连接不到服务器，Transmission可以正常连接服务器，同个浏览器不同在版本上一个可用一个不可用，不可用的是刚出来的正式版edge，

- [[相关截图：]
![image](https://user-images.githubusercontent.com/59524079/71941668-92ed5f80-31f5-11ea-9566-9cc6747c1ef1.png)
![image](https://user-images.githubusercontent.com/59524079/72486673-9365a600-3846-11ea-9a34-f1b266d1adbf.png)
![image](https://user-images.githubusercontent.com/59524079/72486685-9791c380-3846-11ea-95dd-5266440dcee0.png)

以下是Transmission正常的
![image](https://user-images.githubusercontent.com/59524079/71941844-2c1c7600-31f6-11ea-9bbb-75fef962059c.png)

- 重现步骤：

**Comment by ted423** [comment]
@aqqbjfquve 那你换chrome正常的么？

**Comment by aqqbjfquve** [comment]
> @aqqbjfquve 那你换chrome正常的么？

chrome和火狐都正常

**Comment by ted423** [comment]
@aqqbjfquve 我用edge beta 试了下正常，你有把chrome的设置导出来，导入edge的助手么？

**Comment by aqqbjfquve** [comment]
> @aqqbjfquve 我用edge beta 试了下正常，你有把chrome的设置导出来，导入edge的助手么？

我是直接在微软商店中安装的，你可以那我把edge重新安装试试

**Comment by ted423** [comment]
@aqqbjfquve 我的意思是扩展的设置你是导出导入的还是？

**Comment by Rhilip** [comment]
@aqqbjfquve 请按wiki提示，提供插件背景页console和network面板错误信息

**Comment by aqqbjfquve** [comment]
> @aqqbjfquve 我的意思是扩展的设置你是导出导入的还是？

扩展的设置你是导出导入?
