### ISSUE TITLE
推送的种子会出现连接失败

### ISSUE THREAD

**Issue by willie91** [ronggang/PT-Plugin-Plus#40]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

- PT 助手版本:1.0.0.18
- 浏览器名称及版本：Cent Browser
版本 3.8.5.69（正式版本） （64 位） (Chromium 71.0.3578.98)
- 问题描述：推送的种子会出现连接失败,同样的链接我手动添加就可以.
- 相关截图：
![9](https://user-images.githubusercontent.com/32695308/53486625-2c22f400-3ac4-11e9-9606-f98f94e78fc7.jpg)

下载器是qBittorrent

**Comment by Rhilip** [comment]
请问通过插件推送的种子tracker地址和你手动添加的tracker地址有异同吗？

**Comment by willie91** [comment]
> 请问通过插件推送的种子跟踪器地址和你手动添加的跟踪器地址有异同吗？

地址没太注意,我只看了passkey,passkey是一样,那个地址被我删掉了,我重新添加了,遇到的情况挺多的,我再留意一下

**Comment by willie91** [comment]
> > 请问通过插件推送的种子跟踪器地址和你手动添加的跟踪器地址有异同吗？
> 
> 地址没太注意，我只看了密钥，密钥是一样，那个地址被我删掉了，我重新添加了，遇到的情况挺多的，我再留意一下

抱歉,是我下载路径少了个\刚刚仔细看了下改好了,没问题了
