### ISSUE TITLE
猫站 搜索有进度条的资源副标题不显示

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#403]
- PT 助手版本: dev、1.4.6
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
测了助手俩版本都是
发别的站用相同的副标题都没事，猫站其他资源也没事
https://pterclub.com/details.php?id=27378

![image](https://user-images.githubusercontent.com/7042766/72124031-44c79000-339e-11ea-9b8b-eb84a8eb879c.png)
不知道是不是跟fieldSelector 里有个title有关？

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/72130744-59fbe900-33b5-11ea-9e8b-93a75df15f58.png)

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/72131011-0938c000-33b6-11ea-81f5-dd953b8267d9.png)
好吧，看起来是因为进度条影响了获取

**Comment by ronggang** [comment]
![image](https://user-images.githubusercontent.com/8065899/72202120-e03c2c00-3496-11ea-977d-b5b2ba6be2c2.png)
不能复现。

**Comment by ronggang** [comment]
> ![image](https://user-images.githubusercontent.com/7042766/72131011-0938c000-33b6-11ea-81f5-dd953b8267d9.png)
> 好吧，看起来是因为进度条影响了获取
> 
> 所以下载或者做种的副标题获取会出错

是要有进度条是吗？我试试。
