### ISSUE TITLE
1.4.6版本搜索发现个问题

### ISSUE THREAD

**Issue by liliangzhi** [ronggang/PT-Plugin-Plus#405]
- PT 助手版本:1.4.6
- PT 助手安装方式：zip包覆盖升级
- 浏览器名称及版本：QQ浏览器10.5.2
- 浏览器是否安装了其他插件：饼干 油猴 ABP 购物比价
- 停用其他插件后是否正常工作：没有详细测试
- 问题描述：
种子全英文名搜索出的结果没有多少
但是搜电影中文关键词就能搜出全英文的种子
例如：搜 Uncle Drew 2018 UHD BluRay REMUX 2160p HEVC TrueHD7.1 Atmos-HDS 和搜 “德鲁大叔”
种子为51.48 GiB版本  
但是如果把搜索关键词缩减到 Uncle Drew 2018 UHD BluRay REMUX 2160p HEVC 就可以搜索得出。是否关键词过长？

另外还有个搜索外的小问题 就是HDHOME的live.php种子区不能整个页面一键下载 普通种子页torrents.php可以

- 相关截图：
https://img.pterclub.com/images/2020/01/11/QQ20200111013815.jpg
https://img.pterclub.com/images/2020/01/11/QQ20200111013553.jpg

- 重现步骤：

**Comment by ted423** [comment]
@liliangzhi 英文肯定不能全写进去…因为有些人发的时候可能会漏掉

**Comment by Rhilip** [comment]
1. 这种关键词不相同的搜索对比没有意义，你应该比较的是相同关键词在站点以及PTPP中表现不同。
2. 不同问题请分不同issue反馈。

**Comment by ted423** [comment]
额外的小问题应该属于站点适配问题，需要一个有号的愿意适配的大佬来进行适配

**Comment by liliangzhi** [comment]
> 1. 这种关键词不相同的搜索对比没有意义，你应该比较的是相同关键词在站点以及PTPP中表现不同。
> 2. 不同问题请分不同issue反馈。

好把。反复对比。问题在于 TrueHD7.1  天空是贴着TrueHD的7.1  而别人搬运发布的标题是不贴着的 TrueHD 7.1 眼拙了。。

**Comment by liliangzhi** [comment]
> @liliangzhi 英文肯定不能全写进去…因为有些人发的时候可能会漏掉

嗯。。感谢解答。因为一直都是复制整个标题方便点。所以忽略了这点。确实TrueHD7.1 和TrueHD 7.1 没注意原发布标题是TrueHD7.1    别人搬运发布的是TrueHD 7.1（有空格）
