### ISSUE TITLE
Firefox搜索结果不显示发布时间

### ISSUE THREAD

**Issue by ddk233** [ronggang/PT-Plugin-Plus#406]
- PT 助手版本:1.4.6
- PT 助手安装方式：市场
- 浏览器名称及版本：Firefox 72/Firefox 71
- 浏览器是否安装了其他插件：否
- 问题描述： Firefox搜索结果不显示发布时间

- 相关截图：

![图片](https://user-images.githubusercontent.com/56125958/72201194-67d06d80-348c-11ea-9b68-cc57d20c134b.png)
![图片](https://user-images.githubusercontent.com/56125958/72201208-8df60d80-348c-11ea-9dee-9b2603cac9ae.png)

- 重现步骤：如描述，任何搜索结果均不显示发布时间

个人测试：
1. Windows 1909 Firefox  72/PT 助手1.4.6 ->无显示
2. linuxmint-19.3-mate Firefox  71/PT 助手1.4.6 -> 无显示
3. Windows 1909 Edge(Chrome 79) /PT 助手1.4.6 -> 有显示
![图片](https://user-images.githubusercontent.com/56125958/72201319-8aaf5180-348d-11ea-8a35-4829430d953a.png)

**Comment by ted423** [comment]
dupe了
