### ISSUE TITLE
在“所有站点”搜索模式下，mt搜索个别资源不显示

### ISSUE THREAD

**Issue by zlhdd108** [ronggang/PT-Plugin-Plus#408]
- PT 助手版本:v1.4.6
- PT 助手安装方式：crx
- 浏览器名称及版本：opera 66.0.3515.27
- 浏览器是否安装了其他插件：已禁用
- 停用其他插件后是否正常工作：否
- 问题描述：
使用“所有站点”搜索模式，个别资源在mt下搜索不到，单独重试也搜索不到，具体下图

- 相关截图：
1.
![image](https://user-images.githubusercontent.com/16465666/72205567-99166100-34bf-11ea-9814-12bd9d9e242e.png)
2.
![image](https://user-images.githubusercontent.com/16465666/72205579-c06d2e00-34bf-11ea-9aea-f7d515cb240e.png)
3.
![image](https://user-images.githubusercontent.com/16465666/72205582-ce22b380-34bf-11ea-9f5d-ba5cd3508138.png)

- 重现步骤：

**Comment by ted423** [comment]
这种情况下一般是网络错误了
单站刷新重试就是干这个的。

**Comment by zlhdd108** [comment]
> 这种情况下一般是网络错误了
> 单站刷新重试就是干这个的。
问题描述中说明了，单独重试多次，依然无法搜索到；而且出问题的大多为电视剧分类的，mt会定位到“综合”去搜索

**Comment by ted423** [comment]
> > 这种情况下一般是网络错误了
> > 单站刷新重试就是干这个的。
> 
> 问题描述中说明了，单独重试多次，依然无法搜索到；而且出问题的大多为电视剧分类的，mt会定位到“综合”去搜索

我也遇到过，一种是开了二级验证导致网页无法访问，一种就是重试可行的
像网页加载出问题，老版本会在后面显示上一个网站的名字

![image](https://user-images.githubusercontent.com/7042766/72206044-75a1e500-34c4-11ea-96a0-eecddf80424e.png)
你看获取movie那里回了一个fail,其他都是done

**Comment by zlhdd108** [comment]
> > > 这种情况下一般是网络错误了
> > > 单站刷新重试就是干这个的。
> > 
> > 
> > 问题描述中说明了，单独重试多次，依然无法搜索到；而且出问题的大多为电视剧分类的，mt会定位到“综合”去搜索
> 
> 我也遇到过，一种是开了二级验证导致网页无法访问，一种就是重试可行的
> 像网页加载出问题，老版本会在后面显示上一个网站的名字
> 
> ![image](https://user-images.githubusercontent.com/7042766/72206044-75a1e500-34c4-11ea-96a0-eecddf80424e.png)
> 你看获取movie那里回了一个fail,其他都是done


看起来是超时了
![image](https://user-images.githubusercontent.com/16465666/72206105-e8ab5b80-34c4-11ea-951a-1f6f618e82b1.png)

单独访问的时候发现确实有点慢，但是是可以正常打开的

**Comment by ted423** [comment]
改下这里试下？
![image](https://user-images.githubusercontent.com/7042766/72206123-25775280-34c5-11ea-8c8a-f8ebeb4cc46c.png)

**Comment by zlhdd108** [comment]
> 改下这里试下？
> ![image](https://user-images.githubusercontent.com/7042766/72206123-25775280-34c5-11ea-8c8a-f8ebeb4cc46c.png)


确实有用了，不过这里非要先设置一个默认下载服务器才能更改……直接都没有设置，谢谢
