### ISSUE TITLE
建议增加自定义路径功能

### ISSUE THREAD

**Issue by nengtalk** [ronggang/PT-Plugin-Plus#41]
部分人的下载习惯是将文件下载到独立的中文文件夹中，方便整理，比如
/volume1/movie/复仇者联盟
以transmission为例，通常会自动新建“复仇者联盟”文件夹并将文件下载至该文件夹中

建议在下载目录设置中增加<...>,即 /volume1/movie/<...>

当右键发送到此地址时，弹出输入框获取自定义文件路径，发送到服务器开始下载

eg,右键-推送到指定目录/volume1/movie/<...>-弹出输入框，用户键入“肖申克的救赎”-将下载位置/volume1/movie/肖申克的救赎 发送给服务器开始下载

谢谢

**Comment by ronggang** [comment]
@nengtalk 好提议

**Comment by Rhilip** [comment]
我比较喜欢将这个功能作为附加功能（默认关闭，在用户需要时自主启用）
毕竟不是所有人都喜欢一个弹出窗口。
弹出窗口也可以考虑直接给出完整下载路径，而不是补充路径。

我个人的习惯就是下完之后在做整理的。

**Comment by nengtalk** [comment]
> 我比较喜欢将这个功能作为附加功能（默认关闭，在用户需要时自主启用）
> 毕竟不是所有人都喜欢一个弹出窗口。
> 弹出窗口也可以考虑直接给出完整下载路径，而不是补充路径。
> 
> 我个人的习惯就是下完之后在做整理的。

当然，是只有在下载目录设置中用户启用了"<...>"关键字后才会窗口由用户补充路径
如果不启用这个关键字依然是按用户设置好的固定目录走
