### ISSUE TITLE
[dev]FF下AsianCinema以及BHD入站时间不显示

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#410]
- PT 助手版本: dev
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
DXDHD由于站点维护，目前在维护，虽然能显示，但我怀疑是之前的数据
其他站点已正常

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
@ted423 英文界面应该是正常的，中文没有适配。

**Comment by ted423** [comment]
@ronggang BHD只有英文，中文貌似我适配过一次？chrome下正常的

**Comment by ronggang** [comment]
> @ronggang BHD只有英文，中文貌似我适配过一次？chrome下正常的

这个吗？
https://github.com/ronggang/PT-Plugin-Plus/blob/e09f4da1739c3b6698f0b5903bd4f79351456362/resource/schemas/UNIT3D/config.json#L87-L90
看了下，这样适配中文应该不起作用，获取的日期格式不对。

**Comment by ted423** [comment]
@ronggang 但是很奇葩的是chrome一切正常，我不知道发生了什么🤣

**Comment by ted423** [comment]
@ronggang 不过试了下，英文 AsianCinema确实可以了

**Comment by ronggang** [comment]
试了下，dayjs() 在 `Chrome` 和 `FF` 下的确表现结果不一致，在 `Chrome` 下可以正确解析像这样的 `注册日期 Mar 10 2019` 的日期，`FF` 下就不行，直接是无效的日期。应该和两个浏览器的日期解析函数是否严格执行标准有关。

https://codepen.io/ronggang/pen/xxKPeXr
