### ISSUE TITLE
火狐浏览器 从谷歌恢复 无法使用

### ISSUE THREAD

**Issue by lixiaolong2** [ronggang/PT-Plugin-Plus#412]
## 您的功能请求是否与问题有关？ 请描述一下。

火狐浏览器 从谷歌恢复 无法使用

路径 参数备份与恢复  从谷歌浏览器恢复 或者备份

## 描述你想要的解决方案

增加谷歌登陆

**Comment by ted423** [comment]
我记得有谁说过只支持谷歌商店版本

**Comment by ted423** [comment]
结果我试了下，成功了...
你什么浏览器版本和扩展版本？
google登录了么？

**Comment by lixiaolong2** [comment]
> 结果我试了下，成功了...
> 你什么浏览器版本和扩展版本？
> google登录了么？

火狐浏览器

**Comment by ted423** [comment]
@lixiaolong2 我知道是火狐浏览器，我也用的火狐试的，火狐版本号，助手版本号，是否在浏览器上登录了google账号

**Comment by lixiaolong2** [comment]
> @lixiaolong2 我知道是火狐浏览器，我也用的火狐试的，火狐版本号，助手版本号，是否在浏览器上登录了google账号
火狐72.0.1 (64 位）

找到原因了。。google登陆后被风险拦截了。要未知放行
