### ISSUE TITLE
按搜索方案搜索种子只显示10条记录

### ISSUE THREAD

**Issue by haowen2000** [ronggang/PT-Plugin-Plus#415]
- PT 助手版本:1.47
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome79
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：否
- 问题描述：
按搜索方案搜索种子只显示10条记录

- 相关截图：

- 重现步骤：

**Comment by haowen2000** [comment]
刚才使用默认搜索方案，所有站点都只显示10条搜索记录。。。。

**Comment by ted423** [comment]
@haowen2000 检查你的扩展设置
