### ISSUE TITLE
能否添加类似rss的功能。我是路由器挂pt，rss很麻烦，用这个自动添加应该很方便~

### ISSUE THREAD

**Issue by timewalkerF** [ronggang/PT-Plugin-Plus#416]
## 您的功能请求是否与问题有关？ 请描述一下。

能否添加类似rss的功能。我是路由器挂pt，rss很麻烦，用这个自动添加应该很方便~

**Comment by ted423** [comment]
@timewalkerF 之前讨论过了应该，你搜下以前的issue

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/280

**Comment by Aniverse** [comment]
路由器上也可以装 flexget，或者 qbittorrent 自带 RSS，或者 ruTorrent／Flood，或者 Deluge 配置 YaRSS2
