### ISSUE TITLE
能否增加按标签进行搜索的功能

### ISSUE THREAD

**Issue by haowen2000** [ronggang/PT-Plugin-Plus#419]
## 您的功能请求是否与问题有关？ 请描述一下。

比如搜索某站，直接搜索FREE标签，或者2xFrees标签，或者50%标签等，方便刷PT数据

**Comment by ted423** [comment]
@haowen2000 这个在站点本身操作就好了吧？

**Comment by Rhilip** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/search-entry-definition
请参照搜索入口的方式定义 追加请求参数
