### ISSUE TITLE
增加更多框架

### ISSUE THREAD

**Issue by frank777777777** [ronggang/PT-Plugin-Plus#42]
有计划增加更多框架的支持吗？
IPT系(Torrenday, SpeedCD等等)
HD-Torrents
Filelist

**Comment by ronggang** [comment]
@frank777777777 因个人能力有限，手头没有你说的这些站，只能靠大家一起来做，我是希望能整理出方便大家一起参与的文档，这样好添加还不支持的站点，希望提供好的建议，感谢！

**Comment by Rhilip** [comment]
我们有类似计划，会对我们手头能收集到的站点进行适配，但是我们其实并没有那么能“收割”。
同样，只需要你有一定Javascript的，就可以帮助我们。现有文档已经开始逐步完善了。
如果你有其他想法，也可以在我们开发群： 773500545 与我们交流

**Comment by frank777777777** [comment]
不怎么会js....建议可以和jackett一样把已经支持的站点，和计划支持的站点列出来。还有需要邀请的站点标出来。然后给一个非注册站点邮箱(防止被认定公开发药)或者别的方式方便联系，可以贡献邀请帮助开发。

**Comment by Rhilip** [comment]
@frank777777777 
已支持站点可以见我们wiki页面 https://github.com/ronggang/PT-Plugin-Plus/wiki/supported-sites
如果愿意以邀请的形式参与开发，请在群里私聊ronggang或者我吧:ok_hand:
