### ISSUE TITLE
搜索首页不小于指定评分的种子

### ISSUE THREAD

**Issue by lonecrane** [ronggang/PT-Plugin-Plus#422]
## 您的功能请求是否与问题有关？ 请描述一下。

您好！我每天都要打开各站点的种子页首页，看是否有高分电影的新种子，以便在免费期内下载。人工方法有两个弊端，一是必须肉眼寻找评分，二是站点比较多，看完一轮要十分钟。您请评估必要性和可行性。

## 描述你想要的解决方案

绝大部分内站在标题旁边都提供电影评分。提供高分新种搜索功能，对各站点的首页种子，如果高于指定评分就添加到搜索结果中。

**Comment by haowen2000** [comment]
搜索结果能带上评分，就好了

**Comment by Rhilip** [comment]
可行性不足，不同架构，同架构不同站点该部分评分获取展示方法不同。

**Comment by ronggang** [comment]
目前暂无法实现，如有代码层面的思路，欢迎提供。
