### ISSUE TITLE
猫站 搜索不显示免费标签，并且限时免费的结果的副标题中多了剩余时间：

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#424]
- PT 助手版本: dev
- PT 助手安装方式：crx
- 浏览器名称及版本：cent 最新版
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
应该不是我干的

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
看了下， "剩余时间："是文本节点，所以replaceWith干不掉，标签那个有点看不懂

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/73765540-a6b5c280-47af-11ea-8157-f265552c7776.png)
不知道这算不算相关问题

**Comment by ronggang** [comment]
忙完这段时间后我看看。

**Comment by ted423** [comment]
看起来标签是被replaceWith干掉了，所以就没了

**Comment by ted423** [comment]
一个不注意..........猫站副标题又没了
