### ISSUE TITLE
关于搜索结果页面

### ISSUE THREAD

**Issue by FalseSummer** [ronggang/PT-Plugin-Plus#426]
## 您的功能请求是否与问题有关？ 请描述一下。

搜索关键字之后>选择无结果站点

## 描述你想要的解决方案

希望可以在无结果站点的的名字后面，加上站点的超链接，这样的话我可以快速的转种到该站点，因为我每次转发种子到十几二十个站点，并且需要对照哪个站点没有发布需要耗费精力。如果增加这个小功能可以节约非常多时间！希望可以采纳，非常感谢！

## 其他附加信息

https://i.loli.net/2020/01/28/6QBkKCnLrI3Sl1m.png

截图红框处

**Comment by tongyifan** [comment]
点击站点名就可以直接跳转了（ 613da2e6f75f881930da509b1da68f52ed1a150a ）
