### ISSUE TITLE
朋友(?) 种子详情页感谢发布者很大概率无法使用

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#427]
- PT 助手版本: dev
- PT 助手安装方式：crx
- 浏览器名称及版本：cent 最新正式版
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

种子详情页面 感谢发布者 按钮不显示
部分页面  let sayThanksButton = PTService.getFieldValue("sayThanksButton"); 
sayThanksButton 是null,无法调试

在u2,猫站，第一次进种子详情页面是显示该按钮的，尝试设了个断点之后就再也不显示，控制台关了也一样。

进入HDU，第一次显示按钮，刷新两次后按钮不再显示

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
是Bug，是初始化页面选择器时使用了异步进程，导致一定概率执行顺序错误。
