### ISSUE TITLE
猫站pterclub的cloudfare的防ddos导致无法刷新数据

### ISSUE THREAD

**Issue by zhufeng** [ronggang/PT-Plugin-Plus#429]
- 

发现猫站（pterclub）使用了cloudfare的防ddos，导致过一段时间刷新界面的时候会要等好几秒种才能加载页面内容，这样就导致了PT助手无法获取其站点的数据，会显示刷新数据出错。

此问题也有解决办法 ，就是先手动去pterclub首页刷新一下，然后马上在pt助手里面点刷新数据，然而这样的话，pt助手的存在就没有意义了。

当然，防ddos从另一个侧面上来说，也可能是其站点管理组故意阻止pt助手刷新其站点数据吧。

**Comment by ted423** [comment]
@zhufeng 这是正常现象，请手动点一下再刷

**Comment by zhufeng** [comment]
> @zhufeng 这是正常现象，请手动点一下再刷

是否能针对站点做一个延迟5秒刷新再报错的功能呢？

**Comment by ted423** [comment]
@zhufeng 个人想法，常开5秒盾本身就不是一个正常现象，所以扩展应该不会这么操作吧。

**Comment by Rhilip** [comment]
暂时做不到，这个不是等5s的事，而是需要浏览器进行js运行以获取cf那边的sessionid。
我们更希望这个只是站点暂时措施，而不是长久措施。**否则我们会考虑移除该站的官方支持。** 
（这一点我们希望能得到站点方的确认，因为设置更好的WAF规则比无脑开盾好多了）

此外，
1. 并不是所有站都存在cf 5s盾的情况，为了处理单一站点引入一批库得不偿失。
2. 目前的一些 cloudflare pypass或者说scraper库 均只能处理5s盾的情况，对 reCAPTCHA 的情况均不能处理。万一站点升级或更换cf的设置，无法继续处理后续请求。

**Comment by ted423** [comment]
@Rhilip 🌚移除官方支持就不要了吧

**Comment by zhufeng** [comment]
> 暂时做不到，这个不是等5s的事，而是需要浏览器进行js运行以获取cf那边的sessionid。
> 我们更希望这个只是站点暂时措施，而不是长久措施。**否则我们会考虑移除该站的官方支持。**
> （这一点我们希望能得到站点方的确认，因为设置更好的WAF规则比无脑开盾好多了）
> 
> 此外，
> 
> 1. 并不是所有站都存在cf 5s盾的情况，为了处理单一站点引入一批库得不偿失。
> 2. 目前的一些 cloudflare pypass或者说scraper库 均只能处理5s盾的情况，对 reCAPTCHA 的情况均不能处理。万一站点升级或更换cf的设置，无法继续处理后续请求。

我在其站内论坛发帖问了这个事情，没有得到任何回复，帖子就被直接关闭了。

**Comment by ted423** [comment]
@zhufeng 看了下，你的帖子说法也算有些问题，可能在对方的理解里，5秒盾是必要措施，并不清楚更具体的利弊。单纯的助手刷新数据作为参考作为建议是不足够的。

**Comment by ted423** [comment]
看起来猫站5秒盾已经关了

**Comment by zhufeng** [comment]
> 看起来猫站5秒盾已经关了

是的，本帖关闭。
