### ISSUE TITLE
功能建议:希望已下载的种子有标识等

### ISSUE THREAD

**Issue by dumperk** [ronggang/PT-Plugin-Plus#43]
能否在搜索种子后,已经下载或添加过的种子具有标记,提示这个种子已经下载过,1次或几次或不显示次数.
添加站点或添加服务器时,能否加个关闭的按钮,如果想取消要点下其他位置,但感觉没有关闭按钮觉得有点怪.
现在体会到您设计每个站点单独目录的好处了,很棒

**Comment by ronggang** [comment]
1. 如果是从目标网站中去获取是否已下载，这个每个网站会有不同，实现会比较复杂，获取过程也会比较长；如果是想从相应的下载服务器中获取状态，得服务器端有接口才可以；如果只是通过助手下载过，标记为已下载，可能仅能做本电脑当前浏览器有效，或同步到Google起到多电脑有效；后续看情况能不能做。
2. 谢谢建议，后续改进。

**Comment by chenyz1984** [comment]
调用下载工具的接口不可以么？就好像transmission remote gui管理工具那样，去登录下载服务器transmission，获取下载信息（如添加时间、下载进度、下载与上传速度等）

**Comment by Rhilip** [comment]
@chenyz1984 能力有限，实现不了

**Comment by chenyz1984** [comment]
> @chenyz1984 能力有限，实现不了

慢慢来，目前的功能已经很棒了。
