### ISSUE TITLE
Mac 下 Firefox+PT plus 1.4.7+rutorrent 3.9 下載服務器無法通過驗證

### ISSUE THREAD

**Issue by happyda** [ronggang/PT-Plugin-Plus#430]
- PT 助手版本:  v1.4.7
- PT 助手安装方式：（市场安装，或zip包安装） 市場安裝
- 浏览器名称及版本：Firefox 72.0.2（64 位元）
- 浏览器是否安装了其他插件：uBlock Origin/HTTPS Everywhere/1Password Beta/新同文堂/ImTranslator
- 停用其他插件后是否正常工作：否
- 问题描述：
加入Rutorrent 下載服務器無法通過測試服務器連接測試，顯示服務器連失敗。由伺服器端看並沒有瀏覽器送出的任何連接要求，但使用同一台Macbook安裝之Brave/Chrome/Microsoft Edge 及相同組態設定，3個瀏覽器都可以正常使用。 

- 使用MacOS 10.15.3 防毒 Avast Security 14.3 關閉後仍無法連接

- 另有使用IPv6 位址

- 相关截图：
![圖片](https://user-images.githubusercontent.com/3788126/74095406-12d75400-4b2b-11ea-9dc3-ab081fdbb00c.png)

- 重现步骤：
加入新的下載服務器後，輸入服務器地址，登入名與密碼後 按下測試月服務器連接測試 可重現

**Comment by happyda** [comment]
在系統日誌發現這段訊息,原始站台位址我替換成 mysite.example.com 

测试客户连接失败[https:&#x2F;&#x2F;mysite.example.com&#x2F;ruTorrent-3.9&#x2F;]
{"type":"error","success":false,"data":{"status":"error","code":404,"msg":"指定的地址未找到，服务器返回了 404"}}

會不會原本應該是要 http:// 的 slash 被替成unicode 編碼造成無法正確連接站台

**Comment by ronggang** [comment]
@happyda 请根据 https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page 方法定位一下请求的页面返回的内容。

**Comment by happyda** [comment]
Hi ronggang,
使用Firefox 只抓到這樣子的訊息

![截圖 2020-02-27 下午9 57 31](https://user-images.githubusercontent.com/3788126/75452553-7a0b5a00-59ad-11ea-8939-12e7200be8dd.png)

**Comment by happyda** [comment]
Hi ronggang,
使用Firefox 只抓到這樣子的訊息

![截圖 2020-02-27 下午9 57 31](https://user-images.githubusercontent.com/3788126/75452553-7a0b5a00-59ad-11ea-8939-12e7200be8dd.png)

**Comment by ronggang** [comment]
@happyda 是否已切换到调试模式？
在 FF 里输入：
```
about:debugging#/runtime/this-firefox
```
然后找到助手，点击『查看』，打开背景页；
然后再回到助手里，点击测试服务器，看看背景页返回什么结果。

**Comment by happyda** [comment]
@ronggang  依照你所提的方式測試後 截了二個圖，看起與之前所收集到的訊息相同。
今日我在windows 10+ Firefox最新版本也有相同情況，在rutorrent 伺服器端(server site) 並沒有接收到任何的請求，即browser 沒有送出request.

<img width="1680" alt="截圖 2020-02-29 上午7 34 49" src="https://user-images.githubusercontent.com/3788126/75595290-baaac680-5ac6-11ea-8e15-f6cbec19f2da.png">
<img width="1680" alt="截圖 2020-02-29 上午7 35 10" src="https://user-images.githubusercontent.com/3788126/75595310-c6968880-5ac6-11ea-8b17-b98565ddbe9e.png">

**Comment by ronggang** [comment]
@happyda 已找到问题所在，感谢反馈。
