### ISSUE TITLE
UHDbits free等标签支持

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#433]
## 您的功能请求是否与问题有关？ 请描述一下。

UHDbits的标签长这样
`<strong class="torrent_label tooltip blink_me" style="white-space: nowrap;">2x</strong>`
看起来没法靠选择器解决
## 描述你想要的解决方案

加个filters?

**Comment by ronggang** [comment]
UHDbits 目前是单独处理，可暂时在站点的独立脚本中修改。
具体是否需要增加 `filters` 后续视情况而定吧。
