### ISSUE TITLE
关于搜索的实现

### ISSUE THREAD

**Issue by TKXZH** [ronggang/PT-Plugin-Plus#436]
- 
想问一下，您是如何通过passkey获取pt站搜索结果的，是pt站有这样的接口吗？用了这个插件挺久了，最近想做一个类似pt助手的网页版，是通过模拟登陆pt站实现搜索的，比较麻烦，做后台的ts没用过看的有点晕，能否不吝赐教，谢谢

**Comment by ted423** [comment]
不是passkey ，而是cookies
另，不建议网页版

**Comment by TKXZH** [comment]
谢谢。助手并没有让用户配置用户名密码，怎样拿到cookie的呢？从passkey也能拿到cookie是吗？
了解，不是做公开的网页版，类似一个docker内网跑起来，个人使用的那种。

**Comment by TKXZH** [comment]
懂了，是用的本身chrome的cookie，谢谢！
