### ISSUE TITLE
CHD的下载进度能不能加上

### ISSUE THREAD

**Issue by haowen2000** [ronggang/PT-Plugin-Plus#437]
## 您的功能请求是否与问题有关？ 请描述一下。

CHD其实是有下载进度标签的，只不过不像其他网站用的进度条，而是使用的数字百分比来显示下载进度，搜索种子的时候，搜索结果中能不能加上这个进度？

**Comment by ted423** [comment]
我也想加，但网站本身没有任何的显示。

**Comment by ted423** [comment]
不过似乎无法确认正在做种还是下完了

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/pull/438

**Comment by haowen2000** [comment]
> 不过似乎无法确认正在做种还是下完了

确实，CHD的百分比进度，显示的是曾经下载的进度，就算已经下完了100%，删除种子后，还是显示你曾经下载过100%。

换个思路，能不能结合个人控制面板的当前做种列表，对搜索结果进行标记，从而知道某个种子是否在下载服务器。

**Comment by ted423** [comment]
> > 不过似乎无法确认正在做种还是下完了
> 
> 确实，CHD的百分比进度，显示的是曾经下载的进度，就算已经下完了100%，删除种子后，还是显示你曾经下载过100%。
> 
> 换个思路，能不能结合个人控制面板的当前做种列表，对搜索结果进行标记，从而知道某个种子是否在下载服务器。
> 
> 其实每个PT网站都有“当前做种”列表，而且是实时的，实时显示下载服务器上的种子，结合这个列表，对搜索结果进行标记，不知是否可行？

理论上可以的，但要重新写脚本。
btw,印象里NP是由相应信息的，chd 的sysop能加一下才是再好不过的

**Comment by haowen2000** [comment]
> > > 不过似乎无法确认正在做种还是下完了
> > 
> > 
> > 确实，CHD的百分比进度，显示的是曾经下载的进度，就算已经下完了100%，删除种子后，还是显示你曾经下载过100%。
> > 换个思路，能不能结合个人控制面板的当前做种列表，对搜索结果进行标记，从而知道某个种子是否在下载服务器。
> > 其实每个PT网站都有“当前做种”列表，而且是实时的，实时显示下载服务器上的种子，结合这个列表，对搜索结果进行标记，不知是否可行？
> 
> 理论上可以的，但要重新写脚本。
> btw,印象里NP是有相应信息的，chd 的sysop能加一下才是再好不过的

借此机会问一下transmission-web-control，这个插件的“获取更多peer”功能（雷达图标）是怎么用的啊？
在校验种子时，一直不能跳过检验，到底应该怎么用？

**Comment by ted423** [comment]
@haowen2000 正常tr版本无跳检功能
