### ISSUE TITLE
功能建议:希望添加各站点的自动签到功能

### ISSUE THREAD

**Issue by Warm-rain** [ronggang/PT-Plugin-Plus#44]
以前一直用的ppt，直到发现了这个插件，ppt就丢一边去了，希望能够自动签到，免得有时候忘记断签真的很伤心

**Comment by Rhilip** [comment]
暂时不会考虑签到功能
https://github.com/ronggang/PT-Plugin-Plus/issues/13

**Comment by icaobo** [comment]
自动签到功能很实用啊，希望可以增加自动签到功能

**Comment by JackZhangCHN** [comment]
自动签到真的很实用，希望大佬可以添加，谢谢
