### ISSUE TITLE
增加新站点AVGA

### ISSUE THREAD

**Issue by jueerye** [ronggang/PT-Plugin-Plus#444]
- 站点名称：AVGA
- 站点地址：http://avgv.cc
- 站点描述：成人

- 资源类型：成人
- 开放注册：否
- 是否连坐：否
- 站点规则：

**Comment by Rhilip** [comment]
请于此贴提交 使用NPHP架构，且自定义模板能直接适配的站点，本issue做关闭处理
https://github.com/ronggang/PT-Plugin-Plus/issues/30
