### ISSUE TITLE
希望增加语言选择功能

### ISSUE THREAD

**Issue by sjtuross** [ronggang/PT-Plugin-Plus#447]
## 您的功能请求是否与问题有关？ 请描述一下。
英文操作系统，Firefox，插件显示英文，没法改成中文

## 描述你想要的解决方案
提供语言选择功能

## 描述您考虑过的替代方案
尝试安装Firefox中文语言包，Firefox界面已改成中文，但插件还是显示英文

**Comment by ted423** [comment]
@sjtuross 那啥...你确定你把界面所有东西都看过了么

**Comment by sjtuross** [comment]
@ted423 看了遍设置，没看到语言相关的

**Comment by ted423** [comment]
@sjtuross 助手页面最底下.........

**Comment by sjtuross** [comment]
@ted423 额，没想到，多谢！！

**Comment by Rhilip** [comment]
都用英文系统了，助手界面这点英文应该不成问题吧？

**Comment by sjtuross** [comment]
> 
> 
> 都用英文系统了，助手界面这点英文应该不成问题吧？

英文翻译有待完善

**Comment by Rhilip** [comment]
请查看 i18n 相关说明，并参与共享
https://github.com/ronggang/PT-Plugin-Plus/tree/master/resource/i18n
