### ISSUE TITLE
UHDbits搜索结果，资源为电影名字, 而不是常规资源命名

### ISSUE THREAD

**Issue by frank777777777** [ronggang/PT-Plugin-Plus#45]
这个站点(和一些其他gazelle框架的站点)的资源标题都是电影名字，仅仅获取标题的结果是这样，比如:
![image](https://images2.imgbox.com/21/f7/nlGiMl2n_o.jpg)

能否获取文件名作为搜索结果？比如:
![image](https://images2.imgbox.com/6b/e0/GLxnOZLT_o.jpg)

**Comment by ronggang** [comment]
@frank777777777 如果文件名是需要进到详情页才能取到，就不好办，每个结果要多发一次请求才能取到结果，这个请求数量有点大。

**Comment by Rhilip** [comment]
文件名无法从种子列表页获得。好一点的处理方法是加上分辨率等信息作为插件搜索的主标题返回，如
`Look Away` -> ` Look Away / 1080p / x264 / Blu-ray / Scene / GETiT `

**Comment by ronggang** [comment]
> 文件名无法从种子列表页获得。好一点的处理方法是加上分辨率等信息作为插件搜索的主标题返回，如
> `Look Away` -> `Look Away / 1080p / x264 / Blu-ray / Scene / GETiT`

这些内容出现在种子列表中是吗？

**Comment by OliverLew** [comment]
![Screenshot_2019-07-12_11-37-52](https://user-images.githubusercontent.com/12032219/61100682-951a6f80-a499-11e9-9a93-48f1fcc8bf30.png)
种子列表是这样的，有几个基本的信息，应该足够了

**Comment by ronggang** [comment]
v1.3.0 之后UHDbits应该已很好的支持，该主题关闭，如有疑问请重新开启。
