### ISSUE TITLE
firefox Android版无法正确刷新hdroute和hdcity的数据

### ISSUE THREAD

**Issue by zhufeng** [ronggang/PT-Plugin-Plus#450]
- PT 助手版本: v1.4.7 - firefox android
- PT 助手安装方式：（市场安装，或zip包安装） firefox android扩展中心安装
- 浏览器名称及版本：firefox android 68.4.1
- 浏览器是否安装了其他插件：ublock origin
- 停用其他插件后是否正常工作：否
- 问题描述：

firefox android，对于hdroute和hdcity的站点数据，无法刷新。
hdroute直接显示未登录，hdcity不会显示未登录，但是数据无法正常抓取。

分析原因，可能为hdroute具有完整的移动端页面适配，hdcity有部分移动端页面适配。
尝试过开启浏览器的桌面模式，仍然不行。

- 相关截图：
![微信图片_20200226103125](https://user-images.githubusercontent.com/1539043/75306209-577d2200-5883-11ea-934d-2adae309d827.png)

- 重现步骤：
登录即可重现。

**Comment by zhufeng** [comment]
![_20200226103125](https://user-images.githubusercontent.com/1539043/75306790-05d59700-5885-11ea-988d-e5a52b78ecf2.png)
传图好像一直失败？

**Comment by ronggang** [comment]
抱歉，暂时无法测试这两个站。

**Comment by zhufeng** [comment]
> 抱歉，暂时无法测试这两个站。

需要我怎么协助测试呢

**Comment by ronggang** [comment]
如果可以的话，自己查看一下具体的HTML代码，尝试找到相应内容来做一下匹配？

**Comment by zhufeng** [comment]
最新版v1.5.0使用moz开发者中心自签名版，安装在firefox android play版v68.11.0已经解决这两个站点的问题。

hdcity是直接可以用了，可能是v1.5.0新版修复了这个问题。
然后hdroute解决方法是，在站点的CDN里面添加一行 域名/#，即强制使用桌面版布局，然后刷新即可。

**Comment by ted423** [comment]
@zhufeng 吴昊绑定
