### ISSUE TITLE
M-Team网站搜索结果仅返回10行

### ISSUE THREAD

**Issue by ybjy82** [ronggang/PT-Plugin-Plus#452]
- PT 助手版本: 1.4.7 
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Edge
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：无
- 问题描述：按帮助设置m-team返回种子数后, pt助手依旧仅返回10行结果

- 相关截图：
![image](https://user-images.githubusercontent.com/39933692/75421184-a656b480-5974-11ea-8930-7601f4dcdb14.png)
![image](https://user-images.githubusercontent.com/39933692/75421223-be2e3880-5974-11ea-9d1d-0af2c680b69e.png)

- 重现步骤：

**Comment by ted423** [comment]
@ybjy82 请检查助手设置。。
