### ISSUE TITLE
点击下载所有种子下载失败

### ISSUE THREAD

**Issue by 00lingsui** [ronggang/PT-Plugin-Plus#455]
- PT 助手版本:v1.4.7
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome 版本 81.0.4044.17（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：点击下载所有种子，下载的是download.html,打开html文件显示invalid passkey

- 相关截图：

<img>https://s2.ax1x.com/2020/02/29/361Ivd.md.png</img>

- 重现步骤：点击右侧下载所有种子

**Comment by ted423** [comment]
建议检查助手的站点passkey设置

**Comment by cybmzy** [comment]
之前也试过这个情况。有可能是pt站点第一次需要手动点击下载按钮，进入一个说明界面。看过之后才能真正得到种子下载地址。
