### ISSUE TITLE
对所有PT站点中重复率最高的种子检索

### ISSUE THREAD

**Issue by Latezly** [ronggang/PT-Plugin-Plus#459]
## 您的功能请求是否与问题有关？ 请描述一下。

例如《国家地理》A、B这种大包，在绝大多数PT站内都会转发
在用户80%已登录站点的里面都有重复的种子单独搜索列出来
## 描述你想要的解决方案

emmmmm或许直接对所有站点全盘搜索过于暴力，可以尝试以机器学习的方式在本地/云端逐渐记录每个站点重复（包括但不限于种子名称、文件大小、hash值）的种子
对每个PTPP用户的所有站点中正在做种的重复种子进行记录，列出一份在所有站点中重复率最高的种子表格供其他PTPP用户参照下载辅种

## 其他附加信息

这个功能的实际意义可能不是很大，无非用最少的硬盘占用换取更多的做种体积，但还是想听一下开发者和其他用户的意见，以及有没有什么可以优化的方案来实现

**Comment by Rhilip** [comment]
一直以来，这种重复判断都不是PTPP的目标。请尝试使用以下两个工具
- https://github.com/ledccn/IYUUAutoReseed
- https://github.com/tongyifan/Reseed-backend
