### ISSUE TITLE
HDChina，下载链接貌似不对

### ISSUE THREAD

**Issue by rayle2** [ronggang/PT-Plugin-Plus#46]
- PT 助手版本: v1.0.0.19
- 浏览器名称及版本：chrome 72内核
- 问题描述：通过工具搜索出的条目，其他站点复制链接后添加到transmission web control里可以正常下载，HDChina无法成功添加。
- 相关截图：

**Comment by Rhilip** [comment]
删除该站的passkey试试

**Comment by rayle2** [comment]
请问是在站点里删掉，还是在插件里删掉

**Comment by Rhilip** [comment]
插件的站点设置中删除。

**Comment by ronggang** [comment]
原来站点改内容了啊。

**Comment by lhbill** [comment]
好像还是有这个问题，插件里没有设置passkey，hdchina中提示“获取下载链接失败”，其他站正常

**Comment by ronggang** [comment]
由于HDChina修改了下载链接，需要重新适配，下一版本会改进。

**Comment by ronggang** [comment]
已修复
2d2607ad5d8591af924434bd2d511df69558cde5
358910285921114015ba8a4fbb669e948f439164

**Comment by pwbty** [comment]
HDchina还是不行的，最新的1.0.3版本，重新添加网站也不行，还是返回404

**Comment by ronggang** [comment]
@pwbty 在站点设置把密钥要去掉再试一下。

**Comment by ronggang** [comment]
> HDchina还是不行的，最新的1.0.3版本，重新添加网站也不行，还是返回404

经测试，目前在HDChina的种子列表的资源标题上点击右键无法正常推送，可以尝试在下载图标上点击右键进行推送，其他功能应该都可以正常使用。
