### ISSUE TITLE
firefox自定义字体后PT-Plugin-Plus界面显示错乱

### ISSUE THREAD

**Issue by foxconndmd** [ronggang/PT-Plugin-Plus#460]
- PT 助手版本:1.4.7
- PT 助手安装方式：市场安装
- 浏览器名称及版本：firefox 68.5
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
firefox自定义字体且忽略页面的选择时PT-Plugin-Plus界面显示字体错乱

- 相关截图：
![2020-03-04_164121](https://user-images.githubusercontent.com/1817391/75861228-0eefd680-5e38-11ea-8cd6-cb8340b9c1aa.jpg)
![2020-03-04_164244](https://user-images.githubusercontent.com/1817391/75861237-11eac700-5e38-11ea-9a87-107be01d5ac3.jpg)

- 重现步骤：

**Comment by ted423** [comment]
@foxconndmd 我感觉这个得找firefox..?

**Comment by foxconndmd** [comment]
> 
> 
> @foxconndmd 我感觉这个得找firefox..?

除了PT-Plugin-Plus其它扩展web界面都显示正常。

**Comment by ted423** [comment]
好吧，没看图，没看到你改了等宽字体
我这里没有yahei mono这个字体。
就网上下了->https://github.com/whorusq/sublime-text-3/blob/master/fonts/Microsoft-Yahei-Mono.ttf

![image](https://user-images.githubusercontent.com/7042766/75862967-b4a44500-5e3a-11ea-9882-d29e4455d86f.png)
![image](https://user-images.githubusercontent.com/7042766/75862995-bec64380-5e3a-11ea-8a35-3e06b967c182.png)
但我这改了后似乎还正常
我用的最新的

**Comment by foxconndmd** [comment]
> 
> 
> 好吧，没看图，没看到你改了等宽字体
> 我这里没有yahei mono这个字体。
> 就网上下了->https://github.com/whorusq/sublime-text-3/blob/master/fonts/Microsoft-Yahei-Mono.ttf
> 
> ![image](https://user-images.githubusercontent.com/7042766/75862967-b4a44500-5e3a-11ea-9882-d29e4455d86f.png)
> ![image](https://user-images.githubusercontent.com/7042766/75862995-bec64380-5e3a-11ea-8a35-3e06b967c182.png)
> 但我这改了后似乎还正常
> 我用的最新的

和我自定义的等宽字体没关系，重要的是不要选择允许页面选择自己的字体代替您的上述选择。

**Comment by ted423** [comment]
> > 好吧，没看图，没看到你改了等宽字体
> > 我这里没有yahei mono这个字体。
> > 就网上下了->https://github.com/whorusq/sublime-text-3/blob/master/fonts/Microsoft-Yahei-Mono.ttf
> > ![image](https://user-images.githubusercontent.com/7042766/75862967-b4a44500-5e3a-11ea-9882-d29e4455d86f.png)
> > ![image](https://user-images.githubusercontent.com/7042766/75862995-bec64380-5e3a-11ea-8a35-3e06b967c182.png)
> > 但我这改了后似乎还正常
> > 我用的最新的
> 
> 和我自定义的等宽字体没关系，重要的是不要选择允许页面选择自己的字体代替您的上述选择。

试了下确实是，并且看了下ublock用fontawesome没受影响
然后看这里
https://material.io/resources/icons/?style=baseline

你用这设置访问这里就明白了。
简言之就是FF 的这个设置应该是排除了fontawesome （font family） 但遇上别的font-family就会抓瞎

总而言之，这个问题你还得找火狐。

**Comment by foxconndmd** [comment]
> 
> 
> > > 好吧，没看图，没看到你改了等宽字体
> > > 我这里没有yahei mono这个字体。
> > > 就网上下了->https://github.com/whorusq/sublime-text-3/blob/master/fonts/Microsoft-Yahei-Mono.ttf
> > > ![image](https://user-images.githubusercontent.com/7042766/75862967-b4a44500-5e3a-11ea-9882-d29e4455d86f.png)
> > > ![image](https://user-images.githubusercontent.com/7042766/75862995-bec64380-5e3a-11ea-8a35-3e06b967c182.png)
> > > 但我这改了后似乎还正常
> > > 我用的最新的
> > 
> > 
> > 和我自定义的等宽字体没关系，重要的是不要选择允许页面选择自己的字体代替您的上述选择。
> 
> 试了下确实是，并且看了下ublock用fontawesome没受影响
> 然后看这里
> https://material.io/resources/icons/?style=baseline
> 
> 你用这设置访问这里就明白了。
> 简言之就是FF 的这个设置应该是排除了fontawesome （font family） 但遇上别的font-family就会抓瞎
> 
> 总而言之，这个问题你还得找火狐。

谢谢，我设置为让页面选择字体吧。

**Comment by ted423** [comment]
@foxconndmd 我感觉可能火狐在字体判断上面有点锅的样子，你可以到这提个issue看看https://bugzilla.mozilla.org/

**Comment by foxconndmd** [comment]
> 
> 
> @foxconndmd 我感觉可能火狐在字体判断上面有点锅的样子，你可以到这提个issue看看https://bugzilla.mozilla.org/

谢谢回复，英文不行啊，将就用着吧。

**Comment by ted423** [comment]
抱歉，我又确认了下，Material Icons 是根据文字内容来显示图标的样子，跟font-awesome还不完全一样，锅也不全是FF的。

**Comment by foxconndmd** [comment]
> 
> 
> 抱歉，我又确认了下，Material Icons 是根据文字内容来显示图标的样子，跟font-awesome还不完全一样，锅也不全是FF的。

哦，大神看下可以修复不。

**Comment by ted423** [comment]
这个看作者愿不愿意换和觉得有没有必要换吧......

**Comment by foxconndmd** [comment]
> 
> 
> 这个看作者愿不愿意换和觉得有没有必要换吧......

没事，修不修都行。

**Comment by ronggang** [comment]
@foxconndmd 这个设置是不允许使用图标字体吗？
如果是这样，目前没有更新的打算，使用的框架本身就是依赖图标字体。

**Comment by foxconndmd** [comment]
> @foxconndmd 这个设置是不允许使用图标字体吗？
> 如果是这样，目前没有更新的打算，使用的框架本身就是依赖图标字体。

好的，谢谢回复。
