### ISSUE TITLE
MTeam站点的网址发生了变化，请求修改适配

### ISSUE THREAD

**Issue by 1580923067** [ronggang/PT-Plugin-Plus#461]
之前的网址：https://tp.m-team.cc/
已经改为了：https://pt.m-team.cc/
请求适配

**Comment by Rhilip** [comment]
半年前就修了，更新会吗？
https://github.com/ronggang/PT-Plugin-Plus/commit/189a7bfc6e5c243c084bb215d05d05dda9862f97
