### ISSUE TITLE
图标获取问题

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#463]
- PT 助手版本:dev
- PT 助手安装方式：crx
- 浏览器名称及版本：cent browser
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
我看基本所有站点图标都写得整个网址，
ao的图标网址是
https://aidoru-online.me/themes/default/images/favicon.ico

刷新图标时报错时这样的

![image](https://user-images.githubusercontent.com/7042766/76300323-7ce44400-62f7-11ea-8798-449ba73e2f27.png)

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
第一次的时候是好的，但我当时把host写错了，改正后就不行了...
这么写也一样""icon": "/themes/default/images/favicon.ico","

**Comment by ronggang** [comment]
@ted423 把 `icon` 属性去掉，让程序自动处理试一下，如果之前已缓存了，在站点设置的地方，点击站点图标可以重新获取当前站点的图标。

**Comment by ted423** [comment]
> @ted423 把 `icon` 属性去掉，让程序自动处理试一下，如果之前已缓存了，在站点设置的地方，点击站点图标可以重新获取当前站点的图标。

重新获取一样，就是会多加一遍域名

**Comment by ronggang** [comment]
> > @ted423 把 `icon` 属性去掉，让程序自动处理试一下，如果之前已缓存了，在站点设置的地方，点击站点图标可以重新获取当前站点的图标。
> 
> 重新获取一样，就是会多加一遍域名

那应该是代码逻辑有问题，下次我检查一下。

**Comment by ted423** [comment]
> > > @ted423 把 `icon` 属性去掉，让程序自动处理试一下，如果之前已缓存了，在站点设置的地方，点击站点图标可以重新获取当前站点的图标。
> > 
> > 
> > 重新获取一样，就是会多加一遍域名
> 
> 那应该是代码逻辑有问题，下次我检查一下。

不写icon网址也是获取这个....https://aidoru-online.me/https://aidoru-online.me/themes/default/images/favicon.ico]

**Comment by ted423** [comment]
初次添加是显示的，但手动重新获取下，图标就会消失
目前是浏览器重启下图标也会消失
