### ISSUE TITLE
HDArea无法搜索

### ISSUE THREAD

**Issue by a550996508** [ronggang/PT-Plugin-Plus#465]
- PT 助手版本:1.47
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：HDArea无法搜索 站点设置里有这个站点 但是搜索的时候这个站点显示无种子列表或没有种子
 

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@a550996508 这个问题已于dev里修复了

**Comment by a550996508** [comment]
大佬求教下怎么解决 我下载的是最新的1.47版本

**Comment by a550996508** [comment]
甚至这个站点的数据也是无法刷新显示的

**Comment by ted423** [comment]
@a550996508 还没有release,在cdn里使用带www的网址

**Comment by Rhilip** [comment]
see https://github.com/ronggang/PT-Plugin-Plus/issues/464

**Comment by zhufeng** [comment]
1.4.8版hdarea直接加载不了数据了，现在提示“暂不支持”

**Comment by ted423** [comment]
@zhufeng 删掉重加

**Comment by ronggang** [comment]
抱歉，几个月没登录，HDArea 的账号被禁用，无法测试。
