### ISSUE TITLE
截止2020.3.18火狐版插件下架，请问还会上架吗

### ISSUE THREAD

**Issue by EAPermanent** [ronggang/PT-Plugin-Plus#467]
## 您的功能请求是否与问题有关？ 请描述一下。

你好，截止2020.3.18火狐版插件下架了

## 描述你想要的解决方案

请问还会上架吗？感谢作者的作品，很好用！
好的，已经收到回复，谢谢作者

**Comment by ted423** [comment]
@EAPermanent 作者本人回复 ：各位，因本人近期事务繁忙，未能及时处理助手相关事宜，一个多月没有查看邮件和群消息，导致助手在FF没有提交被审核内容而被下架，在此对受影响的同学说声抱歉；FF上应该会在近期重新提交。

**Comment by FPGA1988** [comment]
无法手动安装吗？

**Comment by ddxn365t** [comment]
昨天弄了半天也没装上 ，手动不会安装啊 360浏览器安装被拦截了

**Comment by zhufeng** [comment]
4/1今天搜了下好像又下架了。。。前几天应该是重新上架了。

**Comment by ronggang** [comment]
抱歉，近期 FF 也和 Chrome 类似，涉及审核问题，正在尝试沟通询问具体原因，如果是因为一些版权问题，以后可能也不能上市场。

**Comment by Rhilip** [comment]
refs: https://github.com/ronggang/PT-Plugin-Plus/issues/491
