### ISSUE TITLE
北洋 想使用原生页面的 复制功能

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#469]
- PT 助手版本:dev
- PT 助手安装方式：crx
- 浏览器名称及版本：cent browser
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
原生是写在a的data-clipboard-text属性里，
但是工具条似乎只会看schemas里的设置
site里写似乎没效果
```
  "/details.php": {
	"merge": true,
    "fields": {
      "downloadURL": {
        "selector": ["a#direct_link"],
        "filters": ["query.attr('data-clipboard-text')"]
      }
    }
  }
```

- 相关截图：
![image](https://user-images.githubusercontent.com/7042766/77045620-8ad34c80-69fc-11ea-9219-65585770de08.png)

- 重现步骤：

**Comment by ronggang** [comment]
@ted423 用你的配置试了一下，可以正常使用页面原生的复制功能。

**Comment by ted423** [comment]
> @ted423 用你的配置试了一下，可以正常使用页面原生的复制功能。

能贴出来你改后的那个config么，我这咋弄都没passkey

**Comment by ronggang** [comment]
> > @ted423 用你的配置试了一下，可以正常使用页面原生的复制功能。
> 
> 能贴出来你改后的那个config么，我这咋弄都没passkey

其他内容都不变，就在最后添加：
```json
  "selectors": {
    "/details.php": {
      "merge": true,
      "fields": {
        "downloadURL": {
          "selector": ["a#direct_link"],
          "filters": ["query.attr('data-clipboard-text')"]
        }
      }
    }
  }
```
然后重新编译就可以了。

**Comment by ted423** [comment]
@ronggang 看起来是因为我外面少框了个selectors🌚
