### ISSUE TITLE
反馈 新增个人信息获取功能 bug

### ISSUE THREAD

**Issue by hylbbba** [ronggang/PT-Plugin-Plus#47]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

- PT 助手版本:1.0.0.19
- 浏览器名称及版本：360浏览器10.0.1634.0 ,Chrome 内核版本63.0.3239.132
- 问题描述：
1、新增加的获取站点个人信息功能，部分站点已登录，但插件内显示状态为未登录，无法获取数据，具体有：HDArea、HDCity、hdstreet、HDU、PTHome。
2、HD-Torrents，无数据，无状态显示。

- 相关截图：在2楼

**Comment by hylbbba** [comment]
[img]https://www.z4a.net/images/2019/03/06/_20190306122536.jpg[/img]

**Comment by fan-cy** [comment]
OpenCD也是

**Comment by hylbbba** [comment]
> OpenCD也是

我皇后倒是正常的

**Comment by ronggang** [comment]
@hylbbba 你说的这些站（HDArea、HDCity、hdstreet、HDU、PTHome）目前我还没办法测试
HD-Torrents [已适配](https://github.com/ronggang/PT-Plugin-Plus/commit/30c24b0c90b8a56ed3e92fe1741b8e2839f836e3)，还未发布。

近期会把个人信息适配的定义方法整理，理顺之后会做成说明文档，方便大家参与编辑适配。

**Comment by ronggang** [comment]
@hylbbba 1.0.4版应该可以正常获取这些站点的信息，主题先关闭，如有疑问再重新开。
