### ISSUE TITLE
电脑上的pt助手不能搜索烧包和LeagueHD资源

### ISSUE THREAD

**Issue by dffg10** [ronggang/PT-Plugin-Plus#470]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
我这正常
