### ISSUE TITLE
天雪站无法识别保种体积

### ISSUE THREAD

**Issue by aclihub** [ronggang/PT-Plugin-Plus#473]
- PT 助手版本:v1.4.7
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：chrome 80.0.3987.122（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：天雪站无法识别保种体积，显示为N/A

- 相关截图：
![t](https://user-images.githubusercontent.com/54567707/77735427-84208700-7045-11ea-97c1-72362ecd5bc8.png)

- 重现步骤：无

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/205
