### ISSUE TITLE
红的搜索结果改善

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#476]
- PT 助手版本: dev
- PT 助手安装方式：crx
- 浏览器名称及版本：cent browser
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
红的话，通过ajax返回的信息不包含版本名。
部分有remasterTitle可以获取到一些信息，但是不少虽然有不同版本，remasterTitle确是空的
如Erofex - Time Travellers
页面可以看到− Unconfirmed Release / Neurotrance Records / WEB
和− 2013 - Neurotrance ‎Records / NEURO045 / WEB

Various Artists - Frozen [2013] [Soundtrack]
其中有各语言的版本，版本名还是比较重要的，否则看到一堆FLAC完全不知道具体信息。
所以个人感觉改为html搜索会比较好？

working on it

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
试了下用这个，虽然有结果但是会报错没显示
```  "searchEntryConfig": {
    "page": "/torrents.php?searchstr=$key$&searchsubmit=1",
    "resultType": "html",
    "parseScriptFile": "getSearchResult.js",
    "resultSelector": "table.torrent_table:last > tbody > tr"
  },```

模板改Gallze的话，有结果，但是数据获取就有问题。

而api获取种子信息和组ID里似乎都没有相应信息

另外看了下Json API，似乎torrent和 group的返回都不包含

**Comment by ronggang** [comment]
html 有些内容无法获取，而且处理方式更难。

**Comment by ted423** [comment]
@ronggang 我看了下API，只有group 和torrent的那个能获取到remasterlabel啥的，能比较好的分辨下版本

**Comment by ronggang** [comment]
好，近期抽空再研究一下。

**Comment by ted423** [comment]
看了下 最新的已经有了，应该是后面有更新？
但是搜索结果没显示remasterTitle，所以加上大概会直接点
