### ISSUE TITLE
MoeCat种子详情页使用助手工具栏下载的种子不正确

### ISSUE THREAD

**Issue by cnRuanYF** [ronggang/PT-Plugin-Plus#477]
- PT 助手版本: 1.4.7
- PT 助手安装方式：Microsoft Edge 市场安装
- 浏览器名称及版本：Microsoft Edge 80
- 浏览器是否安装了其他插件：true
- 停用其他插件后是否正常工作：false
- 问题描述：
在MoeCat的种子详情页中，使用助手的工具栏一键发送到下载服务器，实际添加的任务并非该种子
- 重现步骤：
使用助手的工具栏复制下载链接，和页面中的链接比对，发现助手添加的下载链接是详情页中[其他版本]的第一个种子

**Comment by ronggang** [comment]
好久没上 MoeCat ，想上去测试一下，今天上去 403 ，拆门了吗？
如果是因为页面排版问题，需要调整一下获取下载链接的参数。

**Comment by ted423** [comment]
@ronggang 要在他们tg群找管理要临时连接 @CCCCCat

**Comment by ronggang** [comment]
> @ronggang 要在他们tg群找管理要临时连接 @Cccccat

好的，我上一下TG
