### ISSUE TITLE
HDSky种子下载错误

### ISSUE THREAD

**Issue by zl0662** [ronggang/PT-Plugin-Plus#48]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

- PT 助手版本: 1.0.0.19
- 浏览器名称及版本：Chrome  72.0.3626.121
- 问题描述：HDSky种子无法直接下载，跳转网页

No hacking allowed!This method allows POST request only. | This method allows POST request only.
-- | --
This method allows POST request only.

- 相关截图：

**Comment by Rhilip** [comment]
已知问题，能补充说明下是在什么操作（插件页搜索？网站工具栏？）中出现的下载问题吗？方便我们快速定位
