### ISSUE TITLE
在 Firefox市集找不到 1.4.8 版PT Plugin Plus

### ISSUE THREAD

**Issue by happyda** [ronggang/PT-Plugin-Plus#481]
在Firefox Add-on 市集已無法找到 PT Plugin 

- PT 助手版本: 1.4.7
- PT 助手安装方式：市場（市场安装，或zip包安装）
- 浏览器名称及版本：Firefox 74.0
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：無
- 问题描述：
另一台機器firefox 使用的pt plugin 1.4.7 ，移除後想安裝新的 1.4.8 卻在市集遍尋不到 
使用站內wiki 內的連結得到同樣結果。

- 相关截图：
![圖片](https://user-images.githubusercontent.com/3788126/78412715-f1847700-7646-11ea-9796-46c7ca841d8d.png)

- 重现步骤：

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/467

**Comment by Rhilip** [comment]
refs: https://github.com/ronggang/PT-Plugin-Plus/issues/491
