### ISSUE TITLE
请问如何在 Firefox 中手动安装呢？zip 拖进去显示 corrupted

### ISSUE THREAD

**Issue by aur3l14no** [ronggang/PT-Plugin-Plus#482]
既然无法上架，想请教一下手动安装的方式

**Comment by ronggang** [comment]
如果一定要手动安装，暂时只能以调试的方式进行
1、解压zip文件；
2、在 FF 地址栏输入 `about:debugging#/runtime/this-firefox`；
3、点击 `临时载入附加组件`；
4、选择 zip 解压后的目录中的 `manifest.json` 文件即可使用；

**Comment by CoderCore** [comment]
> 
> 
> 如果一定要手动安装，暂时只能以调试的方式进行
> 1、解压zip文件；
> 2、在 FF 地址栏输入 `about:debugging#/runtime/this-firefox`；
> 3、点击 `临时载入附加组件`；
> 4、选择 zip 解压后的目录中的 `manifest.json` 文件即可使用；

如果不手动安装，还有什么更简单的安装方法吗？

**Comment by CoderCore** [comment]
> 
> 
> 既然无法上架，想请教一下手动安装的方式

https://github.com/ronggang/PT-Plugin-Plus/issues/491
