### ISSUE TITLE
搜索结果torrentleech不显示免费种

### ISSUE THREAD

**Issue by xcehnz** [ronggang/PT-Plugin-Plus#483]
- PT 助手版本:  v1.4.8 
- PT 助手安装方式：zip安装
- 浏览器名称及版本：chrome 80.0.3987.163
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
搜索结果torrentleech不显示免费种
- 相关截图：
![Snipaste_2020-04-04_18-27-06.png](https://i.loli.net/2020/04/04/S5sLyVcT7CMN4AJ.png)

- 重现步骤：
搜索 Bloodshot，例如这个[免费种](https://www.torrentleech.org/torrent/1590902) 不显示免费

**Comment by ted423** [comment]
@xcehnz fl免费是后改的,大概没适配
