### ISSUE TITLE
HDD无法搜索，自定义添加提示暂不支持

### ISSUE THREAD

**Issue by AntonLavoisier** [ronggang/PT-Plugin-Plus#485]
- 站点名称：HDD
- 站点地址：https://hddisk.life/
- 站点描述：影视，综合

- 资源类型：
- 开放注册：否
- 是否连坐：否
- 站点规则：

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/78859154-20dd1e80-7a61-11ea-88ce-9daa3268bb44.png)
我这正常，建议检查你的本地设置
