### ISSUE TITLE
分享一个firefox安装方法(非临时安装，可账号同步)

### ISSUE THREAD

**Issue by CoderCore** [ronggang/PT-Plugin-Plus#491]
前往 addons.mozilla.org 注册开发者账号，进入开发者中心，提交新的附加组件，选择我自己托管，待审核通过后，下载签名过的xpi文件即可正常安装，而且可以随账号同步。

**Comment by yjcn** [comment]
感谢老哥分享~  刚试了确实可以

**Comment by Raabo** [comment]
(下载签名过的xpi文件即可正常安装)这个步骤怎么弄的呢

**Comment by CoderCore** [comment]
> 
> 
> (下载签名过的xpi文件即可正常安装)这个步骤怎么弄的呢

找自己发布的插件列表，点进去查看所有版本

**Comment by Raabo** [comment]
> 
> 
> > (下载签名过的xpi文件即可正常安装)这个步骤怎么弄的呢
> 
> 找自己发布的插件列表，点进去查看所有版本

谢谢老哥

**Comment by Rhilip** [comment]
由于Wiki中已经补充该方法链接，故关闭
