### ISSUE TITLE
北洋种子详情页面 无法获取到下载服务器

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#492]
- PT 助手版本:1.4.8
- PT 助手安装方式：crx
- 浏览器名称及版本：cent
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
貌似我的锅,测了下1.4.7没问题，一升级就挂了
种子列表处下载到就有下载服务器显示
- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
试了下，几个自定义下载链接的，HDA和萌猫都没问题，就北洋出问题

**Comment by ted423** [comment]
试了下，自定义cdn加上www后正常，目测跟脚本跑着跑着option.url多了个www有关

**Comment by ted423** [comment]
好吧，不是跑着跑着就变成www,而是点我复制里的连接就是www的，然后脚本发现域名对不上就炸了

**Comment by RtYkk** [comment]
@ted423 我也是这个问题，以为没适配就懒得管（
