### ISSUE TITLE
1PTBAR -NexusPHP架构请求支持

### ISSUE THREAD

**Issue by joyist2018** [ronggang/PT-Plugin-Plus#493]
- 站点名称：1PTBAR
- 站点地址：https://1ptba.com/
- 站点描述：壹PT吧,PT下载,教育视频,课件资源,发布教育类,学习类,纪录片等资源
- 站点架构：NexusPHP

- 资源类型：影视, 纪录片, 综合
- 开放注册：是
- 是否连坐：否
- 站点规则：些部分HR标记

**Comment by ted423** [comment]
@joyist2018 1、在发起请求前，请先确认是否在已支持的架构内； 
2、如果在已支持的架构内，本主题将会被视为无效并关闭；
