### ISSUE TITLE
UHDBits自动变成HDBits的favicon

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#498]
- PT 助手版本: 1.4.8
- PT 助手安装方式：crx
- 浏览器名称及版本：Chrome  81.0.4044.113（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
UHDBits图标自动变成HDBits的，进去站点设置单独重置站点图标缓存后恢复正常，过一段时间又会变到HDBits的。

- 相关截图：
![Snipaste_2020-04-21_09-14-07](https://user-images.githubusercontent.com/35324456/79814308-7f36c500-83b0-11ea-9b28-b305a9262ff2.png)

========
补充一点，Blutopia也会自动变为AsianCinema的图标，重新获取后正常，一段时间后会自己改变。

**Comment by ted423** [comment]
可能我无后者的号所以不会出这个问题？

**Comment by luckiestone** [comment]
> 可能我无后者的号所以不会出这个问题？

要不添加上去试试？没号不能登陆，图标正常获取，不知道会不会也会有bug。

**Comment by ted423** [comment]
@luckiestone 好吧...你是对的。

**Comment by ronggang** [comment]
刚试了一下，试不出来，不知道如何才能复现？

**Comment by ted423** [comment]
好吧，机器人又挂了

> 刚试了一下，试不出来，不知道如何才能复现？

我这加了hdb然后重启了下浏览器，uhd图标就变蓝了

**Comment by luckiestone** [comment]
> 刚试了一下，试不出来，不知道如何才能复现？

像楼上大佬说的那样，都加进站点试下，可能有一定概率图标会变。我目前发现的事UHDBits变HDBits，Blutopia变Asiancinema。除图标之外，我还发现比如收藏了HDB的搜索结果加入某分组。查看该分组收藏结果时，该种子来源链接后方的来源站点会变成UHDBits。不仅是图标变掉，文字和超链接都变成UHDBits主页，但是前面种子详情仍然还是HDB的，没有出错。

**Comment by ronggang** [comment]
我用以下步骤试了，试不出来。🤣🤣
浏览器版本：Microsoft Edge 版本 83.0.478.10 (官方内部版本) Dev (64 位)
- 添加 `UHDBits` 和 `HDBits` 站点；
- 关闭浏览器；
- 重新打开浏览器；
- 打开助手；
- 打开站点设置，图标没有变

**Comment by ted423** [comment]
@ronggang

**Comment by luckiestone** [comment]
=====更新=====
之前edge都没问题，刚才edge中UHD也变成HDB的图标了。还有就是最近图标获取改方式了？FL和IPT的图标总是裂掉，需要重新再站点设置页手动重新获取下。

**Comment by ted423** [comment]
@ted423 猜测跟站点添加顺序有关
