### ISSUE TITLE
开机后第一次不出现插件，重启chrome后才出现

### ISSUE THREAD

**Issue by cani1see** [ronggang/PT-Plugin-Plus#5]

**Comment by ronggang** [comment]
是指在网页中显示的插件图标及一些命令按钮吗？

**Comment by cani1see** [comment]
对

**Comment by cani1see** [comment]
@ronggang 对 似乎新版本1.0.8是好的 我先看看

**Comment by ronggang** [comment]
@cani1see 这个问题比较麻烦，显示图标需要满足以下条件：
1. 已成功从Github获取资源信息；
2. 当前页面加载完成后（包括图片、样式文件等）才会加载插件图标；

所以一旦网络连接不顺利时，图标可能就出不来了。

**Comment by ronggang** [comment]
@cani1see 请更新到最新版再观察问题是否还存在，主题暂时关闭，有需要再打开。
