### ISSUE TITLE
搜索MTV如无结果，插件返回为失败站点

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#503]
- PT 助手版本: 一直存在
- PT 助手安装方式：crx
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
目前Morethan.TV站点搜索时，如果无该搜索结果，插件搜索返回为失败站点，但应该是无结果站点。
比如响应为：
{"status":"success","response":{"results":[],"youMightLike":["short","animation","biography","comedy","autoup","family","drama","horror"]}}
时，按照GazelleJsonAPI搜索脚本，应该返回的是无结果。
没有定位到具体问题，需要帮助。

- 相关截图：

- 重现步骤：
搜索MorethanTV站点没有的种子。

**Comment by Rhilip** [comment]
MTV现在全站无种子，先close了
