### ISSUE TITLE
装了pt助手后chrome无法打开tr页面

### ISSUE THREAD

**Issue by qy19920913** [ronggang/PT-Plugin-Plus#504]
- PT 助手版本:1.48
- PT 助手安装方式：（市场安装，或zip包安装） cxr
- 浏览器名称及版本：chrome 81.0.4044.122（正式版本） （64 位）
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：正常
- 问题描述：
第一次安装pt助手正常，突然有一天不工作了。chrome没有由贵单位管理这个原因估计。重新按步骤。正常工作 _但是chrome无法打开群辉的TR  XXX.XXX.XXX.XXX:9091_这个页面 打开一片空白 更换edge浏览器正常打开 

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
请检查其他，比如密码是不是输错了，与这个扩展无关…

**Comment by Rhilip** [comment]
鉴于Transmission管理页面与本插件无关，且无更明确反馈，该issue关闭。
