### ISSUE TITLE
馒头电影综合板块搜索出错

### ISSUE THREAD

**Issue by shuer001** [ronggang/PT-Plugin-Plus#51]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

- PT 助手版本:1.0.2
- 浏览器名称及版本：Google浏览器72.0.3626.121
- 问题描述：mteam 馒头。搜索综合与电影的种子不成功， 当成人音乐板块没有问题。
- 相关截图：
无

**Comment by ronggang** [comment]
@shuer001 你好，感谢反馈。
但是我没办法复现，可否提供一下错误日志。

**Comment by shuer001** [comment]
你好，很奇怪，成人音乐分类没问题。概览也能获取正确信息。但综合 与电影搜索不行。
[M-Team]获取种子信息出错: TypeError: Cannot read property 'split' of undefined at Parser.getSubTitle (eval at <anonymous> (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/js/background.js:1:250923), <anonymous>:269:45) at Parser.getResult (eval at <anonymous> (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/js/background.js:1:250923), <anonymous>:189:28) at eval (eval at <anonymous> (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/js/background.js:1:250923), <anonymous>:314:28) at eval (eval at <anonymous> (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/js/background.js:1:250923), <anonymous>:316:3) at Object.<anonymous> (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/js/background.js:1:250923) at u (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/libs/jquery/jquery-3.3.1.min.js:2:27457) at Object.fireWith [as resolveWith] (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/libs/jquery/jquery-3.3.1.min.js:2:28202) at k (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/libs/jquery/jquery-3.3.1.min.js:2:77651) at XMLHttpRequest.<anonymous> (chrome-extension://ljklladjiefhalgbkegclhnikfehfial/libs/jquery/jquery-3.3.1.min.js:2:79907)

**Comment by Rhilip** [comment]
能否提供下搜索关键词？

**Comment by shuer001** [comment]
[https://i.loli.net/2019/03/18/5c8f4bd3ec9ba.png
](url)     每个电影综合搜索都会提示错误。其它站不会。

**Comment by ronggang** [comment]
@shuer001 应该是由搜索方案引起的Bug，下一版本会修复，感谢反馈
