### ISSUE TITLE
AsianCinema无法刷新数据，显示为未登录

### ISSUE THREAD

**Issue by AShine0720** [ronggang/PT-Plugin-Plus#514]
- PT 助手版本:1.4.8
- PT 助手安装方式：市场安装/zip压缩包安装
- 浏览器名称及版本：Edge 81.0.416.72(64bit)/Chrome 81.0.4044.138(64bit)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
在已登录AsianCinema的前提下，点击AsianCinema的图标刷新个人数据时，无法刷新出个人数据，并且会显示未登录，但事实上已登录，点击站点名称能够正常跳转，打开的站点也是登录后的界面。印象中这个问题是在升级到1.4.8以后才出现的。
- 相关截图：
https://picgd.com/image/m56lA
https://picgd.com/image/m5IqY
- 重现步骤：
在已登录AsianCinema的前提下，点击AsianCinema的图标刷新个人数据

**Comment by ted423** [comment]
与助手版本无关，是acm最近更新网站模板导致的

**Comment by AShine0720** [comment]
> 与助手版本无关，是acm最近更新网站模板导致的

原来如此，那么会在下次更新修复么，还是可以直接通过更改设置修复？

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/pull/507

**Comment by moerfutin** [comment]
升级了1.4.9，显示登录AsianCinema了，但是无法刷新个人数据呢。有人和我一样吗
![image](https://user-images.githubusercontent.com/9960618/83962638-96cefc00-a8d1-11ea-9ef7-f383246cbce6.png)

**Comment by ted423** [comment]
> 升级了1.4.9，显示登录AsianCinema了，但是无法刷新个人数据呢。有人和我一样吗
> ![image](https://user-images.githubusercontent.com/9960618/83962638-96cefc00-a8d1-11ea-9ef7-f383246cbce6.png)

我这种正常了
