### ISSUE TITLE
u2 不顯示 上傳和下載數據量

### ISSUE THREAD

**Issue by winyiday** [ronggang/PT-Plugin-Plus#515]
- PT 助手版本: v1.4.8
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：u2 不顯示 上傳和下載量

- 相关截图：![圖](https://i.imgur.com/bTM4AON.png)

**Comment by RtYkk** [comment]
@winyiday 复现不了…我这里没问题

**Comment by Rhilip** [comment]
请问你的界面语言是俄语吗？
我试了下u2在界面语言是俄语情况是刷不出来的（应该不会做适配），但是简中、繁中、正体、英文的界面语言设置下都是没有问题的。
另外请贴图告知下 此页面 `域名/usercp.php?action=tracker`（控制面板-网站设定）的配置。

**Comment by winyiday** [comment]
@RtYkk @Rhilip 
谢谢！已经解决了
只有上传量，没有下载量的话就不会显示
