### ISSUE TITLE
搜索结果BUG

### ISSUE THREAD

**Issue by 786745168** [ronggang/PT-Plugin-Plus#52]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

- PT 助手版本:1.0.2
- 浏览器名称及版本：72.0.3626.121
- 问题描述：1.M-Team的搜索结果是没有电影分类的
                     2.搜索结果出来后，TTG的下载种子文件到本地，种子命名只有种子编号
                     3.OpenCD的站点设置里未允许搜索，但是搜索后仍会显示无结果
- 相关截图：

另
非常感谢您开发了这个插件，对您的无私付出感到钦佩，对您的卓越水平感到赞叹！
提一两个小小的建议，能否添加种子时可以选择文件下载目录和跳过散列检测
我使用此插件主要是搜索下载到想要的资源后，通过插件的一键下载功能便捷辅种，但目前还是只能搜索种子后手动添加
当然这都是我的个人想法，且不知道实现难度，若有不到之处，还请见谅

**Comment by frank777777777** [comment]
除非你自己发种能保证文件没改过。
你辅别人的种，即使文件名相同，你也不知道他是不是在视频里多加了一条字幕，改动了nfo, 改变了文件结构等等。
遇到那种改动了文件的发种人，这样无脑一键跳过检验容易导致被警告或者ban....

**Comment by ronggang** [comment]
@786745168 感谢反馈。
1. 你说的没有分类是指没有正常显示分类吗？
2. TTG 因直接使用了RSS接口，所以保存的种子只有编号，后续改进吧。
3. 我没办法重现，另外站点设置不允许搜索仅对<默认>方案可用，其他自定义方案会以实际选择的为准。
4. 关于选择下载目录会在后续版本中加入。
5. 跳过校验一般不建议，所以近期应该不会加入，谢谢。

**Comment by Rhilip** [comment]
关于保存种子，能不能实现就是使用bencode相关库，从种子自带信息中获取name信息。
但是这样需要劫持下载操作，感觉不是很必要为特定一个站点构造这种方法。

**Comment by ronggang** [comment]
> 关于保存种子，能不能实现就是使用bencode相关库，从种子自带信息中获取name信息。
> 但是这样需要劫持下载操作，感觉不是很必要为特定一个站点构造这种方法。

目前应该不需要加这功能，只要按原始下载链接保存，应该会有文件名。

**Comment by 786745168** [comment]
> @786745168 感谢反馈。
> 
> 1. 你说的没有分类是指没有正常显示分类吗？
> 2. TTG 因直接使用了RSS接口，所以保存的种子只有编号，后续改进吧。
> 3. 我没办法重现，另外站点设置不允许搜索仅对<默认>方案可用，其他自定义方案会以实际选择的为准。
> 4. 关于选择下载目录会在后续版本中加入。
> 5. 跳过校验一般不建议，所以近期应该不会加入，谢谢。

就是M-Team的搜索结果里面是没有电影和综合这两个版块的内容，譬如说，我搜指环王，显示的只有两个音乐文件
![image](https://user-images.githubusercontent.com/48416620/54103748-8eef8600-4408-11e9-8779-40c9a375f9a8.png)
