### ISSUE TITLE
filelist换域名了，自定义新加站点刷新数据无效

### ISSUE THREAD

**Issue by laobanbiefangcu** [ronggang/PT-Plugin-Plus#520]
- PT 助手版本: v1.4.8
- PT 助手安装方式：zip包
- 浏览器名称及版本：360极速浏览器/chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
域名为https://filelist.io/，自定义新加站点刷新数据无效

- 相关截图：
<img src="https://s1.ax1x.com/2020/05/17/YgHI7d.png" alt="YgHI7d.png" border="0" />

- 重现步骤：

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/pull/509

**Comment by Rhilip** [comment]
这也太锲而不舍了吧😂

**Comment by laobanbiefangcu** [comment]
> dupe: #509

搞错了，我的crx安装的
