### ISSUE TITLE
下载服务器不支持IPV6格式

### ISSUE THREAD

**Issue by ajogajog** [ronggang/PT-Plugin-Plus#521]
- PT 助手版本:1.48
- PT 助手安装方式：crx
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

下载服务器不能直接使用IPV6地址。

认为形如[24e::::]:端口  这样的格式不合法。

暂时可通过映射IPV6地址到DDNS域名解决。但鉴于现在公网ipv6已经普及，若能直接支持，则省去很多步骤。

- 相关截图：
![image](https://user-images.githubusercontent.com/24715878/82135329-1bc77800-9834-11ea-8c40-8c0f8621c781.png)

- 重现步骤：

**Comment by Rhilip** [comment]
看起来是因为我们对ipv6地址格式的正则存在问题
https://github.com/ronggang/PT-Plugin-Plus/blob/b01dd0687a397a56543bac8a6be546a0557e1a73/src/options/views/settings/Backup/Server/Editor.vue#L129-L135
https://github.com/ronggang/PT-Plugin-Plus/blob/eb90e4b453a45267aa65b5f7441be6e2f62813a2/src/options/views/settings/DownloadClients/Editor.vue#L92-L100

**Comment by ronggang** [comment]
的确原来是不支持ipv6，感谢R酱给出建议。
