### ISSUE TITLE
蒲公英种子发布时间显示问题

### ISSUE THREAD

**Issue by heyq14** [ronggang/PT-Plugin-Plus#525]
- PT 助手版本:1.4.9
- PT 助手安装方式：（市场安装，或zip包安装）市场安装
- 浏览器名称及版本：Microsoft Edge 83.0.478.37
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：无
- 问题描述：
蒲公英（NPUBits）种子发布时间只能显示为已去时间，无法参与按时间排序。
这一问题之前在葡萄也存在，1.4.9版本已修复，希望可以同样修复蒲公英。

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
![image](https://user-images.githubusercontent.com/13842140/82750019-fb715d80-9ddf-11ea-93b5-33b8b0a7b1e2.png)
无法复现。而且那我看到的这个是什么？
即使是已去时间，插件目前所用脚本也能提取到正确的时间值。

**Comment by heyq14** [comment]
是的，在蒲公英选择发生时间时正常，选择已去时间时会出现这个问题
