### ISSUE TITLE
天雪论坛无法一键下载

### ISSUE THREAD

**Issue by LogicDX342** [ronggang/PT-Plugin-Plus#526]
- PT 助手版本:1.4.9
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：chrome for mac 版本 81.0.4044.138（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：天雪论坛 https://www.skyey2.com/ 将种子拖入侧栏后提示正在发送下载链接，过数秒后消失，下载器也没有出现新任务

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
经测试在搜索页面有这问题。
另外建议以后汇报问题把问题描述清楚

**Comment by Rhilip** [comment]
不能复现，你应该拖动下载图标，而不是标题。
