### ISSUE TITLE
主页站点希望能添加自定义超链接

### ISSUE THREAD

**Issue by mjyhj** [ronggang/PT-Plugin-Plus#527]
## 您的功能请求是否与问题有关？ 请描述一下。
https://www.hdarea.co/
我添加了这个站，点开默认是打开这个链接，每次都会出现验证码
![1](https://user-images.githubusercontent.com/22577418/82729099-4b401e00-9d27-11ea-81d0-e9577aef4e1a.png)
但是我手动打开https://www.hdarea.co/index.php
则不需要验证码，直接进入该站

## 描述你想要的解决方案
希望能添加自定义的超链接，可以在PT-PULS里点击直接打开到我要的页面，也不是固定的主页
例如控制中心：https://www.hdarea.co/usercp.php
例如种子列表：https://www.hdarea.co/torrents.php

**Comment by Rhilip** [comment]
目前这块地址是使用CDN地址的，你可以在CDN地址中指定 `https://www.example.com/test.php`
但因此会导致该站点搜索和个人信息出现问题，所以目前看不可能进行修改。
也正如我在 #429 对于某站开启5秒盾的情况说明一样，我们尊重站点自身的保护需求。
但插件这边不可能因为一个站点的特殊情况，对所有进行更改。
