### ISSUE TITLE
春天站点刷新失败，已登录强制退出成未登录

### ISSUE THREAD

**Issue by ghost** [ronggang/PT-Plugin-Plus#528]
- PT 助手版本:1.4.9
- PT 助手安装方式：（市场安装，或zip包安装）CRX安装
- 浏览器名称及版本：Kiwi browser(手机) 77.0.3865.92 
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
添加春天站点，刷新数据显示未登录。登录后返回刷新仍显示未登录。打开春天发现已退出登录。
其他站点按上述操作结果正常。

- 相关截图：

- 重现步骤：
添加春天站点，刷新数据显示未登录。登录后返回刷新仍显示未登录。打开春天发现已退出登录。
其他站点按上述操作结果正常。

**Comment by Rhilip** [comment]
在其他浏览器环境下是否能够重现？本人目前在Edge（Chrome内核）、Chrome中均不能复现

**Comment by niceaigirl** [comment]
试了一下，其他浏览器环境下正常。应该就是这个手机浏览器的问题了。kiwi browser。但是其他站点都正常就春天不正常。大佬看心情吧。毕竟很小众了。

**Comment by rosystain** [comment]
我在平板上用kiwi无法进行授权，用yandex很完美没什么问题。

**Comment by RtYkk** [comment]
- PT 助手版本: 1.4.9
- PT 助手安装方式：zip
- 浏览器名称及版本：Cent Browser 版本 4.0.9.112（正式版本） （32 位） (portable) (Chromium 74.0.3729.169)
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：


- 相关截图：

![chrome_TDgVlEW5ea](https://user-images.githubusercontent.com/45971730/85036755-1654a900-b1b7-11ea-86cf-a61a3968832e.png)

- 重现步骤：
1、登录cmct
2、在助手中刷新数据
3、显示未登录
4、回到网站，cookie失效要求我重新登录。

**Comment by ted423** [comment]
春天这个很早就有反馈了，大概在春天出那个防止短期内大量访问的时候，后面就有人反馈

**Comment by RtYkk** [comment]
@ted423 但是我不用portable又没有这个问题

**Comment by RtYkk** [comment]
@RtYkk 经测试crx安装存在相同问题

**Comment by ronggang** [comment]
@ghost(什么鬼?) @RtYkk 是否使用过助手的Cookie恢复功能？如果是，请尝试清除春天站点的所有cookie，然后到春天手工重新登录后再回到助手试一下。

**Comment by RtYkk** [comment]
> @ghost(什么鬼?) @RtYkk 是否使用过助手的Cookie恢复功能？如果是，请尝试清除春天站点的所有cookie，然后到春天手工重新登录后再回到助手试一下。

没有。您可以自己拿portable/免安装版试试看。

> 1、登录cmct
2、在助手中刷新数据`
3、显示未登录
4、回到网站，cookie失效要求我重新登录。

就是我描述的这个操作。产生两个后果
1、刷新失败，显示未登录
2、cmct cookie失效。

**Comment by Rhilip** [comment]
已经与该站点Sysop联系并等待情况，
你这边能否看一下是浏览器Cookies丢失，还是Cookies存在但是被内部token被服务器注销。
也就是观察背景页请求，服务器有没有出现Set-Cookies的请求头，以及在刷新后，前台访问该站点的请求中有没有携带原有Cookies

**Comment by RtYkk** [comment]
背景页是指？调试信息吗？…

P.S. 该问题已知仅出现在 **免安装版(portable)/Kiwi Browser** 正常安装的chrome/edge都没有问题

**Comment by ted423** [comment]
> 背景页是指？调试信息吗？…
> 
> P.S. 该问题已知仅出现在 **免安装版(portable)/Kiwi Browser** 正常安装的chrome/edge都没有问题

就是开发者模式加载文件夹，扩展页面那会显示一个背景页，那里可以调试和显示一些debug log

**Comment by Rhilip** [comment]
Cent Browser Version 4.2.10.171 (Official Build) (32-bit) (portable) (Chromium 80.0.3987.163) 使用crx版本未能复现
![image](https://user-images.githubusercontent.com/13842140/85371663-355e8c80-b563-11ea-9fbc-5de8086cc679.png)

**Comment by Rhilip** [comment]
@RtYkk 你提及的 “Cent Browser 版本 4.0.9.112（正式版本） （32 位） (portable) (Chromium 74.0.3729.169)” 能够复现

![image](https://user-images.githubusercontent.com/13842140/85374730-c6376700-b567-11ea-9d9d-806c6e1072d0.png)

通过本人测试以及该站点Sysop帮忙，对问题进行确定。

由于站点在设置Cookies会添加Samesite=Lax信息，导致插件在chrome内核版本在77以下的浏览器无法发送该Cookies，随后被站点认为无Cookies访问，发送新的Session Cookies覆盖，登录信息丢失。

该问题影响到**所有chrome内核版本在77以下的浏览器**，请对应升级你所使用的浏览器。

由于该问题并非插件问题，且问题来自Chrome内核侧，添加Samesite也是为了Cookies安全，故标记为invalid

refs: https://stackoverflow.com/questions/51731231/chrome-extension-doesnt-send-samesite-lax-cookies

**Comment by Rhilip** [comment]
@Rhilip @oholack

**Comment by RtYkk** [comment]
我会及时更新我使用的cent portable以便适配最新的samesite cookie。至于kiwi用户，只能等kiwi更新了…刚刚专门下了个最新的GitHub release，仍在使用chromium 77。适配最新内核后，本问题将得到解决。

**Comment by ronggang** [comment]
感谢R酱及各位的测试，的确浏览器种类和版本太多，平时无法一一测试，各类问题只能到末端发现后大家一起排查才能解决，也谢谢大家的包容。
