### ISSUE TITLE
高清城市搜索hyouka vcb报错，疑似单条结果会出问题

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#529]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
似乎搜frds没问题，不过第一条丢了

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
两个都没号，有号的同学帮忙测试一下。

**Comment by ted423** [comment]
没事...我有空会自己看下的，现在是鸽制状态

**Comment by Rhilip** [comment]
应该和站点主题啥的有关系，这个站不同主题返回的页面格式很不相同

**Comment by tongyifan** [comment]
原始主题未能复现

**Comment by ted423** [comment]
> 原始主题未能复现

hdcity.city么？我才发现消息都没获取到

**Comment by tongyifan** [comment]
> > 原始主题未能复现
> 
> hdcity.city么？我才发现消息都没获取到

是的，如图

![Screenshot_20200622_210037.png](https://i.loli.net/2020/06/22/HGIgZas8tkAW5v7.png)

**Comment by tongyifan** [comment]
不过确实有个问题，label没有颜色，这个种子前面有个50%的label

**Comment by ted423** [comment]
> > > 原始主题未能复现
> > 
> > 
> > hdcity.city么？我才发现消息都没获取到
> 
> 是的，如图
> 
> ![Screenshot_20200622_210037.png](https://camo.githubusercontent.com/09bd79e4a552d36ffe69f716b0cf9d3c5bedd0e3/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30362f32322f484749675a617338746b41573576372e706e67)

我进站到现在一直是procity这个主题，你也是么？

**Comment by ted423** [comment]
或者种子列表风格是？

**Comment by tongyifan** [comment]
> 或者种子列表风格是？

ProCITY+Default Modern

**Comment by ted423** [comment]
> > 或者种子列表风格是？
> 
> ProCITY+Default Modern

那我有空看看是不是因为我在保种...，frds那第一个我也在保种

**Comment by ted423** [comment]
cmct,第一页50个结果，我搜的只显示42个，而且目测上传下载全是错的。先这样吧，有空研究下

**Comment by ted423** [comment]
> 不过确实有个问题，label没有颜色，这个种子前面有个50%的label

![image](https://user-images.githubusercontent.com/7042766/85911901-fa0dd780-b85a-11ea-98c3-97490f25f168.png)
我这一步就啥都没有，我看页面是class 是 tr_normal trblock

**Comment by ted423** [comment]
哭了...除了tr_review还有tr_inpro，我说咋又少了一个...
