### ISSUE TITLE
站点用户信息的数据量一列变窄导致多行显示会显得很乱

### ISSUE THREAD

**Issue by fan-cy** [ronggang/PT-Plugin-Plus#53]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

- PT 助手版本: 1.0.2
- 浏览器名称及版本：chrome 72.0.3626.121
- 问题描述：网页窗口宽度稍微缩小后，站点用户信息的数据量一列会变窄导致多行显示，由于这个格里实际有6个元素（上传量，单位，上箭头，下载量，单位，下箭头），多行显示会显得很乱，建议这一列的宽度给予固定宽度保持显示两行
- 相关截图：
![123](https://user-images.githubusercontent.com/30803671/54138670-e585b000-445a-11e9-96d5-78f620fc4fad.JPG)![456](https://user-images.githubusercontent.com/30803671/54138671-e585b000-445a-11e9-9f09-eaeaf3e4a351.JPG)

**Comment by ronggang** [comment]
@fan-cy 感谢反馈。

**Comment by ronggang** [comment]
样式已调整 ( feb4fcb57b45a54f30ff2b1c64c990b44d6e1db2 )
