### ISSUE TITLE
Torrentleech入站时间统计错误

### ISSUE THREAD

**Issue by chploin** [ronggang/PT-Plugin-Plus#532]
- PT 助手版本:1.4.9
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：
- 问题描述：
Torrentleech入站时间统计错误
1.4.8统计正确，实际加入时间5个多月，1.4.9统计出来是70周
- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
我这正常，另建议你说明详细的操作步骤

**Comment by chploin** [comment]
那应该是我的问题，可能重装系统后，和我edge恢复cookie有关，并导入chrome数据有关。因为我chrome完全卸载重新安装不恢复cookie问题依旧。我自己再试试，不好意思了。

发送自 Windows 10 版邮件应用

发件人: ted423
发送时间: 2020年5月30日 18:11
收件人: ronggang/PT-Plugin-Plus
抄送: chploin; Author
主题: Re: [ronggang/PT-Plugin-Plus] Torrentleech入站时间统计错误 (#532)

我这正常，另建议你说明详细的操作步骤

**Comment by proudCC** [comment]
> 
> 
> 我这正常，另建议你说明详细的操作步骤

pussy Torrent也是

**Comment by Mit2g** [comment]
其实不是统计错误 而是站点自行更改了时间 `tl网址.org/profile/你的用户名`可以查询
楼上没有相同问题 初步判断是邀请批次不同 我相信requester也是使用***torrentleech***这个邀请码进站的 如果是 那么为通病

**Comment by chploin** [comment]
> 其实不是统计错误 而是站点自行更改了时间 `tl网址.org/profile/你的用户名`可以查询
> 楼上没有相同问题 初步判断是邀请批次不同 我相信requester也是使用_**torrentleech**_这个邀请码进站的 如果是 那么为通病

站点上我查过的，入站时间没改过，19年12月份。

**Comment by FduJyy** [comment]
> 我这正常，另建议你说明详细的操作步骤

![image](https://user-images.githubusercontent.com/16150809/84560557-e00ec800-ad77-11ea-88da-fb3daf7c7690.png)
![image](https://user-images.githubusercontent.com/16150809/84560579-02a0e100-ad78-11ea-88af-5db8bcf26553.png)

我这里也出现了时间多统计的情况，入站时间与网站查询的结果不符。插件版本为V1.4.9。

**Comment by ted423** [comment]
> > 我这正常，另建议你说明详细的操作步骤
> 
> ![image](https://user-images.githubusercontent.com/16150809/84560557-e00ec800-ad77-11ea-88da-fb3daf7c7690.png)
> ![image](https://user-images.githubusercontent.com/16150809/84560642-81961980-ad78-11ea-947e-393e55d31f57.png)
> 
> 我这里也出现了时间多统计的情况，入站时间与网站查询的结果不符。插件版本为V1.4.9。

鼠标悬停，看看显示的什么时间

**Comment by FduJyy** [comment]
> > > 我这正常，另建议你说明详细的操作步骤
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16150809/84560557-e00ec800-ad77-11ea-88da-fb3daf7c7690.png)
> > ![image](https://user-images.githubusercontent.com/16150809/84560642-81961980-ad78-11ea-947e-393e55d31f57.png)
> > 我这里也出现了时间多统计的情况，入站时间与网站查询的结果不符。插件版本为V1.4.9。
> 
> 鼠标悬停，看看显示的什么时间

2019-01-10 08:00:00
正好差了11个月

**Comment by ted423** [comment]
@ronggang 经测试 dateTime('10th December 2019', 'Do MMMM YYYY').valueOf() 这样的话就会变成2019-01-10 08:00:00

**Comment by Rhilip** [comment]
> @ronggang 经测试 dateTime('10th December 2019', 'Do MMMM YYYY').valueOf() 这样的话就会变成2019-01-10 08:00:00

看了下，dayjs只是用了 customParseFormat， 没有使用 AdvancedFormat，所以 Do 的格式符没法被识别。

https://github.com/ronggang/PT-Plugin-Plus/blob/0a102697c365baf233ca73f3f686caa7be7d4d34/src/background/infoParser.ts#L4-L5

在这里引入一下吧。

refs: https://day.js.org/docs/en/plugin/advanced-format

**Comment by ted423** [comment]
> > @ronggang 经测试 dateTime('10th December 2019', 'Do MMMM YYYY').valueOf() 这样的话就会变成2019-01-10 08:00:00
> 
> 看了下，dayjs只是用了 customParseFormat， 没有使用 AdvancedFormat，所以 Do 的格式符没法被识别。
> 
> https://github.com/ronggang/PT-Plugin-Plus/blob/0a102697c365baf233ca73f3f686caa7be7d4d34/src/background/infoParser.ts#L4-L5
> 
> 在这里引入一下吧。
> 
> refs: https://day.js.org/docs/en/plugin/advanced-format

我感觉把th remove掉就好了？

> > @ronggang 经测试 dateTime('10th December 2019', 'Do MMMM YYYY').valueOf() 这样的话就会变成2019-01-10 08:00:00
> 
> 看了下，dayjs只是用了 customParseFormat， 没有使用 AdvancedFormat，所以 Do 的格式符没法被识别。
> 
> https://github.com/ronggang/PT-Plugin-Plus/blob/0a102697c365baf233ca73f3f686caa7be7d4d34/src/background/infoParser.ts#L4-L5
> 
> 在这里引入一下吧。
> 
> refs: https://day.js.org/docs/en/plugin/advanced-format
我试了一下...这样就可以了
dateTime('10 December 2019').valueOf()

**Comment by Rhilip** [comment]
@ted423 那如果是 1st或者2nd之类的那，还是引入一下advanced-format好了

**Comment by ted423** [comment]
试了下，不知道怎么引入，太菜了，溜了
