### ISSUE TITLE
能否增加U2站 other优惠标签支持

### ISSUE THREAD

**Issue by huazhuzhibai** [ronggang/PT-Plugin-Plus#533]
## 您的功能请求是否与问题有关？ 请描述一下。

U2 other优惠标签

## 描述你想要的解决方案

能否增加U2 other优惠标签的搜索与显示，现在other标签的种子搜索到什么优惠也不显示
## 其他附加信息

![image](https://user-images.githubusercontent.com/65559688/83350011-8b2c8400-a36b-11ea-9bf8-9419e0adf662.png)
![image](https://user-images.githubusercontent.com/65559688/83350013-8f58a180-a36b-11ea-843c-c211aff3a3f3.png)

**Comment by ted423** [comment]
不好支持，你写个other,别人也看不懂具体得信息。
而要把2.33 0.00写上，感觉不好看，还长

**Comment by huazhuzhibai** [comment]
这个站的大部分优惠都是这个标签，现有搜索没有提示所以不知道是否优惠，能否写成其他优惠，至少知道有优惠

**Comment by ted423** [comment]
看其他人咋想....
你就算写个other,你要看具体照样得点进去。
另外other太没标识性了，感觉会怪怪得

**Comment by chenxiangxingxie** [comment]
现在如果搜索出的内容有一百条，除去几个是50 free这种标准的优惠，剩下的因为没有优惠标签，只能点进去一个一个选，如果增加个标签是不是至少能在几十个里面直接筛选出有优惠的，或许几个或许十几个，但我觉得还是节约了操作步骤，提升效率吧？ 而且这个标签我在几个站里，就这个里面见到了，用U2这个站的人看到这标签也自然知道啥意思，其他站没有这标签的也不会显示这个分类标签。

**Comment by huazhuzhibai** [comment]
现在如果搜索出的内容有一百条，除去几个是50 free这种标准的优惠，剩下的因为没有优惠标签，只能点进去一个一个选，如果增加个标签是不是至少能在几十个里面直接筛选出有优惠的，或许几个或许十几个，但我觉得还是节约了操作步骤，提升效率吧？ 而且这个标签我在几个站里，就这个里面见到了，用U2这个站的人看到这标签也自然知道啥意思，其他站没有这标签的也不会显示这个分类标签。

**Comment by RtYkk** [comment]
@chenxiangxingxie 筛选出有优惠的有啥用么？u2不就是没有优惠创造优惠？

**Comment by huazhuzhibai** [comment]
也是，很有道理。光想着搜索了

**Comment by RtYkk** [comment]
不过筛选是挺烦的，2xfree和free还有others定义为三种优惠，我想看个下载免费的都比较麻烦。
不过可以曲线救国，进魔法页面看 /promotion.php?action=list&effectonly=1

**Comment by huazhuzhibai** [comment]
感谢大佬，学到了。我也是刚入U2不太久，还是有点用别的站的思维

**Comment by ronggang** [comment]
或许可以考虑增加自定义标签功能。
