### ISSUE TITLE
群晖的下载目录怎么设置？

### ISSUE THREAD

**Issue by lhbill** [ronggang/PT-Plugin-Plus#54]
如题，白裙，服务器可以连上，选择“一键下载”，可以下载到download station的默认目录
File station中，文件夹为“/volume2/电影/”
但是下载目录中，设置了“/volume2/电影/”，选这个后提示“指定的目录不存在”
编辑下载目录是这样写的，“当前目录列表配置是基于 Synology Download Station 暂存位置的相对路径，如暂存位置为：/volume1/，自定义目录为 music/，那么最终种子的下载目录为：/volume1/music/”，没太看明白什么意思……
求指点一二

**Comment by lhbill** [comment]
![image](https://user-images.githubusercontent.com/34673835/54244884-98443400-4569-11e9-81a3-1d2f526e31e1.png)
![image](https://user-images.githubusercontent.com/34673835/54244889-9da17e80-4569-11e9-8bd7-e96928a02406.png)
![image](https://user-images.githubusercontent.com/34673835/54244893-a09c6f00-4569-11e9-98c9-0b8f7921c681.png)
如上面的图设置，“下载到”里默认的就可以，选“电影”那个就总显示目录不存在

**Comment by ronggang** [comment]
> ![image](https://user-images.githubusercontent.com/34673835/54244884-98443400-4569-11e9-81a3-1d2f526e31e1.png)
> ![image](https://user-images.githubusercontent.com/34673835/54244889-9da17e80-4569-11e9-8bd7-e96928a02406.png)
> ![image](https://user-images.githubusercontent.com/34673835/54244893-a09c6f00-4569-11e9-98c9-0b8f7921c681.png)
> 如上面的图设置，“下载到”里默认的就可以，选“电影”那个就总显示目录不存在

我的错，电影后面不需要加 `/`

**Comment by lhbill** [comment]
谢谢，这样可以了。
个人意见，这种下载目录的设置有点不够直观，不如直接采用绝对路径

**Comment by lhbill** [comment]
谢谢，这样可以了。
个人意见，这种下载目录的设置有点不够直观，不如直接采用绝对路径

**Comment by ronggang** [comment]
> 谢谢，这样可以了。
> 个人意见，这种下载目录的设置有点不够直观，不如直接采用绝对路径

不好意思，目前群晖的官方接口限制，只能这样，无法使用绝对路径。

**Comment by lhbill** [comment]
恩恩，这样已经可以用了，非常感谢！

**Comment by ronggang** [comment]
已增加容错处理 ( ba19be274095b3bb1e755b376c6ad30b8750cb1a )
