### ISSUE TITLE
Site refresh button for My Data page

### ISSUE THREAD

**Issue by zenof** [ronggang/PT-Plugin-Plus#541]
**Is your feature request related to a problem? Please describe.**
At this moment, in My Data page, when click refresh my data button, it will pull all sites statistics data, and it will often have some sites occur errors. And the error site's data will be empty, if we click refresh my data button again, it will begin pull all sites and at that time other sites may occur errors. It is frustrate to ensure all site refreshed successfully at one time.

**Describe the solution you'd like**
Add a refresh button for error site in the status column, when click the refresh button it will only trying to refresh corresponding site.

![image](https://user-images.githubusercontent.com/37714471/84091587-7890fb00-a9ba-11ea-8f29-20fcab64075b.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Rhilip** [comment]
The favicon of this site may the `refresh button` you want, It can pull the statistics data of one site.

**Comment by zenof** [comment]
@Rhilip Oh that's pretty awesome! Thank you for letting me know!
