### ISSUE TITLE
提供 label 功能

### ISSUE THREAD

**Issue by tasi788** [ronggang/PT-Plugin-Plus#547]
## 您的功能请求是否与问题有关？ 请描述一下。

某些 client 提供 label 功能，並且利用 label 整理起來十分舒服，例如 rutorrent 還有 AutoTool 功能，可以利用 label 做進一步的整理。

## 描述你想要的解决方案

希望能夠在 `下载目录设置` 內新增一個 `標籤` 的選項

## 描述您考虑过的替代方案

寫個 script 針對 path 處理。

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/77
