### ISSUE TITLE
可否加强一些搜索浏览等功能和类似rss的订阅下载的功能

### ISSUE THREAD

**Issue by wangxiaomail** [ronggang/PT-Plugin-Plus#548]
用户画像：每周登陆1次的用户，没有太多时间每天关注，只是想周末看看高质量的电影
当前产品现状：
    1. 搜索可否添加翻页功能：对于搜索来说，每次打开查看10个最新的电影，内容有限不能翻页
    2. 搜索结果可否添加豆瓣评分：目前搜索结果有展示，大小，上传下载速度等。该信息对于选片源来说并无太大的帮助，只能够分析出体积大的电影播放质量可能较高，但是内容质量无法区分。

tips：上面的情况会导致每次用户的访问时长不会太长，没有太多的停留的理由。对于pt类工具而言，帮助用户提升找到片源的效率是核心根本。
解决该问题有几个方向：
    1.  数据更多（片源更多）：这里我们做的很好，可以绑定很多网站。**_但是我们缺少多站浏览的功能，用户可以在插件内部直接翻页浏览多站的数据，减少站点切换的成本_**
    2. 找片更快（直接搜索）：具备了多站同时搜索的功能，但是这里不确定是否具备评分等搜索能力，也可能是源站不开放该能力，这里仅仅是建议。
    3. 下载更方便：这个自不必说，我们对于单点下载做的很棒。**_可以新增订阅下载的功能_**

（这里感谢作者开发了这个插件，感激作者贡献的同时也提出一些小的建议，如果可以的话还望采纳，感恩！）

**Comment by ronggang** [comment]
@wangxiaomail 其实应该可以反向操作，去豆瓣找想看的电影，看到喜欢的直接在豆瓣上点助手搜索就可以找到你心仪的片源了。

**Comment by wangxiaomail** [comment]
> @wangxiaomail 其实应该可以反向操作，去豆瓣找想看的电影，看到喜欢的直接在豆瓣上点助手搜索就可以找到你心仪的片源了。

嗯，你说的是的，其实我是想让这个插件可以让更多人在上面浏览，而不是一个辅助下载的小工具。我回头去豆瓣上看看，多谢啦

**Comment by ronggang** [comment]
之前记得也讨论过类似的话题，找自己想看的影视资源大概可以分为两类：
第一种、无目的的浏览；
第二种、有目的的定向查找；

对于第一种，通常情况也可以分类两种方式：
- 去豆瓣之类的网站进行浏览，找最近热门、评分较高或自己喜欢的类型，看到自己喜欢的作品，搜索，然后挑一个符合心意的版本观赏之；
- 去PT站点浏览最近发布的资源，遇到不错的作品遂下载观赏之；此方对于站点较多的同学，要每个站点浏览可能性较小，只能挑几个偏爱的站进行；

对于第二种，目的性比较强，一般情况处理也简单明了，直接搜索，从结果中找自己心仪的版本观赏之。

另外，关于兄台所说的每站仅显示10条内容是可以设置的，把数量调大，一般可以显示每站的第一页内容，如果站点设置为每页100条，助手也可以调整为100条每站，这样10个站浏览时理论上就有1000条了，基本上也够用；不过对于这种情况，一般个人建议在豆瓣进行浏览比较好。

后续可能会计划在豆瓣豆列、想看等列表上加强支持，这样可以更快速找到自己想看的内容。

以上为个人理解和建议，仅供参考。
