### ISSUE TITLE
hdbits种子页面不显示侧边工具栏

### ISSUE THREAD

**Issue by hzw168** [ronggang/PT-Plugin-Plus#549]
- PT 助手版本:1.4.9
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Microsoft Edge 版本 83.0.478.45 (官方内部版本) (64 位)
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
在助手站点设置里能正常添加hdbits站点，在数据页也能正常获取到站点信息，但是在种子页面不显示侧边工具栏。

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@bweih dlddw

**Comment by luckiestone** [comment]
我也遇到过同样的问题，不清楚造成的原因是什么。可以尝试这样解决：
>1. 在`站点设置`中删除所有站点
>2. 添加HDB，这时候应该有工具栏了
>3. 重新添加其他站点（可以通过`一键导入站点`，也可以事先把每个站点的配置文件导出后恢复）

**Comment by bweih** [comment]
@luckiestone 
已经试过了，跟贝壳大佬也确认是bug，下一版本应该会修复。

**Comment by wyyqyl** [comment]
这个问题到现在还没有修复

**Comment by ted423** [comment]
是的，还开着就是没有修复

**Comment by hzw168** [comment]
已经修复了，参考楼上大佬的方法，删除所有站点，添加HDB，然后再导入其他站点。

**Comment by MewX** [comment]
怀疑是插件加载的时候是字符串部分匹配（而不是完全匹配）的问题。不得不吐槽大伙儿真会取名字。

我的情况是site里面删除uhdbits.org，刷新hdb的页面就可以出现侧边工具栏了。

之后可以再把uhdbits添加回来就一切正常了 🤦‍♂️

**Comment by wyyqyl** [comment]
> 

还真是这个问题 感谢大佬
第一次在HDB看到了PTPP工具栏

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/498
可能跟这个问题类似

**Comment by ted423** [comment]
先添加hdb, 再添加uhd无问题，先添加uhd,再添加hdb，不显示侧边栏，推测跟配置前后顺序有关

**Comment by MewX** [comment]
> 先添加hdb, 再添加uhd无问题，先添加uhd,再添加hdb，不显示侧边栏，推测跟配置前后顺序有关

隐藏含义是：网站是按照添加顺序存储为list，读取的时候（index of/find/whatever）也是按顺序查找，也就是说检索的关键词没有完全匹配，如果提前检测到substring match就停止了，具体代码在哪不清楚

**Comment by ted423** [comment]
@MewX https://github.com/ronggang/PT-Plugin-Plus/blob/fe1ee0e81c7d7b3eafd71e4d706c0233d648b42b/src/content/index.ts 可能是这个？

**Comment by ted423** [comment]
@ted423 抄了下代码，虽然没搞懂为啥，但似乎可以了

**Comment by MewX** [comment]
> @ted423 抄了下代码，虽然没搞懂为啥，但似乎可以了

23333 nb

因为hdb是uhdb的子串，所以前面用http(s)://里的//隔开可破

**Comment by ted423** [comment]
@MewX 检测用的似乎全是host

**Comment by Rhilip** [comment]
> > @ted423 抄了下代码，虽然没搞懂为啥，但似乎可以了
> 
> 23333 nb
> 
> 因为hdb是uhdb的子串，所以前面用http(s)://里的//隔开可破

差不多就是这个原因
因为为了cdn域名能使用相同功能，所以使用了 host 检测，但是之前没考虑到host会有子串相同的情况。。 所以在 hdbits 和 uhdbits 的例子中会因为添加顺序等情况导致两个站混用规则。 
于是使用 `http(s)://里的//隔开` 是一个比较可行的解决方法。
