### ISSUE TITLE
高清街域名更新

### ISSUE THREAD

**Issue by sanzuwu** [ronggang/PT-Plugin-Plus#55]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

- PT 助手版本:1.0.2
- 浏览器名称及版本：Yandex Browser最新版
- 问题描述：高清街域名更新了,助手还是老域名,不能更新信息
- 相关截图：![](https://s2.ax1x.com/2019/03/13/AFXL7T.png)

**Comment by Rhilip** [comment]
该记录域名仍可以访问，请再次确认
https://github.com/ronggang/PT-Plugin-Plus/blob/master/resource/sites/hdstreet.club/config.json#L4

**Comment by advondesign** [comment]
同样 高清街搜不到资源
