### ISSUE TITLE
建议移植IYUUAutoReseed的自动辅种功能

### ISSUE THREAD

**Issue by hzgjq** [ronggang/PT-Plugin-Plus#552]
## 您的功能请求是否与问题有关？ 请描述一下。

IYUUAutoReseed目前能对国内大部分的PT站点自动辅种，支持下载器集群，支持多盘位，支持多下载目录，支持远程连接，是一个比较好的辅种工具，但现在只有PHP版，没有浏览器插件版本。
不知道开发组有没意向将IYUU的辅种功能移植集成到助手中。

## 描述你想要的解决方案

根据IYUU项目介绍工作原理为调用transmission、qBittorrent下载软件的API接口，提取正在做种的info_hash提交到辅种服务器API接口，根据API接口返回的数据拼接种子连接，提交给下载器，自动辅种各个站点。

## 描述您考虑过的替代方案

IYUU项目地址：https://github.com/ledccn/IYUUAutoReseed

**Comment by ted423** [comment]
怎么移植，你了解原理么？

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/343
https://github.com/ronggang/PT-Plugin-Plus/issues/238
https://github.com/ronggang/PT-Plugin-Plus/issues/237
https://github.com/ronggang/PT-Plugin-Plus/issues/217

**Comment by Rhilip** [comment]
关于IYUU合作，我之前是有过考虑的。
且同为OB的SYSOP，在IYUU的开发过程中，我与其开发者也进行过一些讨论。

一方面，目前PTPP对于辅种判断是和Reseed基本类似，是基于基准种子加“验证名称、长度、及文件列表内容是否相同”的模式，在精度上确实没有IYUU这么高，引入IYUU基于种子info_hash判断确实能提高用户的辅种体验；
但另一方面，目前IYUU对于权限管理还存在一些问题，虽然已经增加了无合作站点验证过的用户无法使用，但对已验证的用户，其辅种是完全开放的（注：通过`App.Api.Sites`等接口，还是能返回用户未获取的种子站点及可辅种种子列表，具体能不能使用在客户侧筛选），这一点在Reseed上同样存在。这与PTPP的理念有点不同，PTPP只能获取到用户已添加并已经在浏览器处于登录状态，对于用户未登录的站点，获取不到任何信息。
Reseed侧的也仅是在对应网站上显示图标，并可以直接调用，这点和深入合作还是有点区别的。

如果要移植的话，首先PTPP要在设置侧添加对应apikey输入项，然后还需要实现一边IYUU目前已经实现的功能，且根据IYUU公开的和未公开的文档说明，插件侧还需要做sid->site->site name in PTPP的转换，较为繁琐；且做这一系列的流程，是否又有点喧宾夺主的感觉？
且本人在前期与 @ledccn 本人的讨论中，他个人也是有开发web管理页面的想法。所以一直处于搁置甚至是放弃的状态。

在日常建议中，我个人也是推荐 有文件没种子，用Reseed先跑一边；添加到下载器中，在用IYUU跑一边。这样基本都没问题。
至于PTPP目前的辅种功能，多是在初次下载时候进行使用。

**Comment by ted423** [comment]
上面R酱说了好多.....

IYUU通过计划任务或常驻内存，但我认为很明显浏览器扩展并不适用于这个状况。要做的话也是类似一键辅种这种操作，但估计一键下去得跑半天。

**Comment by Rhilip** [comment]
另外还有一点就是， “调用transmission、qBittorrent下载软件的API接口，提取正在做种的info_hash”这点。
PTPP对于下载服务器的定位一直是推送，到目前仅有Transmission实现了获取剩余空间的功能。即使要做，也只能是基于info_hash的搜索，而不涉及从下载服务器中获取info_hash。

所以关于PTPP移植IYUU这块，我到时候询问下他们项目组以及合作站点的意见吧。

**Comment by Rhilip** [comment]
https://github.com/Rhilip/IYUU-GUI
