### ISSUE TITLE
对NexusPHP架构下复制的种子链接的格式进行优化

### ISSUE THREAD

**Issue by RtYkk** [ronggang/PT-Plugin-Plus#556]
## 您的功能请求是否与问题有关？ 请描述一下。
种子列表内的复制链接功能难以起到它相应的效果。
我认为这个功能应该用来快速贴链接导入客户端/下载器，但是复制出来的链接全都不带passkey，不能直接贴到客户端的下载框来批量下载，略微有点鸡肋。

## 描述你想要的解决方案
复制带passkey的种子链接，一般站点的种子链接都是这样的：
`https://<nexusphp.privatetracker.site>/download.php?id=<torrentid>&passkey=<mypasskey>&https=1`
没有具体研究过代码，但是我猜测插件应该是直接爬取
![chrome_Nsq1vf7u6n](https://user-images.githubusercontent.com/45971730/86313295-628ff680-bc57-11ea-8f24-744f7ed54b6a.png)的链接的。
插件能不能对链接略作修改以便直接导入客户端？或者只取<torrentid>的部分填入上述模板。

## 描述您考虑过的替代方案
至于批量下载，可以使用插件的批量下载功能。我也尝试用[Linkclump](https://chrome.google.com/webstore/detail/linkclump/lfpjkncokllnfokkgpkobnkbkmelfefj?hl=zh-CN)作为一个备选，大部分下载链接还是在同一个列的，Linkclump的好处是我可以更方便的定制我这次下载种子的数目。我想下载十个就只需要选中十个，也有在新标签页中打开/复制到剪贴板可以选择。（插件好像也可以通过下载到你想要的数目的时候点击右下角的×来停止）（略微扯远，还是没有解决本issue的问题）

## 其他附加信息
1、U2虽然是每个种子单独一个passkey的，但是这个好像只是发生在tracker，下载链接还是通用passkey
2、HDChina格式略有不同
`https://hdchina.org/download.php?hash=<hash>&uid=<uid>&https=1`
不同人的同一个种子的hash都是不一样的……在种子列表页面复制的链接只有hash，就缺了后面的uid。
3、Gazelle架构完全没有这个问题。种子列表内的链接也都非常直接
`https://<gazelle.privatetracker.site>/torrents.php?action=download&id=<torrentid>&authkey=<myauthkey>&torrent_pass=<mytorrentpass>`
这种格式直接导入也不会遇到问题。

嘛，可能这个功能有点要求高了。只是一个想法，如果不好做的话请直接close。

**Comment by ted423** [comment]
@RtYkk 太长了有点没看懂，设置了passkey的话，列表页复制就会带passkey

**Comment by RtYkk** [comment]
事实证明这个功能已经做了，只是我没发现，但是现在新问题产生了。我重新开一个issue，因为那是个bug
