### ISSUE TITLE
下载服务器拖动排序

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#558]
## 您的功能请求是否与问题有关？ 请描述一下。

现在是按添加顺序排序的，如果要调整顺序的话就只能删了重加

## 描述你想要的解决方案

拖动排序，或者直接可以指定顺序

**Comment by Rhilip** [comment]
看了下vuetify的data-table文档，似乎不支持 拖动排序。只能考虑指定顺序。
但对于下载服务器来说，这样做有必要吗？
refs: https://vuetifyjs.com/en/components/data-tables/#data-tables

**Comment by Rhilip** [comment]
说起来，我似乎没看到那家的table组件直接支持用户拖动排序。拖动排序似乎也跟与列表相关联，而不符合table的设计理念，table的排序一般是基于列的排序，而不是直接的用户拖拽。
要解决也只能像现在站点一样，加一个排序id了。

**Comment by ted423** [comment]
@Rhilip 一个nas，一个seedbox,最近换保种客户端，然后seedbox夹在了两个nas客户端之间，强迫症十分难受 。或者我可以找找配置看有没地方可以直接改

**Comment by ted423** [comment]
试了下，改备份的配置没用.......
原来是严格按首字母排序，我傻了，不该用不统一的命名方式....其中一个用了中文

**Comment by BigUncle** [comment]
> 试了下，改备份的配置没用....... 原来是严格按首字母排序，我傻了，不该用不统一的命名方式....其中一个用了中文

@ted423 想问下，插件配置的文件路径（不是备份压缩包里的`options.json`）在哪呢，想着直接改配置文件里几个服务器的列表顺序。
