### ISSUE TITLE
参数备份与恢复功能中WebDav服务器增加https协议的建议

### ISSUE THREAD

**Issue by valianliu** [ronggang/PT-Plugin-Plus#559]
## 您的功能请求是否与问题有关？ 请描述一下。

参数备份与恢复菜单下，添加WebDav服务器，目前我试了下只支持http协议，https协议的无法连通备份服务器
我的WebDav是使用群晖开的，使用RaiDrive软件映射使用https协议没有问题

## 描述你想要的解决方案

希望可以增加https协议支持，辛苦开发者

**Comment by Rhilip** [comment]
webdav本来就是支持https的，你传入什么地址就用什么地址。
比如坚果云用的就是https https://github.com/ronggang/PT-Plugin-Plus/issues/319
不存在插件这边限制。

**Comment by valianliu** [comment]
确实是https证书校验的问题，感谢大佬回复，close了。
