### ISSUE TITLE
隐藏工具栏五个图标下面的几行字

### ISSUE THREAD

**Issue by e71828** [ronggang/PT-Plugin-Plus#561]
## 您的功能请求是否与问题有关？ 请描述一下。

隐藏工具栏五个图标下面的几行字
## 描述你想要的解决方案

图标简洁，鼠标事件提示，就够了

**Comment by ted423** [comment]
是否是必要的？

**Comment by tongyifan** [comment]
@e71828 反对，就种子页的前两个图标，不看文字就根本分不出哪个是哪个

**Comment by RtYkk** [comment]
反对👎鼠标移上去还要一个个尝试。下面小字一目了然。

**Comment by Rhilip** [comment]
简单提示还是很有必要的，完全没有隐藏的必要。4行文字对于整体而言，隐藏并不能节省多少空间。
此外，部分手机端用户很难通过title属性获取icon的实际意义。
不予接受。

**Comment by e71828** [comment]
手机端操作太秀了吧，服气；期待app版本

**Comment by RtYkk** [comment]
？？？？？

**Comment by e71828** [comment]
![image](https://user-images.githubusercontent.com/24602820/90147668-028f8280-ddb5-11ea-8d0a-4250a2d47122.png)

难道只有我用英文版本么？

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/90149334-f4dafc80-ddb6-11ea-8b31-d4f52f8acadd.png)

**Comment by e71828** [comment]
@ted423 我清楚了系统日志 也达到了你的效果  谢谢大佬
