### ISSUE TITLE
TTG从7月15日开始失效，提示：“获取下载链接失败”

### ISSUE THREAD

**Issue by kervstk** [ronggang/PT-Plugin-Plus#563]
- PT 助手版本:1.4.9
- PT 助手安装方式：crx安装
- 浏览器名称及版本：Chrome 72.0.3626.81
- 浏览器是否安装了其他插件：无PT相关
- 停用其他插件后是否正常工作：
- 问题描述：
   1、从TTG种子页面，无论一键下载、下载到、复制链接均提示：“获取下载链接失败”
   2、从种子列表页面下载所有、下载到、复制链接均提示“请先设置站点密钥（Passkey）。”
   其他各站均正常使用无此问题，以上问题均发生于7月15日之后，从19年开始使用PT助手在TTG并未出现过如下问题

- 相关截图：
![avatar](https://i.loli.net/2020/07/17/FXHRjkWigOo5TaJ.png)
![avatar](https://i.loli.net/2020/07/17/Ne1QYuLjxiM7zdl.png)

- 重现步骤：
去TTG点击相关按钮

**Comment by Rhilip** [comment]
提出的两条，目前（7月30日）均无法重现。
此外，该站点面板推送本来就是通过构造rssdd.php的方式进行推送，必须设置passkey，才能使用“种子列表页面下载所有、下载到、复制链接”
![image](https://user-images.githubusercontent.com/13842140/88934204-e965dc80-d2b2-11ea-9823-25b3e8c686f5.png)

**Comment by kervstk** [comment]
我是有passkey的，而且之前一切正常，也不知道为何最近突然失效了。我未对网站账户进行任何更改，也未对PT助手进行更改设置
其他站均正常，我现在只能手动复制种子链接去添加任务，无法重现那也没办法了，我等PT助手再更新时候看看有没有可能恢复吧

Rhilip <notifications@github.com> 于2020年7月30日周四 下午10:25写道：

**Comment by kervstk** [comment]
> 查看一下是否和这个PR相似 #560

感谢提示，确实如此，通过排除法，我已找到问题的根源，同时也反馈给工具作者了，希望它能解决
[https://greasyfork.org/zh-CN/scripts/382927-%E9%9B%86%E8%A3%85%E7%AE%B1](url)
如果咱们插件这边能直接解决一下就最好了，我目前可以通过关闭和开启来暂时性解决

**Comment by Rhilip** [comment]
> > 查看一下是否和这个PR相似 #560
> 
> 感谢提示，确实如此，通过排除法，我已找到问题的根源，同时也反馈给工具作者了，希望它能解决
> [插件链接](https://greasyfork.org/zh-CN/scripts/382927-%E9%9B%86%E8%A3%85%E7%AE%B1)
> 如果咱们插件这边能直接解决一下就最好了，我目前可以通过关闭和开启来暂时性解决

建议在用户脚本管理器中添加用户排除
![image](https://user-images.githubusercontent.com/13842140/90997060-0318ec00-e5f3-11ea-8042-5a740ff2487c.png)

此外由于已有pr修复，该issue暂做关闭处理
