### ISSUE TITLE
JPopsuki在站点语言为日语时无法获取到数据

### ISSUE THREAD

**Issue by tatsuz0u** [ronggang/PT-Plugin-Plus#566]
- PT 助手版本: 1.4.9
- PT 助手安装方式: 提交到Firefox Developer Hub然后安装
- 浏览器名称及版本: Firefox 78.0.2
- 浏览器是否安装了其他插件: 还启用了1Password和Dark Reader
- 停用其他插件后是否正常工作: 否
- 问题描述: 站点JPopsuki在已支持列表中，但在站点语言为日语时无法获得数据，除做种体积外均为0
- 相关截图: 无
- 重现步骤: 在JPopsuki站点语言为日语的前提下尝试在PT助手中刷新我的数据

**Comment by ted423** [comment]
@Seitazzo 暂不支持日语

**Comment by ted423** [comment]
啊，我的意思是说目前版本没去支持，建议reopen

**Comment by Seitazzo** [comment]
好的，我还以为没打算支持 XD

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/commit/66692e8e0cb20b267ec4541d74fcede28d1065b7
但是感觉做了点无用功
