### ISSUE TITLE
上传下载数据量的显示精度可以提高

### ISSUE THREAD

**Issue by Aniverse** [ronggang/PT-Plugin-Plus#567]
## 您的功能请求是否与问题有关？ 请描述一下。

目前在我的数据中显示的数据量，单位达到 PiB 以后，仅显示小数点后 2 位。如网页上显示我的上传量为 1.417 PB，在助手的页面中仅能显示为 1.41 PiB

## 描述你想要的解决方案

在 NexusPHP/TTG 中，数据量达到 PB 后可以获取到小数点后三位（TTG 是后四位）的上传量数值，希望 PT 助手也能显示到小数点后三位
其实下载量和上传量在单位是 TiB 的时候也可以获取到小数点后三位，这个我个人是无所谓改不改了……

## 其他附加信息

[![QQ20200720101016.png](https://www.z4a.net/images/2020/07/20/QQ20200720101016.png)](https://www.z4a.net/image/T0kGUK)
[![QQ20200720101046.png](https://www.z4a.net/images/2020/07/20/QQ20200720101046.png)](https://www.z4a.net/image/T0kvGO)
[![QQ20200720101122.png](https://www.z4a.net/images/2020/07/20/QQ20200720101122.png)](https://www.z4a.net/image/T0kZd0)

**Comment by ted423** [comment]
@Aniverse 👍

**Comment by Rhilip** [comment]
欸，先这样修吧，其实我更喜欢把这种format的事情交给其他库来做。比如 Numeral.js
不过这样改下应该也能满足TiB级别以上显示三位小数的需求。
