### ISSUE TITLE
用几天就被chrome给干掉了。过几天就得重装。请问怎么解决？

### ISSUE THREAD

**Issue by wangwhc** [ronggang/PT-Plugin-Plus#569]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@wangwhc 看wiki

**Comment by Rhilip** [comment]
非bug，目前无法上架市场导致一堆问题。目前我们这边也比较难办。建议先参照Wiki或者他人意见来处理
