### ISSUE TITLE
关于反馈问题说明

### ISSUE THREAD

**Issue by ronggang** [ronggang/PT-Plugin-Plus#57]
为了您的隐私，请不要在这里上传日志文件，配置文件等信息，因为会包含个人信息，谢谢！
如需要上传日志，请先删除个人信息后再上传！

**Comment by jueerye** [comment]
如何 封装CRX文件 这样浏览器可以 同步备份 扩展插件了啊

**Comment by Rhilip** [comment]
@jueerye 你好，请直接使用商店版本安装。使用未经注册的Chrome插件（CRX文件）会被浏览器直接禁用而无法使用。相关说明见 https://support.google.com/chrome_webstore/answer/2811969
