### ISSUE TITLE
海胆之家请求添加

### ISSUE THREAD

**Issue by kris065** [ronggang/PT-Plugin-Plus#570]
- 站点名称：海胆之家
- 站点地址：www.haidan.video
- 站点描述：新PT站点

- 资源类型：综合
- 开放注册：是
- 是否连坐：否
- 站点规则：无考核，分享率大于等于1即可

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/30#issuecomment-631868886
请先考虑使用NexusPHP模板进行设置
