### ISSUE TITLE
Avistaz 站点在搜索结果中显示种子大小错误

### ISSUE THREAD

**Issue by Aceralon** [ronggang/PT-Plugin-Plus#571]
- PT 助手版本: 1.4.9
- PT 助手安装方式：edge市场安装
- 浏览器名称及版本：edge 84.0.522.44
- 浏览器是否安装了其他插件：有但应该不影响
- 停用其他插件后是否正常工作：
- 问题描述：
此站点搜索到的种子大小显示不正确，只保留了一位小数（进行了四舍五入）。

- 相关截图：
![image.png](https://i.loli.net/2020/07/29/Q4skpBjzZWw65Ig.png)
在扩展里面搜索同一个种子在不同网站的结果，只有avistaz显示为60.60GB

![image.png](https://i.loli.net/2020/07/29/IlQ4u5sb2DEv6VF.png)
在[avistaz页面](https://avistaz.to/torrent/145533-hanzawa-naoki-s01-2013-dc-1080p-bluray-dd20-x264-chd)可以查看到种子的大小也是60.64GB

- 重现步骤：
添加avistaz后搜寻hanzawa

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/88815824-5cf1e600-d1ee-11ea-95f6-a3b908eda626.png)
你数下这是几位小数点...
搜索是从列表页而不是详细页获取数据

**Comment by ted423** [comment]
PS 如果从详情页获取数据会发出大量请求，所以这个基本只能这样

**Comment by luckiestone** [comment]
这是AvistaZ系列站点的共同feature，站点搜索结果列表返回的种子大小就是如此，只有点入种子详情才有更准确的种子大小。助手为减少请求，直接从搜索结果列表读取，并没有从种子详情中获取种子大小。
