### ISSUE TITLE
HDSKY站点因为下载链接构造方式改变导致无法推送

### ISSUE THREAD

**Issue by Rhilip** [ronggang/PT-Plugin-Plus#573]
- PT 助手版本: 至目前所有
- PT 助手安装方式：（市场安装，或zip包安装） 插件本身设计问题，非其他安装方式、环境、其他插件影响
- 浏览器名称及版本： 插件本身设计问题，非其他安装方式、环境、其他插件影响
- 浏览器是否安装了其他插件： 插件本身设计问题，非其他安装方式、环境、其他插件影响
- 停用其他插件后是否正常工作： 插件本身设计问题，非其他安装方式、环境、其他插件影响
- 问题描述：

HDSKY站点因为下载链接构造方式改变导致无法推送。
由于该站点更新后，在下载链接中添加`&t=`以及`&sign=`参数，防止使用者伪造下载链接。
此外：
1. 站点取消了对请求方法的限制，不再强制要求POST方法，使用GET方法同样可以获取到种子。
2. 如果传入了请求参数中包含`&https=1`的话，会直接返回404 （这么设计的原因是什么？？？）

- 相关截图：

PTPP目前构造出来的下载链接（种子列表页面）
![image](https://user-images.githubusercontent.com/13842140/88925708-7c991500-d2a7-11ea-95ce-f061581a0f61.png)

PTPP目前构造出来的下载链接（种子详情页面）
![image](https://user-images.githubusercontent.com/13842140/88925426-1a401480-d2a7-11ea-908c-f3738647a87d.png)

站点实际下载链接

![image](https://user-images.githubusercontent.com/13842140/88925548-3fcd1e00-d2a7-11ea-882d-87876d3d6871.png)

- 重现步骤：

**Comment by RtYkk** [comment]
@Rhilip #557 这个不一起修一下吗？谢谢😊

**Comment by flytigerzhang** [comment]
是的，404问题

**Comment by ted423** [comment]
奇怪..我这咋没推出去
我看下载的种子跟我复制链接的链接是一样的。
但是操作时提示超时

**Comment by ted423** [comment]
好吧，划掉，看了下，不知道为啥客户端里有任务了，虽然试了几次返回值都是超时

**Comment by sonicmingit** [comment]
问下这个怎么更新修复版本?

**Comment by RtYkk** [comment]
> 问下这个怎么更新修复版本?

等1.5.0 release或者自己编译咯，不过是不是还没pr进来？

**Comment by ted423** [comment]
@sonicmingit

**Comment by Rhilip** [comment]
https://github.com/ronggang/PT-Plugin-Plus/actions/runs/246247059
加上了dev分支的自动构建，如果有需要还是建议这里下载并安装吧。

![image](https://user-images.githubusercontent.com/13842140/92596723-d9411400-f2d8-11ea-9030-1ba9fc2563b1.png)

refs: https://github.com/ronggang/PT-Plugin-Plus/commit/10e5271d155289e798998b8784fcfda781dd8448

**Comment by sonicmingit** [comment]
> https://github.com/ronggang/PT-Plugin-Plus/actions/runs/246247059
> 加上了dev分支的自动构建，如果有需要还是建议这里下载并安装吧。
> 
> ![image](https://user-images.githubusercontent.com/13842140/92596723-d9411400-f2d8-11ea-9030-1ba9fc2563b1.png)
> 
> refs: [10e5271](https://github.com/ronggang/PT-Plugin-Plus/commit/10e5271d155289e798998b8784fcfda781dd8448)

非常感谢,可以了.

**Comment by winddriver** [comment]
> https://github.com/ronggang/PT-Plugin-Plus/actions/runs/246247059
> 加上了dev分支的自动构建，如果有需要还是建议这里下载并安装吧。
> 
> ![image](https://user-images.githubusercontent.com/13842140/92596723-d9411400-f2d8-11ea-9030-1ba9fc2563b1.png)
> 
> refs: [10e5271](https://github.com/ronggang/PT-Plugin-Plus/commit/10e5271d155289e798998b8784fcfda781dd8448)

我用这个自动构建的dev版还是不行，需要把hdsky删掉重新添加吗？

**Comment by ted423** [comment]
我这边似乎搜索结果里不行，打开详情页才可以

**Comment by ted423** [comment]
我明白为啥了.....因为搜索结果出来以后用户不会立刻点击，可能会跑去干别的，所以导致了连接过期

**Comment by winddriver** [comment]
我试了下果然打开网站点页面里助手的下载可以，不过这没啥用啊，重要的是搜索结果不能推送

发自我的iPhone

在 2020年9月11日，18:03，ted423 <notifications@github.com> 写道：

﻿

我明白为啥了.....因为搜索结果出来以后用户不会立刻点击，可能会跑去干别的，所以导致了连接过期
