### ISSUE TITLE
搜索有些站点没结果，并提示Error: Conduits:RuntimeMessage: message reply cannot be cloned.

### ISSUE THREAD

**Issue by zhx79513** [ronggang/PT-Plugin-Plus#574]
- PT 助手版本: 1.4.9
- PT 助手安装方式：zip包提交至开发者中心签名后下载安装
- 浏览器名称及版本：Firefox 79.0 (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
  搜索时有些站点没有结果，并提示Error: Conduits:RuntimeMessage: message reply cannot be cloned.

- 相关截图：
  
![PPTP bug](https://user-images.githubusercontent.com/5063357/89047490-0c5ec200-d381-11ea-955a-94e2726625c2.PNG)

- 重现步骤：
  搜索框输入任意资源名称并搜索。

**Comment by zhx79513** [comment]
查看了插件调试的响应消息，里边回复的内容是正常的：
![PPTP bug 2](https://user-images.githubusercontent.com/5063357/89098809-585f4480-d41d-11ea-9a25-ab2399e3e3c7.PNG)

PTer:
![PPTP bug 3](https://user-images.githubusercontent.com/5063357/89098816-6319d980-d41d-11ea-8f02-b2055d8916c0.PNG)

HDA:
![PPTP bug 4](https://user-images.githubusercontent.com/5063357/89098823-6b721480-d41d-11ea-8c3b-8e8411d704bf.PNG)

**Comment by zhx79513** [comment]
只要搜索到了结果必定会出这个错误，而且固定是那几个站点出这个错误。
再补上控制台输出：
![bug](https://user-images.githubusercontent.com/5063357/89288294-fa826500-d687-11ea-8ddc-ac92985daecb.PNG)

**Comment by ted423** [comment]
你的zip包哪来的...
我丢上开发中心的包都是自己编译的，你是不是没编译的包丢上去了

**Comment by ted423** [comment]
还是release那个包？

**Comment by zhx79513** [comment]
> 
> 
> 还是release那个包？
release的包

**Comment by ted423** [comment]
直接用zip包调试呢
![image](https://user-images.githubusercontent.com/7042766/89290386-60242080-d68b-11ea-9ac3-b58b86aa1fcf.png)
另外试下安全模式不用其他扩展试下

**Comment by zhx79513** [comment]
> 
> 
> 直接用zip包调试呢
> ![image](https://user-images.githubusercontent.com/7042766/89290386-60242080-d68b-11ea-9ac3-b58b86aa1fcf.png)
> 另外试下安全模式不用其他扩展试下

安全模式试了，还是一样的错误。
![bug 2](https://user-images.githubusercontent.com/5063357/89292907-a8ddd880-d68f-11ea-8743-4a6830dce274.PNG)

**Comment by ted423** [comment]
更新到79以后出现
![image](https://user-images.githubusercontent.com/7042766/89294855-a761df80-d692-11ea-8f8b-cbded056395e.png)

看来是版本或是火狐更新啥安全策略之类的

**Comment by zhx79513** [comment]
火狐更到80.0.1后，错误依然有，但错误消息变了，变成：
![捕获](https://user-images.githubusercontent.com/5063357/92511639-2c1abd00-f240-11ea-9e8e-e3b9f88674ee.PNG)

**Comment by Rhilip** [comment]
refs: https://bugzilla.mozilla.org/show_bug.cgi?id=1657384
我认为和该bug report相关，就目前来看，影响到Firefox 79，80，81，82

**Comment by Rhilip** [comment]
请测试构造 https://github.com/ronggang/PT-Plugin-Plus/actions/runs/335119552 ， 并反馈
