### ISSUE TITLE
关于用IMDB 编号搜索种子的问题

### ISSUE THREAD

**Issue by moerfutin** [ronggang/PT-Plugin-Plus#575]
- PT 助手版本: v1.4.9
- PT 助手安装方式：zip包安装
- 浏览器名称及版本： 84.0.4137.0（正式版本） （64 位）
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：
- 问题描述：
_**比如用这个imdb编号 「tt0097619」搜索时，会出现不相关的结果，貌似是pt助手只按所请求imdb编号的后5位数字进行检索，这可能就导致了只要imdb编号中含有这5位数字就被罗列进搜索结果了。。。**_

- 相关截图：
![2020-08-01_150652](https://user-images.githubusercontent.com/9960618/89096414-2e9c2280-d409-11ea-9a95-2d26f6a3f734.jpg)

- 重现步骤：
在pt助手搜索框里输入 tt0097619 ****

**Comment by Rhilip** [comment]
@moerfutin 这个不是ptpp的问题，是nphp构架问题。你去没修改过过这块的站点直接搜索试试就知道了。
