### ISSUE TITLE
pthome不显示侧边栏 pthome种子页面不显示侧边工具栏

### ISSUE THREAD

**Issue by lisabus** [ronggang/PT-Plugin-Plus#576]
- PT 助手版本:1.4.9
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome 版本 84.0.4147.105（正式版本） （64 位）
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
助手站点设置里能正常添加pthome站点，在数据页也能正常获取到站点信息，但是在种子页面不显示侧边工具栏。前些天在另一台电脑上Microsoft Edge也有同样问题

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/255
https://github.com/ronggang/PT-Plugin-Plus/issues/214

**Comment by lisabus** [comment]
添加CDN域名，已解决
