### ISSUE TITLE
UT2.0.4配置了下载目录发送后仍然下载到默认目录

### ISSUE THREAD

**Issue by advondesign** [ronggang/PT-Plugin-Plus#58]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.2
- PT 助手安装方式：（市场安装，或zip包安装）zip安装包
- 浏览器名称及版本：chrome最新版
- 问题描述：UT2.0.4配置了下载目录发送后仍然下载到默认目录。我相对路径试过，绝对路径也改过还是不行。听网友说搜索选单个站点搜就能下载到指定目录，结果试过还是下载到默认目录。
- 相关截图：

我的QQ 253185395 求联系指导或者确认这是个BUG 找到原因 谢谢

**Comment by advondesign** [comment]
是不是因为 我的ut没有 webui原因 另外WEBUI如何添加

**Comment by advondesign** [comment]
已经成功添加WEBUI 而且测试可以远程服务器 但分配子目录依然失败

**Comment by advondesign** [comment]
也就是UT默认目录是D:\Dwonloads\  我设置OpenCD的下载目录是D:\Dwonloads\OpenCD  但是UT下载依然下载到D:\Dwonloads\   而不是D:\Dwonloads\OpenCD中

**Comment by advondesign** [comment]
也就是UT默认目录是D:\Dwonloads\ 我PT plungin plus设置OpenCD的下载目录是D:\Dwonloads\OpenCD 但是UT下载依然下载到D:\Dwonloads\ 而不是D:\Dwonloads\OpenCD中

**Comment by advondesign** [comment]
我qq 253185395 加我 你要什么数据我截图发你

**Comment by Rhilip** [comment]
webui的添加可以搜索，一定要添加`webui.zip`并在设置中启用远程才可以使用uTorrent作为下载服务器。
我仔细核对了一下插件发送的信息和uT的webui添加时的http报文，未发现异常.

我查阅了一下uTorrent Form论坛相关信息 
1. [Possible Bug - Add File - sub path issue - Web API - µTorrent Community Forums](https://forum.utorrent.com/topic/71523-possible-bug-add-file-sub-path-issue/) 对subpath有要求已经建立
2. [Does subpath not support unicode? - Web API - µTorrent Community Forums](https://forum.utorrent.com/topic/94929-does-subpath-not-support-unicode/)  不支持非英文字符目录

看起来不是由于插件的问题

----------

请考虑与我们联系
点击链接加入群聊【PT-Plugin 开发交流群】：https://jq.qq.com/?_wv=1027&k=557Q2K1

**Comment by ronggang** [comment]
UT 需要在 `设置 -> 高级 -> 网页界面` 添加一个下载目录

![image](https://user-images.githubusercontent.com/8065899/54399992-f56fef00-46fb-11e9-9c40-ce029dac275b.png)

然后才能基于这个目录来设置子目录，比如：
下载目录为：D:\test
目录设置为：music/
最终保存的路径为：D:\test\music\

**Comment by advondesign** [comment]
![image](https://user-images.githubusercontent.com/48548045/54403328-95347980-470a-11e9-8ada-abf0bf4e7de9.png)
ut2.0.4并没有网页界面-下载目录这一设定  请你以ut2.0.4作为测试对象

**Comment by Rhilip** [comment]
那你的ut版本就不支持二级目录设定。这个不是我们能决定的，是ut方面的限制，请考虑升级到合适版本。

**Comment by advondesign** [comment]
但是 在PT圈子都用ut2.0.4版本

**Comment by Rhilip** [comment]
closed: https://github.com/ronggang/PT-Plugin-Plus/commit/b51bf6cd5b4a4ba758244bea7234c3c1ec111673
