### ISSUE TITLE
AO 未登录判断问题

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#580]
- PT 助手版本:1.4.9
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
AO未登录打开页面状态下会有个跳转，但助手获取时不会返回数据，这时不会进getSearchResult.js，会直接由searcher.ts 返回没有返回预期的数据

个人感觉 "没有返回预期的数据"应该改为 失败类型 而不是 无结果类型
- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
因为实际上是网站有数据而没获取到，放到一堆无结果中会被忽视

**Comment by ted423** [comment]
又出了点问题.....更新后，几个Gazella 音乐站在搜不到数据时都会返回 没有返回预期的数据。
AO也是如此，退出音乐站 ，比如红，则会返回 数据解析失败 ，但也是在无结果里面
皮在未登录状况下也是如此

**Comment by ted423** [comment]
又测试了了下，AO搜不到结果会返回Nothing Found，但是其也是不会进js脚本里判断是否登录或者有没有结果，而会直接由searcher.ts 返回没有返回预期的数据

**Comment by ronggang** [comment]
> 又测试了了下，AO搜不到结果会返回Nothing Found，但是其也是不会进js脚本里判断是否登录或者有没有结果，而会直接由searcher.ts 返回没有返回预期的数据

因为有一个简单粗暴的判断，如果字符串长度小于200，直接判定没有返回预期的数据。😆
