### ISSUE TITLE
免费出现两个标签Free和free

### ISSUE THREAD

**Issue by xcehnz** [ronggang/PT-Plugin-Plus#583]
- PT 助手版本:  v1.4.9
- PT 助手安装方式：zip
- 浏览器名称及版本：chrome 84.0.4147.135
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：免费出现两个标签Free和free

- 相关截图：
![Snipaste_2020-08-24_23-09-37](https://user-images.githubusercontent.com/30279433/91062223-047ffe00-e65f-11ea-9178-598afd1837d0.png)

- 重现步骤：
例如搜索 tt4701182

**Comment by ted423** [comment]
@xcehnz TL 打的小写导致了这个问题

**Comment by ted423** [comment]
@xcehnz 这锅该我背。

**Comment by xcehnz** [comment]
> @xcehnz 这锅该我背。

TL缺少免费标签貌似也是我提的，尴尬🤣
