### ISSUE TITLE
最近豆瓣是不是不能查询信息了？

### ISSUE THREAD

**Issue by godson321** [ronggang/PT-Plugin-Plus#584]
最近豆瓣是不是不能查询信息了？有一段时间没看到关键字搜索的下拉列表了。

**Comment by whgipt** [comment]
我最近两天也发现这个问题了，还以为是我这边出了什么状况

**Comment by Rhilip** [comment]
受豆瓣API关闭影响，后续再改改吧。最近我也不是很空。
ref: https://www.v2ex.com/t/699393

最近空的时候在看相关绕过方法，
直接走 `https://movie.douban.com/j/subject_suggest?q=xxxxxx` 的JSON接口能拿到的东西太少了。我在PtGen中凑活用下。
如果走 `https://search.douban.com/movie/subject_search?search_text=` ，需要解析页面的 `windows.__DATA__` 对象，使用了xxhash + bplist（修改过）方法进行加密。网上流传的方法都有用，但似乎过于麻烦。我过几天看看能不能整出个npm库吧。

**Comment by ronggang** [comment]
联系过豆瓣，他们回复暂不个人开放接口；如果是以企业名义合作，需要提供企业信息和具体的API需求及产品描述，他们要进行审核后再定，我也没企业，也不知道给他怎么回复；😑

所以原来的方式，基本上没戏，只能想其他办法了。

**Comment by xiaobai987292** [comment]
https://frodo.douban.com/api/v2/movie/26799731?apiKey=054022eaeae0b00e0fc068c0c0a2102a

**Comment by Rhilip** [comment]
@xiaobai987292 亲，要的是搜索接口，不是详情接口🤔

**Comment by xiaobai987292** [comment]
https://frodo.douban.com/api/v2/search?q=我的&apiKey=054022eaeae0b00e0fc068c0c0a2102a

**Comment by Rhilip** [comment]
@xiaobai987292 感谢提供该搜索接口，我们这边对比看看吧。
除此以外，现在还比较担心frodo接口的稳定，毕竟走frodo域名接口，目前公开能找到的也就你提出来的这个0540.（事实上，我在8月18日和@haig233 他们讨论对策时，也找过并试过其他找到apikey，但有效的只有0540这个）

**Comment by xiaobai987292** [comment]
> @xiaobai987292 感谢提供该搜索接口，我们这边对比看看吧。
> 除此以外，现在还比较担心frodo接口的稳定，毕竟走frodo域名接口，目前公开能找到的也就你提出来的这个0540.（事实上，我在8月18日和@haig233 他们讨论对策时，也找过并试过其他找到apikey，但有效的只有0540这个）

这个是小程序的 稳定性应该还好

**Comment by ronggang** [comment]
@xiaobai987292 感谢提供接口！
