### ISSUE TITLE
群辉端TR升级后，PTP推送到服务器下载功能失效

### ISSUE THREAD

**Issue by lucenli** [ronggang/PT-Plugin-Plus#588]
- PT 助手版本:1.49
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chromium 80.0.3987.163
- 浏览器是否安装了其他插件：是，但是与此相关的并没有
- 停用其他插件后是否正常工作：否
- 问题描述：群辉端TR升级后，PTP推送到服务器下载功能失效，测试服务器可以连通，本机也可以正常通过chrome访问web管理TR界面，甚至TR remote GUI也可以正常工作，但是用我们的插件就不行，推送到服务器下载会一直读条，最后返回下载失败，报错404

- 相关截图：
![image](https://user-images.githubusercontent.com/16946496/91379983-740c0e00-e856-11ea-922f-86920d4c51a9.png)
以此佐证GUI是可以正常使用的
![image](https://user-images.githubusercontent.com/16946496/91379989-766e6800-e856-11ea-9bd2-ea35ca810e89.png)

- 重现步骤：如果有TR3.0的群辉端的话，应该可以稳定复现？

**Comment by Rhilip** [comment]
#573 ？

**Comment by lucenli** [comment]
> #573 ？

确实....这才意识到失败的都是sky的种子，不好意思，感谢回复
