### ISSUE TITLE
地址栏的搜索方式：PT+空格，导致其他情况下使用不便的问题

### ISSUE THREAD

**Issue by cruxpenn** [ronggang/PT-Plugin-Plus#594]
- 
chrome浏览器，搜索功能中，地址栏输入pt+空格的时候会自动跳转到PT助手，但是我并不需要这个功能，关掉权限或者停用倒是可以关闭这个烦人的骚扰操作，但是助手又不能正常使用。也没有找到其他显眼的开关。能否把这个功能设置成可选的？或者说几个搜索方式独立开来可选。印象中谷歌也挺恨这种一把抓的操作……
（地址栏搜索，遇到一些问题用pt作为第一关键词，用空格分隔下一个关键词，有时候仅仅是输入法手快之后，就会被引导到助手界面，导致使用起来很不方便）

**Comment by Rhilip** [comment]
@cruxpenn 1. 不能设置成可选，因为omnibox是在插件安装时注册的，之后助手在运行设置时没有更改的能力
2. 请给出“印象中谷歌也.....”的依据来源，我目前没有找到相关说法。
3. 如果你真的不喜欢该功能，建议安装前把mainfest.json中 "omnibox": {...} 部分删除即可。

**Comment by ted423** [comment]
@cruxpenn 我觉得这锅得chrome背，因为我也被坑过，不过不是pt,印象里要多按下退格

**Comment by RtYkk** [comment]
![y9tjGU1Vv9](https://user-images.githubusercontent.com/45971730/92316743-e507ae80-f02a-11ea-8329-ff20eda9528c.png)
还行吧，略麻烦一点，还是能用默认搜索引擎搜索的

**Comment by xmt328** [comment]
按完空格之后再按下backspace就能回到普通搜索模式

**Comment by ronggang** [comment]
@cruxpenn 就目前所知的接口，不好动态设置，可以按 @RtYkk 和 @xmt328 的方法来操作。
