### ISSUE TITLE
希望在下载服务器配置中能加入"跳过校验"的选项

### ISSUE THREAD

**Issue by Wickyan** [ronggang/PT-Plugin-Plus#595]
## 您的功能请求是否与问题有关？ 请描述一下。

![SkipChecking](https://user-images.githubusercontent.com/30826200/93241299-bec6d900-f7b7-11ea-908a-d82d28ece2c8.jpg)
qBittorrent 的WebUI在添加种子的时候可以勾选跳过哈希校验，希望能在PT-Plugin-Plus添加到服务器的时候也能跳过哈希校验。

## 其他附加信息

qBittorrent v4.2.5
PT-Plugin-Plus v1.5.0

**Comment by Rhilip** [comment]
不会做该考虑

**Comment by Wickyan** [comment]
呃。。。大批量辅种，明明已经校验完种子了，为啥还要多次校验文件？不是很明白，望告知，不胜感激。

**Comment by ted423** [comment]
@Wickyan 之前讨论过，虽然我找不到了，跳检有风险，因为早期qb可以做到无资源跳检。有很大的风险

**Comment by Wickyan** [comment]
@ted423 按道理空盘跳检即使不使用PT-Plugin-Plus，用户也能手动实现欸，因此造成的作弊损失这与PT-Plugin-Plus是否提供这个功能已经无关了（只要写好警告就行了）。。emmmm既然已经讨论过了，我似乎再说啥也没意义了

**Comment by yubanmeiqin9048** [comment]
> @Wickyan 之前讨论过，虽然我找不到了，跳检有风险，因为早期qb可以做到无资源跳检。有很大的风险

现在的QB已经不会出现这样的问题了

**Comment by ted423** [comment]
> > @Wickyan 之前讨论过，虽然我找不到了，跳检有风险，因为早期qb可以做到无资源跳检。有很大的风险
> 
> 现在的QB已经不会出现这样的问题了

仍然是有风险的，特别遇上那种文件损坏的。
基本可以想象一有这个功能就一堆人使用，然后真遇到问题了就习惯性甩锅
