### ISSUE TITLE
各个版本都有一个错误：uncaught(in promise )undefined

### ISSUE THREAD

**Issue by wangwhc** [ronggang/PT-Plugin-Plus#597]
安装好后过一段时间就会从chrome中自动消息，请问怎么解决。

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by ronggang** [comment]
这是程序里调用 promise 方法时没有处理异常导致，应该不影响正常使用。

**Comment by Rhilip** [comment]
不如我们都改成async/await，然后用try/catch吧 🤣

**Comment by maicss** [comment]
有开发者群吗？
