### ISSUE TITLE
[New Tracker Request] SportsCult

### ISSUE THREAD

**Issue by zenof** [ronggang/PT-Plugin-Plus#598]
- Tracker Name: SportsCult
- Tracker Url: https://sportscult.org/
- Tracker Description: Sports Cult is private tracker for SPORTS, the community is still growing and most of the users are active including the owner who is very helpful and they have recently launched a new feature "LIVE TV" with live tv you can stream sports event live or watch channels. SKY SPORTS, FOX SPORTS, TSN, ESPN, NBSCN, BT, EUROSPORT, NBA TV, SPORTSNET WORLD, BEIN US, m2o (Music channel) channels are available.

- Resource Type: SPORTS
- Open registration: No
- Tracker rules: https://sportscult.org/index.php?page=rules

**Comment by zenof** [comment]
bump

**Comment by ma3252788** [comment]
同求此站

**Comment by VicaYang** [comment]
同求此站

**Comment by ted423** [comment]
try this https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1985097128
