### ISSUE TITLE
北洋园页面内获取种子下载链接失败

### ISSUE THREAD

**Issue by goomadao** [ronggang/PT-Plugin-Plus#60]
- PT 助手版本:1.02
- PT 助手安装方式：chrome市场
- 浏览器名称及版本：Chrome 73.0.3683.75
- 问题描述：在北洋园种子页面内获取到了错误的种子下载链接，在pt助手搜索页面获取到的链接正常，在种子页面内点击复制链接获取到的链接也是下面日志中的错误链接。
- 相关日志：{"event":"requestMessage.getTorrentDataFromURL","module":"background","time":1552718209935},{"data":{"msg":"[https://tjupt.org/注意：链接中包含passkey，切勿泄露！&https=1] 下载失败，返回的状态码为：404","success":false,"type":"error"}
- 相关截图：
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/39483078/54471874-07848700-47fb-11e9-9310-601634f7dec2.png">

**Comment by tongyifan** [comment]
你应该对「下载种子」的按钮右键，选择 下载到，而不是那个获取直链的按钮

**Comment by goomadao** [comment]
> 你应该对「下载种子」的按钮右键，选择 下载到，而不是那个获取直链的按钮

对「下载种子」的按钮右键获取到链接确实正常，但是通过
<img width="114" alt="image" src="https://user-images.githubusercontent.com/39483078/54472537-98139500-4804-11e9-80ae-0ed3cc832f6a.png">
上一键下载、下载到、复制链接按钮获取到的链接都是错误的

**Comment by ronggang** [comment]
已修复待发布：https://github.com/ronggang/PT-Plugin-Plus/commit/358910285921114015ba8a4fbb669e948f439164

**Comment by lvhe19880210** [comment]
ttg出现同样问题

**Comment by lvhe19880210** [comment]
<img width="1341" alt="截屏2019-12-07下午10 08 51" src="https://user-images.githubusercontent.com/29178968/70375905-6c11e400-193e-11ea-913c-8848e8fc490d.png">

**Comment by ted423** [comment]
@lvhe19880210 建议说明详细操作步骤

**Comment by lvhe19880210** [comment]
> @lvhe19880210 建议说明详细操作步骤
> 建议先看是否使用最新的1.4.4

操作步骤跟上面的描述一致 也是对「下载种子」的按钮右键获取到链接确实正常，但是通过其它方式就不行 版本确认是crx最新版

**Comment by ted423** [comment]
@lvhe19880210 我这测试正常

**Comment by ted423** [comment]
@lvhe19880210 另外，你反馈的问题与这个issue应该是不同的原因，所以我建议你开个新issue,虽然我仍然感觉你的可能是被那个阻拦页阻拦了....

**Comment by golezi** [comment]
已更新到1.4.4 复制和发送到服务器都还是有问题
复制出来的是当前网页链接

**Comment by lvhe19880210** [comment]
> @lvhe19880210 另外，你反馈的问题与这个issue应该是不同的原因，所以我建议你开个新issue,虽然我仍然感觉你的可能是被那个阻拦页阻拦了....
我的issue确实不一样，可能不算是bug，我ttg的问题是点进去具体某个种子的页面详情后再下载就正常，多种子主页的话直接拖移或者右键单击某个种子标题链接就不行，但是在某个种子的下载按钮那右键点击就行，而动漫花园就没问题
我觉得应该是跟主页链接类型有关，看我截图貌似rss订阅不认这种链接， 动漫花园种子标题是这样的链接：https://u2.dmhy.org/details.php?id=36792&hit=1 而ttg种子标题是这样的链接https://totheglory.im/t/36792/
<img width="689" alt="截屏2019-12-08上午11 54 10" src="https://user-images.githubusercontent.com/29178968/70384157-5a1f5800-19b5-11ea-8024-09ad66888695.png">

**Comment by Rhilip** [comment]
您好，不属于 北洋园 站点错误，请另开issue讨论说明完整情况，此issue做lock处理
