### ISSUE TITLE
HDSKY 列表页 插件右键下载未修复完全

### ISSUE THREAD

**Issue by ceozero** [ronggang/PT-Plugin-Plus#600]
#573
内容页和一键下载都正常了。
但是右键点击列表页的下载还是404

**Comment by Rhilip** [comment]
其实我挺想知道，你在该站点是怎么右键点击列表页下载的。
因为按照该站点对下载操作的魔改以及本插件对contentMenus的设置，在该站点是不可能实现右键点击发送的。

**Comment by ceozero** [comment]
> 其实我挺想知道，你在该站点是怎么右键点击列表页下载的。
> 因为按照该站点对下载操作的魔改以及本插件对contentMenus的设置，在该站点是不可能实现右键点击发送的。

![pt](https://user-images.githubusercontent.com/22513657/94659149-6d315900-0336-11eb-8c26-aa31a2932055.jpg)
![pt1](https://user-images.githubusercontent.com/22513657/94659139-69053b80-0336-11eb-88d6-b2794f609089.png)

难道只有我一个人这么用吗？
我习惯了在列表页右击帖子链接发送给PT的，，我其他的站也都是这么用的。。有些站需要填key，有的站不需要填key。
hdsky 最近发现链接有变化，然后修复了这个bug，帖子页面和pt搜索页面都能正常下载了，，，列表页右键这里还是没修复完整。

**Comment by Rhilip** [comment]
@ceozero 把你的passkey删了试试？

**Comment by ceozero** [comment]
> @ceozero 把你的passkey删了试试？

删了也是不行的。

**Comment by Chihaya7** [comment]
如下方式 , 拖放下载也未修
![avatar](https://github.com/ronggang/PT-Plugin-Plus/wiki/images/2019-01-04_12-05-51.gif)
[(图片引自wiki介绍)](https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-send-torrent)

另一个自构链接站点HDC同样遗留如上问题
不过hdc可以 拖放种子下载图标获得正确的链接实现下载
![avatar](https://s1.ax1x.com/2020/10/02/0QQPSI.jpg)
但SKY种子下载链接放在表单里,拖放获取不到..
![avatar](https://s1.ax1x.com/2020/10/02/0QQilt.jpg)

**Comment by ronggang** [comment]
> 如下方式 , 拖放下载也未修
> ![avatar](https://github.com/ronggang/PT-Plugin-Plus/wiki/images/2019-01-04_12-05-51.gif)
> [(图片引自wiki介绍)](https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-send-torrent)
> 
> 另一个自构链接站点HDC同样遗留如上问题
> 不过hdc可以 拖放种子下载图标获得正确的链接实现下载
> ![avatar](https://camo.githubusercontent.com/4ba16c15b27c7c1b129ded4d95f12c2b67758ff9/68747470733a2f2f73312e617831782e636f6d2f323032302f31302f30322f3051515053492e6a7067)
> 但SKY种子下载链接放在表单里,拖放获取不到..
> ![avatar](https://camo.githubusercontent.com/7037df58d79c98a17d2d4de107736b86492536d3/68747470733a2f2f73312e617831782e636f6d2f323032302f31302f30322f305151696c742e6a7067)

拖放仅适用于常规的链接，像SKY的 form 目前没有做适配。
