### ISSUE TITLE
DICMusic使用下载推送会把当前专辑的所有版本种子连接全部推送，请问有没办法只推送一个指定的种子？

### ISSUE THREAD

**Issue by KempLeung** [ronggang/PT-Plugin-Plus#601]
第一次玩Gazelle架构的站，很多不熟悉
目前在DICMusic点开一张专辑页面，如果有多个版本的种子，推送下载会把全部种子都推送到下载器，回头还得手动删掉不需要的
请问如何只推送一个指定的种子

PT 助手版本:1.5.0

PT 助手安装方式：Microsoft Edge 商店

浏览器名称及版本：Microsoft Edge 版本 86.0.622.28 (官方内部版本) beta (64 位)

浏览器是否安装了其他插件：否

停用其他插件后是否正常工作：否

问题描述：
目前在DICMusic点开一张专辑页面，如果有多个版本的种子，推送下载会把全部种子都推送到下载器
相关截图：

重现步骤：Dicmusic打开一张有多个版本种子的专辑页面，点击右则PT助手工具栏“下载到”按钮，选定路径后，右下角开始显示推送状态，并闪过多条不同的推送链接，推送完成后显示“n条链接已发送完成”

**Comment by ted423** [comment]
@KempLeung DL连接上右键

**Comment by KempLeung** [comment]
> @KempLeung DL连接上右键

好的，谢谢告知！
问题解决了，可以close了
