### ISSUE TITLE
主板拔过电池后，开机未意识到时间有误，开了浏览器刷新数据，留下了2009-01-01的数据，使数据图表从2009到今年有一段，请问如何消除？

### ISSUE THREAD

**Issue by 183011781** [ronggang/PT-Plugin-Plus#603]
- PT 助手版本:1.5.0
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：
![QQ图片20201003151111](https://user-images.githubusercontent.com/60918961/94985610-bbd73100-058a-11eb-8f04-a1f9ae02611d.png)

- 重现步骤：

**Comment by Rhilip** [comment]
参阅 https://github.com/ronggang/PT-Plugin-Plus/issues/537

**Comment by 183011781** [comment]
> 参阅 #537

经过十几次操作，终于搞定了。。。

**Comment by 183011781** [comment]
> 参阅 #537

感谢
