### ISSUE TITLE
firefox android v68.11.0版使用ptpp v1.50自签名版的一些小bug

### ISSUE THREAD

**Issue by zhufeng** [ronggang/PT-Plugin-Plus#604]
- PT 助手版本: v1.5.0
- PT 助手安装方式：（市场安装，或zip包安装） 使用源码zip提交到moz开发者中心自签名版
- 浏览器名称及版本：firefox android v68.11.0 (play版)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

目前的版本（v1.5.0）自签名版在firefox android上无法获取filelist站的数据，最右侧直接提示暂不支持。
看了一下站点设置，应该是把站的地址写错了。正确的应该是filelist.io，站点设置里面写成了filelist.ro，但是我手动添加CDN地址为https://filelist.io也不行。

另外，也无法获取hdroute站的数据，直接提示“未登录”，但是点进去之后实际上是已经登录了的。
另外v1.4.8版本的时候hdcity站也有这个问题，但是在v1.5.0版hdcity站这个问题已经解决了，点个赞。

之前提过hdroute站的这个问题，但是我不知道怎么协助排查，如果有排查步骤能否提供一下，我可以协助排查问题，谢谢。

- 相关截图：暂无

- 重现步骤：暂无

**Comment by ted423** [comment]
@zhufeng filelist不止一个域名吧

**Comment by zhufeng** [comment]
> @zhufeng filelist不止一个域名吧

filelist.ro 应该是打不开的吧？我试了不行，直接用filelist.io就行。
另外，我看安装在chrome zip电脑版的站点设置，filelist的域名又是正确的filelist.io。
不过这应该跟我提交zip到moz开发者中心审核没有关系吧？

**Comment by ted423** [comment]
@zhufeng 问题不是这个，问题是扩展的站点配置改了以后需要重新添加，fl改域名后目测你没重加

**Comment by zhufeng** [comment]
> @zhufeng 问题不是这个，问题是扩展的站点配置改了以后需要重新添加，fl改域名后目测你没重加

感谢解答，filelist删除站点重新添加一下刷新之后可以了。

然后hdroute的问题也解决了，方法是在站点的CDN里面添加一行 域名/#，即强制使用桌面版布局。

**Comment by zhufeng** [comment]
已解决。
