### ISSUE TITLE
HDHome的"LIVE"版块资源助手搜索不到，且"LIVE"版块种子列表页面不显示侧边工具栏

### ISSUE THREAD

**Issue by yankun141** [ronggang/PT-Plugin-Plus#608]
- PT 助手版本:1.5.0
- PT 助手安装方式：crx安装
- 浏览器名称及版本：Google Chrome 85.0.4183.121（正式版本）（64 位）
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：在助手的“站点设置”里已添加HDHome站点，但"LIVE"版块里的资源助手搜索不到，且"LIVE"版块种子列表页面不显示侧边工具栏（HDHome其他版块种子列表均正常显示侧边工具栏）。

- 相关截图：

- 重现步骤：

**Comment by tongyifan** [comment]
#610
