### ISSUE TITLE
m-team可以显示信息但是不能搜索种子

### ISSUE THREAD

**Issue by wangxinjie16888** [ronggang/PT-Plugin-Plus#609]
- PT 助手版本:1.5.0
- PT 助手安装方式：（市场安装，或zip包安装）crx 安装
- 浏览器名称及版本：360极速浏览器
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
可以添加mteam站点，也可以查看各种信息，就是不能搜索种子

- 相关截图：
<img src="https://www.z4a.net/images/2020/10/07/5e0a6cf42a3ed26cd7860f73ac27f01.png" alt="5e0a6cf42a3ed26cd7860f73ac27f01" border="0">

<img src="https://www.z4a.net/images/2020/10/07/_202010071148307b817f7229018bdc.png" alt="微信截图 20201007114830" border="0">

<img src="https://www.z4a.net/images/2020/10/07/_20201007115013.png" alt="微信截图 20201007115013" border="0">

![_20201007115209.png](https://www.z4a.net/images/2020/10/07/_20201007115209.png)
- 重现步骤：
暂无

**Comment by ted423** [comment]
检查站点里的设置，或者重开下助手页面

**Comment by wangxinjie16888** [comment]
![_20201007121833.png](https://www.z4a.net/images/2020/10/07/_20201007121833.png)
应该是设置好了 助手也重开试过了

**Comment by ted423** [comment]
你这hdhome也没搜索吧？

**Comment by wangxinjie16888** [comment]
缺两个站点····hdhome不行就算了 主要是mteam常用···

**Comment by ted423** [comment]
@wangxinjie16888 试试别用360

**Comment by wangxinjie16888** [comment]
好的  我试下chrome

**Comment by wangxinjie16888** [comment]
![_20201007134322.png](https://www.z4a.net/images/2020/10/07/_20201007134322.png)
怀疑是个bug 只要改成这个样子 就可以去搜索

**Comment by wangxinjie16888** [comment]
取消“站点已离线（停机/关闭）”这个按钮就行了

**Comment by ted423** [comment]
…………手机看图没看仔细……
