### ISSUE TITLE
新版本豆瓣接口速度极慢

### ISSUE THREAD

**Issue by Cyberxxt** [ronggang/PT-Plugin-Plus#615]
- PT 助手版本:1.50
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 86.0.4240.75
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：豆瓣接口修复之后速度变得很慢，打入标题以后很久都跳不出选择下拉菜单。只能通过手动豆瓣搜索tt编号查询剧集。请问是什么问题导致的呢？

- 相关截图：
![image](https://user-images.githubusercontent.com/40683077/95651106-55b65500-0b1a-11eb-8760-20af3fd8b7d1.png)

- 重现步骤：

**Comment by Rhilip** [comment]
请至 https://github.com/ronggang/PT-Plugin-Plus/actions/runs/300230301 中下载最新构建，查看是否修复。
