### ISSUE TITLE
PT助手搜索结果多选下载失败的无法看到是哪个站失败

### ISSUE THREAD

**Issue by petertang010** [ronggang/PT-Plugin-Plus#617]
PT 助手版本:1.50

PT 助手安装方式：zip包安装

浏览器名称及版本：Chrome 86.0.4240.75

浏览器是否安装了其他插件：是

停用其他插件后是否正常工作：否

问题描述：PT助手搜索结果多选下载失败的无法看到是哪个站失败，重试很多次也没有下成功，想进网站下载又知道是哪个站。

相关截图：

重现步骤：

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/555
相关问题

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/555
