### ISSUE TITLE
无法获取Pornbits的入站日期

### ISSUE THREAD

**Issue by tainewoo** [ronggang/PT-Plugin-Plus#619]
- PT 助手版本: PT-Plugin-Plus v1.5.0
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge 86.0.622.38
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：无法获取Pornbits的入站日期, 显示为800-01-01 00:00:00

- 相关截图：
![pornbits_registerdate](https://user-images.githubusercontent.com/13391232/95940027-fe60ff00-0e0f-11eb-942a-79f3574eb4bc.png)

- 重现步骤：添加Pornbits站点并启用"允许获取用户信息",点击刷新我的数据,等待数据刷新完成.

**Comment by ted423** [comment]
我这获取是正常的，能否提供下user/details 关于加入时间这块的截图？

**Comment by tainewoo** [comment]
Hi @ted423 ,
截图如下:
![userdetails](https://user-images.githubusercontent.com/13391232/95995917-a7d1e000-0e64-11eb-87c3-4e992a51a755.png)

**Comment by ronggang** [comment]
这种日期格式需要单独适配。

**Comment by ted423** [comment]
这样么..但我这里不知道为啥识别是正常得。。

**Comment by ted423** [comment]
2019-12-27

**Comment by ronggang** [comment]
看错，看成 last seen 了。按 member since 的日期应该可以正常适配的。。

**Comment by tainewoo** [comment]
奇怪,你们都可以适配么..
我这边识别结果是这样的:
![pbNpt](https://user-images.githubusercontent.com/13391232/98065319-55964480-1e8f-11eb-93af-ca16e01c6696.png)

我是Win10 + MS新版Chrome内核的Edge.
会不会这个有不同?

**Comment by tainewoo** [comment]
需要补充什么信息么?

那部分的网页代码如下:

 `<strong>Member Since:</strong> 2016-12-14		</div>`

**Comment by tainewoo** [comment]
奇怪,今天竟然突然就能获取到进站日期了.
每天自动刷,那么久了第一次成功获取.

**Comment by ted423** [comment]
@tainewoo 讲不清楚原因，一方面也是没太大精力去弄(

**Comment by tainewoo** [comment]
@ted423 
我看了一下,前后的不同在于,我之前"Title"那一栏的值和我的username是一样的,最近我把"Title"这一栏的值清除掉了.
不知道会不会是因为这个有影响到代码里的搜索匹配条件.

**Comment by ted423** [comment]
那应该是了，因为选择器是 #content > div > div.col-md-3 > div:nth-child(5)
多一个少一个啥的都有影响

**Comment by tainewoo** [comment]
那大概是了.
我这边现在有办法work了,你也大概找到原因了,需要的话我回头把这个issue关闭.

**Comment by ted423** [comment]
@tainewoo 先留着吧，有空可以修下
