### ISSUE TITLE
在插件中搜索时KEEPFRDS 错误Error: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by ywtz1** [ronggang/PT-Plugin-Plus#620]
- PT 助手版本:1.5
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：火狐 81.0.2

- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：
- 问题描述：
PT@KEEPFRDS
Error: Could not establish connection. Receiving end does not exist.
搜索时KEEPFRDS显示以上错误

- 相关截图：
![图片](https://user-images.githubusercontent.com/54674564/96075996-e73d1280-0ede-11eb-93d5-5b6f932144b1.png)

- 重现步骤：

[PT-Plugin-Plus-System-Logs.json.log](https://github.com/ronggang/PT-Plugin-Plus/files/5382389/PT-Plugin-Plus-System-Logs.json.log)

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/574
请在这里讨论
