### ISSUE TITLE
不能搜索聆音阅听专区内容

### ISSUE THREAD

**Issue by ywtz1** [ronggang/PT-Plugin-Plus#621]
- 
在插件中搜索时不能搜索到聆音阅听专区内容
请问搜索入口应该如何配置

**Comment by ronggang** [comment]
可以自己定义试试
https://github.com/ronggang/PT-Plugin-Plus/wiki/search-entry-definition

**Comment by shenjiangqiu** [comment]
聆音无法添加自定义搜索
