### ISSUE TITLE
LeagueHD（柠檬）的"音乐"、“动漫”、“MV”、“纪录片”版块里的资源，助手搜索不到

### ISSUE THREAD

**Issue by yankun141** [ronggang/PT-Plugin-Plus#622]
- PT 助手版本:1.5.0
- PT 助手安装方式：crx安装
- 浏览器名称及版本：Google Chrome 85.0.4183.121（正式版本）（64 位）
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：在助手的“站点设置”里已添加LeagueHD站点，但"音乐"、“动漫”、“MV”、“纪录片”版块里的资源助手搜索不到

- 相关截图：

- 重现步骤：

**Comment by shui** [comment]
可以加个参数，综合和分类同时搜索，有结果就一起返回结果，分类没结果也不用单独提示

音乐|`?music=yes`
:--|:--
MV|`?mv=yes`
动漫|`?animate=yes`
纪录片|`?documentary=yes`

**Comment by iyuangang** [comment]
#637 已修复

**Comment by zhui22222** [comment]
为什么更新了还是不行？

**Comment by ted423** [comment]
@zhui22222 你更新啥了

**Comment by iyuangang** [comment]
> 为什么更新了还是不行？

https://github.com/ronggang/PT-Plugin-Plus/actions/runs/372290535 下载这个dev 编译出来的zip 文件更新

**Comment by zhui22222** [comment]
可以了，谢谢。
