### ISSUE TITLE
[站点添加请求] 海胆之家（haidan.video)

### ISSUE THREAD

**Issue by rsj123** [ronggang/PT-Plugin-Plus#623]
RT.

站点名称：海胆之家
站点地址：www.haidan.video
站点描述：新PT站点
资源类型：综合
开放注册：否
是否连坐：否
站点规则：无考核，分享率大于等于1即可

已查看到：
1. [模板](https://github.com/ronggang/PT-Plugin-Plus/issues/30#issuecomment-631868886)
2. 以及Issues #570  

但是模板无法被使用，站点无法被搜索，提示：[海胆]没有定位到种子列表，或没有相关的种子
在网站中也无插件悬浮窗，所以希望重新适配

**Comment by rsj123** [comment]
一个修正，在网页有插件悬浮窗，但插件仍无法搜索

**Comment by hooao** [comment]
haidan站能添加，但搜索功能有问题。
