### ISSUE TITLE
下一步开发建议讨论

### ISSUE THREAD

**Issue by Rhilip** [ronggang/PT-Plugin-Plus#625]
这是一个比较长久的开发建议，其原因在于经过较长时间的开发和合并，目前项目过于臃肿，需要进一步重构。此外，Vue 3的出现（虽然相关生态还未完全建立），有必要进行进一步更新。

就开发角度，目前有以下几点希望讨论：

- [ ] option页面目前使用Vuetify框架（v1），目前此框架已经出了v2版本。另一方面，该框架对汉语开发者并不友好，v1和v2的中文文档都有缺失情况。我个人比较建议切换到 antdv 或者 element-ui 上，相对可能会有更多国内开发者来参与。
- [ ] 目前对各个站点、各个下载服务器都采用js的方法进行解析或支持（即resource目录），不同类之间缺少抽象和继承关系，带来大量的代码冗余，此外resoucre目录的结构和使用方式（eval）导致了最终构造出来的均带有原始文件信息，无法被webpack有效压缩。（目前考虑的是将clients，schemas，sites等移入background中）
- [ ] 取消使用chrome命名空间，改用Web Extension标准中的brower命名空间进行操作。底层使用 https://github.com/mozilla/webextension-polyfill 抹平浏览器差异。（Safari 开始支持 WebExtension， 之前Firefox直接构造chrome对象进行polyfill）
- [ ] 将部分操作从目前Promise异步回调形式，改为 async/await + throw Exception 形式。优化代码结构，同时避免部分大量并发情况。
- [ ] 对原先使用jQuery操作DOM和AJAX的操作，改为使用DOMParser和axios+axios-extensions的方式，页面注入使用vue app应该是可行的。但是目前来看，浏览器原生的 `document.querySelector` 对于CSS选择器的支持程度并没有jQuery高 （部分对比 [jQuery Selector](https://api.jquery.com/category/selectors/) vs [querySelector](http://xahlee.info/js/css_selector_syntax.html)），部分DOM查询操作可能存在较难迁移的问题。（或者可以考虑使用 cheerio-without-node-native ？）
- [ ] （此点与上一点相关）因为目前我们在CSS选择器中多使用`:contains()` 这个不是原生的方法，其未被 `document.querySelector` 所支持，那么是否可以考虑使用XPath的方式，即 `Document.evaluate()` 来进行匹配。相关文档： https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate
- [ ] 解除目前下载服务器和插件主体功能强耦合状态，或提供zip包下载器（注：类似于部分站点提供的以zip包形式下载多个种子文件的功能）。
- [ ] changelog 不放入插件内，使用 `CHANGELOG.md` 文件放在项目根目录。
- [ ] 取消可选权限在`manifest.json`中的注册，这个之前是为了避免商店的审核，但是目前的情况，增加可选选项并没有给通过审核。此外，部分浏览器对可选权限的支持有限，部分情况下用户难以直接进行选择。此外还存在部分站点获取用户信息必须要使用Cookies的情况。
- [ ] 优化用户数据获取，目前用户数据获取存在多步走的情况，以NPHP站点为例，基本要第一步先获取ID，再进一步访问userdetails页面。而其实第一步是第一次获取之后优化掉的。
- [ ] ~~对站点域名进行保护，不直接以url硬编码形式写入配置文件，而是改成base64的形式编码，在运行时还原。（复盘后觉得意义不大，且增加维护难度，故删去）~~ 此外，对CDN域名这个站点配置进行调整，内置已知的站点别名域名，提交给用户选择，如果仍非用户当前使用，则提供填写入口。

**Comment by ted423** [comment]
@Rhilip 拖动出框自动关窗口会好么，我目前感觉刷新数据占用好高，这个切换后会好么🙈

**Comment by Rhilip** [comment]
@ted423 之前看ronggang大的意思，Vuetify v2 是解决了 “拖动出框自动关窗口”问题。当然我更建议换框架，Vuetify维护起来过于麻烦。
对于刷新数据占用，我觉得部分从promise改成async/await可能能解决占用（已经补充）。但是对Promise可能要扩展，比如使用bluebirdjs，因为他的 Promise.map 提供了concurrency选项，这样我们就可以对同时进行的请求数量进行限制，从而减少占用。

**Comment by mifanw** [comment]
批量下载种子这个功能非常好用  尤其在需要下载大量种子辅种的情况下
但是这个下载目录设置功能 不知道是否我没用对  感觉不好用 能不能加上自订目录组合的功能
比如种子的下载地址是 www.aaa.bbb?id=123456&param=789012  批量下载的时候我可以实现设定每次下载下载的目录自动设置为 /Download/aaa/123456/
因为这样比较好管理 也防止有些种子不规范没有根目录导致都在一个文件夹里  如果名称一样还会相互覆盖
当然不止能用ID作为目录  比如当前页面的名称是   站点名 - aaa - bbb  批量下载也能自动根据自订规则下载到目录 /Download/站点名/aaa/ 
类似这样的功能

**Comment by ronggang** [comment]
今年因个人原因，对项目的参与度低了些。🙏
重构需要花大量的时间，看起来目前时间不允许。
关于 `Vuetify` ，当初花了不少时间选择，主要是没有找到好用的 `tabel` 组件，多方比较后还是觉得 `Vuetify` 比 `element-ui` 合适，并一直沿用；v2的之前也大概看了下，升级应该没问题。

这个主题可以好好讨论一下。

**Comment by enigmazack** [comment]
推荐下quasar，相对于其他的ui框架，这个提供了一整套的开发框架，开箱即用，非常方便。

**Comment by Rhilip** [comment]
> 推荐下quasar，相对于其他的ui框架，这个提供了一整套的开发框架，开箱即用，非常方便。

我看了下，觉得quasar 也可行，毕竟其CLI支持建立BEX应用，而且能延续目前使用的Vuetify中的material理念。国内 antdv 或者 element-ui 在这方面处理起来都挺麻烦的。
之前我在提出这个issue的时候还选型过 https://vue-web-extension.netlify.app/ ，觉得也是比较好的替代方法。毕竟目前整个应用构造方式方式过于麻烦，如果能把这部分工作交给底层模块，能极大的减轻我们的工作。
正好quasar其路线图应该是在今年年底能完成对Vue3的支持，我预期的也是明年再开始这块重构（今年剩下时间看起来我和ronggang都不太有空以及精力完成重构工作），到时候可以再做关注。

**Comment by ZORfree** [comment]
为啥没有一键签到呀

**Comment by ted423** [comment]
@ZORfree 自己issue里搜下先 https://github.com/ronggang/PT-Plugin-Plus/issues/334 请不要在正经的讨论里问白痴问题
