### ISSUE TITLE
外站搜索时，如果是中文+英文的搜索条件，返回的是只有英文的结果

### ISSUE THREAD

**Issue by godson321** [ronggang/PT-Plugin-Plus#626]
外站搜索时，如果是中文+英文的搜索条件，返回的是只有英文的结果，并不是and逻辑

![111](https://user-images.githubusercontent.com/28944100/96991172-a4bcab00-155a-11eb-8102-a7245fdd39bf.png)

**Comment by ted423** [comment]
@godson321 你在这个站站内搜索也是一样
