### ISSUE TITLE
FeatureRequest: 增加批量导出任务Torrent文件功能

### ISSUE THREAD

**Issue by tainewoo** [ronggang/PT-Plugin-Plus#627]
## 您的功能请求是否与问题有关？ 请描述一下。

目前助手无法导出下载服务器上或者站点个人资料中的种子.
(我使用的是群晖的DownloadStation,不知道助手搭配其他方案是否已经有这个功能)

## 描述你想要的解决方案

1. 通过(选定的所有或者个别)下载服务器,导出所有任务的torrent,导出时建议至少使用资源名命名,或者站点名+资源名命名,不要命名为编号之类的.
考虑到下载服务器中可能有进行中的任务也有暂停的任务,此导出任务的数目会和站点上看到的做种任务不完全一致,应能包含所有任务.

2. 通过(选定的所有或者个别)站点,导出所有做种任务和下载中任务的torrent,导出时建议至少使用资源名命名,或者站点名+资源名命名,不要命名为编号之类的.
如有可能,可以增加将做种或者下载任务做分类.

## 描述您考虑过的替代方案

暂无.

## 其他附加信息

暂无.

**Comment by Rhilip** [comment]
1. 导出下载服务器的难以做到。请查看并告知各下载器的API是否能支持种子文件导出。据我所知，de,tr,qbt都没有相关支持。建议另寻他法。
2. 同样目前并无想法。建议走linkdump路径，或者要求站点sysop提供zip包下载方法。

**Comment by tainewoo** [comment]
1. 导出下载服务器的,我使用的是群晖的DownloadStation,在DownloadStation里每一个任务最底下是有一个"下载原始Torrent"的链接,但不知道是不是有提供API直接调用.

![export-torrent](https://user-images.githubusercontent.com/13391232/97515097-39942e00-19cb-11eb-8179-c07d2dffdde0.png)

**Comment by Rhilip** [comment]
我在文档中没有找见该方法，估计得抓包了解了。

https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf

另外，对于只有单个下载服务器支持的功能，一般也不会做支持考虑。更希望能是普适性的功能。

**Comment by luckiestone** [comment]
就实现原理上讲插件可能无法完成，IYUU或许有开发本功能的基础条件。

**Comment by Rhilip** [comment]
@luckiestone IYUU一样走API，其转移功能一样是同机指定目录的，所以基础条件都是一样的。要看对应客户端时候开放通过API获取种子的功能。如果没有提供，我们不会考虑支持这种从下载器中导出Torrent的功能，因为也提供不了。

**Comment by ted423** [comment]
@Rhilip ds是基于tr,tr的种子是根据任务名，我感觉winscp连进去找种子传出来似乎是个好选择，或则干脆软连接到共享文件夹，整个搜索啥的

**Comment by ted423** [comment]
@ted423 不过与助手无关就是了😂

**Comment by Rhilip** [comment]
@ted423 那也不是一个插件能够完成的事情。。

**Comment by tainewoo** [comment]
貌似有api?
下图:
![download-api](https://user-images.githubusercontent.com/13391232/102307640-dd4b9480-3f9f-11eb-9225-2d468f8a53bd.png)

**Comment by tainewoo** [comment]
看到个文档:
https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/DownloadStation/All/enu/Synology_Download_Station_Web_API.pdf

**Comment by Rhilip** [comment]
还是那个原因：
1. 官方文档未给出 `SYNO.DownloadStation2.Task.Source` 接口的具体用法。
2. 即使给出了，目前看也只是DS单独支持的方法，我未见到其他Btclient有相关支持，不太可能统一适配。
