### ISSUE TITLE
torrentleech不匹配

### ISSUE THREAD

**Issue by mayziran** [ronggang/PT-Plugin-Plus#629]
- PT 助手版本:1.5.0
- PT 助手安装方式：（市场安装，或zip包安装）microsoft store
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：应该无关
- 停用其他插件后是否正常工作：应该无关
- 问题描述：刚注册torrentleechh，发现无法导入，手动配置显示未登录，应该和cdn无关，域名一致，tg群里大佬说是改版了不适配，希望修复下。

- 相关截图：

- 重现步骤：

**Comment by tainewoo** [comment]
这个问题是因为TL于11月1日改用新版UI导致的.
需要适配.
目前UI好像还继续在微调中.今天看到的和昨天有轻微不同.
