### ISSUE TITLE
下载到非默认目录时为暂停状态，不会自动开始下载。

### ISSUE THREAD

**Issue by vobsub** [ronggang/PT-Plugin-Plus#63]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.02
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome 70.0.3538.110 64bit
- 环境：M-team,Transmission 版本：2.94 (0), RPC: 15, WEB Control: 1.6.0 beta(20180906)
- 问题描述：配置了3个下载目录，除了下载到默认目录正常自动开始下载外，下载到其他目录时是暂停状态的，需要手动点开始才会下载。

**Comment by ronggang** [comment]
@vobsub 感谢反馈，已知Bug (3a2ece70e3bdb4aafe7343cde623c139b5cbc668)，下一版本发布时会修复。
