### ISSUE TITLE
TorrentLeech改版之后无法获取个人数据，种子搜索正常

### ISSUE THREAD

**Issue by xana2333** [ronggang/PT-Plugin-Plus#634]
- PT 助手版本:v1.5.0 
- PT 助手安装方式：（市场安装，或zip包安装）crx包
- 浏览器名称及版本：Chrome  86.0.4240.183
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：不能
- 问题描述：
尝试获取个人数据，提示“未登录”。但是实际上是登陆好了的，使用搜索功能可以正常搜索到预期的种子。

- 相关截图：
![image](https://user-images.githubusercontent.com/68159785/99075551-a119c280-25f4-11eb-9d13-f001753e47da.png)
![image](https://user-images.githubusercontent.com/68159785/99075596-b1ca3880-25f4-11eb-89f4-0142bc3033e4.png)

- 重现步骤：
只要尝试获取TL的个人数据即可重现。

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/629
