### ISSUE TITLE
mac版chrome重启机器后插件就会被自动删除

### ISSUE THREAD

**Issue by gdw1986** [ronggang/PT-Plugin-Plus#635]
- PT 助手版本: 1.5.0
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome:版本 86.0.4240.193（正式版本） (x86_64)
- 浏览器是否安装了其他插件：安装了
- 停用其他插件后是否正常工作：我觉得不是其他插件的问题
- 问题描述：
在口出站工具里能找到
提示：该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

- 相关截图：

- 重现步骤：

<img width="411" alt="截屏2020-11-14 下午9 03 28" src="https://user-images.githubusercontent.com/34961194/99147554-f02b2a80-26bc-11eb-8f1c-2c8d18283e58.png">

**Comment by ted423** [comment]
https://xclient.info/a/1ddd2a3a-d34b-b568-c0d0-c31a95f0b309.html

**Comment by gdw1986** [comment]
> https://xclient.info/a/1ddd2a3a-d34b-b568-c0d0-c31a95f0b309.html

感谢，搞定了！
