### ISSUE TITLE
无法修改基本设置

### ISSUE THREAD

**Issue by zieglar** [ronggang/PT-Plugin-Plus#64]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.2
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome 72.0.3626.121
- 问题描述：基本设置中无法保存每站点结果返回数量、下载体积确认大小、连接下载服务器超时时间

**Comment by ronggang** [comment]
@zieglar 是否已配置下载服务器并选择了一个下载服务器？

**Comment by zieglar** [comment]
已经配置下载服务器并设置为站点默认下载服务器

**Comment by ronggang** [comment]
@zieglar 参数提示已保存成功，但实际没生效吗？重新打开配置页还是看到修改前的内容？

**Comment by zieglar** [comment]
修改设置以后保存按钮为灰色无法点击

**Comment by ronggang** [comment]
@zieglar 保存按钮唯一的条件就是“默认下载服务器”未选择时才会灰色。请尝试将下载服务器删除后重新添加，再回到基本设置里选择一个默认下载服务器，看看保存按钮会不会变为绿色。

**Comment by zieglar** [comment]
已经好了，谢谢。
