### ISSUE TITLE
无法刷新出柠檬和猫站保种数

### ISSUE THREAD

**Issue by springeddie00** [ronggang/PT-Plugin-Plus#645]
- PT 助手版本:最新版
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：google
- 浏览器是否安装了其他插件：no
- 停用其他插件后是否正常工作：
- 问题描述：无法刷新出柠檬和猫站保种数

- 相关截图：

- 重现步骤：

**Comment by Steve-She** [comment]
You can update the plugin from #637 to solve the bug about  LeagueHD

**Comment by springeddie00** [comment]
柠檬已解决 猫站这个现在也无法刷新出保种数

**Comment by wangvic21** [comment]
柠檬修改网址了。。
