### ISSUE TITLE
LeagueHD (now LemonHD) has changed its domain, the plugin needs upate.

### ISSUE THREAD

**Issue by Steve-She** [ronggang/PT-Plugin-Plus#647]
- PT Plugin Plus version: v1.5.0
- PT Plugin Plus installation method: zip package installation
- Browser name and version: Microsoft Edge 87.0.664.60 
- Whether the browser has other plugins installed: Yes, only essential plugins such as ublock and Tampermonkey
- Is it working properly after disabling other plugins: Yes
- Problem Description: LeagueHD has changed its website domain, the plugin needs upate

- Related screenshots: No need.

- Reproduce steps: the plugin cannot get all types of data from LeagueHD (now LemonHD)

**Comment by Rhilip** [comment]
I'm sorry, but I don't know the new host of this site, Could you open a pull request or check if the exist pr #643 #638 #637 fixed your problem ?

**Comment by xiaobai987292** [comment]
> I'm sorry, but I don't know the new host of this site, Could you open a pull request or check if the exist pr #643 #638 #637 fixed your problem ?

the new host is [https://lemonhd.org/](url)

**Comment by Rhilip** [comment]
closed at #648
