### ISSUE TITLE
oppaiti无法正常更新用户信息

### ISSUE THREAD

**Issue by kafuuchino-s** [ronggang/PT-Plugin-Plus#652]
- PT 助手版本: 版本 v1.5.0 zip
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome 版本 87.0.4280.88（正式版本）
- 浏览器是否安装了其他插件：是，但不是pt插件
- 停用其他插件后是否正常工作：否
- 问题描述：
使用一键导入站点的方式导入的，但oppaiti无法正常更新用户信息，之前没有问题，手动可以正常进入oppaiti。

- 相关截图：
![image](https://user-images.githubusercontent.com/51790568/102641425-f432e800-4153-11eb-84f6-e9d454ec8533.png)
![image](https://user-images.githubusercontent.com/51790568/102641558-2c3a2b00-4154-11eb-96fa-4babc2c72ecf.png)
下面是日志
74 | 2020/12/19 上午1:11:13 | requestMessage.getUserInfo
-- | -- | --
75 | 2020/12/19 上午1:11:24 | []网络请求失败！(0 timeout, timeout)
76 | 2020/12/19 上午1:11:24 | oppaiti.me
77 | 2020/12/19 上午1:11:24 | https://oppaiti.me/ajax.php?action=user&id=xxxx
78 | 2020/12/19 上午1:11:24 |  
79 | 2020/12/19 上午1:11:24 | requestMessage.writeLog
80 | 2020/12/19 上午1:11:24 | requestMessage.readConfig

- 重现步骤：
点击网站图标刷新用户信息，最后提示发生错误。

**Comment by Rhilip** [comment]
走的是api接口。那么对应接口连接直接打开是什么情况？能否正常打开？

**Comment by kafuuchino-s** [comment]
> 走的是api接口。那么对应接口链接直接打开是什么情况？能否正常打开？
直接打开打不开，不能正常打开
![image](https://user-images.githubusercontent.com/51790568/102683064-19f8d500-41c6-11eb-8ee7-e12826986011.png)

**Comment by ted423** [comment]
肯定要能打开才能获取数据啊....
网站都挂了，还怎么获取数据...
虽然我这能打开
