### ISSUE TITLE
Leaguehd 柠檬更换域名为lemonhd.org了，需要更新

### ISSUE THREAD

**Issue by valianliu** [ronggang/PT-Plugin-Plus#656]
- PT 助手版本:1.5.0
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：Leaguehd 柠檬更换域名了lemonhd.org，等待更新

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@valianliu 这个很早就修过了

**Comment by valianliu** [comment]
> @valianliu 这个很早就修过了

我用的是1.5版本，还是无法添加新域名信息，请问如何更新呢？谢谢

**Comment by ted423** [comment]
@valianliu action里看看
