### ISSUE TITLE
功能建议：首页的用户数据列表中可否增加各pt站点的超链接

### ISSUE THREAD

**Issue by chenyz1984** [ronggang/PT-Plugin-Plus#66]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:PT Plugin Plus
1.0.2
- PT 助手安装方式：谷歌市场
- 浏览器名称及版本：chrome 版本 71.0.3578.98（正式版本） （64 位）
- 建议描述：在首页的用户数据列表中，增加站点名称直达pt站的超链接，便于站点登录。
- 相关截图：
![333](https://user-images.githubusercontent.com/20869868/54573037-6af1fd00-4a25-11e9-8b38-447ef6c060c8.png)

**Comment by Rhilip** [comment]
在站点配置页面已经有对应显示

**Comment by chenyz1984** [comment]
我的意思是点击那个logo，直接进入pt站点，减少操作步骤。
