### ISSUE TITLE
柠檬域名不对

### ISSUE THREAD

**Issue by jiezi506** [ronggang/PT-Plugin-Plus#660]
- PT 助手版本:1.5
- PT 助手安装方式：市场安装
- 浏览器名称及版本：edge 87.0.664.66
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：
- 问题描述：

柠檬现在域名是
https://lemonhd.org
pt助手里还是
https://lemonhd.com

导致添加失败，不能搜索
- 相关截图：

**Comment by Mit2g** [comment]
此问题已有其他人提出并已解决 请在提问前先使用搜索功能查找是否有类似问题 确认无后再提问
https://github.com/ronggang/PT-Plugin-Plus/issues/656
