### ISSUE TITLE
更新tl修复版后还是刷不出个人信息

### ISSUE THREAD

**Issue by qq1059757949** [ronggang/PT-Plugin-Plus#661]
- PT 助手版本:1.5.0 883ac83、34df6b7
- PT 助手安装方式：dev  zip包安装
- 浏览器名称及版本：谷歌浏览器最新版
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
34df6b7版描述修复tl个人信息获取，可是我更新之后刷新数据一直都是未登录状态，点开网页是登录状态，群里也有另一个人反应这个问题，谷歌浏览器检测更新已经是最新版。另外dev能增加小版本吗？以便查看是否更新插件成功。

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
用户等级不是 `Super User` 吧？建议私发我下源代码。
小版本号我再看看吧，目前是在Artifacts上打上了

**Comment by Rhilip** [comment]
refs: https://github.com/ronggang/PT-Plugin-Plus/commit/de358c97079ae36d59ae0138b6bb9af2b849b90e
请测试

**Comment by tainewoo** [comment]
不知道1.5.1大概啥时候release到市场呢?
