### ISSUE TITLE
生成分享图片时“模糊站点图标”无效

### ISSUE THREAD

**Issue by cnsunyour** [ronggang/PT-Plugin-Plus#662]
- PT 助手版本: 5c5094a 之后到目前的所有 dev 版本
- PT 助手安装方式：crx白名单安装
- 浏览器名称及版本：chrome 87.0.4280.141
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
    ptpp 数据时间轴图中选项“模糊站点图标”启用时显示图片能正常模糊，但是导出 png 图片不能模糊。

- 重现步骤：
    ptpp -> 我的数据 -> 时间轴 -> 模糊站点图标 -> 生成分享图片

**Comment by Rhilip** [comment]
这是应该是依赖库 `html2canvas` 的问题，相关issue为： 
 - https://github.com/niklasvh/html2canvas/issues/1616 
 - https://github.com/niklasvh/html2canvas/issues/2406 

我觉得比较好的方法是换一个图片生成库， 比如 `dom-2-image` 但是这个库很久没更新了（ 虽然 html2canvas 也很久没更新了）
@ted423 你的意见那？

------

很有意思的是，我们现在的实现反而部分依赖了 `html2canvas` 的这个bug，及在生成图片的时候，图片右上角的转动其实是由css实现的，但是由于html2canvas 不支持这个，所以就没有在输出的图片中有显示。

![image](https://user-images.githubusercontent.com/13842140/103890558-3b911080-5123-11eb-99a0-448a8e6696f9.png)
