### ISSUE TITLE
生成数据图时隐藏用户名称应同时隐藏左上角的用户名称

### ISSUE THREAD

**Issue by RtYkk** [ronggang/PT-Plugin-Plus#668]
## 您的功能请求是否与问题有关？ 请描述一下。

虽然左上角的名称是可以自己改的，但是很多人都容易忽略这个地方。
我建议同时隐藏

## 其他附加信息

![chrome_HVvpteQP3Z](https://user-images.githubusercontent.com/45971730/104815225-2f593180-584e-11eb-8c20-31facace7bac.png)

**Comment by Rhilip** [comment]
我觉得左上角的用户名称和时间轴中的站点用户名还是有区别的，而且如所述，右上角目前已经提供有修改功能
