### ISSUE TITLE
手动刷新用户数据 一直转圈中

### ISSUE THREAD

**Issue by goodryb** [ronggang/PT-Plugin-Plus#67]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.2
- PT 助手安装方式：市场安装
- 浏览器名称及版本：chrome 73 ，macOS 10.14.3
- 问题描述：手动刷新用户数据 一直转圈中
- 相关截图：

![image](https://user-images.githubusercontent.com/3907975/54574059-ce7e2980-4a29-11e9-8b28-8f9301c50004.png)

**Comment by Rhilip** [comment]
个人信息功能还处于beta阶段，请尝试关闭所有启用站点，一个一个启用搜索查看是因为那个站点的原因导致此情况

**Comment by goodryb** [comment]
@Rhilip 怪我没看清楚，站点设置里面没有打开个人信息的选项，打开之后就可以了
