### ISSUE TITLE
是否考虑增加docker版

### ISSUE THREAD

**Issue by Oscar1011** [ronggang/PT-Plugin-Plus#670]
## 您的功能请求是否与问题有关？ 请描述一下。

是否考虑增加docker版

## 描述你想要的解决方案

部署后能够导入站点cookie，最好是可以直接将插件端的cookie导出后直接导入，这样可以解决在一些设备上无法使用插件的尴尬问题。然后能在web界面进行种子搜索。 然后推送下载之类的。

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/240
