### ISSUE TITLE
在 Firefox Developer Edition 下发送到 rTorrent 下载器提示 undefined

### ISSUE THREAD

**Issue by xnxin** [ronggang/PT-Plugin-Plus#671]
- PT 助手版本: 1.49
- PT 助手安装方式：zip
- 浏览器名称及版本：FireFox Developer Edition 85.0b7 
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：在馒头上使用下载或一键下载，会提示红色 undefined 错误，在调试 `about:debugging#/runtime/this-firefox` 页面中打开 PT 插件查看请求后，rtorrent 返回 

```json
{"result:""Success"}
````
PS: 已经在隐私模式下仅打开 PT-Plugins 插件测试，仍然是红色`undefined.`,排除其他插件干扰。

**Comment by Steve-She** [comment]
I really suggest you to use version 1.5.1, it may fix your bug.

**Comment by xnxin** [comment]
Nope. update to 1.5.1, still have same error.

**Comment by xnxin** [comment]
贴个图
<img width="1447" alt="截屏2021-01-21 下午4 17 24" src="https://user-images.githubusercontent.com/10513841/105323284-ea921980-5c04-11eb-90b2-8cbb03ddda4e.png">

**Comment by xnxin** [comment]
似乎是 https://github.com/ronggang/PT-Plugin-Plus/blob/7d0b92828eddaed2ff4387ae09c8942a45321548/resource/clients/ruTorrent/init.js#L47 这个地方，现在返回的是 `Success`,是 `ruTorrent` 版本问题还是兼容性问题呢？
