### ISSUE TITLE
能否在dege扩展商店发布一下更新呢

### ISSUE THREAD

**Issue by DHJ666** [ronggang/PT-Plugin-Plus#673]
- 
能否在dege扩展商店发布一下更新呢

**Comment by Rhilip** [comment]
我们并没有在dege扩展商店发布过哦

![image](https://user-images.githubusercontent.com/13842140/105505284-bfdaba80-5d03-11eb-9dd6-b36556b1116a.png)

**Comment by DHJ666** [comment]
抱歉打错啦，是microsoft Edge

**Comment by DHJ666** [comment]
> 我们并没有在dege扩展商店发布过哦
> 
> ![image](https://user-images.githubusercontent.com/13842140/105505284-bfdaba80-5d03-11eb-9dd6-b36556b1116a.png)

打错啦，是Edge哈哈
