### ISSUE TITLE
请修改Wiki

### ISSUE THREAD

**Issue by MagicBoost** [ronggang/PT-Plugin-Plus#674]
安装crx前的注册表项ExtensionInstallWhitelist已经被谷歌更改为ExtensionInstallAllowlist，chrome://policy显示ExtensionInstallWhitelist已弃用。
虽然现版本会被自动替换为ExtensionInstallAllowlist，但是请尽快修改。

**Comment by ted423** [comment]
我改了，你看下呢

**Comment by MagicBoost** [comment]
没问题了
