### ISSUE TITLE
无法"一键导入"HDC和TGG站点。且手动添加站点后无法获取个人数据，无法搜索

### ISSUE THREAD

**Issue by sdjnmxd** [ronggang/PT-Plugin-Plus#678]
- PT 助手版本: `v1.5.1`
- PT 助手安装方式：`GitHub Release zip`
- 浏览器名称及版本：`Firefox 84.0.2`
- 浏览器是否安装了其他插件：`true`
- 停用其他插件后是否正常工作：`false`
- 问题描述：
> 特别的：HDC和TGG均已关闭游客登陆，不知是否和这个有关系
1. 站点设置无法一键导入HDC和TGG，HD Dolby正常。
2. 我的数据无法成功获取HDC和TGG的数据，显示未登录，实则已登录。HD Dolby正常。
3. 顶部搜索输入任意字符，无法获取HDC和TGG的数据，显示"没有定位到种子列表，或没有相关的种子"。HD Dolby正常。

- 相关截图：
  - 站点设置 
    - <img width="2556" alt="图片" src="https://user-images.githubusercontent.com/6388562/105794435-03644b80-5fc6-11eb-91d5-e45c7bd3a0a9.png">
  - 我的数据
    - <img width="2560" alt="图片" src="https://user-images.githubusercontent.com/6388562/105794483-14ad5800-5fc6-11eb-85e4-74a7b8207cda.png">
  - 搜索结果
    - <img width="1149" alt="图片" src="https://user-images.githubusercontent.com/6388562/105796127-1e848a80-5fc9-11eb-8856-8b8e81172530.png">
  - HDC登录态
    - <img width="948" alt="图片" src="https://user-images.githubusercontent.com/6388562/105794601-46262380-5fc6-11eb-9d0d-628f2cb7312d.png">
  - TGG登陆态
    - <img width="741" alt="图片" src="https://user-images.githubusercontent.com/6388562/105794630-54743f80-5fc6-11eb-8dba-4d70154195c6.png">
  - 扩展权限状态
    - <img width="953" alt="图片" src="https://user-images.githubusercontent.com/6388562/105795917-a0c07f00-5fc8-11eb-80f0-40036425101d.png">

- 重现步骤：
  1. 去Release页下载`PT-Plugin-Plus-v1.5.1.zip`
  2. 采用[issue #491](https://github.com/ronggang/PT-Plugin-Plus/issues/491)方法将zip提交至AMO（自己托管）
  3. 安装扩展
  4. 扩展首页->参数设置->权限设置：启用所有权限
  5. 扩展主页->参数设置->站点设置：点击"一键导入站点"按钮，TGG和HDC未能自动导入，HD Dolby正常
  6. 扩展主页->参数设置->站点设置：点击"新增"按钮，选择"HDChina"后点击"下一步"。填入"密钥"，启用"允许获取用户信息（Beta）"，启用"允许搜索"，点击"√"
  7. 扩展主页->参数设置->站点设置：点击"新增"按钮，选择"TGG"后点击"下一步"。填入"密钥"，启用"允许获取用户信息（Beta）"，启用"允许搜索"，点击"√"
  7. 扩展主页->概览->我的数据：点击"刷新我的数据"，TGG和HDC未能成功获取数据，显示"未登录"，HD Dolby正常
  8. 扩展主页->顶部全局搜索框：输入"a"，TGG和HDC未能成功获取数据，显示"没有定位到种子列表，或没有相关的种子"，HD Dolby正常

**Comment by sdjnmxd** [comment]
大概找到原因了，目测确实是站点关闭游客登录导致的，TGG和HDC的login都直接吐的"伪备案"页，应该影响到了扩展的后续逻辑判断，不知能否使用其他的判断登陆方式？

<img width="2559" alt="图片" src="https://user-images.githubusercontent.com/6388562/105797491-0877c980-5fcb-11eb-96e0-0bec27f582b7.png">

**Comment by ted423** [comment]
@sdjnmxd 你说的是你已经登陆了？

**Comment by Rhilip** [comment]
这种访问index.php直接被302到login.php的行为不像是已经登录的状态，
建议看下那几个3xx的请求，发送的cookies是否正确。

**Comment by sdjnmxd** [comment]
> @sdjnmxd 你说的是你已经登陆了？

没错，如果使用浏览器访问是正常登陆的，扩展用JQuery直接发起请求则是未登录
初步原因找到了，浏览器直接访问带过去的Cookie和扩展使用JQuery带过去的Cookie完全不同，看起来像扩展有沙箱之类的？
还在进一步寻找本质原因

**Comment by sdjnmxd** [comment]
> 这种访问index.php直接被302到login.php的行为不像是已经登录的状态，
> 建议看下那几个3xx的请求，发送的cookies是否正确。

感谢，我仔细看了一下，浏览器访问站点和扩展使用JQuery直接请求站点带过去的Cookie确实不同，如果Cookie不同的话这表现确实符合预期，暂时没想明白为什么两个Cookie不一样，怀疑扩展是有沙箱之类的？还在进一步寻找本质原因。

**Comment by Rhilip** [comment]
听起来挺奇怪的。
插件能工作的核心就在于插件的XMLHTTPRequest是能自动携带上浏览器已有的cookies，
而且同样也解释不了为什么未关闭游客访问的站点能正常获取信息。

**Comment by sdjnmxd** [comment]
问题解决了，目测是浏览器的“增强型跟踪保护”设置为严格导致了一些莫名其妙的问题，改为标准即可正常使用。
感谢以上诸位！
