### ISSUE TITLE
概览用户数据页，个人数据有误

### ISSUE THREAD

**Issue by chenyz1984** [ronggang/PT-Plugin-Plus#68]
- PT 助手版本:1.02
- PT 助手安装方式：谷歌商店
- 浏览器名称及版本：chrome 版本 73.0.3683.75（正式版本） （64 位）
- 问题描述：概览用户数据页，个人数据有误。馒头站数据量均显示为0，分享率无限也显示为0
- 相关截图：

**Comment by Rhilip** [comment]
暂不支持该站查询做种数及做种体积信息，所以置0
