### ISSUE TITLE
部分站点无法在搜索结果页直接下载

### ISSUE THREAD

**Issue by zhui22222** [ronggang/PT-Plugin-Plus#680]
- PT 助手版本:1.5.1
- PT 助手安装方式：（zip包安装）
- 浏览器名称及版本：87.0.4280.141（正式版本） （64 位）
- 浏览器是否安装了其他插件：油猴
- 停用其他插件后是否正常工作：否
- 问题描述：
在搜索结果页面，选中条目后推送到下载服务器、辅种、复制种子链接下载等操作均无法下载，必须进入种子的详情页才可以正常下载。目前手上仅有的几个站点中FRDS、备胎有此情况，其他站点正常。

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@zhui22222 麻烦检查自己有没有设passkey

**Comment by zhui22222** [comment]
没有啊，不知道还要设这个😔

**Comment by ted423** [comment]
@zhui22222 设置为空是正常的

**Comment by zhui22222** [comment]
果然可以啦，谢谢
