### ISSUE TITLE
一键下载不支持路径关键字

### ISSUE THREAD

**Issue by 1787951236** [ronggang/PT-Plugin-Plus#681]
- PT 助手版本:1.5.1
- PT 助手安装方式：zip
- 浏览器名称及版本：google
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：一键下载不支持路径关键字，如果在助手的默认目录添加”/volume1/$site.name$/music“不会下载至“/volume1/OpenCD/music”而会下载至”/volume1/$site.name$/music“在下载到指定服务器中这个功能是正常的

- 相关截图：
![2](https://user-images.githubusercontent.com/39167665/106153965-10499080-61ba-11eb-8517-d13c0dafb0e2.png)
![3](https://user-images.githubusercontent.com/39167665/106153968-117abd80-61ba-11eb-970b-e8935dcb636f.png)
![4](https://user-images.githubusercontent.com/39167665/106153970-12135400-61ba-11eb-9f18-ebfa52d89cb2.png)
![1](https://user-images.githubusercontent.com/39167665/106153972-12135400-61ba-11eb-8246-9aeffeb4d1f9.png)
- 
![Uploading Cache_-6374e6a8435cd3c0..jpg…]()

- 重现步骤：在pt助手内的下载目录设置中修改默认目录为带关键字目录/volume1/$site.name$/music保存后去pt站点击一键下载，一键下载处显示正常，但在下载服务器里下载目录为/volume1/$site.name$/music使用一键下载下方的下载到服务器下载目录为正常

**Comment by Rhilip** [comment]
请补充 `相关截图` 和 `重现步骤`

**Comment by ted423** [comment]
@1787951236 默认下载只与下载器设置有关应该，只有选定目录时才支持替换关键字？

**Comment by 1787951236** [comment]
> 请补充`相关截图`和`重现步骤`

已补充

**Comment by Rhilip** [comment]
我其实觉得这个挺严重的，但是为什么直到现在才有人提😂😂😂
