### ISSUE TITLE
hdcity.city；hdcity.work账号不通用？

### ISSUE THREAD

**Issue by jiezi506** [ronggang/PT-Plugin-Plus#688]
- PT 助手版本:1.5.1
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：edge 版本 88.0.705.56
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：
- 问题描述：hdcity.city；hdcity.work是两个站还是一个站，账号似乎不通用。好像ptpp只支持.city，可否增加.work。

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
`hdcity.city；hdcity.work是两个站还是一个站，账号似乎不通用` 请咨询对应站点
`好像ptpp只支持.city，可否增加.work。` 请使用CDN域名功能
