### ISSUE TITLE
希望增加个开关，个别站点可以不获取消息以便不显示左上角得那啥

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#689]
## 您的功能请求是否与问题有关？ 请描述一下。
例如TeamHD,天天让人买VIP。不想点进去

**Comment by Rhilip** [comment]
![image](https://user-images.githubusercontent.com/13842140/106750022-3d86ba80-6662-11eb-95ee-00714dc7eb6e.png)

**Comment by ted423** [comment]
我只会写点基础的...核心的不会
菜得理直气壮
