### ISSUE TITLE
无法获取PTHOME站点信息，未收录站点CCFBits

### ISSUE THREAD

**Issue by pxm1123** [ronggang/PT-Plugin-Plus#69]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:v1.0.3
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 72.0.3626.121
- 问题描述：（1）PTHOME站，在浏览器登录后，这个插件无法获取这个站的任何信息。
                     （2）未收录站点：CCFBits（ccfbits.org）
- 相关截图：

**Comment by ronggang** [comment]
@pxm1123 
1. PTHOME 没有账号，所以未测试个人信息是否可用；
2. CCFBits 暂时未知是否适用，你可以自行定义一下试试。

**Comment by Rhilip** [comment]
CCF我会在近期加入，PTHOME暂时无能为力

**Comment by pxm1123** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，感谢大佬！
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                pxm1123
                            
                    
                        
                            
                                    pxm1123@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年3月21日 19:46，Rhilip<notifications@github.com> 写道： 


CCF我会在近期加入，PTHOME暂时无能为力



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Rhilip** [comment]
CCFBits 已添加 8e5f889b1d6b2ea70d865db1d84a82c36d9a605e
@waldens 还请能否查看下PTHOME站点情况

**Comment by waldens** [comment]
@Rhilip 已验证，6天前发布的版本v1.0.4
概述 手动刷新用户数据，可以获取到PTHome的数据
顶部搜索栏，可以搜索到PTHome的种子

**Comment by Rhilip** [comment]
感谢测试。
顺带抱歉原来预定于v1.0.4解决CCFBits的适配，结果因为个人现实事务问题拖到了下一个版本

**Comment by ronggang** [comment]
> 感谢测试。
> 顺带抱歉原来预定于v1.0.4解决CCFBits的适配，结果因为个人现实事务问题拖到了下一个版本

是我发的快了点。😅
