### ISSUE TITLE
春天数据获取异常。

### ISSUE THREAD

**Issue by xiaobaoxiao** [ronggang/PT-Plugin-Plus#691]
- PT 助手版本:1.5.1
- PT 助手安装方式：（市场安装，或zip包安装）crx
- 浏览器名称及版本：搜狗浏览器11.0.0.33862（截止当前最新版本）执行chrome://flags/，获得：内核版本为80.0.3987.87
- 浏览器是否安装了其他插件：editthiscookie
- 停用其他插件后是否正常工作：否
- 问题描述：春天站，无法获取用户数据，显示未登录。同系统下edge版本正常。

- 相关截图：

- 重现步骤：
使用最新搜狗浏览器(widnows版)即可复现。

**Comment by Rhilip** [comment]
与 https://github.com/ronggang/PT-Plugin-Plus/issues/528 相同原因，建议向对应浏览器开发反馈或者换用其他浏览器

![image](https://user-images.githubusercontent.com/13842140/107340314-93db7980-6af8-11eb-8c5a-c5a834861c96.png)
![image](https://user-images.githubusercontent.com/13842140/107340831-29770900-6af9-11eb-808f-95db6d7bfcd7.png)
