### ISSUE TITLE
Pornbits上传下载量在T级别时识别错误

### ISSUE THREAD

**Issue by tainewoo** [ronggang/PT-Plugin-Plus#692]
- PT 助手版本: 1.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge 88.0.705.63
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：Pornbits上传下载量在T级别时识别错误. 之前是930.5 GB的时候识别还是正常的, 1月28日可能是上传量继续增加于是站点显示为0.9 TB,但是这个时候助手就识别为921.60 GB了,之后虽然上传量一直有增加但是仍然属于0.9 TB的范围内,助手这边的读数一直没有再变化过,仍然保持921.60 GB.

以下是页面获取代码:

> 		<div style="margin-top: 1em;">
> 			<strong>Last seen:</strong> moments ago		</div>
> 		<div>
> 			<strong>Member Since:</strong> 2016-12-14		</div>
> 					<div>
> 				<strong>Email:</strong> xxxx@xxxx.com			</div>
> 		<div style="margin-top: 1em;">
> 			<img src="https://pornbits.net/images/up.png" class="icons" /> 0.9 TB Uploaded
> 		</div>
> 		<div>
> 			<img src="https://pornbits.net/images/down.png" class="icons" /> 25.9 GB Downloaded
> 		</div>
> 		<div>
> 			<span class="glyphicon glyphicon-transfer"></span> Ratio: 37.21		</div>

- 相关截图：
![PB](https://user-images.githubusercontent.com/13391232/107451885-2b85aa00-6b83-11eb-9902-42fa8028364b.png)

![PB2](https://user-images.githubusercontent.com/13391232/107451896-32acb800-6b83-11eb-9c8e-85531ed5d23d.png)

- 重现步骤：获取Pornbits的数据,最好是TB级别.

**Comment by Rhilip** [comment]
插件在获取个人信息时会将获取的字面量转化为 bytes，然后在展示的时候再转回。
所以我不认为这种情况存在问题，因为 0.9TB 就是 921.60 GiB 。

**Comment by ted423** [comment]
@tainewoo 这种属于误差范围内，我觉得。因为0.9t就是0.9x1024=921.6

**Comment by tainewoo** [comment]
好的,那就没事,我close.
