### ISSUE TITLE
请添加对its站点的支持

### ISSUE THREAD

**Issue by jueerye** [ronggang/PT-Plugin-Plus#695]
<!-- 
1、在发起请求前，请先确认是否在已支持的架构内；支持

- 站点名称：its
- 站点地址：https://shadowthein.net/
- 站点描述：总合

- 资源类型：总合
- 开放注册：否
- 是否连坐：是
- 站点规则：DO NOT:
publish the full name, URL or access details of the tracker, whether directly or implicitly. Always refer to "iTS" instead.
trade an account or an invite to iTS. Giving away an invite to a stranger is the same as trading it.
give away your account.
buy or sell accounts or invites to any filesharing site, whether directly or indirectly (e.g.: for seedbox access).
create multiple accounts or share accounts with others. Your account is personal and is not to be shared with others.
cheat or attempt to cheat on the tracker.
endanger or attempt to endanger the security of the tracker in any way.
publish a review of the site without staff approval.
upload iTS exclusive releases to other file sharing sites without clearing it with the iTS uploader.
recruit iTS members to other sites through iTS resources or systematically invite iTS users to other sites without staff approval.
tag an upload as personal or internal if you are not the original ripper/releaser.
use offensive usernames or titles, or misleading ones such as "Admin", "Staff" etc.
be a repeat offender.
Depending on the severity of the action, some of these may even get you banned on other sites as well!

**Comment by Rhilip** [comment]
Please follow the issue template
