### ISSUE TITLE
可否增加小站hdai

### ISSUE THREAD

**Issue by jiezi506** [ronggang/PT-Plugin-Plus#698]
- 站点名称：hdai
- 站点地址：https://www.hd.ai/
- 站点描述：

- 资源类型：电影
- 开放注册：是
- 是否连坐：否
- 站点规则：

**Comment by ted423** [comment]
@jiezi506 r酱说不考虑再加新的np站点

**Comment by Rhilip** [comment]
仅接受测试通过的PR，且站点满足要求：

```
2020.09.24 : 本贴及相关PR不再接收成立时间（持续时间）小于3个月的站点。
```
