### ISSUE TITLE
M-team 搜索结果显示错误

### ISSUE THREAD

**Issue by shuer001** [ronggang/PT-Plugin-Plus#70]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.3
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 73.0.3683.75
- 问题描述：M-TEAM 综合，电影板块 部分搜索结果不显示链接和文字说明，百分百出现。音乐板块正常
- 相关截图：![image](https://i.loli.net/2019/03/21/5c9318a3d9632.png
)

**Comment by ronggang** [comment]
@shuer001 只有MT这样吗？其他站会不会？
另外，如果可以，请打开调试工具，看看能不能找到出错信息
https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page

**Comment by shuer001** [comment]
其它站都正常。 如下图，0不正常，1正常，好像有的不能记录种子信息。
![image](https://i.loli.net/2019/03/22/5c94956080e48.jpg）
![image](https://i.loli.net/2019/03/22/5c949560ce5e6.jpg）

**Comment by Rhilip** [comment]
@shuer001 截图中有个人隐私信息，已删除，请打码后重新上传

**Comment by shuer001** [comment]
![image](https://i.loli.net/2019/04/06/5ca834259e824.jpg
)  M-TAEM每个电影都有这样的情况。换了最新的edge 75 Chromium版 也会出现这个问题。其它浏览器未测试

**Comment by ronggang** [comment]
@shuer001 截图中还是有人个信息，已删除。
大概内容我看了一下，的确没有获取取标题信息，不知可否告知在网站的等级，以网站的风格设置。

**Comment by shuer001** [comment]
@ronggang  等级 通判/cu  开启了成人内容 ；实验室功能全部开启。  介面風格	 blue gene  其它应该都没有变动。宽带ipv6+v4

**Comment by Rhilip** [comment]
你好，请尝试在你的个人设置中关闭IMDb悬浮信息提醒，并告知关闭后是否能够正常显示种子标题信息。
![TIM截图20190408160016](https://user-images.githubusercontent.com/13842140/55708022-7b3f3b80-5a17-11e9-9b72-f39160625906.png)

**Comment by shuer001** [comment]
@Rhilip   关闭IMDb悬浮信息  能正常显示。
