### ISSUE TITLE
TorrentLeech改版之后注册时间无法正常获取

### ISSUE THREAD

**Issue by MewX** [ronggang/PT-Plugin-Plus#703]
- PT 助手版本:  v1.5.1
- PT 助手安装方式：zip
- 浏览器名称及版本：Chrome v88
- 浏览器是否安装了其他插件： n/a
- 停用其他插件后是否正常工作： n/a
- 问题描述：

注册时间无法正常获取

- 相关截图：

![image](https://user-images.githubusercontent.com/5752560/108848171-c62ac200-7634-11eb-9e1d-41db86050aa8.png)

- 重现步骤：

同步TorrentLeech的信息即可复现。

Developer console显示：

```
bonus: "903.84"
downloaded: 14055280476.16
id: "<deleted>"
isLogged: true
joinTime: null <-- Problem here
lastUpdateStatus: "success"
lastUpdateTime: 1614085536231
levelName: "Registered"
messageCount: 0
name: "<deleted>"
seeding: 16
seedingSize: 632406713303.04
uploaded: 52602611957.76
```

然而网站上显示的是：

Item | Value
-- | --
Invited by | deleted
Username | deleted
Class | Registered
Register date | Wednesday 3rd February 2021
Last visit | Tuesday 23rd February 2021 12:54:52 PM (11 minutes ago)
Invitations | 0
IRC | N/A
Passkey | deleted
Torrent comments | deleted
Has seedbox | No

**Comment by Rhilip** [comment]
https://github.com/ronggang/PT-Plugin-Plus/blob/fe1ee0e81c7d7b3eafd71e4d706c0233d648b42b/resource/sites/www.torrentleech.org/config.json#L73

似乎是没有对 3rd 的情况进行设置？

**Comment by maicss** [comment]
@Rhilip 借楼问一下，助手里收录了torrentseeds，我看torrentdb跟这个架构差不多，但是torrentseeds的架构是特殊的，而且架构列表里没有，怎么添加这样的站点？

**Comment by MewX** [comment]
@maicss 参考https://github.com/ronggang/PT-Plugin-Plus/wiki/developer

建一个类似于这个文件夹的新文件夹 https://github.com/ronggang/PT-Plugin-Plus/blob/master/resource/sites/www.torrentleech.org/ 然后提交pull request ：）

**Comment by maicss** [comment]
@MewX 我就问问能不能添加，要是不能就算了，我还不会弄这个。谢谢
