### ISSUE TITLE
重构建议：TorrentLeech用的是Jackett引擎

### ISSUE THREAD

**Issue by MewX** [ronggang/PT-Plugin-Plus#711]
同样的有TorrentBytes (TBy); TorrentCCF (TCCF); TorrentDay (TD); TorrentDB; TorrentFactory; TorrentHR; TorrentHeaven (invite needed)。

Jackett: https://github.com/Jackett/Jackett

**Comment by MewX** [comment]
@maicss FYI

**Comment by MewX** [comment]
oops, sorry wait a sec

**Comment by Rhilip** [comment]
emmm，不知道该说些什么好😂😂😂😂

----------
我们的重构在 https://github.com/ronggang/PT-Plugin-Plus/tree/next 分支上，相关计划也可见 https://github.com/ronggang/PT-Plugin-Plus/projects/2
目前我是重构的组织者，但由于上半年过于忙碌，可能没太多时间投入到重构工作中。
