### ISSUE TITLE
柠檬站搜索电视综艺信息获取异常

### ISSUE THREAD

**Issue by fqh1995** [ronggang/PT-Plugin-Plus#713]
- PT 助手版本:1.5.1
- PT 助手安装方式：（zip包安装魔改版本）
- 浏览器名称及版本：**Microsoft Edge
版本 89.0.774.39 (官方内部版本) beta (64 位)**
- 浏览器是否安装了其他插件：有
- 停用其他插件后是否正常工作：是
- 问题描述：
种子搜索发布时间异常，为未来时间【葡萄】
柠檬站点获取大小为0的异常

- 相关截图：
![image](https://user-images.githubusercontent.com/31031100/109483189-e8e82b00-7ab9-11eb-9f5a-f3a8e4075f03.png)
![image](https://user-images.githubusercontent.com/31031100/109483220-f2719300-7ab9-11eb-99c3-b377caac5f1e.png)

- 重现步骤：

**Comment by Rhilip** [comment]
> 1. 种子搜索发布时间异常，为未来时间【葡萄】

![image](https://user-images.githubusercontent.com/13842140/109506894-1f816e00-7ad9-11eb-900d-7400ecdc4842.png)

这个我不能复现，无论是修改版还是官方编译版。
请问你是稳定复现这个问题吗？或者能否给出 zip 文件？
还是相比 讨论贴 https://github.com/ronggang/PT-Plugin-Plus/discussions/705 ，有其他更新？

> 2. 柠檬站点获取大小为0的异常

没账号，帮不了

**Comment by ted423** [comment]
顺便冒个泡，我这里搜索正常.
不过由于柠檬搜索展示弄了两套，要看看有没有这方面的影响

**Comment by shuosiw** [comment]
现在确实柠檬搜索不显示信息，看看需要提供什么信息来协助定位问题？PS: 评论数是正常的..

![image](https://user-images.githubusercontent.com/2578976/112337906-4fe3b300-8cf9-11eb-8692-ce3e443f6a46.png)

**Comment by ted423** [comment]
@shuosiw 是否有使用dev的版本

**Comment by shuosiw** [comment]
> @shuosiw 是否有使用dev的版本

@ted423 尝试重新覆盖安排了 1.5.1 版本，还是不行

**Comment by shuosiw** [comment]
测试一下，发现点击 **获取各站第一页种子**，柠檬站点的数据是可以正常显示的，但是通过搜索出来的，就没办法显示。这两者有什么区别呢？

另外，在搜索出来的没有详细信息的条目上，点击跳到对应的页面，页面又可以全部正常显示，说明也不是网络问题

**Comment by ted423** [comment]
@shuosiw 是否使用了action里的dev版本

**Comment by shuosiw** [comment]
不是的， release 版本里面的 v1.5.1 @ted423 

另外，刚才发现有部分的柠檬搜索又是可以显示信息，比如动漫分类就可以..

![image](https://user-images.githubusercontent.com/2578976/112343897-87a12980-8cfe-11eb-9e9c-0da430d56e9e.png)

**Comment by shuosiw** [comment]
大概发现是什么原因了..柠檬目前有两套种子页面.

旧的那套是插件是可以正常搜索显示信息的，对应就是 动漫、音乐分类，以及最新种子的页面，也就是还是一个种子一行的那种

![image](https://user-images.githubusercontent.com/2578976/112344520-2037a980-8cff-11eb-8601-020b1832fe0f.png)

而新的那套，插件就不支持显示信息，对应剧集、电影、纪录片，也就是一个行可能对应多个种子

![image](https://user-images.githubusercontent.com/2578976/112344703-537a3880-8cff-11eb-995c-e8ca791d6962.png)

**Comment by ted423** [comment]
@shuosiw 所以去action里下最新的dev版用……

**Comment by shuosiw** [comment]
> @shuosiw 所以去action里下最新的dev版用……

这个也有测试，也是不行...还是说我的安装方式有问题？

1. 在 action 找到最新的 commit 点击进去，下载了 dev-build-1c03981-crx
2. 下载下来的是 zip 包，解压拿到 crx 文件
3. 打开 chrome 插件管理，然后把 crx 文件拖到插件管理页面安装，会有安装成功的提示界面
4. 重启 chrome


@ted423 请问一下，你现在用的是什么版本？试试搜一下 **司藤** 看看有没能展示种子信息？

**Comment by ted423** [comment]
我又确认了下，搜电影没问题，但搜电视综艺这块有问题

**Comment by shuosiw** [comment]
@ted423 嗯嗯，坐等修复了..

**Comment by IndeedSi** [comment]
![image](https://user-images.githubusercontent.com/16617799/113085991-c1e95a00-921b-11eb-84d3-c7eea840b879.png)
我的葡萄个别种子也有这个问题，可以重现，但只有一部分种子有问题。

**Comment by shuosiw** [comment]
发现一个临时的解决方案，就是把 柠檬 上所有类型都设置为原来的 NexusPHP 展示方式。

![image](https://user-images.githubusercontent.com/2578976/113086338-04a73400-9214-11eb-8e31-33050e871f91.png)


控制面板 - 个人设置 - 默认显示设置 也修改为 NexusPHP，这样设置后 柠檬 的搜索就都正常了。

**Comment by ted423** [comment]
> ![image](https://user-images.githubusercontent.com/16617799/113085991-c1e95a00-921b-11eb-84d3-c7eea840b879.png)
> 我的葡萄个别种子也有这个问题，可以重现，但只有一部分种子有问题。

这种其实建议新开一个issue专门讨论，比如你用没用什么白大那个扩充的插件

**Comment by fqh1995** [comment]
> > ![image](https://user-images.githubusercontent.com/16617799/113085991-c1e95a00-921b-11eb-84d3-c7eea840b879.png)我的葡萄个别种子也有这个问题，可以重现，但只有一部分种子有问题。
> 
> 西格尼·斯库斯·布列斯·布吕特·布吕特·布吕特·斯库勒
我用的就是大白版本

**Comment by shuosiw** [comment]
@IndeedSi 辛苦大佬，现在使用全站搜索已经可以正常显示体积及发布时间等信息了，非常感谢！！

另外也反馈一下使用过程中发现的其他问题：

1. 副标题不展示
2. 没有种子促销信息

![image](https://user-images.githubusercontent.com/2578976/114905911-114e9d80-9e4c-11eb-9ed5-355c50d57c44.png)

**Comment by cxb1998** [comment]
> 发现一个临时的解决方案，就是把 柠檬 上所有类型都设置为原来的 NexusPHP 展示方式。
> 
> ![image](https://user-images.githubusercontent.com/2578976/113086338-04a73400-9214-11eb-8e31-33050e871f91.png)
> 
> 控制面板 - 个人设置 - 默认显示设置 也修改为 NexusPHP，这样设置后 柠檬 的搜索就都正常了。

我发现在ptpp的站点设置里把柠檬的类型改成Gazelle也可以显示正常（但副标题和种子促销信息仍然不会显示）
