### ISSUE TITLE
海胆之家不支持搜索

### ISSUE THREAD

**Issue by ArthurSmoke** [ronggang/PT-Plugin-Plus#716]
- PT 助手版本: v1.5.1
- PT 助手安装方式：EDGE市场
- 浏览器名称及版本：EDGE
- 问题描述：
    使用未收录中的站点配置自定义配置
    ```json
    {
    "name": "海胆之家",
    "timezoneOffset": "+0800",
    "schema": "NexusPHP",
    "url": "https://www.haidan.video/",
    "description": "海胆之家",
    "tags": ["影视,综合"],
    "host": "haidan.video"
    }
    ```
    可以获取用户信息，无法搜索

- 相关截图：
    用户信息截图：
    ![image](https://user-images.githubusercontent.com/1540343/109747196-a20d4900-7c11-11eb-878c-1a58619fc374.png)
    搜索结果截图：
    ![image](https://user-images.githubusercontent.com/1540343/109747224-adf90b00-7c11-11eb-997b-2ef6b0d46ab7.png)
    日志：
    ![image](https://user-images.githubusercontent.com/1540343/109747299-cd903380-7c11-11eb-8d57-34323e05696c.png)

- 重现步骤：
    按自定义使用NexusPHP配置添加站点，搜索任一资源

**Comment by Rhilip** [comment]
我未在 https://github.com/ronggang/PT-Plugin-Plus/wiki/supported-sites 页面找到该站点，
同样我也并无该站点账号。

参考 https://github.com/ronggang/PT-Plugin-Plus/issues/698 说明，我们并没有主动适配该站点的计划，如有需求，请考虑pr。
