### ISSUE TITLE
自定义站点支持自定义parser

### ISSUE THREAD

**Issue by oyyq99999** [ronggang/PT-Plugin-Plus#717]
## 您的功能请求是否与问题有关？ 请描述一下。

目前通过json或界面上自定义站点，在种子列表页右键点链接直接下载会因为自定义站点没在system配置里面而导致没有parser，然后种子url就会错误，并且看上去没有任何办法(除非改插件的systemConfig.json文件)

## 描述你想要的解决方案

支持通过站点的config.json获取parser函数

**Comment by ted423** [comment]
虽然我有点没看懂
大意是自己写站点配置，然后被扩展引用？

**Comment by oyyq99999** [comment]
仿佛我想要的是这个改动之前的效果😂️
https://github.com/ronggang/PT-Plugin-Plus/commit/5ed886b4e9bcb250d3c761c504434222a00e2f39#diff-660a48b387ef0f402e92201cc396679f79e0a52a43b6e6960f5ff07ef756d5b3

**Comment by Rhilip** [comment]
不会再考虑再json中手写js代码的实现，过于繁琐。
我觉得你应该是想实现 类似我们 自定义插件的功能，请参考 wiki 说明： https://github.com/ronggang/PT-Plugin-Plus/wiki/config-custom-plugin

**Comment by Rhilip** [comment]
@oyyq99999
