### ISSUE TITLE
六维空间无法搜索

### ISSUE THREAD

**Issue by Devil-Z** [ronggang/PT-Plugin-Plus#722]
- PT 助手版本:
© 栽培者 2021, 版本 v1.5.1
- PT 助手安装方式：
EDGE应用商店
- 浏览器名称及版本：
Microsoft Edge
版本 89.0.774.45 (官方内部版本) (64 位)

- 问题描述：
没有定位到种子列表或者没有相关种子。
手动去六维搜是有的。
所有搜索都无法定位种子。
- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
@Devil-Z 六维应该当时（对应pr）也只实现个人信息的获取，对于搜索并未实现。

**Comment by Rhilip** [comment]
dupe: #132
