### ISSUE TITLE
朋的 下载所有 功能失效

### ISSUE THREAD

**Issue by phenix6** [ronggang/PT-Plugin-Plus#724]
点击复制链接显示为 https://pt.keepfrds.com/download.php?id=6830&passkey=41189****@qq.com&https=1，其中psaakey错误，在种子详情页点击下载和复制链接都是正确的，可以所有

**Comment by ted423** [comment]
@phenix6 哥啊，passkey错误怎么想都…………

**Comment by ted423** [comment]
@phenix6 不是扩展的问题
