### ISSUE TITLE
朋友 的下载所有功能失效

### ISSUE THREAD

**Issue by phenix6** [ronggang/PT-Plugin-Plus#725]
- PT 助手版本:1.5.1
- PT 助手安装方式：crx（市场安装，或zip包安装）
- 浏览器名称及版本： Google Chrome  89.0.4389.82（正式版本）64 位
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
首页下载所有失效，保存所有种子失败，点击复制链接显示为https://pt.keepfrds.com/download.php?id=6830&passkey=41189****@qq.com&https=1，其中psaakey错误，在种子详情页点击下载和复制链接都是正确的，可以使用
其他站点正常

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
检查你自己的frds站点设置。不行就截图传上来。
work fine for me.
我先关了

**Comment by ted423** [comment]
@phenix6 检查你是不是自己填了passkey,还写错了
