### ISSUE TITLE
搜索结果页的“种子发布时间”字段不能正确处理时区问题

### ISSUE THREAD

**Issue by wsy** [ronggang/PT-Plugin-Plus#728]
- PT 助手版本: 1.5.1
- PT 助手安装方式：Edge应用商店
- 浏览器名称及版本：Edge 89.0.774.50
- 浏览器是否安装了其他插件：不涉及
- 停用其他插件后是否正常工作：不涉及
- 问题描述：
不能正确处理HD-Torrent的时区信息。
HD-Torrents在页面上显示的种子的发布时间，已经是GMT+8:00的时间了，插件将HD-Torrents给我的时间又加了8小时。
下面三张图截于2021-03-15 19:58
插件给我的时间已经是2021-03-16凌晨三点了。

- 相关截图：
![当前时间](https://user-images.githubusercontent.com/2684991/111150249-d1846400-85c8-11eb-8d9c-c6a8de11a788.png)
![插件截图](https://user-images.githubusercontent.com/2684991/111150089-a39f1f80-85c8-11eb-9867-3298b1661018.png)
![HD-Torrents截图](https://user-images.githubusercontent.com/2684991/111150176-bade0d00-85c8-11eb-9bd2-8f76f90dc993.png)

- 重现步骤：
电脑：Windows 10 Pro中文版，地区：中国，时区：北京
登录HD-Torrents，进入“My Panel”页的“Change Profile”选项卡。
将Country改成China，将时区改成“（GMT + 8:00 hours）Hong Kong, Perth, Singapore, Taipei”
确认HD-Torrents显示的种子发布时间是北京东八区的时间。
在插件里搜索种子，显示的种子的发布时间是错误的。

**Comment by ted423** [comment]
请检查你自己的站点设置里hd-t的时区设置

**Comment by wsy** [comment]
> 请检查你自己的站点设置里hd-t的时区设置

时区设置没问题，就是+08:00
![时区设置](https://user-images.githubusercontent.com/2684991/111151439-6f2c6300-85ca-11eb-9d37-e387ddeda4af.png)

**Comment by ted423** [comment]
hd-t的控制面板和助手都有时区设置，请保持两者一致，故本单关闭

**Comment by wsy** [comment]
看到了，bug误报了，抱歉。

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/111151750-d6e2ae00-85ca-11eb-94f6-17e800936fa6.png)
你看下你助手里怎么设的

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/111151805-e9f57e00-85ca-11eb-82bc-9647f8a2db0b.png)

**Comment by ted423** [comment]
没事
