### ISSUE TITLE
HDChina和opcd不能获得保种数量和体积

### ISSUE THREAD

**Issue by sanzuwu** [ronggang/PT-Plugin-Plus#73]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.3
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Yandex Browser最新版
- 问题描述：HDChina和opcd不能获得保种数量和体积
- 相关截图：
[img]https://s2.ax1x.com/2019/03/22/A36c4O.png[/img]

**Comment by ronggang** [comment]
@sanzuwu 感谢反馈

**Comment by Rhilip** [comment]
HDChina使用POST的方法获取用户做种信息，需要另写支持
OpenCD的我也没有做种，暂时不清楚情况

**Comment by ronggang** [comment]
> HDChina使用POST的方法获取用户做种信息，需要另写支持
> OpenCD的我也没有做种，暂时不清楚情况

因为OpenCD和HDChina需要 CRAZY_USER 以上用户才能在用户页面直接列出做种信息。
