### ISSUE TITLE
馒头地址更换了，什么时候同步一下呢 谢谢

### ISSUE THREAD

**Issue by jameyhhh** [ronggang/PT-Plugin-Plus#730]
- 站点名称：
- 站点地址：
- 站点描述：

- 资源类型：
- 开放注册：是/否
- 是否连坐：是/否
- 站点规则：

**Comment by Mit2g** [comment]
已经commit并交由action自动编译打包 如有需要请切换至[action版](https://github.com/ronggang/PT-Plugin-Plus/actions/runs/654222387) 若没有紧急需要请关闭此issue并等待正式版更新和release
