### ISSUE TITLE
m-team站点地址变更

### ISSUE THREAD

**Issue by hyzsfl** [ronggang/PT-Plugin-Plus#733]
- 以下是站点公告
- 2021.03.15 - 域名更改  因应域名汙染，网址从https://pt.m-team.cc 更改为 https://kp.m-team.cc 希望广大同好互相告知

**Comment by ted423** [comment]
....先看看commit

**Comment by Mit2g** [comment]
同类型issue https://github.com/ronggang/PT-Plugin-Plus/issues/730
https://github.com/ronggang/PT-Plugin-Plus/issues/726

已有[相关commit](https://github.com/ronggang/PT-Plugin-Plus/actions/runs/654222387)提交并编译发布 请切换至[action版](https://github.com/ronggang/PT-Plugin-Plus/actions)使用
若不想切换 可参考[教程](http://tieba.baidu.com/p/7262712800?share=9105&fr=share&see_lz=0&share_from=post&sfc=copy&client_type=2&client_version=12.3.8.11&st=1615886008&unique=DC46EF3206A1CAB2B17E4D46FD9E4A60)手动添加
