### ISSUE TITLE
馒头域名变更导致插件个人数据获取失败

### ISSUE THREAD

**Issue by toma77777** [ronggang/PT-Plugin-Plus#737]
- PT 助手版本:v1.5.1
- PT 助手安装方式：Zip包安装
- 浏览器名称及版本：Google Chrome 版本 89.0.4389.90（正式版本） (x86_64)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
**网站通知原文：**
2021.03.15 - 域名更改
因应域名汙染，网址从https://pt.m-txxx.cc 更改为 https://kp.m-txxx.cc 希望广大同好互相告知
(除主站网址外，其他服務不受影響)

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
emm先开在这吧，dupe： #736 #735 #734

**Comment by RtYkk** [comment]
馒头真是害人，改个网址十个 commit 六个 issue…

**Comment by Mit2g** [comment]
同类型issue 
https://github.com/ronggang/PT-Plugin-Plus/issues/735
https://github.com/ronggang/PT-Plugin-Plus/issues/733
https://github.com/ronggang/PT-Plugin-Plus/issues/730
https://github.com/ronggang/PT-Plugin-Plus/issues/726 提问前请先看有没有人提出相同问题


已有[相关commit](https://github.com/ronggang/PT-Plugin-Plus/commit/48ed7a5b70d59eed556e2e91dd2e762108086b9f)提交并编译发布至[action版](https://github.com/ronggang/PT-Plugin-Plus/wiki/get-from-gh-actions) 
**正式版用户等待发布**
若不想切换 参考[教程](http://tieba.baidu.com/p/7262712800?share=9105&fr=share&see_lz=0&share_from=post&sfc=copy&client_type=2&client_version=12.3.8.11&st=1615886008&unique=DC46EF3206A1CAB2B17E4D46FD9E4A60)通过手动添加cdn域名的形式使用

**Comment by Mit2g** [comment]
> emm先开在这吧，dupe： #736 #735 #734 #733 #730 #726

可以pin其中一个issue吗？或许是个临时解决方法

**Comment by Rhilip** [comment]
> > emm先开在这吧，dupe： #736 #735 #734 #733 #730 #726
> 
> 可以pin其中一个issue吗？或许是个临时解决方法

就open这个算了，之前可能是因为closed才没注意。

**Comment by jameyhhh** [comment]
大佬们，都怎么解决的？我馒头还是无法获取，地址不对了。

**Comment by RtYkk** [comment]
@jameyhhh https://t.me/ptpluginplus/29?single
https://t.me/ptpluginplus/32

**Comment by toma77777** [comment]
> 同类型issue
> #735
> #733
> #730
> #726 提问前请先看有没有人提出相同问题
> 
> 已有[相关commit](https://github.com/ronggang/PT-Plugin-Plus/commit/48ed7a5b70d59eed556e2e91dd2e762108086b9f)提交并编译发布至[action版](https://github.com/ronggang/PT-Plugin-Plus/wiki/get-from-gh-actions)
> **正式版用户等待发布**
> 若不想切换 参考[教程](http://tieba.baidu.com/p/7262712800?share=9105&fr=share&see_lz=0&share_from=post&sfc=copy&client_type=2&client_version=12.3.8.11&st=1615886008&unique=DC46EF3206A1CAB2B17E4D46FD9E4A60)通过手动添加cdn域名的形式使用

谢谢，已通过这个方式暂时解决。

**Comment by jameyhhh** [comment]
> @jameyhhh https://t.me/ptpluginplus/29?single
> https://t.me/ptpluginplus/32

谢谢，已解决。

**Comment by ltkun** [comment]
直接手动添加一个网址就行了

**Comment by ddd-zero** [comment]
以后干脆出一个 可以手动微调默认站点网址的选项吧

**Comment by Rhilip** [comment]
@ddd-zero CDN选项就是给你们微调的

**Comment by stargz** [comment]
> @ddd-zero CDN选项就是给你们微调的
> 然而有人就是不知道用，有人还傻乎乎的添加自定义站点。

CDN，这个词用的很有迷惑性，尽管点击之后的注释非常清晰。。。

**Comment by Rhilip** [comment]
@stargz 这个我比较赞同，所以我下一版换成了 legacyUrl 这种配置

**Comment by stargz** [comment]
> @stargz 这个我比较赞同，所以我下一版换成了 legacyUrl 这种配置

或者AlternativeUrl？再或者“镜像Url”

供参考哈。
