### ISSUE TITLE
Android 浏览器 kiwi browser 可以安装插件但是不能导入备份数据 也不能获得权限

### ISSUE THREAD

**Issue by ltkun** [ronggang/PT-Plugin-Plus#739]
- PT 助手版本: 1.5.1
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：kiwi browser
- 浏览器是否安装了其他插件：no
- 停用其他插件后是否正常工作：no
- 问题描述：
可以安装插件但是不能导入备份数据 也不能获得权限 手动添加数据是可以正常运行的

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@ltkun 这个不是官方支持的浏览器，理论应该找浏览器开发者

**Comment by ltkun** [comment]
> @ltkun 这个不是官方支持的浏览器，这种问题理论应该找浏览器开发者。

之前手机版firefox和yandex都是支持的正常使用的 也都不是官方支持的 最近又用了这两个浏览器发现都取消了支持第三方扩展 kiwi是基于chrome好不容易找到个手机能用的 结果发现了这个bug 好不容易有个手机支持第三方插件的浏览器还希望下一版本可以正常使用。找浏览器开发者肯定本末倒置了 难道firefox不支持去找firefox chrome不支持去找chrome

**Comment by RtYkk** [comment]
本末倒置个屁，手机上用 pt 助手我从心里讲就是个伪需求。费拉 kiwi 破 bug 一堆，能用就行了，还要求和 PC 上一模一样吗？

**Comment by ted423** [comment]
@RtYkk 啊，无论如何不要激动。
btw
开不开权限，kiwi支持什么样得权限我们说了不算。

**Comment by ted423** [comment]
issue先锁了

**Comment by Rhilip** [comment]
我讲一下我的想法吧。
kiwi关于浏览器插件的支持是自主实现的。
所以在我们插件请求可选权限（cookies）的时候确实会出现权限获取不了的情况。这更可能是kiwi浏览器的实现问题，而不是我们插件处能解决的。也就如ssd的背景页无法发送cookies的情况在kiwi更新版本中同样存在。
而强行将可选权限改为强制权限会break我们用户守则（虽然大家都不一定关注这个），所以这么做也没有相应理由。
