### ISSUE TITLE
服务器下载提示无效的种子文件

### ISSUE THREAD

**Issue by chuisoo** [ronggang/PT-Plugin-Plus#74]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:v1.0.3
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：Google Chrome版本 72.0.3626.121（正式版本） （64 位）
- 问题描述：服务器下载提示无效的种子文件，但进入相关下载页后，不用pt助手可以下载，是哪里设置出了问题吗？
- 相关截图：{ "type": "error", "msg": "无效的种子文件", "success": false }

**Comment by Rhilip** [comment]
请告知具体站点

**Comment by lzl20110** [comment]
> 请告知具体站点

hdsky nanyangpt pter hdarea cmct 搜索页面无法一键添加 都提示种子无效  种子详情页可以点击一键下载 好几个版本前就有这个BUG了

**Comment by ronggang** [comment]
> > 请告知具体站点
> 
> hdsky nanyangpt pter hdarea cmct 搜索页面无法一键添加 都提示种子无效 种子详情页可以点击一键下载 好几个版本前就有这个BUG了

搜索页面是指站点的搜索页面吗？进行的是什么操作？右键标题下载，还是拖放下载？

**Comment by chuisoo** [comment]
在pt助手里点击查看最新种子，之后点击服务器下载，就会提示无效种子。cmct hdhome pter pthome mhz我有的都存在这个问题

**Comment by lzl20110** [comment]
> > > 请告知具体站点
> > 
> > 
> > hdsky nanyangpt pter hdarea cmct 搜索页面无法一键添加 都提示种子无效 种子详情页可以点击一键下载 好几个版本前就有这个BUG了
> 
> 搜索页面是指站点的搜索页面吗？进行的是什么操作？右键标题下载，还是拖放下载？

助手上的搜索页面 站点种子列表页面的标题右键下载 拖拽下载 都是种子无效 种子详情页的悬浮窗下载 拖拽下载 标题右键下载都是正常的

**Comment by ronggang** [comment]
@chuisoo @lzl20110 以下情况会提示种子无效
1. 下载链接返回的不是种子文件（文件头不包含：x-bittorrent）
2. 下载链接返回的不是二进制流文件（文件头不包含：octet-stream）

请提供一下下载操作时，服务器返回的文件信息。
1. 按 [该方法](https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page) 打开背景页
2. 进行下载操作
3. 在背景页查看类似于 `download.php` 页面的请求信息
![image](https://user-images.githubusercontent.com/8065899/54892916-64182e00-4eee-11e9-847f-e3ce5851534a.png)
4. 查看请求返回的头信息 `content-type` ，如果是 html 之类的，就会提示种子无效。

**Comment by lzl20110** [comment]
@chuisoo 找到原因了 这个是首次下载导致，需要在网站上确认后才能下载种子文件。我现在已经正常了 感谢开发者 @ronggang

**Comment by Dadians** [comment]
@chuisoo 您好。我查看请求返回的头信息 content-type，是html类型的，这该怎么办呀

**Comment by Dadians** [comment]
@ronggang @Rhilip 您好。我查看请求返回的头信息 content-type，是html类型的，这该怎么办呀

**Comment by Dadians** [comment]
其他站点都是正常的，只有自行添加的未收录的一个站点（学校站点 NexusHD）有这个问题

**Comment by ted423** [comment]
> 

手动点下载看看正不正常，还有看看html里啥内容

**Comment by Dadians** [comment]
@ted423 手动下载是正常的。不知道咋看html内容，下图可以吗：
![image](https://user-images.githubusercontent.com/79250427/168410025-a71c8c42-e5ef-4067-9801-d4c6db679bd9.png)

**Comment by ted423** [comment]
@Dadians 我感觉你可能或许可能要请他们sysop一起看下了，里面还写了个generator

**Comment by ted423** [comment]
才想起来，那个截图是不是不全，我记得发送到下载器，f12是能看到整个网址的，看下和界面下载那个网址有没有区别
