### ISSUE TITLE
站点设置-停机/离线

### ISSUE THREAD

**Issue by tudnew** [ronggang/PT-Plugin-Plus#741]
## 您的功能请求是否与问题有关？ 请描述一下。

停机/离线没有显示在列表，不方便查看哪些站点设置了停机，经常忘了恢复。

## 描述你想要的解决方案

增加一个竖栏显示，如同允许搜索、个人信息。

**Comment by RtYkk** [comment]
@tudnew …这个功能早就有了

**Comment by tudnew** [comment]
> @tudnew …这个功能早就有了

请问具体从哪设置？

**Comment by RtYkk** [comment]
@tudnew 你看看站点设置里面，现在我不在电脑边

**Comment by RtYkk** [comment]
sorry，我有问题

**Comment by Rhilip** [comment]
其实就我记忆来说，这个功能当初是在应对pt站点于版权日纷纷停机的时上线的。用于临时在搜索和个人信息中去掉这些站点。
但这样和已有的 允许搜索、个人信息 快捷方式又相互冲突。
所以**一直想把这个功能给去除掉的**。

请问你的应用场景是什么？

**Comment by tudnew** [comment]
> 其实就我记忆来说，这个功能当初是在应对pt站点于版权日纷纷停机的时上线的。用于临时在搜索和个人信息中去掉这些站点。
> 
> 但这样和已有的 允许搜索、个人信息 快捷方式又相互冲突。
> 
> 所以**一直想把这个功能给去除掉的**。
> 
> 
> 
> 请问你的应用场景是什么？

就像你说的那样，各站总会有这那样无法运行的时候，既然有这个功能说明还是有用处的，但现在的问题是关闭开启都需要点击才能看到，而当自己忘记时就只能一个一个全点开看有没有关闭了。

**Comment by tudnew** [comment]
@Rhilip 如果功能和允许搜索，个人信息完全重叠的话，去掉也是更好的选择，每次刷新不出信息总感觉是忘记开了。

**Comment by ted423** [comment]
@tudnew 那或许在个人信息那有个停机提醒？然后就跳过信息刷新？

**Comment by Rhilip** [comment]
这是当初设想，从这个叙述上看，与 允许搜索，个人信息 两个功能完全重叠。
但其实这里我们忽略了一个情况，就是 站点没了，但是有部分人还需要对应数据的统计留存。
“停机/离线” 这个功能更多的是为了这部分要求。

https://github.com/ronggang/PT-Plugin-Plus/blob/7d0b92828eddaed2ff4387ae09c8942a45321548/src/interface/common.ts#L257-L259

-----------------------

或者这种修改是否可行，就是对于设置了 停机/离线 的站点，其在 `#/set-sites` 页面的 “允许搜索、个人信息” 按钮直接禁用？
我目前并不想再在该页面添加一列。

**Comment by tudnew** [comment]
@ted423 @Rhilip 
你们俩说的方法都可以😅，只要能一目了然的看见这个功能是否生效就可以。
