### ISSUE TITLE
搜索界面柠檬显示不出种子信息

### ISSUE THREAD

**Issue by shuosiw** [ronggang/PT-Plugin-Plus#742]
- PT 助手版本: v1.5.1
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome  89.0.4389.82
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：
- 问题描述：种子搜索页面，搜索出来的 柠檬 lemonhd 的种子信息无法正常显示，包括大小、上传下载人数等

- 相关截图：

![image](https://user-images.githubusercontent.com/2578976/111900442-91602e00-8a6d-11eb-842b-6defb5d5f20c.png)

- 重现步骤：

在插件搜索种子时候，柠檬的种子都会出现这个问题

**Comment by ted423** [comment]
dupe https://github.com/ronggang/PT-Plugin-Plus/issues/713
