### ISSUE TITLE
M-team已更新

### ISSUE THREAD

**Issue by SNGDude** [ronggang/PT-Plugin-Plus#744]
请更新从PT到KP，老域名无法使用

**Comment by ted423** [comment]
在这么提issue，我就开始ban人了

**Comment by Mit2g** [comment]
Open issue里这么大一个标题都没能阻止你发这个issue吗？
![5ABDCEC6-E204-48EF-9FC1-A62739E0306A](https://user-images.githubusercontent.com/50163397/111949398-a4313c00-8b1b-11eb-87d8-f0a832a19960.jpeg)

**Comment by SNGDude** [comment]
没看到，出门着急发了一下

--------------原始邮件--------------
发件人："ted423 ***@***.***&gt;;
发送时间：2021年3月22日(星期一) 下午2:34
收件人："ronggang/PT-Plugin-Plus" ***@***.***&gt;;
抄送："SNGDude ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [ronggang/PT-Plugin-Plus] M-team已更新 (#744)
-----------------------------------

 

 
在这么提issue，我就开始ban人了

**Comment by ted423** [comment]
还请下次注意一下吧，这个dev版本已经修复好久了。
github 的 issue区也是建设项目的一环，探讨问题，解决问题，上来不仔细看直接把所有问题丢给别人挺不礼貌的。
特别是1周内一个问题丢5，6个issue。
