### ISSUE TITLE
添加下载种子失败

### ISSUE THREAD

**Issue by liuleionline** [ronggang/PT-Plugin-Plus#745]
- PT 助手版本: 1.5.1
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Google Chrome
版本 89.0.4389.90（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：不能添加下载种子，无论是在助手页搜索出来的还是在pt网站种子网页都不行。

- 相关截图：
![image](https://user-images.githubusercontent.com/81206456/112086601-7acdea00-8bc7-11eb-9a8f-7d449b5a23a0.png)
![image](https://user-images.githubusercontent.com/81206456/112086656-9507c800-8bc7-11eb-8e94-061d9d412949.png)

**Comment by ted423** [comment]
@liuleionline 什么网站,还是都不行，试试wiki那里用crx试试呢

**Comment by liuleionline** [comment]
所有pt都不行，好几个，hdc，hdsky，ttg，ssd等等

**Comment by ted423** [comment]
@liuleionline 客户端设置及测试有没有问题呢

**Comment by liuleionline** [comment]
pt测试下载服务器，通。
手动下载种子到群晖download station，也是OK。
就是用助手不行，奇怪了，前几天出现，还以为必须升级151，结果升了也不行。

**Comment by liuleionline** [comment]
code 101，是啥错误？

**Comment by ted423** [comment]
@liuleionline 你download station是不是升级的，看下issue区download station的issue呢？

**Comment by liuleionline** [comment]
一直升级的，我也怀疑是不是群晖的DS的API变了？

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/687

**Comment by ted423** [comment]
@liuleionline 是的，变了

**Comment by liuleionline** [comment]
另外几个用transmittion的哥们没这个问题。

**Comment by liuleionline** [comment]
这个问题可以通过CRX安装解决？

**Comment by Mit2g** [comment]
> 这个问题可以通过CRX安装解决？

不可以 插件中的这部分并没有更新 如果你有能力可以修改后pr

**Comment by liuleionline** [comment]
我仔细看了，我的群晖并没有升级到7，但是估计DS单个升级了

**Comment by liuleionline** [comment]
群晖API变化这个，只能等你升级了，：）

**Comment by Rhilip** [comment]
目前PTPP未适配最新DS， 我们的讨论见 #687 ，请转至该issue讨论。
未作适配的主要原因是因为 SYNO.DownloadStation2.Task 的API 目前并未公开，目前我在
https://github.com/ronggang/PT-Plugin-Plus/blob/next/src/background/btclients/synologyDownloadStation.ts
的实现仅为测试，具体是否能够使用不明。

refs: https://github.com/seansfkelley/synology-download-manager/issues/166
