### ISSUE TITLE
不支持普通的BT链接传送到Qbittorrent

### ISSUE THREAD

**Issue by haowen2000** [ronggang/PT-Plugin-Plus#748]
- PT 助手版本:1.5.1
- PT 助手安装方式：市场
- 浏览器名称及版本：edge最新版
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
经测试，PT站点右键发送种子链接到下载服务器，能到达我的QB下载服务器。

但普通的BT网站上的magnet链接，例如www.hao6v.com上的下载链接基本都是magnet链接，
无法通过PT plus右链传送到下载服务器，这是插件BUG，还是QB 下载服务器本身就不支持传送这种链接？

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
印象里一直有问题

**Comment by ted423** [comment]
测了一下，tr可以，qb就一直这样
![image](https://user-images.githubusercontent.com/7042766/112116290-175ab100-8bf5-11eb-9f18-2a785a66b573.png)

**Comment by haowen2000** [comment]
> 测了一下，tr可以，qb就一直这样
> ![image](https://user-images.githubusercontent.com/7042766/112116290-175ab100-8bf5-11eb-9f18-2a785a66b573.png)

我的QB下载服务器也是一直跑进度条，发送不成功

这是QB的问题，还是插件的问题？
