### ISSUE TITLE
WINDOWS Transmission WEB 远程下载服务器无法添加

### ISSUE THREAD

**Issue by MYJN** [ronggang/PT-Plugin-Plus#75]
- PT 助手版本: v1.0.3
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Cent Browser 3.8.5.69（正式版本） （64 位） (Chromium 71.0.3578.98)
- 问题描述：windows 10(10.0.14393) Transmission 2.94 远程下载服务器WEB无法添加
- 相关截图：
![2019-03-24_103215](https://user-images.githubusercontent.com/13313477/54874162-b5f28280-4e20-11e9-8861-1410fbc18fbc.jpg)
![2019-03-24_103755](https://user-images.githubusercontent.com/13313477/54874184-f94cf100-4e20-11e9-8dbb-226e62ba8d68.jpg)

**Comment by MYJN** [comment]
Transmission WEB设置界面图
![2019-03-24_104023](https://user-images.githubusercontent.com/13313477/54874205-58ab0100-4e21-11e9-9131-94b5e9f8da81.jpg)

**Comment by ronggang** [comment]
@MYJN 直接用浏览器访问地址是否可以正常访问？另外，如果启用身份验证是否可以访问？

**Comment by MYJN** [comment]
> @MYJN 直接用浏览器访问地址是否可以正常访问？另外，如果启用身份验证是否可以访问？

1.Transmission可以直接进行浏览器访问.
2.开启身份验证,打开WEB无需进行验证直接访问

**Comment by ronggang** [comment]
> > @MYJN 直接用浏览器访问地址是否可以正常访问？另外，如果启用身份验证是否可以访问？
> 
> 1.Transmission可以直接进行浏览器访问.
> 2.开启身份验证,打开WEB无需进行验证直接访问

那你需要确认一下Tr的设置是否有问题，启用身份验证后是需要用户名和密码才可以正常访问的。

**Comment by MYJN** [comment]
> > > @MYJN 直接用浏览器访问地址是否可以正常访问？另外，如果启用身份验证是否可以访问？
> > 
> > 
> > 1.Transmission可以直接进行浏览器访问.
> > 2.开启身份验证,打开WEB无需进行验证直接访问
> 
> 那你需要确认一下Tr的设置是否有问题，启用身份验证后是需要用户名和密码才可以正常访问的。

1.Transmission WEB设置项就上面的那几个,再没有其他WEB相关的设置项
2.开启WEB验证后
![2019-03-25_184014](https://user-images.githubusercontent.com/13313477/54914077-1f60b700-4f2f-11e9-97d9-10315252f92e.jpg)
PT 助手是可以添加上Transmission,
但是几分钟后刷新报错404
![2019-03-25_184411](https://user-images.githubusercontent.com/13313477/54914195-5cc54480-4f2f-11e9-9bd5-cd397ba36230.jpg)

**Comment by Rhilip** [comment]
看这个404报错信息总觉得是win下transmission的问题

**Comment by ronggang** [comment]
@MYJN TR应该不正常了，你从官网上重新下载安装一下吧。

**Comment by MYJN** [comment]
> @MYJN TR应该不正常了，你从官网上重新下载安装一下吧。

Transmission安装包是从官网下载的,我昨天反复下载反复安装测试了10几次,怕涉及权限问题安装路径都换几次,还是不行
![2019-03-26_081505](https://user-images.githubusercontent.com/13313477/54962379-8f0e8a80-4f9f-11e9-88ba-bace8b315dbe.jpg)

**Comment by MYJN** [comment]
> 看这个404报错信息总觉得是win下transmission的问题

可能是
![2019-03-26_081808](https://user-images.githubusercontent.com/13313477/54962521-2d025500-4fa0-11e9-9daa-70c0774e34ee.jpg)

**Comment by ronggang** [comment]
@MYJN 可以尝试更改一下端口号试试。

**Comment by MYJN** [comment]
> @MYJN 可以尝试更改一下端口号试试。

试过了,结果一样不行,我这边9091这个端口没有被占用

**Comment by ronggang** [comment]
> > @MYJN 可以尝试更改一下端口号试试。
> 
> 试过了,结果一样不行,我这边9091这个端口没有被占用

那我也想不到是什么原因，你得找找TR的问题。

**Comment by ronggang** [comment]
长时间没有反馈，本主题暂时关闭，有需要请重新开启。
