### ISSUE TITLE
无法手动修改添加的站点地址，如mt，emp

### ISSUE THREAD

**Issue by weigeloveu** [ronggang/PT-Plugin-Plus#750]
- PT 助手版本:1.5.1
- PT 助手安装方式：ms市场安装
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
empornium换地址了,无法手动修改添加的站点地址，手动添加提示不支持
现在地址是
www.empornium.is
www.empornium.sx
我查过wiki，里边说站点构架是common，站上写着是Luminance（https://github.com/Empornium/Luminance）
之前按照common添加正常使用，现在不行了，望大神修复一下

**Comment by Mit2g** [comment]
尝试使用此种解决方法解决 https://github.com/ronggang/PT-Plugin-Plus/issues/737#issuecomment-802566255

**Comment by weigeloveu** [comment]
> 尝试使用此种解决方法解决 [#737 (comment)](https://github.com/ronggang/PT-Plugin-Plus/issues/737#issuecomment-802566255)
已解决，多谢
