### ISSUE TITLE
 Synology Download Station更新版本后无法推送种子

### ISSUE THREAD

**Issue by mm519897405** [ronggang/PT-Plugin-Plus#753]
- PT 助手版本:1.5.1
- PT 助手安装方式：zip
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述： Synology Download Station更新版本后无法推送种子

- 相关截图：点击下载到Synology Download Station的目录后，会弹出提示：
{ "error": { "code": 101 }, "success": false }

- 重现步骤：点击下载到Synology Download Station的目录后，会弹出提示：
{ "error": { "code": 101 }, "success": false }

**Comment by ted423** [comment]
Dupe https://github.com/ronggang/PT-Plugin-Plus/issues/687
