### ISSUE TITLE
蒲公英复制页面所有种子链接错误

### ISSUE THREAD

**Issue by xiaoguiwk** [ronggang/PT-Plugin-Plus#755]
- PT 助手版本:1.5.1
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：chrome 89.0.4389.90
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
https://npupt.com/downloads/uTorrent-NPUBits-NF.exe&passkey=*****************&https=1

这是第一个种子错误链接

https://npupt.com/javascript:torrent_download(175436,373,100.0,false,false,false);&passkey=**************************&https=1

这是第二个种子错误链接，后面一百多个和这个一样

- 相关截图：
没图

- 重现步骤：
直接复制所有种子链接

**Comment by badmintonsong** [comment]
+1 深受其困扰

**Comment by ted423** [comment]
先关了
