### ISSUE TITLE
action版里面柱状图日期显示BUG，日期显示为前一天，折线图显示正常。

### ISSUE THREAD

**Issue by charlisepahina1** [ronggang/PT-Plugin-Plus#756]
- PT 助手版本:1.5.1 dev-build-a9d0b9a
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：chrome 89
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
- 
柱状图日期显示BUG，日期显示为前一天，折线图显示正常。

- 相关截图：
<a href="https://sm.ms/image/6oTAvIPuNCaXfKb" target="_blank"><img src="https://i.loli.net/2021/03/30/6oTAvIPuNCaXfKb.png" ></a>
<a href="https://sm.ms/image/8EblwQqLrg5cixV" target="_blank"><img src="https://i.loli.net/2021/03/30/8EblwQqLrg5cixV.png" ></a>

- 重现步骤：
打开数据图

**Comment by charlisepahina1** [comment]
<a href="https://sm.ms/image/8EblwQqLrg5cixV" target="_blank"><img src="https://i.loli.net/2021/03/30/8EblwQqLrg5cixV.png" ></a>

<a href="https://sm.ms/image/6oTAvIPuNCaXfKb" target="_blank"><img src="https://i.loli.net/2021/03/30/6oTAvIPuNCaXfKb.png" ></a>

**Comment by sabersalv** [comment]
我是故意按前一天显示的. 假设你每天早上0点准时记录, 3月30日0点记录完成, 那上传量就是3月30日-3月29日, 这个上传量肯定就是3月29日的了。另一个假设你每天早上12点准时记录,  3月30日12点记录完成, 那上传量就是3月30日-3月29日, 这个上传量是算3月30日，还是3月29日呢? (具体来说, 3月30日占了12个小时, 3月29日占了12个小时, 五五开). 而且每个人记录时间都是不一样的, 所以这个时间显示没有统一标准。
