### ISSUE TITLE
葡萄搜索结果时间错误

### ISSUE THREAD

**Issue by IndeedSi** [ronggang/PT-Plugin-Plus#758]
Linked #713

- PT Plugin Plus version:  © ronggang 2021, Version v1.5.1 
- PT Plugin Plus installation method: zip package installation （从GitHub下载，没有用增强版之类的，没有改过源码）
- Browser name and version: Chrome, Version 89.0.4389.90 (Official Build) (x86_64)
- Whether the browser has other plugins installed:  Yes
- Is it working properly after disabling other plugins: No
- Problem Description:
葡萄搜索结果里面，种子的发布时间在未来

- Related screenshots:
![putao](https://user-images.githubusercontent.com/16617799/113085991-c1e95a00-921b-11eb-84d3-c7eea840b879.png)

- Reproduce steps:
搜索“司藤”， 前两个种子

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/113392779-3b25b000-93c8-11eb-82dd-3f17a89c7f41.png)
没能再现，你每次搜索都一定会有这个问题是么？

**Comment by ted423** [comment]
是否有装过action#103的版本试试
https://github.com/ronggang/PT-Plugin-Plus/suites/2360651709/artifacts/49985567

**Comment by IndeedSi** [comment]
> ![image](https://user-images.githubusercontent.com/7042766/113392779-3b25b000-93c8-11eb-82dd-3f17a89c7f41.png)
> 没能再现，你每次搜索都一定会有这个问题是么？

是的，我这里每次都是一样的问题。
不好意思，不太清楚mac上面crx要怎么安装。一直都是用的zip

**Comment by IndeedSi** [comment]
做了一下snapshot，感觉我这里的时间似乎就是有点问题。

比如01-06集的那个种子，snapshot之后在console里面我看到的时间是`time: "2021-3-823:10:31"`，而且这个也不是我最后界面上显示的时间。
![image](https://user-images.githubusercontent.com/16617799/113465429-d709f700-946e-11eb-9128-19477a5ab7e8.png)

但是在rss里面和你的截图里面时间都是 `<pubDate>Mon, 08 Mar 2021 21:18:43 +0800</pubDate>`
![image](https://user-images.githubusercontent.com/16617799/113465467-23edcd80-946f-11eb-8c26-a9025c7474d8.png)

而且我的所有葡萄的种子的时间都是10:31结尾的，我在想是不是解析这个时间的时候有什么问题就fall back到了这个数字...

**Comment by ted423** [comment]
@IndeedSi 网页搜索时，显示时间是？

**Comment by IndeedSi** [comment]
今天研究了一下，发现好像是葡萄网站的bug。一个workaround就是把这里的“时间显示类型”改成发生时间，就不会有任何问题了

![image](https://user-images.githubusercontent.com/16617799/113496792-1a7c6800-9538-11eb-8f12-a11e59d04df3.png)


如果选了已去时间，那么时间就会显示成多少天多少时。而且这个计算并没有考虑我的时区，所以对应的时间也是错的，感觉这个是葡萄的bug。

![image](https://user-images.githubusercontent.com/16617799/113496819-7941e180-9538-11eb-8006-b006acf305f3.png)

https://github.com/ronggang/PT-Plugin-Plus/blob/fe1ee0e81c7d7b3eafd71e4d706c0233d648b42b/resource/sites/lemonhd.org/getSearchResult.js#L264
这段代码里面虽然能够解析出来大概是在哪个小时，但是分钟跟秒就是按照搜索时间算的，所以才会出现都一样的情况。

**Comment by ted423** [comment]
@IndeedSi 👍
