### ISSUE TITLE
M-Team 更改了域名

### ISSUE THREAD

**Issue by bovey1** [ronggang/PT-Plugin-Plus#759]
因应域名汙染，网址从https://pt.m-team.cc 更改为 https://kp.m-team.cc 希望广大同好互相告知
(除主站网址外，其他服務不受影響)

官网通知。导致现象用这个kp域名无法使用软件

- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@bovey1 你这是在玩火🌚

**Comment by Rhilip** [comment]
#737
