### ISSUE TITLE
群晖 DSM 6.2.4 推送下载出现错误，一直返回101

### ISSUE THREAD

**Issue by Daniel-love-Snow** [ronggang/PT-Plugin-Plus#764]
1. 
    - PT 助手版本:  栽培者 2021, 版本 v1.5.1 crx
    - PT 助手安装方式：解压安装
    - 浏览器名称及版本：Google Chrome   89.0.4389.114（正式版本） （64 位）
    - 浏览器是否安装了其他插件：yes
    - 停用其他插件后是否正常工作：no

2.
    - PT 助手版本:  栽培者 2021, 版本 v1.5.1
    - PT 助手安装方式：市场安装
    - 浏览器名称及版本：Microsoft Edge 版本 89.0.774.68 (官方内部版本) (64 位)
    - 浏览器是否安装了其他插件：no
    - 停用其他插件后是否正常工作：no

- 问题描述：
推送到下载服务器，返回  {"error":{"code":101},"success":false}
链接服务器正常
init.js中  this.version 改为2-6都不行
- 相关截图：
![2](https://user-images.githubusercontent.com/6451541/113535055-f2a70600-9604-11eb-8786-6aea8148a894.png)

![1](https://user-images.githubusercontent.com/6451541/113534996-c3909480-9604-11eb-8e9a-1315fd2ff41f.png)
 
![4](https://user-images.githubusercontent.com/6451541/113535757-e754da00-9606-11eb-95c7-bb7b79252064.png)
![3](https://user-images.githubusercontent.com/6451541/113535681-b96f9580-9606-11eb-9ea2-101ac3ca5ffd.png)

- 重现步骤：
点击按钮：推送到下载服务器

**Comment by Rhilip** [comment]
dupe: https://github.com/ronggang/PT-Plugin-Plus/issues/687
并非仅DSM7出现问题，较高版本的DS同样。目前请考虑降级或换用其他bt软件。

**Comment by Alkylation** [comment]
DSM 6.2.3也错误101

**Comment by ted423** [comment]
> DSM 6.2.3也错误101

请按照标准提问题，例如扩展版本需要说明
