### ISSUE TITLE
请问firefox商店的PT Plugin Plus插件是您上传的吗？

### ISSUE THREAD

**Issue by Leojc** [ronggang/PT-Plugin-Plus#767]
链接：https://addons.mozilla.org/zh-CN/firefox/addon/xhlpt-plugin-plus/

**Comment by Rhilip** [comment]
并不是。你可以考虑给FF举报，应该是私有域上传没设置好。

**Comment by Leojc** [comment]
咦，不是说“因不符合 Mozilla 审核政策被下架”了吗？ 那这个又是怎么上架的呢？ 可以麻烦官方上架一份吗？

**Comment by Rhilip** [comment]
@Leojc 这个不清楚，但至少我们官方上传的是被下架了，你应该去问Mozilla为什么？是被举报还是真的不符合，毕竟官方反馈的信息特别模糊（这也是国外公司的特点）。
我们每次正式发版（即release）都会尝试申请，一直没通过，这也不是我们的问题。

**Comment by Leojc** [comment]
我有个建议，根据 #491 ,可以选择不由firefox来发布，而是直接得到签名好的xpi文件，由自己发布。那是不是可以每次发版的时候，附带一个xpi文件，放到release里面，供Firefox用户安装呢？这样对firefox用户会方便很多，就是你们会麻烦一些了，要多进行一次签名。

**Comment by Rhilip** [comment]
似乎可以通过CI实现相关操作，到时候我和ronggang他讨论下吧。
