### ISSUE TITLE
EMP在种子列表中批量下载/批量复制下载链接不会下载曾经下载过的种子

### ISSUE THREAD

**Issue by qfishpear** [ronggang/PT-Plugin-Plus#768]
- PT 助手版本:  v1.5.0 
- PT 助手安装方式：crx解压安装
- 浏览器名称及版本：Google Chrome 已是最新版本  版本 89.0.4389.114（正式版本） （32 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
emp的话曾经下过的种子和没下过的种子在下载列表里显示是不一样的，批量下载or复制链接只会下载/复制未曾下过的种子
而实际上无论下没下过，下载的图标都是可以点击里面都是包含下载链接可以用于下载的
更新：上面描述似乎与实际不符，实际情况是无论如何在种子列表页面都只能复制到一个下载链接
- 相关截图：
下过的：
![下过的种子](https://i.loli.net/2021/04/07/SwgN9rpBqItuRTx.jpg)
没下过的：
![没下过的种子](https://i.loli.net/2021/04/07/S1kfQ4bX2OdJgvc.jpg)
复制链接的时候只能复制到没下过的所有种子的链接，批量下载也是

- 重现步骤：
在种子列表中使用两次批量下载，等第一次下完之后刷新页面再下一次/再复制链接就会发现这个问题
为了测试可以考虑下体积小的种子： https://www.empornium.is/torrents.php?order_way=asc&order_by=size&

**Comment by ted423** [comment]
EMP一直有点问题，并且因为某人犯懒的原因，暂时没人修

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/commit/4f5f3518dbf37c9e30894cf802693b8a7b445ca3
原来不知道为啥脑抽引用的detail的js
