### ISSUE TITLE
馒头出公告域名更改了

### ISSUE THREAD

**Issue by mickeywaley** [ronggang/PT-Plugin-Plus#771]
-Show/Hide 2021.03.15 - 域名更改
因应域名汙染，网址从https://pt.***.cc 更改为 https://kp.***.cc 希望广大同好互相告知
(除主站网址外，其他服務不受影響)

**Comment by Mit2g** [comment]
Dupe #737 
请不要重复创建同类型issuse

**Comment by RtYkk** [comment]
开 issue 前能不能搜一下？？？一个域名开了多少 issue？？
#726 #733 #735 #736 #737 #744 #759 #770 
别玩星际了
