### ISSUE TITLE
pthome种子下载链接改变

### ISSUE THREAD

**Issue by wxuuu** [ronggang/PT-Plugin-Plus#773]
PT 助手版本: 1.5.1
PT 助手安装方式：zip包安装
浏览器名称及版本：谷歌浏览器 89.0.4389.114 (正式版本) （64 位） (cohort: Stable)
浏览器是否安装了其他插件：是
停用其他插件后是否正常工作：否
问题描述：pthome种子下载链接从passkey变为downhash
例：https://www.pthome.net/download.php?id=&downhash=

**Comment by Rhilip** [comment]
我觉得这个问题至少在 dev 中已修复 https://github.com/ronggang/PT-Plugin-Plus/pull/706
请不要在该站点的设置中添加passkey，即 此处留空
![image](https://user-images.githubusercontent.com/13842140/114509953-b1e46800-9c68-11eb-8799-b0145fcbd564.png)
