### ISSUE TITLE
豆瓣frodo失效，不能直接查询imdb编号

### ISSUE THREAD

**Issue by Cyberxxt** [ronggang/PT-Plugin-Plus#777]
- PT 助手版本:1.51
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：是
- 问题描述：豆瓣frodo失效，不能直接查询imdb编号

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
说实在的，frodo接口~~关掉~~（更正，目前情况不明）之后，
豆瓣唯一一个开放的就  `https://movie.douban.com/j/subject_suggest?q=${query}` 
然而这个接口虽然能传入query为imdb编号形式，并不能从response中直接获得imdb编号，而且返回信息也有限。

**Comment by techmovie** [comment]
@Rhilip 通过subject_suggest拿到豆瓣id后，可以通过这个接口https://movie.querydata.org/api?id=1302425 拿豆瓣信息。
项目地址：https://github.com/iiiiiii1/douban-imdb-api。作者应该还在维护。

**Comment by Rhilip** [comment]
@techmovie 不会考虑走第三方接口

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/discussions/984
