### ISSUE TITLE
请求添加nexus pt站个人信息页历史种子批量下载

### ISSUE THREAD

**Issue by yfhong** [ronggang/PT-Plugin-Plus#779]
## 您的功能请求是否与问题有关？ 请描述一下。

因挂PT主机系统盘崩了、qbittorrent数据未备份，导致所有做种任务需要重新下载种子文件。

## 描述你想要的解决方案

nexus pt站个人信息页，有5类历史种子记录，其中会记录所有曾经下载过的种子。如果能在此页批量下载所有种子，会方便很多。
![pt站点个人信息页历史种子信息](https://user-images.githubusercontent.com/1052330/115683967-89a3ea00-a389-11eb-938e-18009afe66bf.PNG)

**Comment by Rhilip** [comment]
我更建议你使用userscript或者其他批量下载插件的形式进行以上操作。

**Comment by ted423** [comment]
@yfhong 功能比较客制化，。思路是批量获取种子id,然后自己添加passkey等构造下载链接。但大概站点本身不太喜欢这种操作，请求太多
