### ISSUE TITLE
HDArea无法获取登录状态

### ISSUE THREAD

**Issue by linler007** [ronggang/PT-Plugin-Plus#78]
- PT 助手版本:v1.0.2
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：360安全浏览器10.0.1634.0 极速模式
- 问题描述：HDarea可以正常添加，但是添加之后刷新信息一直提示未登录，实际上已经正常登录
- 相关截图：
![image](https://user-images.githubusercontent.com/48899937/54894733-f6bccb00-4ef6-11e9-8088-14193d30727a.png)

**Comment by ronggang** [comment]
@linler007 助手使用的是不带www的域名，请确认这个域名是否已登录。

**Comment by linler007** [comment]
可以了，非常感谢！
核实情况如下：默认输入https://hdarea.co/之后点击登录，登录后会自动跳转到https://www.hdarea.co/index.php，这个时候刷不出来，然后重新在地址栏输入https://hdarea.co/打开再刷新就可以了。

**Comment by ronggang** [comment]
那就关闭主题了。
