### ISSUE TITLE
zip版本运行在Chromium提示有error

### ISSUE THREAD

**Issue by xyxu1024** [ronggang/PT-Plugin-Plus#780]
- PT 助手版本: 1.5.1
- PT 助手安装方式：（市场安装，或zip包安装）zip包
- 浏览器名称及版本：Chromium Version 89.0.4389.114 (Developer Build) built on Debian 10.2, running on Debian 10.9 (32-bit)
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：-
- 问题描述：
按照wiki的zip安装方式，扩展程序页“加载已解压的扩展程序”安装，提示error，但目前使用没有发现异常，也可以导入备份数据。

- 相关截图：
![Capture20210422171605](https://user-images.githubusercontent.com/19919729/115689379-9a0a9380-a38e-11eb-9a64-a758170631c4.png)
![youdu图片20210422171748](https://user-images.githubusercontent.com/19919729/115689477-b27aae00-a38e-11eb-9f60-4f5713a98f62.png)

- 重现步骤：
按照wiki安装方式首次安装即出现

**Comment by Rhilip** [comment]
此处错误是给开发者看的，普通用户不用考虑。
