### ISSUE TITLE
希望能在豆瓣页面加入IMDB分数

### ISSUE THREAD

**Issue by haowen2000** [ronggang/PT-Plugin-Plus#784]
## 您的功能请求是否与问题有关？ 请描述一下。

希望能在豆瓣页面加入IMDB分数

## 其他附加信息

豆瓣页面的“用PT助手搜索”按钮是助手添加的吧，要是能添加IMDB分数项目就方便了。

虽然装了其他脚本能显示IMDB分数了，但助手 如果 能也显示 IMDB分数就不用多装一个脚本插件了。

**Comment by ted423** [comment]
@haowen2000 不是…

**Comment by haowen2000** [comment]
> @haowen2000 不是…

刚才通过测试，原来豆瓣原生就有IMDB编号链接，要点进去才能查看IMDB分数。


那能不能在““用PT助手搜索”按钮”旁添加IMDB分数链接？免得多装一个插件。

**Comment by Rhilip** [comment]
@haowen2000 更建议你使用用户脚本的形式
如：
 - https://greasyfork.org/zh-CN/scripts/329484
 - https://greasyfork.org/zh-CN/scripts/7687-moremovieratings
