### ISSUE TITLE
CHDbits和HDSky都最多搜索到100个结果，设置已设为200

### ISSUE THREAD

**Issue by hlc1209** [ronggang/PT-Plugin-Plus#787]
CHDbits和HDSky都最多搜索到100个结果，设置已设为200

我的设置应该没问题因为MTeam我可以得到多余100的结果。

多余100个结果的实用性在于，例如chd现在全站免费，我想要下载所有sgnb资源，总数超过400个。确实可以直接在chd网站上操作，但是插件中界面更好且有多种过滤和筛选选项

**Comment by ted423** [comment]
@hlc1209 搜索结果默认不会显示翻页的结果，建议在站点页面操作
