### ISSUE TITLE
frds站种子链接没有key

### ISSUE THREAD

**Issue by sanzuwu** [ronggang/PT-Plugin-Plus#79]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.3
- PT 助手安装方式：（zip包安装）
- 浏览器名称及版本：yedanx
- 问题描述：在种子页面点击复制链接，获得的连接没有key，设置里已经填写key了
- 相关截图：

**Comment by ronggang** [comment]
@sanzuwu 是 keepfrds 吗？种子列表还是种子详情页面？

**Comment by sanzuwu** [comment]
是keepfrds，种子列表复制的链接有key，种子详情页没有，获得的链接是这样的：https://pt.keepfrds.com/download.php?id=9152&https=1

**Comment by ronggang** [comment]
@sanzuwu 获取链接的优先级是这样的
1. 页面中有带 passkey 的下载链接，直接获取
2. 如果有类似 download.php 这样的链接直接获取；
3. 如果都没有，则使用已设置的 passkey 进行组合生成下载链接 ；

我没有 keepfrds，所以我猜想 keepfrds 大概是走了第2个条件。
