### ISSUE TITLE
每次安装后自动消失

### ISSUE THREAD

**Issue by liuleionline** [ronggang/PT-Plugin-Plus#803]
- PT 助手版本: 1.5.1
- PT 助手安装方式：拖拽文件夹
- 浏览器名称及版本：chrome 90.0.4430.212
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：没有测试
- 问题描述：每次安装后第二天重启pt助手就消失了

- 相关截图：

- 重现步骤：

**Comment by Rhilip** [comment]
非助手问题

**Comment by RtYkk** [comment]
@liuleionline RTFM

**Comment by mookixiao** [comment]
请问解决了吗？我也遇到这个问题
edge浏览器，其他插件好好的，就是这个有时候会消失，好几台设备都出现过

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx

> 请问解决了吗？我也遇到这个问题 edge浏览器，其他插件好好的，就是这个有时候会消失，好几台设备都出现过

**Comment by mookixiao** [comment]
> https://github.com/ronggang/PT-Plugin-Plus/wiki/install-from-crx
> 
> > 请问解决了吗？我也遇到这个问题 edge浏览器，其他插件好好的，就是这个有时候会消失，好几台设备都出现过
我试试吧，当时看crx安装还要改注册表什么的太麻烦就用zip装的，结果就碰到上面说的过段时间自动消失的问题🤪
