### ISSUE TITLE
在搜索结果页面进行关键词过滤，再进行多选的话，如果使用shift进行快速选择，不能正确选择相应的选项。

### ISSUE THREAD

**Issue by imogel** [ronggang/PT-Plugin-Plus#805]
- PT 助手版本:v1.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge 版本 90.0.818.56 (官方内部版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：未测试
- 问题描述：
在搜索结果页面进行关键词过滤，再进行多选的话，如果使用shift进行快速选择，不能正确选择相应的选项。
清理缓存以及重新安装插件均无法解决。

- 相关截图：
![image](https://user-images.githubusercontent.com/47932877/118069313-8b842a80-b3d6-11eb-9a2d-ef12a058e086.png)
截图1

![image](https://user-images.githubusercontent.com/47932877/118069333-9343cf00-b3d6-11eb-864f-9ab536253186.png)
截图2

- 重现步骤：
1.搜索任意信息，进入搜索结果页面，等待搜索完成。*打开多选功能*
2.在“过滤搜索结果”框中输入过滤关键字，如“265”、“1080p”、“2160p”等。
3.在如截图1的过滤结果中，选中第二个选项，然后按住“shift”按键再点击第五个选项，进行多选。结果只选中了2个，但实际选中了5个。
4.此时删除过滤关键字，可以看到实际选中的为截图2中的5个选项。

**Comment by Rhilip** [comment]
原先我以为shiftClick这个多选出错应该是Vuetify的问题，所以一直没有做处理
但在官方v1.5.x中，并不能实现shiftClick多选，
搜索Vuetify相关的issue，官方对shiftClick的支持也是在2.5.0之后。。

--------------

后来翻了下我们的实现，发现是自己的polyfill 🤣🤣🤣🤣
so，用一种简单的方法来修了
