### ISSUE TITLE
Feature request: 账号inactive提醒

### ISSUE THREAD

**Issue by cyzs233** [ronggang/PT-Plugin-Plus#808]
**Is your feature request related to a problem? Please describe.**
进了多个pt站，时间一长，总有些淡出视线，因为长期没有数据量而被删号。希望能在被删号前提醒用户登录网站活跃一下。

**Describe the solution you'd like**
pt站都是根据数据量来判断死号的，而且各站的账号保留天数也是固定的。点插件时查一下数据量最后一次更新的时间，就能提醒用户还有多少天有删号风险。

**Describe alternatives you've considered**
**Additional context**

**Comment by ted423** [comment]
@cyzs233 我不觉得这是助手需要做的……

**Comment by Rhilip** [comment]
助手侧无法准确知道用户上次访问时间（部分pt站点的判断依据）
此外，也正如 @ted423 所说，非助手应该做的功能。

**Comment by cyzs233** [comment]
PT用户可能一个月不用pt，但基本每天都会用chrome。
![bhj](https://user-images.githubusercontent.com/25927091/118691065-48ddaa80-b83b-11eb-96da-56606ed37ff2.png)
像这样在工具栏提醒那些站点需要登录不是很方便么。@ted423

**Comment by ted423** [comment]
@cyzs233 1. 你既然使用了浏览器，没有保号，也没有上pt就说明你已经失去了热情
2. 有个自动刷新，有这个功能我觉得就不再需要提醒
3. pt助手的判断登录时间是不准确的，所以作为实现你说的这个功能误差可能会会非常大。况且我认为浏览器扩展从原理以及功能上也不适合做这种类似后台偷偷跑功能，或者定时任务之类的。

**Comment by gutenye** [comment]
需要的是这个https://github.com/ronggang/PT-Plugin-Plus/discussions/743
