### ISSUE TITLE
u2的魔力值/积分计算错误

### ISSUE THREAD

**Issue by RichieChow** [ronggang/PT-Plugin-Plus#81]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:v1.0.3
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Chrome 73.0.3683.86
- 问题描述：u2的魔力值/积分计算错误，实为金银铜100进制

- 相关截图：
![ucoin](https://user-images.githubusercontent.com/34783557/55080448-2297a680-50d9-11e9-8014-28adc08f8ac0.jpg)

**Comment by ronggang** [comment]
@RichieChow 感谢反馈。
