### ISSUE TITLE
下载所有的提示有误

### ISSUE THREAD

**Issue by winddriver** [ronggang/PT-Plugin-Plus#813]
- PT 助手版本:1.5.1
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chromium 86.0.4240.198
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：下载所有，即便种子大小小于100G也会提示超过100G

- 相关截图：
![2021-5-26 20-44-39](https://user-images.githubusercontent.com/3221597/119662221-ba34e300-be63-11eb-855c-db731f007057.png)

- 重现步骤：
随便打开一个pt站，搜索，然后选择下载所有

**Comment by ted423** [comment]
无法复现，我这发送成功

**Comment by winddriver** [comment]
点确定还是可以发送的，就是这个提示不应该出现，因为起始并没有超过100G

**Comment by ted423** [comment]
@winddriver 我这没有提示
