### ISSUE TITLE
柠檬站搜索主页列表显示不正确

### ISSUE THREAD

**Issue by zhoudi** [ronggang/PT-Plugin-Plus#816]
- PT 助手版本: 1.5.1
- PT 助手安装方式：（市场安装，或zip包安装） zip安装
- 浏览器名称及版本：Chrome 90.0.4430.212
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：查询列表无法正常显示https://lemonhd.org/index.php 信息, 

- 相关截图：
![image](https://user-images.githubusercontent.com/2352583/120091289-3ff2b000-c13c-11eb-8305-e84ea50447b2.png)

- 重现步骤：

1. 获取各站第一页种子
2. 柠檬站相关列表对应信息不对, 同时无优惠等信息

**Comment by ted423** [comment]
@zhoudi 应该dupe了

**Comment by RtYkk** [comment]
Duplicated: #713
