### ISSUE TITLE
“一键下载”时会忽略路径关键字

### ISSUE THREAD

**Issue by luhua2018** [ronggang/PT-Plugin-Plus#817]
- PT 助手版本: v1.5.1
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Microsoft Edge 91.0.864.37
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
  在种子详情页点击助手工具栏的 `一键下载` 后根据提示输入信息，但是点击确定后实际的下载路径却没有将路径关键字替换。

- 相关截图：
  ![image.png](https://i.loli.net/2021/06/01/UH5fzQnipIoS2uC.png)

- 重现步骤：
   1. 在下载路径设置中使用路径关键字；
   2. 到PT站的种子详情页点击`一键下载`，观察实际下载路径和预期的下载路径是否一致。

**Comment by Rhilip** [comment]
dupe #681

**Comment by luhua2018** [comment]
是的，看起来我遇到的问题跟 #681 是一样的。
