### ISSUE TITLE
支持qb的下载;分类功能

### ISSUE THREAD

**Issue by rty813** [ronggang/PT-Plugin-Plus#821]
## 您的功能请求是否与问题有关？ 请描述一下。
qbittorrent支持下载分类，不同分类会自动保存到不同的目录。但是PT助手下载时，不支持选择下载分类
![image](https://user-images.githubusercontent.com/22488813/120985736-7bc9ed00-c7ae-11eb-9fc0-80eb069eec73.png)

## 描述你想要的解决方案
PT助手新增下载分类，下载时选择不同分类

**Comment by Rhilip** [comment]
旧版不做考虑，next分支已经做了 label/category 支持
