### ISSUE TITLE
建议search功能2160p，1080p泛定义

### ISSUE THREAD

**Issue by willie91** [ronggang/PT-Plugin-Plus#822]

**Comment by ted423** [comment]
@willie91 个人想法是ptpp通过源数据的分类，视频格式分辨率等对应到相应的tags,自己重新分类，不使用原站点的分类信息。这样可以避免分类太乱的问题。

**Comment by Rhilip** [comment]
没看懂，请补充完整issue内容

**Comment by ted423** [comment]
@Rhilip 各站都有自己的分类，因此出现搜索结果的一些4k没法包含所有的结果。

**Comment by Rhilip** [comment]
哦，那这个没法做，我个人倾向于尊重站点的分类而不是自己rewrite。
但是目前关于搜索结果的二次筛选我倒是有想法，等next版写options页面的时候再做。
