### ISSUE TITLE
添加uTorrent服务器失败

### ISSUE THREAD

**Issue by lupohan44** [ronggang/PT-Plugin-Plus#823]
- PT 助手版本:1.5.1
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 91
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：添加下载服务器uTorrent失败, 显示"服务器连接失败", 用postman照流程测试正常

- 相关截图：
![image](https://user-images.githubusercontent.com/23133361/121772137-2b83ce00-cba6-11eb-96d6-4882cfbfca72.png)
![image](https://user-images.githubusercontent.com/23133361/121772173-5a01a900-cba6-11eb-8cd6-4f21c2adf043.png)

- 重现步骤：添加uTorrent webui下载服务器, 测试过2.2.1, 3.5.5, ng-torrent-ui全都一样的问题

**Comment by lupohan44** [comment]
用http没反代之前的url也测试过 一样的情况

**Comment by Rhilip** [comment]
插件背景页对应网络请求的返回是否正常？

**Comment by lupohan44** [comment]
> 插件背景页对应网络请求的返回是否正常？

开发者窗口里似乎无法监控插件背景页的请求, 所以找不到方法看对应的网络请求...

**Comment by Rhilip** [comment]
https://github.com/ronggang/PT-Plugin-Plus/wiki/how-to-open-background-page

**Comment by lupohan44** [comment]
卡巴斯基注入了一段JS导致解析出错
![image](https://user-images.githubusercontent.com/23133361/121775095-1f087100-cbb8-11eb-9b89-80451e39fc7f.png)
关闭卡巴斯基JS注入后正常
![image](https://user-images.githubusercontent.com/23133361/121775106-39424f00-cbb8-11eb-8268-ca46f5477ced.png)
![image](https://user-images.githubusercontent.com/23133361/121775114-3fd0c680-cbb8-11eb-8fcd-75576b682566.png)
应该是解析token的部分要修改
还发现一个t=后面timestamp似乎消失了(cache影响应该不大?)
![image](https://user-images.githubusercontent.com/23133361/121775144-6858c080-cbb8-11eb-8759-b3445ca3c760.png)

**Comment by Rhilip** [comment]
这年头还有人用卡的？
建议贴一下不同情况下的html， token用xxxx表示就行。

**Comment by lupohan44** [comment]
> 建议贴一下不同情况下的html， token和其他隐私信息用xxxx表示就行。
未注入:
URL:
`https://xxx/gui/token.html?t=`
Response:
`<html><div id='token' style='display:none;'>xxxxxx</div></html>`
注入后:
URL:
`https://xxx/gui/token.html?t=`
Response:
`<html><script type="text/javascript" src="https://gc.kis.v2.scr.kaspersky-labs.com/AAAA/main.js?attr=BBBB" charset="UTF-8"></script><div id='token' style='display:none;'>xxxxxxxxx</div></html>`
AAAA为UUID 带-的
BBBB似乎是随机产生的东西 出现了a-z, A-Z, 0-9, -和_

> 这年头还有人用卡的？
等过期了就准备换了 有什么推荐的吗 误报不要太严重的 之前用过avast 一堆CDN报毒 用的我非常难受

**Comment by lupohan44** [comment]
看起来真的是直接写?t=
`url: this.options.address + "token.html?t=",`
是不是应该在后面加个timestamp 不然这个t=没什么用啊

**Comment by Rhilip** [comment]
哦，了解了不过确实挺有意思的
![image](https://user-images.githubusercontent.com/13842140/121775571-22512c00-cbbb-11eb-8af4-30e5a59f8733.png)

目前用的是jQuery的这种写法，可以看到出错了，对于卡注入的页面没能获取到token。
另一种是我目前在next的写法，到时候切到这种实现上吧。

**Comment by Rhilip** [comment]
> 看起来真的是直接写?t=
> `url: this.options.address + "token.html?t=",`
> 是不是应该在后面加个timestamp 不然这个t=没什么用啊

有点记不清了，应该是uT对于每个请求都需要提供 `&t=` 这个请求参数，不然会出错。

**Comment by ted423** [comment]
话说这个还准备修么，还是丢到next解决？

**Comment by Rhilip** [comment]
> 话说这个还准备修么，还是丢到next解决？

next没有这个问题，因为一开始处理方法就不同。backport的意义不大，可以关闭。
