### ISSUE TITLE
GGn 使用JSON API 获取信息

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#825]
## 描述你想要的解决方案
Apologies for the late response and many thanks for your patience. So this is a pretty typical example of the sort of thing that isn't malicious in nature, but we'd prefer having it use our API: wiki.php?action=article&id=401.

**Comment by Rhilip** [comment]
However switch to gazelle api,
Means we can't get torrent's progress and status information when search.

**Comment by ted423** [comment]
看了下公告去询问的。staff就强调了要用api。
所以我感觉用api还是会好些
就个人来讲，ggn搜索感觉还是上网站搜索看起来好些？因此状态信息这些或许不是特别必要。
另外或许不支持的在搜索结果中标明unsupport会不会看起来更直观点，能避免掉一些混乱

**Comment by Rhilip** [comment]
从GGN的wiki说明中，可以看出 apikey 并不是可以通过自动化程序申请（或通过解析页面获取的）的，而是需要额外PM
我不太支持切换到API上。

**Comment by Rhilip** [comment]
另外公告的Exception中也指出

> Applications like jackett also aren't affected and can continue to be used for legitimate purposes. With that said, we encourage use of our API wherever possible as opposed to other approaches.

**Comment by ted423** [comment]
了解
