### ISSUE TITLE
Blutopia 积分正则表达式对空格处理的问题

### ISSUE THREAD

**Issue by zamlty** [ronggang/PT-Plugin-Plus#830]
- PT 助手版本：1.5.1 dev-build-845982c
- PT 助手安装方式：zip 包安装
- 浏览器名称及版本：百分浏览器（Chromium 86.0.4240.198）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
  Blutopia 积分在 PTPP 上只能显示空格以前的数字，我觉得正则表达式对空格的处理需要更新下。Blutopia 积分目前的正则表达式里用的是空格
  https://github.com/ronggang/PT-Plugin-Plus/blob/845982c44c472e3efdcf7fac1bf1d32a7777107c/resource/sites/blutopia.xyz/config.json#L60
  但是网页上的空格用的是 `&thinsp;`，这会导致 `&thinsp;` 没有被替换成空字符串，只有（第一个）空格以前的数字会被解析到
  我自己的解决方法是用 `\\s` 代替空格（如下），不过我不知道哪个文件是 PTPP 真正会读的配置，修改了好几处文件才把 Blutopia 积分显示改成功。希望开发大大们可以看看这样合不合理，感谢！
  ```diff
  - "filters": ["query.parent().text().trim().replace(/ /g,'').match(/([\\d.]+)/)", "(query && query.length>=2)?parseFloat(query[1]):0"]
  + "filters": ["query.parent().text().trim().replace(/\\s/g,'').match(/([\\d.]+)/)", "(query && query.length>=2)?parseFloat(query[1]):0"]
  ```

- 相关截图：
  - Blutopia 网页显示的积分
![image](https://user-images.githubusercontent.com/29914613/123021517-cda58080-d406-11eb-986a-80c505d00274.png)
  - Blutopia 网页代码
![image](https://user-images.githubusercontent.com/29914613/123021638-0c3b3b00-d407-11eb-943a-b7ac23f6394c.png)
  - PTPP 里 Blutopia 积分显示不正确
![image](https://user-images.githubusercontent.com/29914613/123021709-2bd26380-d407-11eb-88b5-5f3f2517d79b.png)

**Comment by ted423** [comment]
@zamlty 👍

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/commit/cafeaf6f1b4295205a38242c8e92b37ba1fe64a2
