### ISSUE TITLE
Blutopia 搜素模式更新

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#831]
## 您的功能请求是否与问题有关？ 请描述一下。

新的请求网址如下
/torrents?perPage=25&name=Infection
/torrents?perPage=25&imdbId=2294629
/torrents?perPage=25&imdbId=11032374
测试ACM可以使用第一个，但不能使用imdb那个

**Comment by ted423** [comment]
简单改了下，目测脚本也需要重写

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/123043839-7534aa00-d42b-11eb-97cb-28fc8cca4ffb.png)

**Comment by Rhilip** [comment]
是unit3d的问题，他们新版本的搜索字段和老版本不一样，直接改底层模板好些。

**Comment by ted423** [comment]
已经把blu的代码丢模板里改了，主要我手头就一个blu和acm，acm又是老版本，我怕一改其他站全炸了
