### ISSUE TITLE
SoulVoice 一键下载地址错误

### ISSUE THREAD

**Issue by xiashali** [ronggang/PT-Plugin-Plus#833]
- PT 助手版本:4de33f0
- PT 助手安装方式：Actions crx
- 浏览器名称及版本：Chromium 版本 91.0.4472.114（正式版本）Arch Linux （64 位）
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：不适用
- 问题描述：
pt.soulvoice.club/torrents.php pt.soulvoice.club/live.php 一键下载所有正常，https://pt.soulvoice.club/details.php 种子页面发送下载链接时地址错误

- 相关截图：
![image](https://user-images.githubusercontent.com/6998208/124374240-4391cd80-dccc-11eb-82fe-a6bad974ec45.png)

- 重现步骤：

**Comment by ted423** [comment]
@xiashali 吴昊，跟官方提供的连接有区别么？
是否有自己设置过cookies

**Comment by carloswear** [comment]
这个站我也有，刚才测试了一下，报错502
![QQ截图20211125150530](https://user-images.githubusercontent.com/41362266/143395286-564ec1c6-edf7-4081-a657-7814fc459cfc.png)

**Comment by MewX** [comment]
一楼的截图貌似是网址重复出现？
