### ISSUE TITLE
求增加iTS支持

### ISSUE THREAD

**Issue by balle13** [ronggang/PT-Plugin-Plus#834]
- 站点名称：In the Shadow
- 站点地址：https://shadowthein.net/
- 站点描述：iTS

- 资源类型：影视
- 开放注册：否
- 是否连坐：否
- 站点规则：

**Comment by Mit2g** [comment]
Dupe with https://github.com/ronggang/PT-Plugin-Plus/issues/695
iTS部分支持已被merge https://github.com/ronggang/PT-Plugin-Plus/pull/738

**Comment by ted423** [comment]
请勿SPAM

**Comment by ted423** [comment]
Sorry ,看起来我弄错了一些东西，不过在pr内的就先不要再开issue了
