### ISSUE TITLE
nicept搜索正常，但是跳转种子详情页会自动转到站点首页

### ISSUE THREAD

**Issue by fqh1995** [ronggang/PT-Plugin-Plus#836]
- PT 助手版本:1.5.1白大魔改版本
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Microsoft Edge
版本 92.0.902.49 (官方内部版本) beta (64 位)**pc端**
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：
- 问题描述：
nicept搜索正常，但是跳转种子详情页会自动转到站点首页

- 相关截图：
搜索正常
![image](https://user-images.githubusercontent.com/31031100/126094000-af2a1c21-d36e-4b0d-b590-c210c741fe98.png)
进入详情页出错，转为首页
![image](https://user-images.githubusercontent.com/31031100/126094078-cbdae541-9e47-4a10-8f36-c7ea88b271bb.png)
正常首页截图
![image](https://user-images.githubusercontent.com/31031100/126094115-c408b1c0-cb80-4802-922a-e3d07b0c43e7.png)

- 重现步骤：

**Comment by ted423** [comment]
Works Fine on me
没使用魔改。
看搜索界面有很大不同，请给出助手中搜出来的连接。
你添加的nicept的配置页中的域名是否正常，包括是否带https

**Comment by fqh1995** [comment]
整好了，原来是我的主页设置为种子页，感谢提醒
