### ISSUE TITLE
请求添加Retroflix

### ISSUE THREAD

**Issue by balle13** [ronggang/PT-Plugin-Plus#838]
<!-- 
1、在发起请求前，请先确认是否在已支持的架构内；
- 站点名称：Retroflix
- 站点地址：https://retroflix.club/
- 站点架构：改版前借鉴Nexus，PTPP选择N架构可使用一半功能，最近改版了已无法使用，具体架构不详。
- 站点描述：非主流老电影

- 资源类型：
- 开放注册：是
- 是否连坐：不详
- 站点规则：可发邀请

**Comment by ted423** [comment]
无有意义的详细信息
