### ISSUE TITLE
Safari 适配

### ISSUE THREAD

**Issue by xnxin** [ronggang/PT-Plugin-Plus#851]
## 您的功能请求是否与问题有关？ 请描述一下。

Extension 并无问题

## 描述你想要的解决方案

Safari 进行适配， [参考](https://developer.apple.com/documentation/safariservices/safari_web_extensions?language=objc)

## 其他附加信息

由工具直接转换后报错，考虑阅读源码后修改。
<img width="613" alt="截屏2021-07-30 14 56 45" src="https://user-images.githubusercontent.com/10513841/127613977-74dffb4b-318c-4257-b00e-0345cd05842b.png">

**Comment by ted423** [comment]
供参考 https://blog.gslin.org/archives/2019/09/21/9217/safari-%E4%B8%8A-ublock-origin-%E7%9A%84%E6%83%85%E6%B3%81/

**Comment by ted423** [comment]
算了删掉了，我想试着看下移植到safari上是否有api方面的兼容性限制，但实际那篇文章也没太多的具体分析，况且我也不是很懂这些。

**Comment by Rhilip** [comment]
Apple的文档一点参考意义都没有。

我有在next分支将对浏览器调用从chrome对象转移至browser对象计划（Promise比回调地狱香呀），

但是即使这样对 Safari 也不会进行“官方性质”的支持。
