### ISSUE TITLE
可不可以添加个一键提取各站热搜的功能？

### ISSUE THREAD

**Issue by hjie** [ronggang/PT-Plugin-Plus#852]
## 您的功能请求是否与问题有关？ 请描述一下。

提取各站热搜

## 描述你想要的解决方案

一键提取

**Comment by Rhilip** [comment]
似乎并没有多大意义，毕竟只有NPHP系有这个功能

**Comment by ted423** [comment]
@Rhilip 我倒是倾向于去豆瓣上看看热门算了
