### ISSUE TITLE
TorrentLeech似乎又无法无法正常获取注册时间了

### ISSUE THREAD

**Issue by MewX** [ronggang/PT-Plugin-Plus#855]
- PT 助手版本: © ronggang 2021, Version v1.5.1.9be9649 zip
- PT 助手安装方式：zip
- 浏览器名称及版本：92.0.4515.107
- 浏览器是否安装了其他插件：-
- 停用其他插件后是否正常工作：-
- 问题描述：和 #703 完全一样，但是使用的版本已包含上次的修复，且上次确实修复了

- 相关截图：

![image](https://user-images.githubusercontent.com/5752560/128162456-127eaf8f-3742-45f3-af92-83fa06409283.png)

控制台里的输出：

```
bonus: "9729.00"
downloaded: 366553983877.12
id: "****"
isLogged: true
joinTime: null
lastUpdateStatus: "success"
lastUpdateTime: 1628071307352
levelName: "Extreme User"
messageCount: 0
name: "****"
seeding: 132
seedingSize: 987153521704.9603
uploaded: 26795098368901.12
```

- 重现步骤：刷新

**Comment by ted423** [comment]
很奇怪的是我这正常...

**Comment by ted423** [comment]
哦。。。我打开了网页，然后我也米勒

**Comment by ted423** [comment]
网页改了这个
Register date -> Registration date
