### ISSUE TITLE
概览页面的pt这些年走过的路页面无法直接关闭

### ISSUE THREAD

**Issue by chenyz1984** [ronggang/PT-Plugin-Plus#86]
- PT 助手版本:1.0.4
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome 73.0.3683.75（正式版本） （64 位）
- 问题描述：pt这些年走过的路的页面不能关闭么？只能通过点其他功能间接关闭。
- 相关截图：
![5](https://user-images.githubusercontent.com/20869868/55300043-51f73c00-5468-11e9-9b41-4488a54c8938.png)

**Comment by ronggang** [comment]
是的，目前只能按其他地方离开，后续加个关闭按钮吧。

**Comment by ronggang** [comment]
请更新至v1.0.5
