### ISSUE TITLE
Jpopsuki不统计部分信息

### ISSUE THREAD

**Issue by jaaaaaaaah** [ronggang/PT-Plugin-Plus#860]
- PT 助手版本:v1.5.1.7eeab85
- PT 助手安装方式： crx（市场安装，或zip包安装）
- 浏览器名称及版本：Microsoft Edge 版本 94.0.975.1 (官方内部版本) dev (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
我的数据 Jpopsuki 不统计等级、上传量、分享率和做种数量，为空。

- 相关截图：
![image](https://user-images.githubusercontent.com/44402079/129007782-73eff725-377a-4b18-a4da-0e0f845b02b7.png)
- 重现步骤：
刷新数据

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/commit/51da1b104ad739ed0b87466a931cc47d9a9f8752
