### ISSUE TITLE
[Mark一下]毒蛇疑似准备关站 

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#863]
- PT 助手版本:  v1.5.1.51da1b1
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

不过算小道消息，看看后续咋样

- 相关截图：

- 重现步骤：

**Comment by RtYkk** [comment]
**更新：
2020.09.24 : 本贴及相关PR不再接收成立时间（持续时间）小于3个月的NPHP架构站点。**

**Comment by Rhilip** [comment]
> **更新： 2020.09.24 : 本贴及相关PR不再接收成立时间（持续时间）小于3个月的NPHP架构站点。**

这个站是已经接收了的吧？而且那条规则只针对NPHP架构。
