### ISSUE TITLE
顶栏搜索的热门影响文字输入

### ISSUE THREAD

**Issue by wsspsb** [ronggang/PT-Plugin-Plus#870]
- 使用场景: 打开插件,点击顶栏的搜索栏,输入文字,回车搜索(我使用的火狐浏览器, 搜狗输入法, 不知道其他浏览器是不是也会这样)
- 问题: 搜索栏中靠左的热门会延迟加载出来, 导致中文输入还没有空格确认文字,就把英文填进去了,而且焦点好像也不在搜索栏了,导致必须再次点击搜索栏才能输入
- 建议: 点击搜索栏后就不要影响输入, 这样体验更好, 比如热门按钮先加载出来, 内容后面填充, 不知道是否可行. 不行的话看有没有其他办法
- 截图: 
![图片](https://user-images.githubusercontent.com/23711469/129496780-5b5419e2-c23d-4d2f-a2ee-1f2b68908ad4.png)
(比如上面想输入依依不舍,结果yiyi被输入进去了,输入焦点也没了)
![图片](https://user-images.githubusercontent.com/23711469/129496785-8011e374-cf42-4671-9ff5-35e97265af3b.png)

**Comment by wsspsb** [comment]
啊  为什么没有维护者回复下我......   是我没描述明白还是不准备处理,或者忘记这个了.
看到了回复下吧  谢谢

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/projects/2

**Comment by ted423** [comment]
感觉现在顶部搜索条弹不出来，所以问题解决

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/discussions/984
