### ISSUE TITLE
hdsky在种子详情页用PT助手复制链接到客户端无法下载种子

### ISSUE THREAD

**Issue by cxx66666** [ronggang/PT-Plugin-Plus#871]
- PT 助手版本:v1.5.2
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Microsoft Edge 92.0.902.67
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：不正常
- 问题描述：
在hdsky种子详情页，点击助手的复制链接后，助手是复制了“下载种子“的链接，把这个链接复制到客户端里，无法下载，图1。
如果是复制“下载链接”的这个链接到客户端才能正常下载，图2。
自从hdsky更改了下载链接结构，这个问题一直没解决。

- 相关截图：
https://ptpimg.me/9i7ti7.png
https://ptpimg.me/n9gxly.png

- 重现步骤：

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/573

**Comment by ted423** [comment]
那个连接是有时效的，超时了就会没法用

**Comment by hzw168** [comment]
> 那个连接是有时效的，超时了就会没法用

我自己刚发布的种子，助手复制链接到客户端做种就不行。

**Comment by ted423** [comment]
@hzw168 你没设这个站点的passkey吧

**Comment by hzw168** [comment]
> @hzw168 你没设这个站点的passkey吧

设了也一样，你随便找个种子试一下就知道了

**Comment by ted423** [comment]
@hzw168 我的意思是设了才不正常，不过另一方面，sky可能不支持直接粘贴到客户端下载，当让我也可能说错

**Comment by ted423** [comment]
@hzw168 浏览器里这个连接是可用的，需要cookie,至于没有cookie能否去下载到种子，这个可能需要找sky官方人员确认

**Comment by hzw168** [comment]
> 
> 
> @hzw168 我的意思是设了才不正常，不过另一方面，sky可能不支持直接粘贴到客户端下载，当让我也可能说错

设不设passkey都不行，我的建议是能不能把助手“复制链接”这个链接改成复制上面的“下载链接”https://ptpimg.me/mis1kd.png

**Comment by ted423** [comment]
试了下，你说的对，可能因为我没太关注sky的下载连接这块。
目前详情页获取的下载连接是采用的页面上不带passkey的形式，而官方有提供一个https://hdsky.me/download.php?id=96917&passkey=X&sign=X
形式的可以直接粘贴到客户端的连接
理论上这个可以在搜索中和列表中批量复制使用？

**Comment by hzw168** [comment]
是的，必须带passkey的链接才可以在客户端直接使用，搜索中和列表中批量复制的链接目前也是不带passkey的，建议修改下。
