### ISSUE TITLE
transmission下载服务器连接测试失败

### ISSUE THREAD

**Issue by chenyz1984** [ronggang/PT-Plugin-Plus#88]
> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本:1.0.4
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：谷歌版本 73.0.3683.86（正式版本） （64 位）
- 问题描述：更新了1.0.4pt助手，tr的web汉化用了一键包失败后，手动解压安装的。现状是，web访问tr无法访问，windows客户端工具可以访问。pt助手中测试下载服务器的链接也测试失败，不确定到底是pt助手的问题，还是web汉化包的问题
- 相关截图：
配置文件
![SETTINGS](https://user-images.githubusercontent.com/20869868/55308942-ccd34d80-548e-11e9-877c-d4fd2ac28509.png)
直接http://IP:9091/transmission/rpc访问结果
![CSRF](https://user-images.githubusercontent.com/20869868/55308968-d65cb580-548e-11e9-9c34-15c95798aa3d.png)
浏览器web访问tr的报错
![guisrc](https://user-images.githubusercontent.com/20869868/55309233-bf6a9300-548f-11e9-8330-27e1d46b6fc1.png)

**Comment by ronggang** [comment]
@chenyz1984 你启用了RPC白名单，所以除了白名单之外其他地址应该都无法访问。你可以试一下在停用TR的情况下，将 `rpc-host-whitelist-enabled` 设置为 false，再重新开启TR，再访问试试。

**Comment by ronggang** [comment]
长时间没有反馈，本主题暂时关闭，有需要请重新开启。
