### ISSUE TITLE
收藏列表不显示具体内容  只显示分组跟总体积

### ISSUE THREAD

**Issue by lbq1121** [ronggang/PT-Plugin-Plus#885]
- PT 助手版本:edge浏览器最新版（ 版本 v1.5.2.f2e4f20）
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Edge 92.0.902.84 (官方内部版本) (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：在进入我的收藏之后只显示**总体积跟分组** 在下方的具体列表中**无任何显示** 具体见**截图**

- 相关截图：
![image](https://user-images.githubusercontent.com/24562314/131836537-0bdba59b-a1b6-4252-8e58-5dbd563949de.png)
![image](https://user-images.githubusercontent.com/24562314/131836557-b93ad6e2-a055-43cd-9f01-32915d80781c.png)

- 重现步骤：
点击插件图标，单击**我的收藏**

**Comment by lbq1121** [comment]
是弃坑了吗？ 都好几个月了

**Comment by ted423** [comment]
@lbq1121 It's open source

**Comment by lbq1121** [comment]
Yes, I know this is an open source project. I'm just surprised that no new version has been released for a long time

**Comment by MewX** [comment]
> @ted423  Yes, I know this is an open source project. I'm just surprised that no new version has been released for a long time

It's not a quick fix, so don't be surprised. 🤭 Even if there's a new version, this issue will remain existing.

So, why don't you work on a fix yourself 👍👍👍

**Comment by ted423** [comment]
@lbq1121 chrome以及FF商店都已下架，以后版本获取都以action为准，新版本是否release已经没有太大影响，除了edge用户😂

**Comment by ted423** [comment]
@lbq1121 另外owner确实已经神隐，所以release大概遥遥无期

**Comment by lbq1121** [comment]
> @lbq1121 chrome以及FF商店都已下架，以后版本获取都以action为准，新版本是否release已经没有太大影响，除了edge用户😂

可我就是edge用户啊

**Comment by MewX** [comment]
> > @lbq1121 chrome以及FF商店都已下架，以后版本获取都以action为准，新版本是否release已经没有太大影响，除了edge用户😂
> 
> 可我就是edge用户啊

<img width="527" alt="image" src="https://user-images.githubusercontent.com/5752560/155146085-05259039-fcd1-432f-bcbd-3de23d90c723.png">

人数不够多呀

**Comment by ted423** [comment]
可能跟这个问题类似
https://github.com/ronggang/PT-Plugin-Plus/issues/420

**Comment by ted423** [comment]
在那个issue统一跟进，这个先关了
