### ISSUE TITLE
PTHOME下载种子到指定服务器提示无效的种子文件，已经手动下载种子成功

### ISSUE THREAD

**Issue by GLORYFeonix** [ronggang/PT-Plugin-Plus#887]
- PT 助手版本:1.52
- PT 助手安装方式：crx
- 浏览器名称及版本：chrome92.0.4515.159
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
PTHOME下载种子到指定服务器提示无效的种子文件，已经手动下载种子成功

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@GLORYFeonix 看看wiki

**Comment by ted423** [comment]
@GLORYFeonix 另外看下你发送的下载连接是什么

**Comment by GLORYFeonix** [comment]
> @GLORYFeonix 看看wiki

wiki指的是需要手动下载一遍种子吗？我已经下载成功了

**Comment by GLORYFeonix** [comment]
> @GLORYFeonix 另外看下你发送的下载连接是什么

![image](https://user-images.githubusercontent.com/50977527/132126340-79431d3f-c423-4a4f-b847-853b6d079e1a.png)

**Comment by Rhilip** [comment]
@GLORYFeonix 不要在站点设置中填入passkey。这是一个过时而且错误的设定，我们会在之后版本中移除该项。

**Comment by a717445834** [comment]
> @GLORYFeonix 不要在站点设置中填入passkey。这是一个过时而且错误的设定，我们会在之后版本中移除该项。

我没有设置,但是在列表中右击下载到服务器也不行,要进去页面,然后再右击下载才行,站点是pthome,而且访问该站点页面右侧没有助手显示出来

**Comment by a717445834** [comment]
> > @GLORYFeonix 不要在站点设置中填入passkey。这是一个过时而且错误的设定，我们会在之后版本中移除该项。
> 
> 我没有设置,但是在列表中右击下载到服务器也不行,要进去页面,然后再右击下载才行,站点是pthome,而且访问该站点页面右侧没有助手显示出来

已通过CDN解决,https://github.com/ronggang/PT-Plugin-Plus/wiki/config-site

**Comment by Rexexe** [comment]
> @GLORYFeonix 不要在站点设置中填入passkey。这是一个过时而且错误的设定，我们会在之后版本中移除该项。

确实不填就可以了
