### ISSUE TITLE
hr页面希望增加工具栏，方法一键下载回来做种

### ISSUE THREAD

**Issue by brucmao** [ronggang/PT-Plugin-Plus#888]
## 您的功能请求是否与问题有关？ 请描述一下。

现在工具栏只在种子页面显示，比如https://chdbits.co/torrents.php?
## 描述你想要的解决方案

希望在hr页面，比如https://chdbits.co/hnr.php?id=12345  页显示工具栏方便一键下载回来做种,或者让用户自定义也可以

## 描述您考虑过的替代方案

尝试在站点设置里面，将hr页面添加到站点cdn列表，未成功

## 其他附加信息

希望在该页面显示工具栏
![image](https://user-images.githubusercontent.com/6119652/132146038-c111ea61-9563-400d-9e28-922a31672efb.png)

**Comment by ted423** [comment]
不太懂这个列表怎么才会更新，下了一个h3没做种，但是一直没显示，不过目测这里没有提供下载链接
故功能可能没法简单实现。
实用度低
