### ISSUE TITLE
部分站点个人数据异常

### ISSUE THREAD

**Issue by i365star** [ronggang/PT-Plugin-Plus#89]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

瓷器/馒头无法取得做种信息，时光无法获取魔力

- PT 助手版本:1.0.4
- PT 助手安装方式：zip包
- 浏览器名称及版本：
- 问题描述：
- 相关截图：

**Comment by Rhilip** [comment]
当前暂不支持 `馒头` 这个站点获取做种信息（v1.0.4）
具体说明请看：
 - 瓷器：https://github.com/ronggang/PT-Plugin-Plus/issues/73
 - 馒头：https://github.com/ronggang/PT-Plugin-Plus/issues/68

-----------------------------

HDTime已修复（a433e9c4b64c4412d4d7c7f35bcb39c2a61dd870），请等待合入，原先问题出在脚本仅匹配`魔力值`字段，而该站少了一个字2333
![TIM截图20190405213722](https://user-images.githubusercontent.com/13842140/55631680-2f0fb380-57eb-11e9-9e72-ed832bd9c4c8.png)
