### ISSUE TITLE
火狐官方扩展中心下架了助手,可以提供xpi文件安装吗

### ISSUE THREAD

**Issue by xuanyuan100** [ronggang/PT-Plugin-Plus#893]
## 您的功能请求是否与问题有关？ 请描述一下。

官方商店下架扩展

## 描述你想要的解决方案

可以提供xpi文件下载安装,谢谢

**Comment by zhufeng** [comment]
自己注册一个mozilla开发者账号，提交ptpp的源码上去即可立即生成一个带签名的xpi。

**Comment by xuanyuan100** [comment]
> 
> 
> 自己注册一个mozilla开发者账号，提交ptpp的源码上去即可立即生成一个带签名的xpi。

谢谢,已经提交,等待审核,我下载下来的xpi别人应该也可以用吧,到时候一块上传过来

**Comment by Rhilip** [comment]
> > 自己注册一个mozilla开发者账号，提交ptpp的源码上去即可立即生成一个带签名的xpi。
> 
> 谢谢,已经提交,等待审核,我下载下来的xpi别人应该也可以用吧,到时候一块上传过来

可以的，但因为非官方签名、托管，存在陌生人信任问题，所以我们不推荐他人使用其他人签名的xpi。

**Comment by xuanyuan100** [comment]
[PT-Plugin-Plus-v1.5.2.zip](https://github.com/ronggang/PT-Plugin-Plus/files/7224161/PT-Plugin-Plus-v1.5.2.zip)
我就把我自己签名的xpi文件上传了,解压拖进火狐即可.
其实你们应该搞个xpi文件放上去的,至于用户用不用,相不相信,那就不管了
