### ISSUE TITLE
北邮人更换域名

### ISSUE THREAD

**Issue by a76yyyy** [ronggang/PT-Plugin-Plus#895]
- 站点名称：北邮人
- 站点地址：https://byr.pt
- 站点描述：著名教育网PT站点（仅支持ipv6访问与下载），有10大类资源，资源更新快，保种好。

- 资源类型：
- 开放注册：否
- 是否连坐：是/否
- 站点规则：

**Comment by Rhilip** [comment]
dupe: #891
