### ISSUE TITLE
与超级拖拽插件同时使用时种子列表无法拖拽打开新标签页

### ISSUE THREAD

**Issue by wgzeyu** [ronggang/PT-Plugin-Plus#90]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

- PT 助手版本：v1.0.3
- PT 助手安装方式：Chrome应用商店安装
- 浏览器名称及版本：Google Chrome 73.0.3683.86
- 问题描述：超级拖拽插件可以拖拽链接在新标签页打开，没有安装PT助手时使用正常，安装PT助手后，在种子列表拖拽链接后，新标签页出现的不是打开链接，而是搜索以下内容：
{"url":"details.php?id=XXXXX&hit=1","title":"XXXXXXXXXXX"}
超级拖拽：https://chrome.google.com/webstore/detail/super-drag-for-google-chr/dlknjglebgomjjfaijjnebecgjbfjihk
- 相关截图：
![截图](https://wgzeyu.gtxcn.com/img/TIM%E6%88%AA%E5%9B%BE20190403154509.png)

**Comment by ronggang** [comment]
功能冲突了，你在设置里可以把助手的拖放功能关闭。

**Comment by wgzeyu** [comment]
才发现有这个功能。。关闭就好了
