### ISSUE TITLE
无法推送PT种子文件，求解（报错信息undefined）

### ISSUE THREAD

**Issue by zyw28** [ronggang/PT-Plugin-Plus#904]
### Discussed in https://github.com/ronggang/PT-Plugin-Plus/discussions/903

<div type='discussions-op-text'>

<sup>Originally posted by **zyw28** September 19, 2021</sup>
使用黑群晖进行下载，设置完成了站点、下载目录，但一推送PT种子文件注提示下图：
![image](https://user-images.githubusercontent.com/56476413/133914726-9cff44b2-150e-4389-95bf-e2ef599ba07c.png)

后台查看有报错信息：
![image](https://user-images.githubusercontent.com/56476413/133914772-4875105b-6541-426e-af58-aad6ab1c1682.png)

![image](https://user-images.githubusercontent.com/56476413/133914788-ca5a2eed-ab12-4a17-82a9-c1b7440f3f08.png)

</div>

**Comment by Rhilip** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/687
