### ISSUE TITLE
使用一段时间后，报错”无法访问您的文件“

### ISSUE THREAD

**Issue by freephenix** [ronggang/PT-Plugin-Plus#906]
- PT 助手版本: v1.5.2
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：尚未尝试
- 问题描述：
使用一段时间后，再次打开会提示如下

无法访问您的文件
该文件可能已被移至别处、修改或删除。
ERR_FILE_NOT_FOUND

- 相关截图：
![WX20210922-195342](https://user-images.githubusercontent.com/15763635/134338907-edfc2350-90d3-4d62-b17a-50503e66a07e.png)

- 重现步骤：
使用一段时间后，再次打开就会导致如此

**Comment by ted423** [comment]
文件夹不能删，看看wiki,用crx

**Comment by ted423** [comment]
与扩展代码无关
