### ISSUE TITLE
北邮人域名已经更改 对应的json文件需要更改 否则无法连上服务器

### ISSUE THREAD

**Issue by RogerPanBUAAedu** [ronggang/PT-Plugin-Plus#907]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：

- 相关截图：

- 重现步骤：

**Comment by RogerPanBUAAedu** [comment]
https://byr.pt/ 是为新域名 感谢

**Comment by Rhilip** [comment]
dupe #891
