### ISSUE TITLE
希望能动态调整搜索结果的标题栏宽度

### ISSUE THREAD

**Issue by aiselo** [ronggang/PT-Plugin-Plus#908]
## 您的功能请求是否与问题有关？ 请描述一下。

压制组对于一个资源而言，是很重要的信息。但是一般压制组的名字都放在标题的最后面，造成的结果就是，如果一个资源的标题过长，搜索结果表格中的标题栏往往没有显示到压制组信息。当然，把鼠标悬停在标题上几秒钟，就能看到完整的标题，但是有点麻烦，也不够直观。特别是，如果这样的资源有好多个的话，一个个地查看，会花费不少时间。

## 描述你想要的解决方案

可以把标题栏的宽度设大点，当然最好的方法是可以通过鼠标拖动来动态调整宽度。如果要简单点，可以动态隐藏/显示某些列，使标题栏有更多的显示空间。

## 其他附加信息

<img width="1117" alt="WX20211002-011114@2x" src="https://user-images.githubusercontent.com/3375942/135662667-0c290d0a-b70d-4fb1-a0c9-0a85ad3dde5c.png">

**Comment by Rhilip** [comment]
如果你屏幕过小，请考虑对页面进行缩放，以便于能完整显示标题列信息。
关于你提出的解决方案，经查阅vuetify文档，并未有相应支持，故不考虑。
