### ISSUE TITLE
Aither.cc's seach query updated from /torrents/filter?search=[query] to /torrents?name=[query]

### ISSUE THREAD

**Issue by PrivatePasta** [ronggang/PT-Plugin-Plus#911]
- PT Plugin Plus version: v1.5.2.f2e4f20
- PT Plugin Plus installation method: Zip package
- Browser name and version: Version 94.0.4606.61 (Official Build) (64-bit)
- Whether the browser has other plugins installed: Yes
- Is it working properly after disabling other plugins: No

- Problem Description: 
Search will not work with Aither.cc because the plugin is requesting the query to aither.cc/torrents/filter?search=[query] but it should be updated to aither.cc/torrents?name=[query]

- Related screenshots:
Not needed

- Reproduce steps:
Just try searching for anything in Aither from ptpp

- Log: [aither.txt](https://github.com/ronggang/PT-Plugin-Plus/files/7280270/aither.txt)

**Comment by MewX** [comment]
好像最近u3d的都有点问题，jptv.club也是，我回头看下，可以先assign给我

**Comment by PrivatePasta** [comment]
I'm in a few other unit3d trackers, haven't faced any other problems. Even this search thing I've only seen in Aither. All other unit3d trackers are still using /torrents/filter?search=[query] .

**Comment by PrivatePasta** [comment]
JPTV search url looks like:
https://jptv.club/torrents/filter?_token=[token]&search=[query]

**Comment by ted423** [comment]
please check the newsest commit
https://github.com/ronggang/PT-Plugin-Plus/commit/f5878b96c68db3fa8d8ae5903addf26ac87c9dc7
cause problems
