### ISSUE TITLE
1.5.2在Edge Insider 97.0.1060.0上无法创建辅种任务

### ISSUE THREAD

**Issue by RoyLi-Pvt** [ronggang/PT-Plugin-Plus#921]
- PT 助手版本:1.5.2.f2e4f20和最新Dev构建1.5.2.139a742
- PT 助手安装方式：Edge市场以及Zip
- 浏览器名称及版本：Edge Insider 97.0.1060.0
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
  按照辅种创建流程操作后提示辅种创建成功但辅种列表中不显示

- 相关截图：
无，就是辅种任务列表空的

- 重现步骤：
1，搜索The Suicide Squad 2021
2，容量96.35GB的我这里有5个
3，选择这五个，然后点击辅种
4，全部校验成功，然后设置目录，tr－自定义目录
5，显示创建辅种任务中，后续步骤在辅种任务列表查看
6，创建完成，窗口自动关闭，辅种任务列表空

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/420
刷新后是否会显示，一般来说同类issue跟帖就好

**Comment by RoyLi-Pvt** [comment]
不显示

**Comment by ted423** [comment]
在那个issue统一跟进，这个先关了

**Comment by RoyLi-Pvt** [comment]
额 刚发现我issue引错了应该是很像 #442
