### ISSUE TITLE
无法获取北洋园的上传、下载数据量

### ISSUE THREAD

**Issue by byangmath** [ronggang/PT-Plugin-Plus#922]
- PT 助手版本：1.5.2.f2e4f20
- PT 助手安装方式：zip包
- 浏览器名称及版本：华为浏览器，版本: 11.0.7.301 | 内核版本: 92.0.4515.107
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：无法获取北洋园的上传、下载数据量

- 相关截图：
![1636127234(1)](https://user-images.githubusercontent.com/40292563/140538942-1ae7fff7-3fff-4c02-bd6c-e3acad5508d8.png)

**Comment by ted423** [comment]
请使用dev版本
