### ISSUE TITLE
AB无法批量下载

### ISSUE THREAD

**Issue by Duan-rax** [ronggang/PT-Plugin-Plus#923]
- PT 助手版本:1.5.2
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：无
- 停用其他插件后是否正常工作：否
- 问题描述：AB无法获取种子列表页的链接，反馈未定位到链接，无法进行批量下载

- 相关截图：

- 重现步骤：1-安装助手 2-打开AB 3-复制链接 4-失败 无法定位到链接

**Comment by MewX** [comment]
等 #945 提交之后就可以用了

**Comment by MewX** [comment]
这个也可以关了
