### ISSUE TITLE
avz 架构站点 imdb 搜索支持.

### ISSUE THREAD

**Issue by Bright-W** [ronggang/PT-Plugin-Plus#929]
## 您的功能请求是否与问题有关？ 请描述一下。
当前ptpp 搜索功能并不支持avz 架构的站点使用imdb 搜索. avz 站点本身是支持imdb 搜索的. 希望ptpp 能支持avz 架构的站点使用imdb 搜索

## 描述你想要的解决方案
avz 站点 电影和剧集分类下面支持imdb 搜索. 
电影搜索: https://avistaz.to/movies?imdb=tt3812366
剧集搜索: https://avistaz.to/tv-shows?imdb=tt2185037

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/996
close because this
