### ISSUE TITLE
北邮人换新域名了

### ISSUE THREAD

**Issue by Frankcsc** [ronggang/PT-Plugin-Plus#930]
- PT 助手版本:v1.5.2
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：chrome
- 浏览器是否安装了其他插件：是的
- 停用其他插件后是否正常工作：否
- 问题描述：

北邮人新域名：https://byr.pt/
旧域名bt.byr.cn已经停用，目前ptpp无法获取北邮人相关信息

- 相关截图
- 
![QQ截图20211209001419](https://user-images.githubusercontent.com/45666537/145243802-002c183b-7419-45f7-8ea3-5832a8be4169.png)
![QQ截图20211209001905](https://user-images.githubusercontent.com/45666537/145244088-03412356-4c5b-4b72-bd47-de5bd03ab120.png)
：

**Comment by Rhilip** [comment]
dupe: #891

**Comment by frankujs** [comment]
现在又登不上了

**Comment by imhuangjz** [comment]
> 现在又登不上了

谁知道现在怎么登录？谢谢
