### ISSUE TITLE
搜索结果过滤页面按住shift进行多选时选到的结果和想选的结果不同

### ISSUE THREAD

**Issue by zfro** [ronggang/PT-Plugin-Plus#932]
- PT 助手版本:  v1.5.2.75475d8 crx
- PT 助手安装方式：zip包安装
- 浏览器名称及版本：Chrome 版本 96.0.4664.93（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
在搜索结果页面，使用右上角的过滤框时，在过滤后的结果里使用 shift 按键实现多选并下载时，下载的种子并非全为当前过滤结果页面里的种子。

- 相关截图：

过滤页面，本打算选择2-5 ，结果如图![image.png](https://p.sda1.dev/3/041f0d68f0b6d129cb9a4f701d466d9b/image.png)

清除过滤关键词的结果:![](https://p.sda1.dev/3/25b9415a1c6272e9012a16d2bff09b97/chrome-extension___dmmjlmbkigbgpnjfiimhlnbnmppjhpea_index.html _3_.png)

- 重现步骤：
搜索，过滤，按住shift多选

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/805
