### ISSUE TITLE
北洋园更新规则后无法正常获取数据

### ISSUE THREAD

**Issue by kalonezero87** [ronggang/PT-Plugin-Plus#934]
- PT 助手版本:1.52
- PT 助手安装方式：（市场安装，或zip包安装）Zip包安装
- 浏览器名称及版本：edge &chrome
- 浏览器是否安装了其他插件：否
- 停用其他插件后是否正常工作：否
- 问题描述：
北洋园更新规则后无法正常获取数据

- 相关截图：

![屏幕截图 2021-12-11 175211](https://user-images.githubusercontent.com/75162522/145672258-396d45dd-2984-4d6e-a0e0-ac89ca58d7a4.png)

- 重现步骤：

**Comment by ted423** [comment]
请装dev
