### ISSUE TITLE
jquery ajax 追加字符串 cache:false 导致无法搜索出结果 

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#942]
- PT 助手版本:   v1.5.2.3f9c990 crx
- PT 助手安装方式：Action（市场安装，或zip包安装）
- 浏览器名称及版本：Cent
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
怀疑是跟搜索字符串有关 
/torrents?in=1&search=Casino%202&_=1640333708379
打开报错
/torrents?in=1&search=Casino%202
- 相关截图：
![image](https://user-images.githubusercontent.com/7042766/147334118-f23597ed-a9ed-4e9a-9d9a-38dab45e985a.png)

- 重现步骤：

**Comment by ted423** [comment]
看了下，基本所有的http搜索都会增加这么一个参数

**Comment by Rhilip** [comment]
@ted423 那个_=？

**Comment by Rhilip** [comment]
我大体浏览了下，这个应该是在这个commit中引入的 https://github.com/ronggang/PT-Plugin-Plus/commit/899d23432660ed9cdd41bbdc0d9c209b36f0126c
但是我的观点和ronggang有点不一样，我觉得是否应该缓存应该由site和browser来控制，我们强行写 `cache: false` 意义并不大，而且目前因为这个导致站点无法使用，可以删去或者改为`true`。

**Comment by ted423** [comment]
@Rhilip 或者针对az禁用？
我是感觉除非追0day,否则一般不太会遇到问题，另缓存应该还是比较有用的。

**Comment by Rhilip** [comment]
那或许可以这样

```patch
Index: src/background/searcher.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/background/searcher.ts b/src/background/searcher.ts
--- a/src/background/searcher.ts	(revision 006d02a114ec382abd76c44ca6b0594d869097b3)
+++ b/src/background/searcher.ts	(date 1640351514473)
@@ -546,7 +546,7 @@
     return new Promise<any>((resolve?: any, reject?: any) => {
       this.searchRequestQueue[url] = $.ajax({
         url: url,
-        cache: false,
+        cache: ['AvistaZ'].includes(site.schema),
         dataType: "text",
         contentType: "text/plain",
         timeout: this.options.connectClientTimeout || 30000,
```

![image](https://user-images.githubusercontent.com/13842140/147355274-45aa8d9c-19a2-4120-801b-e9a42cd996fe.png)

**Comment by ted423** [comment]
这个问题似乎也开始出现在柠檬
