### ISSUE TITLE
全站搜索界面里HDChina的free不显示。

### ISSUE THREAD

**Issue by 1603006427** [ronggang/PT-Plugin-Plus#944]
- PT 助手版本:  v1.5.2.f2e4f20
- PT 助手安装方式：zip包安装（市场安装，或zip包安装）
- 浏览器名称及版本：Google Chrome版本 96.0.4664.110（正式版本） （64 位）
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：/
- 问题描述：全站搜索界面里HDChina的free不显示。

- 相关截图：
- <img src="https://pic.imgdb.cn/item/61ca7ed72ab3f51d9190acd1.png">
<img src="https://pic.imgdb.cn/item/61ca7ed72ab3f51d9190acd8.png">

- 重现步骤：正常搜索就会有，如搜索 tt0313443。

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/913

**Comment by 1603006427** [comment]
> 感谢
