### ISSUE TITLE
希望增加获取促销种子

### ISSUE THREAD

**Issue by gsmlm** [ronggang/PT-Plugin-Plus#946]
## 您的功能请求是否与问题有关？ 请描述一下。

希望增加获取整站促销种子（免费、2xFree……）

## 描述你想要的解决方案

&spstate=2

**Comment by ted423** [comment]
个人建议这个功能直接打开网站本身页面就好

**Comment by willie91** [comment]
想要刷数据可以用pt小助手https://hub.docker.com/r/crazyq/pt_helper

**Comment by ted423** [comment]
或者使用如下方案，搜索可以增加专门的free条件，然后搜索字符串自动添加参数去搜索。
但工作量太大，大概需要一个非常勤劳的维护者，以确保非NP的适配。
产生的意义小，现有的搜索free 以及2xfree标签是可以筛选的。除非结果非常多的模糊搜索，否则基本可以满足搜索所需电影，获取到free条目的功能

**Comment by fengqi** [comment]
理论上搜索方案扩展下就可以了

**Comment by MewX** [comment]
这个真的很费劲，即使是np的架构，html tag也都是各种改动 😛 

而且很多免费种，站点都没有办法搜索到，需要一页一页爬，如果某一页出错不说，搞不好还会被封号

**Comment by fengqi** [comment]
> 这个真的很费劲，即使是np的架构，html tag也都是各种改动 😛
> 
> 而且很多免费种，站点都没有办法搜索到，需要一页一页爬，如果某一页出错不说，搞不好还会被封号

各站点不是都可以指定搜索促销种子吗，在折叠起来的搜索箱可以看到，连TTG也有这个选项。

**Comment by MewX** [comment]
> > 这个真的很费劲，即使是np的架构，html tag也都是各种改动 😛
> > 而且很多免费种，站点都没有办法搜索到，需要一页一页爬，如果某一页出错不说，搞不好还会被封号
> 
> 各站点不是都可以指定搜索促销种子吗，在折叠起来的搜索箱可以看到，连TTG也有这个选项。

哦对哦，我瞎了没看到这个按钮 🤦‍♀️

**Comment by ted423** [comment]
关了，最终还是觉得意义不大
