### ISSUE TITLE
Orpheus 无法获取积分值

### ISSUE THREAD

**Issue by bollnh** [ronggang/PT-Plugin-Plus#949]
- PT 助手版本: v1.5.2
- PT 助手安装方式：crx
- 浏览器名称及版本：Chrome 96.0.4664.110 
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：未知
- 问题描述：Orpheus 无法获取积分值

- 相关截图：
[![1.png](https://i.postimg.cc/sDfHfxYR/1.png)](https://postimg.cc/QVPJ0XY6)

- 重现步骤：
添加OPS，刷新后无法看到积分（魔力值）

**Comment by ted423** [comment]
@bollnh 是否是action的版本

**Comment by ted423** [comment]
看了下，感觉后面改过版或者怎样
