### ISSUE TITLE
OurBits 无法获取信息

### ISSUE THREAD

**Issue by maicss** [ronggang/PT-Plugin-Plus#950]
- PT 助手版本: 1.5.2
- PT 助手安装方式：（市场安装，或zip包安装）zip
- 浏览器名称及版本：chrome 96
- 浏览器是否安装了其他插件：0
- 停用其他插件后是否正常工作：0
- 问题描述：

- 相关截图：
- 
![image](https://user-images.githubusercontent.com/9784767/148068760-9800ea58-2ec9-48b8-aac6-c714deb616f3.png)

- 重现步骤：
- 无

**Comment by Rhilip** [comment]
站点问题，不在PTPP解决的范畴内

**Comment by maicss** [comment]
站点可以访问的。

**Comment by ted423** [comment]
@maicss 楼上就是OB sysop
