### ISSUE TITLE
下载目录只能设置六个，超出后在站点右键下载种子时只显示“发送到默认服务器。。。”

### ISSUE THREAD

**Issue by Chen-jipeng** [ronggang/PT-Plugin-Plus#952]
- PT 助手版本:v1.5.2.f2e4f20
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：edge(97.0.1072.55)
- 浏览器是否安装了其他插件：是（Tampermonkey）
- 停用其他插件后是否正常工作：否
- 问题描述：
-     下载目录只能设置六个，超出后在站点右键下载种子时只显示“发送到默认服务器。。。”不确定是否为Windows11（版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎11/‎18
操作系统版本	22000.376
体验	Windows 功能体验包 1000.22000.376.0
）右键菜单更新所致。
      

- 相关截图：

![Uploading 屏幕截图 2022-01-08 175739.png…]()

- 重现步骤：
下载目录超过六个后稳定出现。

**Comment by Rhilip** [comment]
不能复现，截图不能显示
请告知 下载目录设置 页 以及右键点击情况

**Comment by Chen-jipeng** [comment]
![目录设置页](https://user-images.githubusercontent.com/61075434/148774685-f6d7cf8c-80e0-4fe4-b0b0-25f10ef451a7.jpg)
![右键界面](https://user-images.githubusercontent.com/61075434/148774700-7f083ceb-898d-42ac-bc0c-3ecaa3edd7ad.jpg)

**Comment by Chen-jipeng** [comment]
其余站点均出现相同现象。

**Comment by Rhilip** [comment]
不能复现 （win10），请参照wiki，给出网页以及插件背景页console面板有无报错。

**Comment by Chen-jipeng** [comment]
![操作过程](https://user-images.githubusercontent.com/61075434/148950202-7bc7fe30-e783-4c5e-8fd6-e9a9d86de618.jpg)
![操作过程2](https://user-images.githubusercontent.com/61075434/148950211-237dfebe-4bf3-4235-acd6-c8bb2df1fd7d.jpg)
没学过前端，不确定是否有用。。。。

**Comment by Chen-jipeng** [comment]
我的还是不行。。。

**Comment by ted423** [comment]
未能复现
非最新版
![image](https://user-images.githubusercontent.com/7042766/188308983-3117571a-55ab-486c-8e5d-fd30a85f7697.png)
