### ISSUE TITLE
在PT助手中输入用户名、密码来添加站点并支持导出备份

### ISSUE THREAD

**Issue by waynon** [ronggang/PT-Plugin-Plus#953]
## 您的功能请求是否与问题有关？ 请描述一下。

目前重装系统/更换浏览器后需要将所有的网站手动登录一遍，非常麻烦

## 描述你想要的解决方案

在PT助手中输入用户名和密码来添加站点，同时这会在浏览器中存储cookie，从而免去重装系统/更换浏览器时手动输入各站点密码的烦恼。并且支持用户名、密码批量导出备份，再次重装系统/更换浏览器后可直接导入。

## 描述您考虑过的替代方案

PT助手根据用户在PT助手中输入的账户密码模拟用户登录行为登录。

**Comment by ted423** [comment]
@waynon 不建议，有非常高的安全风险，自己要负更大的责任

**Comment by ted423** [comment]
@waynon 模拟登录这个行为本身就有很大问题了

**Comment by waynon** [comment]
> @waynon 不建议，有非常高的安全风险，自己要负更大的责任

什么风险？什么责任？

**Comment by Rhilip** [comment]
技术上是半可行的，另外这违反了我们对cookie的隐私准则。
https://github.com/ronggang/PT-Plugin-Plus/blob/master/privacy-statement.md#%E4%BA%94cookie%E4%B9%8B%E4%BD%BF%E7%94%A8

```
当您进行搜索操作时，助手会访问您已配置的站点，Cookie 由浏览器提供，助手无权访问也不会对内容进行探测和修改，一切内容由浏览器和站点进行相互验证；
```

**Comment by waynon** [comment]
仓库主您好，隐私准则可以改的呀，我觉得这是一个很有用的功能！

而且代码编写得当的话应该是没有风险的，对于有验证码的站点的模拟登录可以由PT助手尝试破解一次，如果失败，再将验证码显示给用户，再由用户在PT助手中输入验证码。

目前国内的PT站都是使用的老旧的NexusPHP，应该都没有对模拟登录进行检测。而且这个功能方便了用户，也没有损害仍何人的利益。

**Comment by ted423** [comment]
@waynon 如果准则说改就改，这还能算准则么……你放心让这样的软件或扩展管理你的帐号密码？

**Comment by Rhilip** [comment]
如果你对将自己账号信息交出挺放心的，你可以使用 Jackett ，虽然在国内使用的人不多，但是Jackett确实对国内多数站点有支持（仅在搜索种子方面）。
PTPP从一开始的定位就是 WebExtension （或者说 Chrome Extension），将Cookie等状态控制交给浏览器来管理，而不是一个集大成者的“国内毒瘤APP”

**Comment by waynon** [comment]
> @waynon 如果准则说改就改，这还能算准则么……你放心让这样的软件或扩展管理你的帐号密码？

Google经常提示“我们变更了隐私协议”，很多大公司也经常改协议的。

而且像 1Password那样的密码保管软件、Chrome、Edge等浏览器都可以访问用户的密码。

此外这个不是开源的吗？开发者让大家审核自己的代码，我们用户还有什么不放心。如果真的存在窃取用户密码的情况，也可以由Fiddler等抓包软件发现，所以我相信开发者不会做这种败坏自己名声的事情。

最后，这个功能可以作为一个可选功能，可以在设置中启用或禁用。

我感觉PT助手还是挺好用的，所以还是希望你们再考虑一下。希望不要把这个issue直接关掉，可以开放一段时间让大家讨论一下。

**Comment by waynon** [comment]
PT助手对国内站点的支持应该是最广的，所以希望继续用它，Jackett支持的国内站点还是少了点吧
