### ISSUE TITLE
PTTime无法获取正确的做种数

### ISSUE THREAD

**Issue by bollnh** [ronggang/PT-Plugin-Plus#954]
- PT 助手版本:  v1.5.2.b2b3525 action 版本
- PT 助手安装方式：crx 安装
- 浏览器名称及版本：Chrome 96.0.4664.110
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：未知
- 问题描述：pttime一直显示做种数为20，猜测是因为pttime“当前做种”只显示了20条，但实际应该使用“当前活动”的做种数才是正确的数值。

- 相关截图：PTTime: ![](https://s2.loli.net/2022/01/10/jPyhYTwlzQVaWgN.png), PTPP: ![](https://s2.loli.net/2022/01/10/KIStQThxFmeGZ5g.png)

- 重现步骤：添加pttime 并刷新数据即可

**Comment by Rhilip** [comment]
无该站点 @Asterisci 能否协助？

**Comment by Asterisci** [comment]
> 无该站点 @Asterisci 能否协助？

最近无法及时解决，抱歉，可能得年后才有空，而且我的账号也注销了😂

**Comment by ted423** [comment]
@Asterisci 注销了就关了算了

**Comment by yc-pt** [comment]
这个应该是站点的原因，个人信息页只显示20条信息
![image](https://user-images.githubusercontent.com/100306492/155372109-0395b517-2f82-46cc-b552-48ccc60c7065.png)
但应该有其他方法解决。
