### ISSUE TITLE
插件在Edge浏览器无法读取MT数据

### ISSUE THREAD

**Issue by luckiestone** [ronggang/PT-Plugin-Plus#955]
- PT 助手版本: v1.5.2.f2e4f20
- PT 助手安装方式：市场安装
- 浏览器名称及版本：97.0.1072.55
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：该版本Edge在刷新MT数据时显示未登陆，实际MT已经登陆。且使用PTPP插件尝试获取MT数据后，手动访问MT任何页面会自动跳转/login.php，显示您已登录。同版本插件使用Chrome测试无问题。Edge在两台电脑测试均存在此问题。

- 相关截图：无

- 重现步骤：Edge使用PTPP获取MT数据。

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/149061950-866282b5-d3b0-4154-9cbc-57ef33e2ef43.png)
未再现
![image](https://user-images.githubusercontent.com/7042766/149061990-eb73fa30-df3c-4755-a467-259a4fcf98be.png)
是否有导入cookies的操作？

**Comment by luckiestone** [comment]
> ![image](https://user-images.githubusercontent.com/7042766/149061950-866282b5-d3b0-4154-9cbc-57ef33e2ef43.png) 未再现 ![image](https://user-images.githubusercontent.com/7042766/149061990-eb73fa30-df3c-4755-a467-259a4fcf98be.png) 是否有导入cookies的操作？

那也挺奇怪了，我插件删除重新安装，而且特地没有恢复cookies也不行。我再找找问题

**Comment by ted423** [comment]
@luckiestone 试下

**Comment by luckiestone** [comment]
> @luckiestone 试下清cookies然后重新登录

没用，我看后台访问index.php会被302重定向到https://kp.m-team.cc/verify.php?returnto=%2Findex.php

**Comment by puxxustc** [comment]
清空浏览器缓存试试

**Comment by ted423** [comment]
@luckiestone https://www.coder.work/article/5036719

**Comment by luckiestone** [comment]
> 

知识盲区了，还是等MT那边调整验证策略吧

**Comment by luckiestone** [comment]
> 

知识盲区了，还是等MT那边调整验证策略吧

**Comment by ted423** [comment]
@ted423 好像也不是这个问题……

**Comment by luckiestone** [comment]
> @ted423 好像也不是这个问题……

估计就是插件采用后台请求的方式，可能这种方式过不了CF验证，然后重定向去verify了

**Comment by ted423** [comment]
@luckiestone 你有开二次验证么？我是mt固定走代理，所以基本不会弹二次验证，现在也没有ＣＦ

**Comment by luckiestone** [comment]
> @luckiestone 你有开二次验证么？我是mt固定走代理，所以基本不会弹二次验证，现在也没有ＣＦ

开了，而且经常动不动CF。

**Comment by Rhilip** [comment]
跳转至verity页面我认为不是插件问题。
mt的验证策略并不公开，猜测多是ip，浏览器等因素变动。
请用户关闭二步进行测试。

**Comment by tainewoo** [comment]
建议先验证在Edge正常打开MT是不是经常会需要重新登录.
MT本身是支持IPv4和IPv6的.如果自己的设备(电脑或者手机)能获得IPv6,那么就容易出现反复需要重新登录MT的问题.
实测本机禁用IPv6,只用IPv4的时候没有问题.不然就容易出现过不了多久又要重新登录的问题.
需要重新登录的时候,表示说Edge拿到的cookie已经失效,那插件也就无法获取数据了.

**Comment by luckiestone** [comment]
MT似乎更新了验证策略，本次提示重新登陆后，已经恢复正常。

**Comment by ted423** [comment]
我遇到了一个很蛋疼的问题，ipv6的话，几小时填一次验证

**Comment by luckiestone** [comment]
> 

我这边今天又发生这个问题了。一共两个站不正常：MT每次插件刷新都会有这个问题，还有就是FL，过几个小时就登出了。上次我close这个issue的时候这两个站同时好的，不知道是感觉不像是站点问题，不知道是我IP问题，还是浏览器更新了啥。

**Comment by ted423** [comment]
@luckiestone FL我这也是日常登出

**Comment by luckiestone** [comment]
> @luckiestone FL我这也是日常登出

这就很怪了，实际上我也没有开外网IPV6。

**Comment by ted423** [comment]
@luckiestone 最近才从cent换的edge

**Comment by luckiestone** [comment]
> @luckiestone 最近才从cent换的edge

看来Edge的锅无疑了

**Comment by qrzbing** [comment]
Chrome 同样触发此问题，开启了二步验证。

**Comment by ted423** [comment]
> Chrome 同样触发此问题，开启了二步验证。

开二次验证就是这样，这不是issue
