### ISSUE TITLE
”设置保存目录“按钮缺失

### ISSUE THREAD

**Issue by oyuntuayC** [ronggang/PT-Plugin-Plus#959]
![image](https://user-images.githubusercontent.com/96269522/150410279-91bb9c95-a175-43e2-a9c1-b47d8837f613.png)
如题，验证成功后没有出现

**Comment by chenjingchun** [comment]
> ![image](https://user-images.githubusercontent.com/96269522/150410279-91bb9c95-a175-43e2-a9c1-b47d8837f613.png) 如题，验证成功后没有出现

我也是这个问题，请问解决了吗？

**Comment by ted423** [comment]
@chenjingchun 锁了，github里希望能遵循基本礼仪，看wiki ,搜issue。最后再提问
