### ISSUE TITLE
hdchina右键发送到插件下载，下载失败

### ISSUE THREAD

**Issue by xzxiaoshan** [ronggang/PT-Plugin-Plus#96]
如果反馈 BUG，为了更快解决您的问题，请提供以下信息，谢谢。

> 注意：上传日志或配置信息前，请先删除个人信息！

PT 助手版本: 1.0.4
PT 助手安装方式：（市场安装，或zip包安装）zip
浏览器名称及版本：Chrome 版本 73.0.3683.86（正式版本） （64 位）
问题描述：hdchina（瓷器）官网列表页，对其中一条记录，拖放到插件图标和右键发送到插件，都是失败。
相关截图：
![1](https://user-images.githubusercontent.com/16459864/55606329-f51ebd00-57aa-11e9-8f22-3065588177fe.png)

**Comment by Rhilip** [comment]
请删除插件站点设置中的密钥并重试，相关issue见： https://github.com/ronggang/PT-Plugin-Plus/issues/46
