### ISSUE TITLE
请求支持qnap download station

### ISSUE THREAD

**Issue by EinProfispieler** [ronggang/PT-Plugin-Plus#960]
## 您的功能请求是否与问题有关？ 请描述一下。

请求支持qnap download station，目前群辉的不兼容qnap的。

**Comment by mitlearn** [comment]
可能你忽略的是 群晖的也不支持 https://github.com/ronggang/PT-Plugin-Plus/issues/687
开发者很希望有设备并且会开发的提pr

**Comment by ted423** [comment]
个人不建议考虑，这个客户端都不显示tracker状态，没感觉到有支持的必要

**Comment by ted423** [comment]
对站点基本也是非标客户端

**Comment by Rhilip** [comment]
未发现有API文档，请提供
