### ISSUE TITLE
AvistaZ 架构不支持

### ISSUE THREAD

**Issue by starsjf** [ronggang/PT-Plugin-Plus#962]
- PT 助手版本:v1.5.2.f2e4f20
- PT 助手安装方式：市场安装
- 浏览器名称及版本：Edge
- 浏览器是否安装了其他插件：97.0.1072.69 
- 停用其他插件后是否正常工作：
- 问题描述：AvistaZ 架构不支持，不能搜索，也不能够推送。之前是能够搜索，不能推送，但是现在怎么样都不行了。

**Comment by ted423** [comment]
@starsjf

**Comment by ted423** [comment]
最新版本以及功能建议登录后从Action里获取。如有问题请参看Wiki

提Issue前请务必检查Dev版本

**Comment by zexindai** [comment]
> 最新版本以及功能建议登录后从Action里获取。如有问题请参看Wiki
> 
> 提Issue前请务必检查Dev版本

我是

**Comment by ted423** [comment]
@zexindai 扩展版本号都不对

**Comment by ted423** [comment]
@zexindai https://github.com/ronggang/PT-Plugin-Plus/issues/942

**Comment by ted423** [comment]
@zexindai 提Issue前请务必检查Dev版本、Pull Request以及之前的Issue

**Comment by zexindai** [comment]
> @zexindai #942



> @zexindai 扩展版本号都不对

从action重新安装dev版© 栽培者 2022, 版本 v1.5.2.70f942a crx后已解决，感谢

**Comment by HenryQW** [comment]
我这里 dev版© 栽培者 2022, 版本 v1.5.2.70f942a 还是不行，az站搜索451，尝试定义站点搜索入口配置也会报错

<img width="507" alt="Screenshot 2022-02-05 at 17 17 08" src="https://user-images.githubusercontent.com/5896343/152651819-58a11b30-5672-479e-9c3f-03ded0747c58.png">

**Comment by ted423** [comment]
> 

删了重加试试

**Comment by HenryQW** [comment]
删了两回才正常，不知道为啥 😆
