### ISSUE TITLE
建议考虑一个docker本地部署的PTPP版本

### ISSUE THREAD

**Issue by chixinzei** [ronggang/PT-Plugin-Plus#963]
- 
是否可以考虑增加docker image版本？可以免去安装浏览器插件的步骤。并且大多数玩PT的也都拥有自己的nas docker环境。

**Comment by ted423** [comment]
dupe https://github.com/ronggang/PT-Plugin-Plus/issues/670

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/240
