### ISSUE TITLE
HDB 搜索结果显示错乱

### ISSUE THREAD

**Issue by MewX** [ronggang/PT-Plugin-Plus#967]
- PT 助手版本: v1.5.2.92b7154
- PT 助手安装方式：zip
- 浏览器名称及版本：Chrome 98.0.4758.82
- 浏览器是否安装了其他插件：N/A
- 停用其他插件后是否正常工作：N/A
- 问题描述：HDB 搜索结果显示错乱

- 相关截图：

<img width="987" alt="image" src="https://user-images.githubusercontent.com/5752560/152728391-981753cf-a002-4b85-8050-21b1cbab1921.png">

- 重现步骤：搜索 “The Year Earth Changed”。

**Comment by ted423** [comment]
![image](https://user-images.githubusercontent.com/7042766/155867994-e33ae61c-ae26-4cbe-843d-705f8ae807e3.png)
没再现

**Comment by ted423** [comment]
看起来像是多列少列导致的错位

**Comment by MewX** [comment]
哦哦我懂了，之前我开了双category：

<img width="356" alt="image" src="https://user-images.githubusercontent.com/5752560/155872758-95d125f3-0efc-4b0c-9ac1-69d2e979b08e.png">

之前写freeleech 脚本的时候也遇到了这个问题： https://greasyfork.org/en/scripts/439660-hdbits-showing-free-leech-info

解决方案就是取反 `find('td:not([class="catcell"])')`

**Comment by ted423** [comment]
试了下，我这yes直接就搜不到东西了..
