### ISSUE TITLE
“下载历史”什么情况下会有内容

### ISSUE THREAD

**Issue by suosuosi** [ronggang/PT-Plugin-Plus#969]
- 请教下，什么情况下，”下载历史“会有统计内容？我使用站点推送、右键下载、助手搜索后下载，下载完成后”下载历史“均不显示内容。也没有找到给 下载历史 权限的地方，请教了

**Comment by ted423** [comment]
@suosuosi 关闭重打开呢

**Comment by dawnray** [comment]
我这里也有同样问题

**Comment by ted423** [comment]
正常站点里推送就会有

**Comment by suosuosi** [comment]
更多信息：
win7 pro x64， 1.5.2 crx，chrome 版本 97.0.4692.99（正式版本） （64 位）
下载 推送 搜索均正常，hdc+mteam

**Comment by ted423** [comment]
是否装了action的版本？

**Comment by suosuosi** [comment]
> 是否装了action的版本？
没明白啥意思，下载这里的releases 最后一个版本crx文件，通过教程导入注册表安装的crx
chrome插件方面也没有很特别的，abp+ublock等广告插件 关闭后也没反映

**Comment by mitlearn** [comment]
使用这个方法安装的是action版
https://github.com/ronggang/PT-Plugin-Plus/wiki/get-from-gh-actions
你的属于正式版

**Comment by suosuosi** [comment]
> 使用这个方法安装的是action版 https://github.com/ronggang/PT-Plugin-Plus/wiki/get-from-gh-actions 你的属于正式版

哦，谢谢，是的，我装的releases版本

**Comment by zhufeng** [comment]
v1.5.2.6e34444 版本测试均会保存下载历史。

**Comment by ted423** [comment]
最好提供其他信息，浏览器版本，系统

另外需要安装最新action版本来提供结果

**Comment by kimi-tc** [comment]
我这里也有同样问题，版本 v1.5.2.d62bcba zip， chrome

**Comment by ted423** [comment]
> 我这里也有同样问题，版本 v1.5.2.d62bcba zip， chrome

按照wiki使用crx试试
