### ISSUE TITLE
个别网站搜索结果中@符号识别成email

### ISSUE THREAD

**Issue by QzQ** [ronggang/PT-Plugin-Plus#97]
- PT 助手版本: 1.0.4
- PT 助手安装方式：市场安装
- 浏览器名称及版本： Chrome  73.0.3683.86
- 问题描述：个别网站（套套）搜索结果中@符号识别成email
- 相关截图：
源文件名：Madame 2017 Blu-ray 1080p AVC DTS-HD MA 5.1-DIY@TTG
显示为：Madame 2017 Blu-ray 1080p AVC DTS-HD MA [email&nbsp;protected]

**Comment by Rhilip** [comment]
这是cloudflare的锅。。。

**Comment by QzQ** [comment]
因为套套启用了CloudFlare？

**Comment by Rhilip** [comment]
具体请看CloudFlare的官方说明：https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

---------------------------

CF会为所有**开启**`Email Address Obfuscation`的站点提供这种隐藏email的方式
![TIM截图20190405210624](https://user-images.githubusercontent.com/13842140/55629847-cd4d4a80-57e6-11e9-93ec-0eb7dd41e940.png)
（虽然只要经过简单的解码就可以完成解析，而且这种email protect其实反而暴露了email地址信息，但是目前脚本没有集成这个功能。
