### ISSUE TITLE
无法添加群晖下载

### ISSUE THREAD

**Issue by fsnhljz** [ronggang/PT-Plugin-Plus#971]
- PT 助手版本:v1.5.2.f2e4f20
- PT 助手安装方式：edge市场安装
- 浏览器名称及版本：edge
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
下载服务器Synology Download Station添加失败，无法验证。
但我本身使用另外一个插件NAS Download Manager (for Synology)是能够正常使用的，建议参考此插件

- 相关截图：

- 重现步骤：

**Comment by mitlearn** [comment]
PTPP向部分DSM客户端发送下载任务报错 后续
因查询到API文档及需求日益强烈等缘由 作者提交了PR (https://github.com/ronggang/PT-Plugin-Plus/pull/964)尝试解决问题 因缺少测试无法将改动Merge至主分支（这意味着下一个release版本可能依旧不支持） 希望之前遇到相关问题的用户下载安装此版本 积极反馈问题或回报使用情况 每一个反馈都是推动Merge的有力支撑！

下载地址： Github (https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1745535832) | 频道转发 (https://t.me/ptpluginplus/79) | 安装方法
 (https://github.com/ronggang/PT-Plugin-Plus/wiki/get-from-gh-actions)前情提要：https://t.me/ptpluginplus/66

#DSM #helpwanted

**Comment by Rhilip** [comment]
dupe: #687

**Comment by tyejuan** [comment]
一样的问题，好像一直没有明确的解决方法。插件本身是否无法修复这个问题呢？
