### ISSUE TITLE
备份到 WebDAV 时，建议创建 PT 助手的文件夹，而不是在根目录备份

### ISSUE THREAD

**Issue by Nikaple** [ronggang/PT-Plugin-Plus#976]
- PT 助手版本: © 栽培者 2022, 版本 v1.5.2.f2e4f20 crx
- PT 助手安装方式：CRX
- 浏览器名称及版本：Chrome
- 浏览器是否安装了其他插件：无关
- 停用其他插件后是否正常工作：无关
- 问题描述：
建议在 WebDAV 备份失败时，尝试先创建PT助手的文件夹。否则会因为根目录没有写权限，导致备份失败。目前是通过请求手动新增了一个 `testCol` 的文件夹，然后再将 WebDAV 的地址指向子文件夹，才能上传成功。

	如果会导致与前面版本的兼容性问题，也可在 wiki 补充需要先创建子文件夹才能使用的步骤，毕竟自己琢磨还挺费时间

- 相关截图：
![image](https://user-images.githubusercontent.com/24775744/154793505-026d3f2f-d6e1-4614-8ffd-33a0120952fe.png)

- 重现步骤：
	1. 坚果云为PT助手分配一个独立的key
	2. 填写坚果云信息，WebDAV 地址指向根目录：https://dav.jianguoyun.com/dav/
	2. 点击备份

**Comment by Rhilip** [comment]
dupe: #319

**Comment by ted423** [comment]
QNAP的webdav没有这个问题，个人认为根目录没有写权限不是助手的问题。
