### ISSUE TITLE
添加签到提醒功能

### ISSUE THREAD

**Issue by fzlins** [ronggang/PT-Plugin-Plus#977]
## 您的功能请求是否与问题有关？ 请描述一下。

有时候会忘记签到其中一个或者几个站点，又或者会因为服务器连接出错导致签到失败而不知道。

## 描述你想要的解决方案

可以在我的签到中加上一览签到状态，每次刷新数据的时候，用绿钩表示已经签到了，红叉表示还未签到。

**Comment by ted423** [comment]
我认为无意义

**Comment by fzlins** [comment]
> 我认为无意义

Thanks for letting me know
