### ISSUE TITLE
无法提取天雪SkyeySnow的用户数据

### ISSUE THREAD

**Issue by jaaaaaaaah** [ronggang/PT-Plugin-Plus#978]
- PT 助手版本: v1.5.2.6e34444
- PT 助手安装方式：crx
- 浏览器名称及版本：100.0.1163.1 (官方内部版本) dev (64 位)
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：
无法获取用户在天雪的数据量、分享率、做种数、做种体积、魔力值/积分

- 相关截图：
![image](https://user-images.githubusercontent.com/44402079/155053501-709ecdeb-a354-4498-93bf-7524b63dc337.png)

- 重现步骤：
更新数据

**Comment by MewX** [comment]
我来修吧，这个是因为UI改动所以查询不出来

**Comment by MewX** [comment]
@jaaaaaaaah 试试看新的 [action 版本](https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1885988334) 有没有其他bug了

**Comment by jaaaaaaaah** [comment]
> @jaaaaaaaah 试试看新的 [action 版本](https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1885988334) 有没有其他bug了

emmm 积分显示了，其他数据都是0（以前是空白）。虽然我确实没在做种，不过上传下载量不应该是0。

**Comment by MewX** [comment]
> > @jaaaaaaaah 试试看新的 [action 版本](https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1885988334) 有没有其他bug了
> 
> emmm 积分显示了，其他数据都是0（以前是空白）。虽然我确实没在做种，不过上传下载量不应该是0。

oh 好像还真是，

<img width="476" alt="image" src="https://user-images.githubusercontent.com/5752560/155276652-6a2729dd-1ec2-4b86-b65d-b86a6bebf832.png">

浏览器里手动跑同样的脚本倒是可以正常得出结果：

```
$("#psts li:contains('上传量')").text().match('上传量.*?/\\s*([\\d\\.]+\\s*?[ZEPTGMK]?i?B)')[1].sizeToNumber()
10737418240
```

**Comment by MewX** [comment]
@jaaaaaaaah 麻烦试试看新的 [action 版本](https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1915658986) 有没有bug了 🤣

**Comment by jaaaaaaaah** [comment]
> @jaaaaaaaah 麻烦试试看新的 [action 版本](https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1915658986) 有没有bug了 🤣

一切正常，费心了！
