### ISSUE TITLE
hdpost无法搜索

### ISSUE THREAD

**Issue by zhufeng** [ronggang/PT-Plugin-Plus#979]
- PT 助手版本: v1.5.2.6e34444 
- PT 助手安装方式：firefox自签名 / edge crx解压
- 浏览器名称及版本：firefox 91.6.0 ESR / edge 92.0.902.67
- 浏览器是否安装了其他插件：是
- 停用其他插件后是否正常工作：否
- 问题描述：

1、hdpost无法搜索，提示404，看了下debug日志，应该是搜索的链接不对了。
在resource/schema/unity3d的config.json里面看到定义的搜索接口这样的：
```  "searchEntryConfig": {
    "page": "/torrents/filter",
    "queryString": "search=$key$",
```
由于可能是因为hdpost修改了u3d的代码，所以应该改成如下这样就能正常搜索：
```  "searchEntryConfig": {
    "page": "/torrents",
    "queryString": "name=$key$",
```
上述搜索接口使用ptpp站点设置里面的“搜索入口”自定义一个，就能搜到内容，但是返回的结果无法显示种子大小、做种人数等信息，可能还需要重新解析一下，待解决，如下文的截图显示。

2、在尝试解决上一个问题的过程，用到了“搜索入口”的功能，顺带发现了这个功能的bug。对站点添加一个”搜索入口“之后，点保存，不会提示是否保存成功，再点进去”搜索入口“，看不到刚才已经成功创建的搜索入口配置，但是在创建搜索方案里面能看到。

- 相关截图：
![image_2022-02-21_21-50-01](https://user-images.githubusercontent.com/1539043/155058481-80f9a5f8-cb03-467c-bc4f-8e527fefeba1.jpg)
    
![image_2022-02-21_22-48-58](https://user-images.githubusercontent.com/1539043/155058506-957bd6cd-4f34-4c38-861c-7ab4d7666ef4.jpg)

- 重现步骤：
1、搜索hdpost的种子资源。
2、创建任意站点的”搜索入口“。

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/831
关联问题，统一处理，故问题关闭
