### ISSUE TITLE
添加群晖DS，提示验证失败

### ISSUE THREAD

**Issue by gkgx163** [ronggang/PT-Plugin-Plus#986]
-  v1.5.2.f2e4f20:
- PT 助手安装方式：edge插件
- 浏览器名称及版本：edge 98.0.1108.56
- 浏览器是否安装了其他插件：是，但是无PT相关插件
- 停用其他插件后是否正常工作：否
- 问题描述：
添加下载服务器，提示身份验证错误，关闭二次验证，问题依旧。

- 相关截图：
![image](https://user-images.githubusercontent.com/59253327/155284783-4cb236ca-1586-4860-aa03-04ab326a74ea.png)

- 重现步骤：

**Comment by mitlearn** [comment]
Dupe with https://github.com/ronggang/PT-Plugin-Plus/issues/971

**Comment by ted423** [comment]
话说readme里是不是应该加粗...
