### ISSUE TITLE
对 iTS 的支持目前有若干bug

### ISSUE THREAD

**Issue by MewX** [ronggang/PT-Plugin-Plus#987]
之前的支持bug在这： #834  #695  #694 

目前iTS的bug如下：

1. 用户信息获取部分为空

<img width="624" alt="image" src="https://user-images.githubusercontent.com/5752560/155315007-629fc68b-b822-4f12-8203-2c0912b39e57.png">

Note: 和 @ted423 确认过可以把数据传输简化成上传量，然后把下载量和ratio设成 -1 即可。

2. 无法下载到服务器

<img width="91" alt="image" src="https://user-images.githubusercontent.com/5752560/155315751-7355cb2c-b6dc-4af3-87e3-316514cc6397.png">

3. 添加对collection页面的下载支持：`its/collections.php?collection_id=???`

----

@luckiestone 大佬还有空修不？

**Comment by ted423** [comment]
好像reopen都会自动关

**Comment by MewX** [comment]
> 好像reopen都会自动关

所以我新建了 =，=
