### ISSUE TITLE
Batch Save All Feature on Karagarga's History and Current Page. 

### ISSUE THREAD

**Issue by leonard4546** [ronggang/PT-Plugin-Plus#989]
Hey, is it possible to add feature to Batch download all torrents in page for history.php?id=userid and current.php?id=userid

Currently this feature is available on browse.php page. and Both history and Current page has download button so is it possible to add that?

**Comment by ted423** [comment]
Karagarga.in ?

**Comment by leonard4546** [comment]
> Karagarga.in ?

Yes Btw I created new issue for this
