### ISSUE TITLE
建议取消AZ联盟的支持

### ISSUE THREAD

**Issue by ted423** [ronggang/PT-Plugin-Plus#996]
- PT 助手版本: All
- PT 助手安装方式：（市场安装，或zip包安装）
- 浏览器名称及版本：
- 浏览器是否安装了其他插件：
- 停用其他插件后是否正常工作：
- 问题描述：
![image](https://user-images.githubusercontent.com/7042766/156478120-3f8c0f79-fa1c-4da7-8d45-a2f818d9c973.png)
https://tieba.baidu.com/p/7744859250

- 相关截图：

- 重现步骤：

**Comment by ted423** [comment]
@ronggang @Rhilip 并且考虑Release一版

**Comment by abixalmon** [comment]
We officially support https://github.com/Jackett/Jackett

If you want to search our websites, please use the search API as used by Jackett

Refer here: https://github.com/Jackett/Jackett/issues/8873

**Comment by Rhilip** [comment]
> Searching our website directly is not good. Please use our API to perform search.
> 
> We officially support https://github.com/Jackett/Jackett
> 
> If you want to search our websites, please use the search API as used by Jackett

Thank you for provide offical document even in other repo,
We will try to obey this docuement,

But currently, we can only remove all support for avistaz sites.

Also, Our project want to get userInfo like uid, username,level, uploaded, downloaded,seeding,seedingSize et al.
Will sites provide these API ?

**Comment by abixalmon** [comment]
> Also, Our project want to get userInfo like uid, username,level, uploaded, downloaded,seeding,seedingSize et al.
> Will sites provide these API ?

User information will never be available in any form or API, as we respect the privacy and confidentiality of user information.

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/1070
更新相关问题
Release Issue

**Comment by ted423** [comment]
最新的AZ公告显示 Jackett API disabled.
故目前API请求支持大概也是不行了
