### ISSUE TITLE
Remove AvistaZ sites.

### ISSUE THREAD

**Issue by abixalmon** [ronggang/PT-Plugin-Plus#997]
Please remove avistaz.to, privatehd.to, cinemaz.to & exoticaz.to from this extension.

If you dont, we am banning every user using this extension from our websites

**Comment by abixalmon** [comment]
请从此扩展中删除 avistaz.to、privatehd.to、cinemaz.to 和exoticaz.to。

如果您不这样做，我们将禁止所有用户在我们的网站上使用此扩展程序

**Comment by Rhilip** [comment]
> Please remove avistaz.to, privatehd.to, cinemaz.to & exoticaz.to from this extension.
If you dont, we am banning every user using this extension from our websites

> 请从此扩展中删除 avistaz.to、privatehd.to、cinemaz.to 和exoticaz.to。
如果您不这样做，我们将禁止所有用户在我们的网站上使用此扩展程序

Do you represent those four site?

**Comment by abixalmon** [comment]
https://github.com/ronggang/PT-Plugin-Plus/issues/996#issuecomment-1057856310
