### ISSUE TITLE
无法提取白兔俱乐部-club.hares.top的用户数据

### ISSUE THREAD

**Issue by SeanSuny** [ronggang/PT-Plugin-Plus#998]
PT 助手版本:  v1.5.2.f2e4f20

PT 助手安装方式：crx

浏览器名称及版本：谷歌 99.0.4844.51（正式版本）（64 位）

浏览器是否安装了其他插件：是

停用其他插件后是否正常工作：否

问题描述：
无法获取用户在白兔俱乐部的等级、数据量、分享率、做种数、做种体积、魔力值/积分、入站时间

相关截图：
![20220304-125649](https://user-images.githubusercontent.com/20199755/156702179-e9f6d739-90dd-436c-b989-e8c35e627a7a.png)

重现步骤：
更新数据

**Comment by Rhilip** [comment]
目前该站不在我们支持的范围内

**Comment by SeanSuny** [comment]
好的谢谢

**Comment by ted423** [comment]
这个站是由 kevgao 提交的pr
后续也欢迎其他人提交pr
