### ISSUE TITLE
当进站不足一天是时间显示好像有bug

### ISSUE THREAD

**Issue by onlyJinx** [ronggang/PT-Plugin-Plus#999]
- PT 助手版本:
- PT 助手安装方式：（市场安装，或zip包安装）zip包安装
- 浏览器名称及版本：如截图
- 问题描述：

当进站不足一天是时间显示好像有bug
- 相关截图：
![image](https://user-images.githubusercontent.com/21324835/156873113-be9828b4-701f-4305-8293-b2aa5b42a57d.png)

- 重现步骤：

**Comment by ted423** [comment]
版本

**Comment by onlyJinx** [comment]
`© 栽培者 2022, 版本 v1.5.2.dc2c56f crx`

**Comment by ted423** [comment]
https://github.com/ronggang/PT-Plugin-Plus/actions/runs/1881184317
测试下这个或比这个更早之前的版本呢

**Comment by onlyJinx** [comment]
抱歉，已无法验证，因为刚才下载完你提供的这个版本后就去看数据发现已经是超过1天了，目前显示1天4小时，以后有机会(进其他pt站)我再测试

**Comment by ted423** [comment]
试了下 中英文似乎都有问题

**Comment by ted423** [comment]
@ted423 似乎应该是 timeline.time.mins
